### ISSUE TITLE
Nested objects and One To Many at once ?

### ISSUE THREAD

**Issue by Biegal** [schotime/NPoco#101]
Hi All,

Sorry if that topic is clarified already somewhere, didn't find it.

Question is if there is some way to have mapping of nested objects and OneToMany at once ?
In other words (using examples from wiki) can I get User object, that will be filled with
Address and list of Cars ?
```
public class User
{
    public int UserId { get; set; }
    public string Name { get; set; }
    public Address Address { get; set; }

    public List<CarDto> Cars { get; set; }
}

public class Address
{
    public string Street { get; set; }
    public string City { get; set; }
}

public class CarDto
{
    public string Make { get; set; }
    public string Color { get; set; }
}
```
FetchToMany accepts only two generic params.

**Comment by schotime** [comment]
This will work in V3. Only allow one many though.

**Comment by schotime** [comment]
Implemented in V3.
