### ISSUE TITLE
MappingFactory bug when a property and column names are different

### ISSUE THREAD

**Issue by CaspianCanuck** [schotime/NPoco#106]
I have discovered a bug in the older (pre-PocoData-refactoring) version of NPoco I'm using for a project at work and think it still applies to the refactored code.

When a POCO property is mapped to a DB column with a different name the GetFactory() method does not emit the IL necessary to populate that column. This happens because the code, when checking if a property exists that matches the column, relies on the column name alone. The fix that I have come up with involves looking for a 1-to-1 name match first, then looking for a match by column.MemberInfo.Name which contains the mapped property's name.

Which branch should I use to submit my pull request?

**Comment by schotime** [comment]
Hey, I'm starting on V3 and was wondering if you would be able to give it a test in relation to this issue.
Cheers

**Comment by CaspianCanuck** [comment]
Hi Adam,

Sorry, your email got filtered into my spam folder somehow...

Sure, I'd be happy to help you test this issue although, frankly, I don't
even recall what it involved. Care to refresh my memory?

Tim


On Sun, Jun 14, 2015 at 7:46 AM, Adam Schroder <notifications@github.com>
wrote:

> Hey, I'm starting on V3 and was wondering if you would be able to give it
> a test in relation to this issue.
> Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schotime/NPoco/issues/106#issuecomment-111815665>.
>



-- 

Tim


P.S. If you have trouble reaching me at *tim@askerov.net
<tim@askerov.net>* please
try *taskerov@gmail.com <taskerov@gmail.com>* instead.

**Comment by schotime** [comment]
If you can clone the v3 branch and give it a try that would be great.

**Comment by CaspianCanuck** [comment]
I'm leaving on vacation but will try to get it done (work permitting) in
mid-September after I get back.

Cheers!

On Thu, Aug 20, 2015 at 10:07 AM, Adam Schroder <notifications@github.com>
wrote:

> If you can clone the v3 branch and give it a try that would be great.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schotime/NPoco/issues/106#issuecomment-133022186>.
>



-- 

Tim


P.S. If you have trouble reaching me at *tim@askerov.net
<tim@askerov.net>* please
try *taskerov@gmail.com <taskerov@gmail.com>* instead.

**Comment by schotime** [comment]
V3 alpha now on Nuget. Test away.
