### ISSUE TITLE
Transaction default isolation level

### ISSUE THREAD

**Issue by zii-dmg** [schotime/NPoco#127]
We can't create transaction with really default isolation level becauce level is declared in DatabaseType.GetDefaultTransactionIsolationLevel() or Database class constructor but db can be configured with another level (suppose I don't know this level).
So for default level we should create transaction with IDbConnection.BeginTransaction() parameterless overload. In this case IDbConnection itself will decide which default isolation level is used in db (DatabaseType.GetDefaultTransactionIsolationLevel() can be removed).

**Comment by schotime** [comment]
BeginTransaction() takes isolation level as a parameter. 
You can also override the GetDefaultTransactionIsolationLevel() and return what ever you like.
