### ISSUE TITLE
Question: Is there any interest in adding async support to NPoco?

### ISSUE THREAD

**Issue by MatthewVines** [schotime/NPoco#135]
Is this a pull request you would accept? Or would you rather it be developed in some sort of extension assembly?

**Comment by schotime** [comment]
Its starting to happen.
See https://github.com/schotime/NPoco/issues/45#issuecomment-93699844 for details.

**Comment by enriko-riba** [comment]
+1

**Comment by Hand-E-Food** [comment]
+1 Expressing interest!

**Comment by konstk** [comment]
Definitely need async for .NET 4.5.

+1 !!!

**Comment by schotime** [comment]
Its pretty much in 2.0 now and will stay for 3.0
