### ISSUE TITLE
Are ReferenceProperties in roadmap ?

### ISSUE THREAD

**Issue by Biegal** [schotime/NPoco#139]
Hi,

The ReferenceProperties branch made me interested, as I tried to do something similar sometime ago (altough it works, it's nowhere near 'production' quality).
My question is, are you keen to introduce that to NPoco, or was it just a spike ?
Do you have any specific problems or tasks to tackle ? Maybe I could take a look too,

Regards,
Marcin

**Comment by schotime** [comment]
V3 will have support for this. There is a dev3.0 branch which you can try out. Not fully released yet.

**Comment by schotime** [comment]
V3 roadmap  
https://github.com/schotime/NPoco/wiki/Version-3
