### ISSUE TITLE
Named parameters

### ISSUE THREAD

**Issue by Biegal** [schotime/NPoco#14]
Hi,

Lately I'm trying to use NPoco to execute stored procedures. Biggest problem was to pass named parameters. I was able to do that with few additions and conditions, but I don't like this code very much and it will be hard for me to keep it up to date with changes on main branch.

Do you think this functionality could find it's place in NPoco codebase ?
If so, I could try and figure out better solution for this.

Regards,
Marcin

**Comment by billrawlinson** [comment]
I know this is closed but I have a related question as was reluctant to open a new issue for it.


Let's say I have a stored procedure that returns an integer (not a full model).

Is there a way to use nPoco to execute the stored procedure and get the integer result.

Here is the definition of the procedure:

```sql
CREATE procedure [dbo].[PurgeEventLog](@totalRecordsAffected INT OUTPUT)  as
...
```

I have tried a few different things; the most likely being:

```cs
            int result=0;
            var s = new Sql("EXEC dbo.[PurgeEventLog] @@totalRecordsAffected OUTPUT", result);
            db.Execute(s);
```

However, I get an exception each time:

```
System.Data.SqlClient.SqlException Must declare the scalar variable "@totalRecordsAffected ".
```

I've tried also just having the procedure return a value and using `db.ExecuteScaler<int>` but I just get back `0`.

I also tried using the guidance in @litera blog post but it didn't seem to work either:

```cs
            var totalRecordsAffected = new SqlParameter("@totalRecordsAffected", SqlDbType.Int);
            totalRecordsAffected.Direction = ParameterDirection.Output;

            Sql sql = Sql.Builder.Append("EXEC dbo.[PurgeEventLog] @@totalRecordsAffected out", new
            {
                totalRecordsAffected = totalRecordsAffected
            });

            int result = Database.SingleOrDefault<int>(sql);
            return (int)totalRecordsAffected.Value;

```

I still get the same error:

```
System.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable "@totalRecordsAffected".
```

Any help here would be appreciated.
