### ISSUE TITLE
sql server: can't insert null into varbinary column

### ISSUE THREAD

**Issue by dheijl** [schotime/NPoco#142]
Varbinary maps to byte[], but if you assign null to a byte[] column you get the following exception:

```
System.Data.SqlClient.SqlException: Implicit conversion from data type nvarchar to varbinary is not allowed. Use the CONVERT function to run this query.
Result StackTrace:  
bij System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bij System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bij System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   bij System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   bij System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   bij System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   bij System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   bij System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   bij System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   bij NPoco.Database.ExecuteNonQueryHelper(IDbCommand cmd) in c:\Users\dh\Documents\Visual Studio 2013\Projects\NPoco\src\NPoco\Database.cs:regel 1781
   bij NPoco.Database.Execute(Sql Sql) in c:\Users\dh\Documents\Visual Studio 2013\Projects\NPoco\src\NPoco\Database.cs:regel 618
   bij NPoco.Database.Execute(String sql, Object[] args) in c:\Users\dh\Documents\Visual Studio 2013\Projects\NPoco\src\NPoco\Database.cs:regel 598
```

A simple test to cause the failure:

``` sql
CREATE TABLE [dbo].[Test](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [data] [varbinary](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```

``` csharp
    public partial class Test {
        public int Id { get; set; }
        public byte[] data { get; set; }
    }

...snip...

       db.Insert<Test>(new Test { data = null });  // exception

```

Danny

**Comment by Esfera5** [comment]
Why the workaround? Can't this be part of NPoco itself?

**Comment by dheijl** [comment]
It is now (3.1 dev branch).

**Comment by schotime** [comment]
Will try and get a nuget out tomorrow.

**Comment by marslan390** [comment]
When it will merge to to master? @dheijl

**Comment by Shazwazza** [comment]
Hi, I've just got this same problem but with SqlCe and I'm fine to use a work around, however I've noticed that this 'fix' for Sql server isn't quite right. The fix for the code seems to be here https://github.com/schotime/NPoco/blob/2f41c21af8e8bfa13558b28b2cdbecd604d16655/src/NPoco/DatabaseTypes/SqlServerDatabaseType.cs#L102

But why is the column name hard coded here to `__bytes` ? I don't see any other place in the code where `__bytes` is used. I would have thought the column name would be based on the column name for the Poco?

**Comment by schotime** [comment]
@Shazwazza The column names get rewritten to @0, @1 or ?, ? before execution so the name doesn't really matter at this point.

**Comment by Shazwazza** [comment]
Aha of course, thanks for that. I've got a couple fixes for this locally for SqlCe since it needs the 'Image' column type, do you want me to submit a PR or since SqlCe is pretty much dead, maybe not?

**Comment by schotime** [comment]
You are most welcome to

**Comment by PeterN** [comment]
Probably just hit this issue myself... Does the 6 year old work around still work, or is was that merged and my issue is something else?

**Comment by schotime** [comment]
@PeterN For sql server this should be fixed.

**Comment by PeterN** [comment]
So I get the following exception when trying to save an object with a null byte[] array. The database field is a varbinary (without not null), and I'm using WithFluentConfig set up my table mappings. This particular mapping only contains TableName and PrimaryKey methods.

`System.InvalidCastException: The SqlParameterCollection only accepts non-null SqlParameter type objects, not SqlParameter objects.
   at Microsoft.Data.SqlClient.SqlParameterCollection.ValidateType(Object value)
   at Microsoft.Data.SqlClient.SqlParameterCollection.Add(Object value)
   at NPoco.Database.AddParameter(DbCommand cmd, Object value)
   at NPoco.Database.CreateCommand(DbConnection connection, CommandType commandType, String sql, Object[] args)
   at NPoco.Database.CreateCommand(DbConnection connection, String sql, Object[] args)
   at NPoco.Database.InsertImp[T](PocoData pocoData, String tableName, String primaryKeyName, Boolean autoIncrement, T poco)
   at NPoco.Database.Insert[T](String tableName, String primaryKeyName, Boolean autoIncrement, T poco)
   at NPoco.Database.Save[T](T poco)`

**Comment by zhangb99** [comment]
I have something straightforward like this.  It was working fine in Core 3.1/NPoco 4.0.2, but the exact same code got "SqlParameterCollection only accepts non-null SqlParameter " when upgrading to .NET 5/NPoco 5.1.2

Is there still a bug?

```
    _database.Insert(form);

    [TableName("FormData"), PrimaryKey("Id")]
    public class Form
    {
        public int Id { get; set; }
        public string FormId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string FormData { get; set; }
        public byte[] FormPdf { get; set; }

```
