### ISSUE TITLE
SqlBulkCopy does not like SqlParameter

### ISSUE THREAD

**Issue by dheijl** [schotime/NPoco#147]
I ran into a problem with InsertBulk() on Sql Server.

Given the following mapping for VarBinary (byte[]) columns that can be null:

            public override Func<object, object> GetToDbConverter(Type destType, MemberInfo sourceMemberInfo) {
                if (sourceMemberInfo.GetMemberInfoType() == typeof(byte[])) {
                    return x => {
                        if (x == null)
                            return new SqlParameter("_bytes", SqlDbType.VarBinary, -1) { Value = DBNull.Value };
                        else
                            return new SqlParameter("_bytes", SqlDbType.VarBinary, -1) { Value = (byte[])x };
                    };
                }
                return base.GetToDbConverter(destType, sourceMemberInfo);
            }

InsertBulk() will cause SqlBulkCopy to complain that it can't convert the given value (the SqlParameter from the mapping) to VarBinary.

I used the following work-around in SqlBulkCopyHelper (by using SqlParameter.Value instead of the Sqlparameter if the mapping returned a SqlParameter):

                        var newType = value.GetTheType();
                        if (newType == typeof(SqlParameter)) {
                            values[i] = ((SqlParameter)value).Value;
                        } else {
                            if (newType != null) {
                                table.Columns[i].DataType = newType;
                            }
                            values[i] = value;
                        }

I doubt that this is the proper way to fix it, but it works for me...

**Comment by dheijl** [comment]
Turns out that your change to the pull request (always trying to change the type) does not work: DBNull is not an acceptable type. 
Accidentally discovered when switching from my fork to the latest 2.6.86 nuget.

**Comment by schotime** [comment]
Fix and published in 2.6.87

**Comment by dheijl** [comment]
thanks!

**Comment by dheijl** [comment]
Thanks, I hope I can test it tomorrow.

Danny
 Op 12 jan. 2015 00:04 schreef "Adam Schroder" <notifications@github.com>:

**Comment by dheijl** [comment]
Just tested it, it's OK now!
