### ISSUE TITLE
OUTPUT clause.. add support for it!

### ISSUE THREAD

**Issue by dazinator** [schotime/NPoco#150]
Interested to know what you think of the following and If you would be open to a PR in this area.

Imagine on Insert of a record, there are several database - generated values.
1. The ID (AutoIncrement)
2. Created On Date (DEFAULT to Now)
3. A reference number (some other DEFAULT constraint might generate this)

And on UPDATE of the same record there might be several database generated values:
1. ModifiedOnDate

And on UPDATE or INSERT of the record, there might be a further database generated value:
1. LastModifiedBy

Now, when I insert a POCO, I would want the following properties of my POCO to be automatically set as a result of that INSERT
1. Id
2. CreatedOn
3. ReferenceNo
4. LastModifiedBy

And later when I UPDATE that POCO I would want the following properties to be automatically set as a result of the UPDATE
1. ModifiedOn
2. LastModifiedBy

Ok, so the way I am proposing to solve this is:
1. Create a new `OutputColumn` attribute.
2. Apply that attribute like so:

``` csharp

[TableName("petapoco")]
[PrimaryKey("id")]
class deco_non_explicit
{

        public int Id { get; set; }
        [OutputColumnAttribute(OutputColumnMode.Insert)]
        public DateTime CreatedOn { get; set; }

        [OutputColumnAttribute(OutputColumnMode.Insert)]
        public string ReferenceNumber { get; set; }

        [OutputColumnAttribute(OutputColumnMode.Update)]
        public DateTime ModifiedOn { get; set; }

        [OutputColumnAttribute(OutputColumnMode.Insert | OutputColumnMode.Update)]
        public string LastModifiedBy { get; set; }

}
```

These attributes would then be used during the generation of the SQL INSERT and SQL UPDATE statements. This would basically mean 2 things:
1. An appropriate OUTPUT clause is generated for the DB provider type. (i.e ORACLE, SQL etc)
2. Rather than assuming ExecuteScalar() or ExecuteNonQuery for Inserts / Updates, where there is an OUTPUT clause, we would need to do an ExecuteReader and map the output values back into the appropriate properties. If the POCO also has an AUTOINCRIMENTID, we'd also have to advance to the next ResultSet, and retrieve the ID value.

What do you think of this approach? I am happy to do some work around it..

**Comment by schotime** [comment]
I would probably have to see some of the code to see how it would fit in, but it looks ok.
We would also have to consider the fluent API as well.
We might want to conditionally call executereader as well as it could impact performance.

So, if you want to proceed with a PR we can then discuss the implementation from there.

**Comment by dazinator** [comment]
I made some progress with this, if you'd like to review the commit above, I put a nice lengthy comment on it :)

**Comment by dazinator** [comment]
It seems to be working ok for INSERT, as per the unit tests, I won't proceed with making this work for UPDATE until you have had a chance to review and comment.

**Comment by dazinator** [comment]
If i get a chance this weekend, I will start doing the same for the Update<> method.

**Comment by Pakk1** [comment]
How come this never made to an official release, is there another similar functionality that was developed?

**Comment by dazinator** [comment]
Glad to see this is closed, did the functionality get added in the end? Or was it abandoned?

**Comment by schotime** [comment]
It did not make it, I went through all issues and closed ones that were old and if they're still relevant people can reupdate.
