### ISSUE TITLE
Fluent mappings and composite key issue

### ISSUE THREAD

**Issue by SlyJay** [schotime/NPoco#151]
Hi all,
We are trying to use  npoco  in our production environment. We are using fluent mappings to map some core classes with some table that have different names for composite primary keys. The problem occurs when we use the save method that fails searching for tables names instead of using the property names mapped in fluent configuration.

Am I missing something?

Thanks in advance

Sly

**Comment by schotime** [comment]
How are you creating the Database object?
Are you using the DatabaseFactory?

**Comment by SlyJay** [comment]
Yes. And everything is working fine. Tables with autoincrement key, a custom mapper for managing skins except for composite primary keys. For what I understood, when searching for keys, it first splits using comma then it searchs for properties using table names and not the properties mapped names.

**Comment by SlyJay** [comment]
Here is data mapping class used to create the Database object using DatabaseFactory.

```javascript
internal class DocumentPermissionMap : Map<DocumentPermission>
{
	public DocumentPermissionMap()
	{
		this.CompositePrimaryKey(x => x.DocumentClassId, x => x.GroupId);
		this.TableName("ArchivesPermissions");
		this.Columns(x =>
		{
			x.Column(y => y.DocumentClassId).WithName("ArchivesPermissions_ArchivesId");
			x.Column(y => y.GroupId).WithName("ArchivesPermissions_GroupId");
			x.Column(y => y.Right).WithName("ArchivesPermissions_Rights").WithDbType<string>();
			x.Column(y => y.XMLFilters).WithName("ArchivesPermissions_Filters");
		});
	}
}
```
I had a chance to debug and the problem seems to be the isNew method when it perfoms this cicle:

```javascript
   foreach (var compositeKey in pd.TableInfo.PrimaryKey.Split(','))
                {
                    var keyName = compositeKey.Trim();
                    var pi = poco.GetType().GetProperty(keyName);
                    if (pi == null) throw new ArgumentException(string.Format("The object doesn't have a property matching the composite primary key column name '{0}'", compositeKey));
                }
```
The keyName contains the column name and not the property name so it returns a null value.

May be I'm doing something wrong with mappings.

**Comment by schotime** [comment]
Hey, Just got to this. Apologies.
Should have a new version out in the next couple of days. 
I've already committed it to the new v3 coming soon but will cherry pick back to v2.

**Comment by SlyJay** [comment]
That's great. 
We are currently working with a local version of NPoco with thislittle fix. We will upgrade as soon as you are ready.

Thank you for this wonderful project.

**Comment by schotime** [comment]
Its in 2.10.9
Cheers.
