### ISSUE TITLE
Can I Fetch without knowing type T?

### ISSUE THREAD

**Issue by whoever123** [schotime/NPoco#152]
I have something like Car:Vehicle and Truck:Vehicle and I need to query database that returns either.  Due to the underlining framework restriction, I cannot pass in generic type T, only string.  So I can create a dynamic type from the string, like 

```Type type = typeof(Vehicle).Assembly.GetType("Car");

Is there a way to fetch based on the dynamic type and return a list of Vehicle that contains Car?  Thanks

**Comment by schotime** [comment]
This would probably work. Could create a wrapper for it.

```csharp
Type type = typeof(Vehicle).Assembly.GetType("Car");
var vehicles = db.Query<Vehicle>(new[] { type }, null, "select * from cars");
```

**Comment by whoever123** [comment]
Wow!  This is amazing!  Saved me tons of monkey reflection.  Thank you so much.

    var vehicles = db.Query<Vehicle>(new[] { type }, null, new Sql("select * from cars"));
