### ISSUE TITLE
Auto interface implementation?

### ISSUE THREAD

**Issue by ThisNoName** [schotime/NPoco#153]
Thanks for the great work and all the help.  Just in case you are still looking to add new things.  

One feature I really liked from insight.database is auto interface implementation.  It's basically something like this:

    public interface IUserRepository { 
        [SQL("select * from user where id=@id")]
        List<User> GetUser(int id);

        [SQL("storedprocdoesstuff")]
        void DoStuff(string stuff);
    }

then you can call interface directly and the framework take care of the rest

    IUserRepository repo = db.As<IUserRepository>();
    repo.GetUser(1);

NPoco is so powerful and flexible on the insert/update side, there seems little needs for this.  But queries tend to have more variations.  One common complaint about micro ORM is mixing SQL in line.  Having auto interface would allow clear separation of SQL, with repository, avoid tons boilerplate code, and maybe promote command query segregation?

**Comment by schotime** [comment]
Hi,
That is a pretty cool pattern but we tend to use query objects for inline SQL.
These are pretty easy to create yourself.

```csharp
    public interface IDbQuery<T>
    {
        T Execute(IDatabase db);
    }
```
and here is the IDatabase extension

```csharp
    public static class DbExt
    {
        public static TModel Execute<TModel>(this IDatabase database, IDbQuery<TModel> query)
        {
            return query.Execute(database);
        }
    }
```
which can be used like.
```csharp
    public class GetUsersById : IDbQuery<List<User>>
    {
        private readonly int _userId;

        public GetUsersById(int userId)
        {
            _userId = userId;
        }

        public List<User> Execute(IDatabase db)
        {
            return db.Fetch<User>("select * from users where userid = @0", _userId);
        }
    }
```
and then
```csharp
var users = db.Execute(new GetUsersById(1));
```

**Comment by whoever123** [comment]
That's way too much code ^_^

I think the original concept was around stored procedure.  If you have method name and signature  matching stored procedure, you basically write list of empty interface declaration and nothing else, and it just works.  The sample I show there was actually all the code needed to get it up and running.  

After writing inline SQL with micro ORM for a while, now it doesn't seem a bad idea sweeping them all under one rug, maybe with the few exception of dynamically built  queries.  Really wish there's a way to combine the simplicity of the auto interface with the flexibility of NPoco Fetch/Query. 

Just some random thoughts.  Thanks again for the great work!

**Comment by schotime** [comment]
Yeh most of the time we use LINQ queries with NPoco for simple things like the query above, but for complex ones, the query class makes it really easy to test and really easy to see whats going on. We also chain methods for optional parameters eg.

```csharp
    var users = db.Execute(new GetUsersById(1).AndActive());
```

**Comment by sgrassie** [comment]
@schotime would you mind elaborating a little on the chained method usage? I assume you build up a more complicated query from the chained methods by using an `Sql.Builder` accordingly?

**Comment by schotime** [comment]
@sgrassie Sorry for not getting back to you earlier. Was just going through all the issues and saw this.

That is correct though. Just use the SqlBuilder and the above interfaces.

```csharp
public class MyQuery : IDbQuery<List<User>> 
{
   public string Email {get;set;}
   public MyQuery WithEmail(string email) {
       Email = email;        
       return this;
   }
   public List<User> Execute(IDatabase db)
   {
       var sqlBuilder = new SqlBuilder();
       var template = sqlBuilder.AddTemplate("select * from users where /**where**/ and system_role = @0", "User");
       if (!string.IsNullOrEmpty(Email)) {
           template.Where("email = @0", Email);
       }
       return db.Fetch<User>(template);
   }
}
```

**Comment by whoever123** [comment]
It has been a while and I saw 3.0 is in the working.  Still really love the idea of an AutoInterface.  

I think in most case, people write inline query with micro ORM rather than separate interface is because even in its simplest form, you still have to define interface, write implementation for each method, making connection, call proc, etc., quite a lot boilerplate stuff.

But with the Insight.Database style AutoInterface, there's no implementation, just the interface itself with SQL attached if necessary.  This is all the code you have

    public interface IBeerRepository
    {
        [Sql("GetBeerProc @CategoryId=@id")]
        List<Beer> BeerList(string category);

        [Sql("SELECT * FROM Whatever WHERE @whoever=@para")]
        void GetWhatever(int para);
    }

and when call, you simply write

        IBeerRepository repo = db.As<IBeerRepository>();
        var result = repo.BeerList("draft");

Of course, because NPoco has the power to auto generate SQL, if IBeer inherits IDatabase, there's nothing stop you from taking full advantage of NPoco's flexibility and change tracking, etc.

        repo.Insert(beer);

With this, I would reserve inline query to the most basic form like SingleOrDefault, Insert, etc. and any customized SQL can neatly tucked in one place.  Sounds like the best of both worlds.

**Comment by schotime** [comment]
Happy to take a pull request on this but it is non-trivial. 
NPoco would need to take a dependency on CastleDynamicProxy and all that goes with it.

**Comment by whoever123** [comment]
Thanks for taking time looking into it.

The Insight.Database where I got this idea from doesn't seem to have dependency on Castle.  It looks like it has a extension on db connection, then use reflection.emit to generate implementation of the interface, which also parse the stored proc or sql attribute attached to each interface method.

I don't know enough to tell if it has more to it, or any performance implication, or maybe it has some conflict with NPoco approach.  But it does sound like a great addition to NPoco.  Just the thought of tucking all the raw SQL away without extra boiler plate coding seems worth the price.

https://github.com/jonwagner/Insight.Database/blob/master/Insight.Database/Extensions/DBConnectionExtensions.cs

https://github.com/jonwagner/Insight.Database/blob/master/Insight.Database/CodeGenerator/InterfaceGenerator.cs

**Comment by schotime** [comment]
My point was, that it is not trivial and using castle would be the easiest without re-implementing the wheel.
