### ISSUE TITLE
Select Distinct

### ISSUE THREAD

**Issue by ghotiphud** [schotime/NPoco#154]
I've tried several methods to select distinct, but I had to drop back to the SqlBuilder to make it happen.  Is the SelectDistinct method functional?  Also, how would I select more than one column using this method?

Attempt:
```csharp
var requests = testDB.FetchBy<TEST_TABLE>(query =>
    query.SelectDistinct(x => x.Col1)
        .Where(x => x.Col2 == "001" )
);
```

Working:
```csharp
var sqlBuilder = new SqlBuilder();
var template = sqlBuilder.AddTemplate("Select Distinct /**select**/ from Test.Table where /**where**/");
            
sqlBuilder
    .Select("Col1")
    .Where("Col2= @0", "001");
```

**Comment by ghotiphud** [comment]
I figured out the SelectDistinct(x => new { x.Col1, x.Col2 }) formatting to return more than one column, but it's still not actually doing the distinct query.

Additionally, I'm getting the below error:

```
 A first chance exception of type 'System.InvalidOperationException' occurred in System.Core.dll

Additional information: variable 'x' of type 'AAADAL.POC_SERVICE_REQUEST' referenced from scope '', but it is not defined
```

**Comment by schotime** [comment]
There is now a Distinct Method on the `Query<T>` method on IDatabase.
Give it a try.
Have made the change in https://github.com/schotime/NPoco/wiki/Revision-History#2791-beta
It is in 2.7.91-beta on NuGet.
Let me know if it works for you.

**Comment by techniq** [comment]
I guess my PR https://github.com/schotime/NPoco/pull/143 can be closed?
