### ISSUE TITLE
WITH clause in sql

### ISSUE THREAD

**Issue by andersjonsson** [schotime/NPoco#157]
Using a WITH clause results in a broken sql statement.

Simplified example:

    var ndb = new MyDb(db2.Connection); //using the MyDb class from your debugging example
		
    ndb.Execute("CREATE TABLE #transactions (id INT, clientid INT, value INT)");
    ndb.Execute("INSERT INTO #transactions (id, clientid, value) VALUES (1, 1, 100)");
    ndb.Execute("INSERT INTO #transactions (id, clientid, value) VALUES (2, 2, 120)");
    ndb.Execute("INSERT INTO #transactions (id, clientid, value) VALUES (3, 1, 12)");
    ndb.Execute("INSERT INTO #transactions (id, clientid, value) VALUES (4, 2, 84)");
    ndb.Execute("INSERT INTO #transactions (id, clientid, value) VALUES (5, 2, 5)");
		
    ndb.Execute("CREATE TABLE #clients (id INT, clientname VARCHAR(50))");
    ndb.Execute("INSERT INTO #clients (id, clientname) VALUES (1, 'client 1')");
    ndb.Execute("INSERT INTO #clients (id, clientname) VALUES (1, 'client 2')");
	
    var result = ndb.Fetch<dynamic>(@"WITH transactionsums as (SELECT SUM(value) totalSum, clientid FROM #transactions GROUP BY clientid )
    SELECT * FROM #clients cl
    INNER JOIN transactionsums ts ON ts.clientID = cl.clientID
    ");

Running this example results in the sql query:

SELECT  FROM [Object] WITH transactionsums as (SELECT SUM(value) totalSum, clientid FROM #transactions GROUP BY clientid )
    SELECT * FROM #clients cl
    INNER JOIN transactionsums ts ON ts.clientID = cl.id

without the "SELECT  FROM [Object]" part, it works.

Is there a way to tell NPoco to leave my query alone?

**Comment by warrenrumak** [comment]
Hi Anders, yes, put a semicolon before "WITH".  Make sure it's the first character in the query. (See the related code in AutoSelectHelper.cs)

Also -- putting a semicolon before a with statement is a good habit to get into since it's one of the few statements in T-SQL that will fail if it's not the first query in a batch.

**Comment by andersjonsson** [comment]
That did the trick!

Thanks
