### ISSUE TITLE
Dynamic parameters

### ISSUE THREAD

**Issue by andersjonsson** [schotime/NPoco#158]
I have a few sql queries that is composed at runtime.
The Where clause is built in several stages, which means that the number of parameters can alter between executions. This is old, messy code and I don't have the time to rebuild it all right now.
Going from DataTables to Pocos will be good enough for now :)

I've tried using:
Dictionary<string, object> (parametername, value),
dynamic (expandoobject)
List<SqlParameter>

If I use numbered parameters (@0, @1 and so on) I can get it to work, but the numbers would have to be altered between executions, so it'll result in quite messy code.

Any suggestions?

**Comment by schotime** [comment]
This is what we use to build where clauses.

https://github.com/schotime/NPoco/wiki/Sql-Templating

**Comment by andersjonsson** [comment]
Hi,

Thank you for answering!

That might be feasible, but this is a really big (and quite scary) sql query with subselects, 
cross applies etc.

Named parameters would be a lot more clear, if it's possible.

**Comment by schotime** [comment]
You can already do that.

```csharp
db.Fetch<User>("select * from users where user_id = {user_id}", new { user_id = 1 });
```

The object can be a poco or anonymous object.

**Comment by andersjonsson** [comment]
Yes, but since the number of parameters will vary it would be nice to be able to use a dictionary(string, object)

Thanks for your answers. I guess I'll create a Poco with all possible parameters, whether I use them or not.

**Comment by schotime** [comment]
Wouldn't be that bad of a pull request if you want to submit one.

**Comment by andersjonsson** [comment]
I'll take a look at doing that.

**Comment by andersjonsson** [comment]
Sent a pull request. My first ever, so I'm not sure if I did it correctly.

**Comment by andersjonsson** [comment]
Sent a new pull request. Not sure that I understand all of this branching stuff yet.
Hopefully it's ok :)
