### ISSUE TITLE
Unexpected behaviour of SingleInto with nullable DateTime

### ISSUE THREAD

**Issue by rhegner** [schotime/NPoco#161]
I came across a strange behaviour of `SingleInto` with a nullable DateTime column. The steps to reproduce the problem are:
1) Insert a row where the DateTime column is NULL.
2) Read the row into POCO t5 (see code below) with `SingleInto`. Everything is as expected.
3) Set the DateTime field of POCO t5 to a non-NULL value (only in memory, don't write to database)
4) Read the row again into POCO t5 with `SingleInto`. I would expect that the DateTime field is again set to NULL by `SingleInto`, but instead it keeps the non-NULL value.

Is this a bug in NPoco? Or am I doing something wrong? Or am I just misunderstanding how `SingleInto` is supposed to work?

Below you can find a complete and self-contained samle program to reproduce the problem.

```C#
using NPoco; // Nuget 2.7.93
using System;
using System.IO;

namespace NPocoDateTimeTest
{
	class Program
	{

		[TableName("TestTable")]
		[PrimaryKey("TestTableId", AutoIncrement = false)]
		class TestTable
		{
			public Guid TestTableId { get; set; }
			public DateTime? Timestamp { get; set; }

			public override string ToString() { return String.Format("{0} - {1}", TestTableId, Timestamp); }
		}

		static void Main(string[] args)
		{

			var filename = "test.dat";
			using (var fs = File.Create(filename)) { }
			var db = new Database(String.Format("data source = '{0}'; persist security info = false", filename), DatabaseType.SQLCe);

			db.Execute("CREATE TABLE TestTable (TestTableId uniqueidentifier NOT NULL PRIMARY KEY, Timestamp datetime NULL)");

			var t1 = new TestTable() { TestTableId = Guid.NewGuid(), Timestamp = null };
			db.Insert(t1);
			Console.WriteLine("t1: {0}", t1);

			var t2 = new TestTable() { TestTableId = Guid.NewGuid(), Timestamp = DateTime.UtcNow };
			db.Insert(t2);
			Console.WriteLine("t2: {0}", t2);

			var t3 = db.Single<TestTable>("WHERE TestTableId = @0", t1.TestTableId);
			Console.WriteLine("t3: {0} - ok, same as t1", t3);

			var t4 = db.Single<TestTable>("WHERE TestTableId = @0", t2.TestTableId);
			Console.WriteLine("t4: {0} - ok, same as t2", t4);

			var t5 = new TestTable();
			db.SingleInto(t5, "WHERE TestTableId = @0", t1.TestTableId);
			Console.WriteLine("t5: {0} - ok, same as t1", t5);
			t5.Timestamp = DateTime.UtcNow;
			Console.WriteLine("t5: {0} - modified in memory", t5);
			db.SingleInto(t5, "WHERE TestTableId = @0", t1.TestTableId);
			Console.WriteLine("t5: {0} - WOULD EXPECT SAME AS t1 AFTER READING AGAIN!!!", t5);

			var t6 = new TestTable();
			db.SingleInto(t6, "WHERE TestTableId = @0", t2.TestTableId);
			Console.WriteLine("t6: {0} - ok, same as t2", t6);

			Console.ReadKey();
		}
	}
}

```

**Comment by schotime** [comment]
NPoco does not set the values for any column if they are they are null. Therefore what ever the default/current value of the property is, then that will be still the case after trying to map a null value.

What is the use case?

**Comment by rhegner** [comment]
The use case is like this:

In my WPF application I data-bind the GUI directly to these POCO. When the user edits one of these objects, he has the possibility to apply or discard the changes he made to the POCO. 

Now for 'apply' I do an `Update` on the database and for 'discard' I use `SingleInto` to reset all the fields of the POCO to the values stored in the database.

This works perfectly but not for nullable columns.

Currently I'm using the following workaround: In my discard methods I set all the fields corresponding to nullable columns to `Null` before calling `SingleInto`.

I don't understand the rationale behind the current behaviour of NPoco. For me it would be much more intuitive if after `SingleInto` the POCO would just contain exactly what's stored in the database - no matter if it  is a null value or not.

**Comment by schotime** [comment]
This is not how NPoco/PetaPoco work right now so I would need to do some testing and see if this needs to be a switch.

**Comment by schotime** [comment]
This will be the default behaviour when mapping to an existing instance in v3.

**Comment by rhegner** [comment]
Very nice! Do you plan to release v3 soon?
Btw, do you publish change logs for the versions you make available on Nuget somewhere? I couldn't find any change logs for NPoco...

**Comment by schotime** [comment]
There will be an alpha of v3 within the next few weeks. That is my plan anyways.
https://github.com/schotime/NPoco/wiki/Revision-History

**Comment by schotime** [comment]
Implemented in V3 now in alpha on NuGet
