### ISSUE TITLE
Insert<T>() does't seems to return primary key for a table with autoIncrement=fase and composite primary keys

### ISSUE THREAD

**Issue by joonhwan** [schotime/NPoco#164]
Hi, Thanks for sharing this neat library. BTW

As in 

https://github.com/schotime/NPoco/blob/master/src/NPoco/Database.cs#L1311-L1314

, if primaryKeyName is like "RuleBatchId, RuleId" (as learn in https://github.com/schotime/NPoco/wiki/Composite-Primary-Keys)
, ...then it returns null. 

Would it be possible to return a dynamic object containing those primary key fields

**Comment by schotime** [comment]
Do you have an example of how you want that data returned considering its already in the object.

**Comment by BrunoAbreuCoreCard** [comment]
Probably he's talking about when we are inserting some record in a table with composite keys, we want the whole new row to be returned, or at least its composite keys, which NPOCO does not do yet, it always returns null. Can we re open this issue?

**Comment by schotime** [comment]
You already have the composite keys, as you inserted them.

**Comment by BrunoAbreuCoreCard** [comment]
@schotime Yeah sure, in that case, but what if the PKs are both auto generated by database?
