### ISSUE TITLE
async1 branch: Query<T>().Where(...).FirstOrDefault() broken for SqlServer 2012 database type

### ISSUE THREAD

**Issue by dheijl** [schotime/NPoco#165]
In the following statement:

    db.Query<SomeTable>().Where(st => st.SomeProperty == "x").FirstOrDefault()

FirstOrDefault() adds a limit(1) clause to the sql, but as there is no order by present the query fails and throws the following exception:

  `Sql Server 2012 Paging via OFFSET requires an ORDER BY statement.`

**Comment by schotime** [comment]
Ideally you should add an orderby if you are doing a FirstOrDefault otherwise why use first if you are expecting more than one result. and If you are expecting more the one result, talking the first one doesn't mean anything without an orderby.

**Comment by dheijl** [comment]
I'm expecting one or none here, so I should really use SingleOrDefault instead...
