### ISSUE TITLE
Inherited POCOs do not work as expected (NPoco attributed are not read)

### ISSUE THREAD

**Issue by konstk** [schotime/NPoco#166]
We use generated pocos with explicit column name mapping. It is so happens that we must in certain circumstances dynamically create classes inherited from POCOs. It this situation, the attributes are not read correctly by the ColumnInfo class. We fixed it locally, but now we cannot use NuGet to keep NPoco up-to-date.

The change is quite trivial:
ColumnInfo.cs

            var attrs = mi.GetCustomAttributes(true);

Should be replaced with:

            var attrs = Attribute.GetCustomAttributes(mi, true);

If you can integrate this change, it will help us a lot!

Thanks in advance!

Konst

**Comment by schotime** [comment]
What version are you using?

**Comment by konstk** [comment]
Whatever version is in "master" branch at the moment. I expect it to be the latest stable version.

**Comment by konstk** [comment]
I also downloaded the latest tag 2.6.88, the code seems the same in ColumnInfo.cs

**Comment by konstk** [comment]
Just downloaded the latest package from Nuget to test. Cannot read properties which are overridden. Here is a simple test (Name property in the derived class is NULL after reading from the database):

    class Program
    {
        [TableName("Test")]
        [PrimaryKey("ID")]
        [ExplicitColumns]
        public partial class MyBase
        {
            [Column("ID")]
            public virtual int Id { get; set; }
            [Column("Name")]
            public virtual string Name { get; set; }
        }

        public class MyClass : MyBase
        {
            public override string Name
            {
                get
                {
                    return base.Name;
                }
                set
                {
                    base.Name = value;
                }
            }
        }

        static void Main(string[] args)
        {
            Database db = new Database("MyDb");

            // gem1.ID has value, gem1.Name has value
            var gem1 = db.Fetch<MyBase>().First();

            // gem2.ID has value, gem2.Name is NULL
            var gem2 = db.Fetch<MyClass>().First();

        }
    }

**Comment by konstk** [comment]
MSDN:
https://msdn.microsoft.com/en-us/library/dwc6ew1d.aspx

Remarks (from MSDN on the same page)
This method ignores the inherit parameter for properties and events. To search the inheritance chain for attributes on properties and events, use the appropriate overloads of the Attribute.GetCustomAttributes method. 

Thus, it is documented that for properties mi.GetCustomAttributes(true) will NOT traverse the hierarchy and Attribute.GetCustomAttributes(mi, true) should be used.

**Comment by schotime** [comment]
Ok.
Fixed in 2.7.101

**Comment by konstk** [comment]
Thank you very much!!!

**Comment by konstk** [comment]
Did a quick check with 2.7.101, works great! Issue closed.
