### ISSUE TITLE
Cannot specify table as parameter for BulkInsert

### ISSUE THREAD

**Issue by Arithmomaniac** [schotime/NPoco#168]
For the old PetaPoco methods, you can usually manually specify the table you want them to go into:

```csharp
pocodb.Insert("Schema1.Artifact", "ArtifactID", artifact)
```

Can this be added to `BulkInsert`? Like so:

```csharp
pocodb.Bulk(artifacts, "Schema1.Artifact")
```

**Comment by schotime** [comment]
You can just add the `[TableInfo("Schema1.Artifact")]` attribute to the Artifact class.
