### ISSUE TITLE
Save<T>(T object) overload missing

### ISSUE THREAD

**Issue by troyji** [schotime/NPoco#169]
@schotime 

I am trying to upgrade from PetaPoco to the NPoco (2.7.101) NuGet package.  NPoco does not support the `Save<T>(T object)` overload.  This overload infers the object type so that I do not have to explicitly define the type in the call.  Because it is not supported, I would have to go to all my calls to `Save(myObject)` and add the types, `Save<MyType>(myObject)`.

**Comment by schotime** [comment]
I will have a look into it

**Comment by schotime** [comment]
Implemented in v3
