### ISSUE TITLE
Using dynamic in queries appears broken

### ISSUE THREAD

**Issue by sgrassie** [schotime/NPoco#171]
After upgrading to 2.7.101 from 2.6.88, some of my queries which use e.g. `Database.Fetch<dynamic>(sql)` have stopped working. By 'stopped working', I mean that all I can see in the debugger is that `{object}` is returned, and none of the expected properties are available.

This is in code which hasn't changed for around a year. The data (in sql server) is fine, and the queries return data when ran from SSMS.

I've cloned the repo and I've tried to debug through the issue to see if I can spot what's going on, without success. The `PocoExpandoTests` all passed when I just ran them.

For the time being, I've reverted the NPoco package to 2.6.88, to get around the problem. If anyone has any suggestions for areas/things I could look at in the NPoco code, I will try to debug it further. Looking through the commit logs, nothing stands out to me which is an obvious candidate for causing this.

Also, there don't appear to be any other issues raised for this, which tells that either 1) no one else uses `dynamic` in queries, 2) no one who uses dynamic in queries has yet to upgrade to 2.7.101, or 3) something else I've overlooked in my code is causing the problem.

If it comes to it, I will remove the `dynamic` queries and add POCOs, although that's some work I'd like to avoid if possible.

**Comment by schotime** [comment]
Weird.
Here is a screenshot of the latest.

![image](https://cloud.githubusercontent.com/assets/202923/7739001/505ef450-ff9e-11e4-8e4e-4bc4eb665336.png)

Can you send further information about your query? scenario?

**Comment by sgrassie** [comment]
Yes, that's exactly what I see when I run the tests.

My setup is: Windows 8.1 64bit, VS2013 .NET 4.5, SQL Server 2012. The application itself is an ASP.NET MVC site.

In order to remove any of my own doubt about any problems I might have introduced into the application, I just created a brand new and very simple console app and added the latest stable NPoco from Nuget, v2.7.101, added the same connection string as my application, and was able to reproduce the problem:

![npoco_dynamic](https://cloud.githubusercontent.com/assets/194140/7743437/b4155b9e-ff92-11e4-9c3b-a410d5a7b9bb.png)

This table is a typical 'product' table, this query is straightforward, and the count _is_ correct.

I've also just tried changing the version of the package through some of the ones on Nuget:

- 2.6.88 *working*
- 2.6.89-beta *working*
- 2.6.90-beta *working*
- 2.7.91-beta *working*
- 2.7.93-beta *working*
- 2.7.95-beta *NPoco namespace missing*
- 2.7.96 *working*
- 2.7.101 *not working*
- 2.8.97-beta *NPoco namespace missing*
- 2.8.98-beta *NPoco namespace missing*
- 2.8.99-beta *NPoco namespace missing*

If you need any further information, let me know. I'm also open to suggestions of areas of code to debug to see if I can spot the problem.

**Comment by sgrassie** [comment]
Additionally, I've just build the `dev2.0` branch in `release` mode and replaced the assembly in the above console application, and it works fine. So I'm stumped.

**Comment by schotime** [comment]
I think I found the culprit. All my fault unfortunately. 
Somehow when I did the build it failed to checkout the correct version and so it was running an older version. Hopefully 2.8.102 fixes things.

Had some issues with semantic versioning hence the change to 2.8.

Apologies again and thanks for your help.

**Comment by sgrassie** [comment]
I can confirm that this issue is resolved in 2.8.102.

Thanks @schotime!
