### ISSUE TITLE
V3 one-to-many

### ISSUE THREAD

**Issue by dheijl** [schotime/NPoco#172]
The V3 wiki page only mentions many-to-one (foreign key) relationships.

Now that FetchOneToMany is gone, will one-to-many relations also be supported?

V3 looks good!

**Comment by schotime** [comment]
Not at the moment, maybe not ever.
I'm still trying to keep it lite at heart and I think that one to many will complicated that. Especially when most of the time you can do it with two queries or project it from a flat model.

Its definitely taking shape.

If you have time to test it that would be great. You will need to download the source and run the build scripts though at the moment. Will release a nuget alpha when comfortable most things work.

**Comment by dheijl** [comment]
I already compiled it and did some tests yesterday (with reference properties and Include queries).

I've been using the FetchOneToMany functionality of the previous versions a lot, but now discovered that the V3 Include syntax does not handle it. It may complicate things for you but it makes life a lot sweeter for us simple users...

**Comment by schotime** [comment]
How would you expect it to work?

**Comment by dheijl** [comment]
I was perfectly happy with the old Relation Extensions for PetaPoco and with how FetchOneToMany worked in NPoco before V3. I found it one of the really productive features when mapping from relational data to objects. It has also better performance that firing an extra query for each master record. I suppose that reference properties/Include would have to support Lists. 
But I suppose it would not be a trivial change in V3...

**Comment by schotime** [comment]
What if the many table then had relations? 
Would you expect they would be loaded also?

**Comment by dheijl** [comment]
Not really, I think that's the time to start thinking about the entity framework ...

**Comment by dheijl** [comment]
Thanks ever so much for bringing back one to many, what made you decide you to do it?

**Comment by schotime** [comment]
> Not really, I think that's the time to start thinking about the entity framework...

Haha, then its time to rethink programming.

**Comment by schotime** [comment]
> Thanks ever so much for bringing back one to many, what made you decide you to do it?

Wasn't about deciding to do it, more about whether it was feasible with the new model and how it was going to look.

**Comment by dheijl** [comment]
> ... time to rethink programming.

Agreed. 

> ... and how it was going to look.

A valid concern.

**Comment by dheijl** [comment]
I tried IncludeMany() but couldn't get it to work. Should it work? 
FetchOneToMany seems impractical with the weird SQL syntax with the underscores.

**Comment by schotime** [comment]
Well with out knowing what you did,  its pretty hard to help you out. Did you follow the test? What was the error? Did you use the reference attribute? 

As far as the syntax goes that is the generic way in v3 to map any type of object whether its nested or not. Its the convention.

**Comment by dheijl** [comment]
[PrimaryKey("OrganisatieId")]   
    public class Organisatie {
        public int OrganisatieId { get; set; }
        [Reference(ReferenceMappingType.Many, Name = "OrganisatieId", ReferenceName = "OrganisatieId")]
        public List<Gebruiker> Gebruikers { get; set; }
        ...snip...
    }

    [PrimaryKey("GebruikerId")]
    public class Gebruiker {
        public int GebruikerId { get; set; }
        public int OrganisatieId { get; set; }
        ...snip...
    }

    var result = db.Query<Organisatie>().IncludeMany(o => o.Gebruikers).OrderBy(o => o.OrganisatieId).ToList();

The result is an Organisatie row with one Gebruiker for every Gebruiker in that Organisatie. What am I missing?
         
IMHO the new mapping convention sql syntax is a step backwards compared to the original relation extensions syntax for PetaPoco. I don't mind that the new syntax is used internally by the linq query provider, but I can't imagine writing it myself, or having someone else see it...

**Comment by schotime** [comment]
What was the SQL produced? Does it return the correct results?

**Comment by dheijl** [comment]
The sql was correct:

`SELECT [O].[OrganisatieId] as [OrganisatieId], [O].[TermID] as [TermID], [O].[Niscode] as [Niscode], [O].[INACode] as [INACode], [O].[Kanaal] as [Kanaal], [O].[Permission] as [Permission], [O].[Benaming] as [Benaming], [O].[UpdUser] as [UpdUser], [O].[UpdMachine] as [UpdMachine], [O].[UpdTime] as [UpdTime], [G].[GebruikerId] as [Gebruikers__GebruikerId], [G].[OrganisatieId] as [Gebruikers__OrganisatieId], [G].[NN] as [Gebruikers__NN], [G].[Naam] as [Gebruikers__Naam], [G].[Transacties] as [Gebruikers__Transacties], [G].[EnotEmail] as [Gebruikers__EnotEmail], [G].[InaNr] as [Gebruikers__InaNr], [G].[UpdUser] as [Gebruikers__UpdUser], [G].[UpdMachine] as [Gebruikers__UpdMachine], [G].[UpdTime] as [Gebruikers__UpdTime] 
FROM [Organisatie] [O]  
LEFT JOIN Gebruiker [G] ON [O].[OrganisatieId] = [G].[OrganisatieId]  
ORDER BY [OrganisatieId] ASC`

**Comment by schotime** [comment]
Do the results actually have a many? It compares the primary key value of the previous row to determine. Was the primary key value mapped in?

**Comment by dheijl** [comment]
Yes, there are many manys for most of the Organisatie objects.
What do you mean by "Was the primary key value mapped in" ?
The result list is simply the result of the query without mapping the Gebuiker objects in the list. Every Organisatie object is repeated as many times as there are Gebruiker objects linking to that Organisatie, with the Gebruikers list containing just the 1 Gebruiker object from that row.   

To give you an idea of the keys involved:

`SELECT [O].[OrganisatieId] as [OrganisatieId], [G].[GebruikerId] as [Gebruikers__GebruikerId], [G].[OrganisatieId] as [Gebruikers__OrganisatieId]
FROM [Organisatie] [O] 
LEFT JOIN Gebruiker [G] ON [O].[OrganisatieId] = [G].[OrganisatieId] 
ORDER BY [OrganisatieId] ASC`

results in the following:

   919	10014	919
   919	8273	919
   919	7583	919
919	8391	919
919	8281	919
919	7620	919
919	7660	919
919	8158	919
919	7751	919
919	8159	919
919	7797	919
919	7837	919
919	7876	919
919	7889	919
919	7904	919
919	8200	919
919	8161	919
919	7953	919
919	7959	919
919	8160	919
919	8162	919
919	8041	919
920	7625	920
920	9501	920
920	7839	920
920	7873	920
920	7970	920
920	7977	920
920	9112	920
920	8223	920
920	8049	920
920	8100	920
920	8102	920
920	8104	920
920	8383	920
920	8428	920
920	8753	920
920	8731	920
920	8891	920
920	9735	920
920	9553	920
920	9428	920
920	9379	920
920	9409	920
920	9801	920
920	9278	920
920	9802	920
920	10009	920
921	7519	921
921	7541	921
921	7553	921
921	7599	921
921	7627	921
921	7639	921
921	7644	921
921	7663	921
921	7671	921
921	7679	921
921	9407	921
921	8450	921
921	7799	921
921	7800	921
921	7827	921
921	7830	921
921	9137	921
921	9028	921
921	7903	921
921	7909	921
921	8190	921
921	7926	921
921	8950	921
921	7946	921
921	7962	921
921	7975	921
921	7980	921
921	9322	921
921	8017	921
921	8219	921
921	8363	921
921	8032	921
921	9615	921
921	9026	921
921	8072	921
921	8085	921
921	9029	921
921	8432	921
921	9287	921
921	8414	921
921	8540	921
921	8531	921
921	9027	921
921	8967	921
921	8999	921
921	8802	921
921	8825	921
921	8807	921
921	8364	921
921	9059	921
921	9617	921
922	7548	922
922	7568	922
922	7574	922
922	7577	922
922	8905	922
922	7928	922
922	8965	922
922	8051	922
922	8963	922
923	7597	923
923	7637	923
923	7653	923
923	7678	923
923	9307	923
923	9922	923
923	9092	923
923	9058	923
923	9474	923
923	9306	923
923	8225	923
923	9523	923
923	9091	923
923	9264	923
923	8852	923
923	9524	923`

and so on ...

**Comment by schotime** [comment]
Hmmm....
That looks correct.
Are you running on the latest version?
Can you try and run this.

```csharp
var result = db.Query<Organisatie>().IncludeMany(o => o.Gebruikers).OrderBy(o => o.OrganisatieId).ToList();
var pd = db.PocoDataFactory.ForType(typeof(Guard));
var pk = pd.GetPrimaryKeyValues(result.First());
```

Let me know what pk returns. Its should be an object array with the primary key value as the first item.

**Comment by dheijl** [comment]
I'm using the latest dev3 version cloned and synced from Github.

pk returns a Gebruiker object with all properties set.

**Comment by schotime** [comment]
hmmm...thats not right

**Comment by schotime** [comment]
should be [919] for the first row.

**Comment by dheijl** [comment]
quickwatch attached

![pk](https://cloud.githubusercontent.com/assets/2384545/8130108/297682d0-1110-11e5-8149-cbd5466e1597.jpg)

**Comment by schotime** [comment]
OK. Well that's why it isn't working. Gives me something to go on now. Thanks for that. Very strange that my one/many test is virtually the same as this. 

Will take a look tomorrow.

**Comment by dheijl** [comment]
Thanks, appreciated!

**Comment by schotime** [comment]
I have recreated your exact example and it works as expected. Can you ensure you are running https://github.com/schotime/NPoco/commit/6043334a3057dbb50da8ce880dc2e0b99f2d32ec . You may be have to reclone or reset from that branch because I rebased it from dev2.0 yesterday. 

Checkout this test to see if there are any differences  https://github.com/schotime/NPoco/blob/6043334a3057dbb50da8ce880dc2e0b99f2d32ec/src/NPoco.Tests/NewMapper/NestedConventionTests.cs#L195

**Comment by dheijl** [comment]
> because I rebased it from dev2.0 yesterday

So that's why git wouldn't sync properly, and I had to reclone.

I don't see anything different in the test.

I'll start from scratch later today and will let you know how it goes.

**Comment by dheijl** [comment]
I started from scratch with the 6043334 download and all is well.
Results are now as expected, and the following unit test runs and produces the expected output:

       [Test()]
        [Category("Dev3.0")]
        public void GetOrganisatiesWithGebruikersTest() {
            using (IDatabase db = new Database(NPocoTestLibTests.Properties.Settings.Default.NPocoTestDb, DatabaseType.SqlServer2012)) {
                db.Execute("truncate table Gebruiker");
                db.Execute("delete from Organisatie");
                for (int i = 0; i < 10; ++i) {
                    db.Insert(new Organisatie { SomeData = i.ToString() });
                }
                var orgs = db.Query<Organisatie>().ToList();
                foreach (var o in orgs) {
                    for (int i = 0; i < 10; i++) {
                        db.Insert<Gebruiker>(new Gebruiker { OrganisatieId = o.OrganisatieId, SomeData = i.ToString() + "__" + o.SomeData });
                    }
                }
                var result = Organisatie.GetOrganisatiesWithGebruikers(db);
                Assert.That(result, Is.Not.Null);
                Assert.That(result.Count(), Is.EqualTo(10));
                foreach (var r in result) {
                    Assert.That(r.Gebruikers, Is.Not.Null);
                    Assert.That(r.Gebruikers.Count, Is.EqualTo(10));
                    Console.WriteLine(r.SomeData);
                    foreach (var g in r.Gebruikers) {
                        Console.WriteLine("  " + g.SomeData);
                    }
                }
            }
        }

where:

    public partial class Organisatie
    {
        [Reference(ReferenceMappingType.Many, Name = "OrganisatieId", ReferenceName = "OrganisatieId")]
        public List<Gebruiker> Gebruikers { get; set; }

        public static IEnumerable<Organisatie> GetOrganisatiesWithGebruikers(IDatabase db) {
            return db.Query<Organisatie>().IncludeMany(o => o.Gebruikers).OrderBy(o => o.OrganisatieId).ToList();
        }
    }

There must have been a problem with my dev 3.0 clone.

Sorry for bothering you with this, and thanks again for the OneToMany!

**Comment by schotime** [comment]
Awesome!!!
Gotta stop scaring me like that. 
Thanks for providing all the information to get to the bottom of it..

**Comment by dheijl** [comment]
I'm sorry to have you scare you again, but it still doesn't work, dependent on the number of columns and the column names. 

But the fix is simple: in PocoData.cs, line 178 I made the following change to make it work:

    var members = multiplePrimaryKeysNames
        Select(x => Members.FirstOrDefault(y => y.PocoColumn != null && y.ReferenceMappingType == ReferenceMappingType.None && string.Equals(x, y.PocoColumn.ColumnName, StringComparison.OrdinalIgnoreCase)))
        .Where(x=>x != null);

The reason: the reference property came first in the Members list and had as PocoColumn.ColumnName the name of the primary key...

Ignoring reference properties fixes it.

**Comment by schotime** [comment]
Ahhh...you know what. I thought about that the other day but discounted it for some reason. Nice catch.
Pushed ;)
