### ISSUE TITLE
V3: Property with underscore is not read in

### ISSUE THREAD

**Issue by konstk** [schotime/NPoco#173]
Tested after your last commit with the mapping fix (when Column mapping is different from property name). There is one small bug still remains. I have the following object:

```csharp
[TableName("scanners")]
[PrimaryKey("ID")]
[ExplicitColumns]
public partial class Scanner
{
	[Column("ID")]
	public virtual long ID { get; set; }
	[Column("scanner")]
	public virtual string _Scanner { get; set; }
}
```
For the property ```_Scanner``` the data is not read (value is NULL). If I change the property name to, for example, ```AScanner```, it works.

**Comment by schotime** [comment]
Nice find.
Fixed in db038f4

**Comment by konstk** [comment]
Got the latest version. I get ```NullReferenceException``` in ```IsEqual(GroupResult<PosName> groupedName, string value)```, value parameter is null (groupedName is the property with underscore).

**Comment by schotime** [comment]
Fixed in latest.

**Comment by konstk** [comment]
Tested, it works now! Thank you!
