### ISSUE TITLE
What is the preferred method to move from PetaPoco to NPoco in an existing project using NuGet 

### ISSUE THREAD

**Issue by achaffman** [schotime/NPoco#175]
I'm weary of removing PetaPoco without knowing what needs to be changed in order to switch my code to NPoco.  Any recommendations?

It looks like NPoco is an assembly whereas PetaPoco was just source added under /Models

The documentation seems to be lacking in this area.  Thanks for assistance!

**Comment by csharpforevermore** [comment]
Just follow best practice and make sure you back-up / check-in first. 

NPoco is made from a fork of the PetaPoco source, so all but the latest commits will be identical. I would be surprised if you have much of a problem, and I still sometimes look up a solution for PetaPoco when using NPoco. If it doesn't work, then I search for the solution in NPoco specifically.

**Comment by achaffman** [comment]
are the file names still the same? the TT files, etc and in the same locations?  as i said I'm installing using NuGet.  The NuGet installation didn't display any errors or warnings.

**Comment by csharpforevermore** [comment]
Most of the files are the same. The namespaces have been changed though so
it is possible to install both. To actually upgrade, uninstall PetaPoco and
fix the references.

​If you have no errors then I would accept the upgrade and perform a manual
integration test.

I am sure you'll be fine.  Also - PetaPoco hasn't been updated in some time
so chances are they are almost identical - except for the extra
enhancements in NPoco.​

**Comment by achaffman** [comment]
The big thing i ran into that i'm hoping is corrected in Npoco is paging when using distinct in the query.  With petapoco it throws an exception on the count query that has to run because it is not handling the distinct properly.  I just want something that is maintained.  I've had little problems with Petapoco and i like using it, so Npoco seems to be the natural choice

**Comment by csharpforevermore** [comment]
I believe this is what you want then:
https://github.com/schotime/NPoco/issues/154 ?

**Comment by schotime** [comment]
Closed due to cleanup. Reopen if necessary.
