### ISSUE TITLE
Upgrading from 2.6.88 breaks paged query

### ISSUE THREAD

**Issue by firedog** [schotime/NPoco#177]
The following query works with paging in 2.6.88 but breaks in later versions of NPoco.
```SQL
SELECT *
FROM accommodations a
ORDER BY LEN(name) asc, name asc -- Natural sort order approximation to get A1, A2, ..., A9, A10 instead of A1, A10, A2, ...
```

NPoco releases after 2.6.88 will issue the following count query...
```SQL
SELECT COUNT(*) FROM (SELECT *
FROM accommodations a
ORDER BY LEN(name) asc, name asc) peta_tbl
```

...which will fail with error:
Msg 1033, Level 15, State 1, Line 4
The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.

In version 2.6.88 the (working) count query issued is:

```SQL
SELECT COUNT(*) FROM (SELECT *
FROM accommodations a
) peta_tbl
```

I am using DatabaseType.SqlServer2012 when setting up the DatabaseFactory

**Comment by schotime** [comment]
Hi @firedog 

Thanks for raising this issue.
I think I have a fix for this. Will be in 2.10.1-beta.

Can you please give it a try and let me know.

Adam

**Comment by firedog** [comment]
Yes @schotime that fixed it!

Thanks!
