### ISSUE TITLE
Exception has thrown on the Query/Include when entity model has two different result columns of the same type

### ISSUE THREAD

**Issue by jturcinovic** [schotime/NPoco#178]
When model has two different result columns of the same type, NPoco is not able to generate the corresponding SQL command properly.
For example, Person entity has following columns:

`public int HomeAddressId { get; set; }`
`public int WorkAddressId { get; set; }`

which should have corresponding result columns of the same type:

`[ResultColumn]`
`public Address HomeAddress { get; set; }`

`[ResultColumn]`
`public Address WorkAddress { get; set; }`

When executing a query and trying to include a results for the two properties, an exception is thrown.
The SQL join command uses the same table alias for both of the  properties.

example of the join command:
`_db.Query<Person>()
.Include(x => x.HomeAddress, (person, homeAddress) => person.HomeAddressId == homeAddress.Id)
.Include(x => x.WorkAddress, (person, workAddress) => person.WorkAddressId == workAddress.Id);`

**Comment by schotime** [comment]
Hi
This is a known limitation unfortunately.
V3 will get around this but its still in alpha. 

You are most welcome to try it out, and if you need further info leave a question here and checkout https://github.com/schotime/NPoco/wiki/Version-3

Cheers

**Comment by jturcinovic** [comment]
Hi, 
Thank you on the info.

We shall do workaround with current version and will wait for the V3 release.

Kind Regards, 
Jovica

**Comment by schotime** [comment]
V3 released ;)
