### ISSUE TITLE
Result column objects are mapped to the model object by type

### ISSUE THREAD

**Issue by jturcinovic** [schotime/NPoco#179]
Most likely related to the issue: https://github.com/schotime/NPoco/issues/178

When model has two different result columns of the same type, if only one of them is populated with a Include method, the resulting object will not be mapped to the defined property (used in the lambda expression), but to the first property of the given type.

The SQL parser uses reflection and evaluates the property type and not the name - and it produces incorrect results when we are dealing with the explained situation.

**Comment by schotime** [comment]
Related to #178
