### ISSUE TITLE
Using conventions how to specify the primary key and its sql alias

### ISSUE THREAD

**Issue by worldspawn** [schotime/NPoco#184]
Hey,

I have a base class for my entities called UniqueObject and property on that called `Id`. For the implementations of UniqueObject I have tables where the primary is <TableName>Id. I cannot figure out how to define this with npoco.

At the moment I have:

```
x.PrimaryKeysNamed(z => z.Name.ToLower() + "id");
x.Columns.Named(z => z.Name == "Id" ? z.ReflectedType.Name.ToLower() + "id" : z.Name.ToLower());
```

However when trying to insert I get: `Npgsql.NpgsqlException: ERROR: 23502: null value in column "calculationsetid" violates not-null constraint`

```
var id = Guid.NewGuid();
var calcSet = new CalculationSet
{
                    Id = id,
                    Name = "Test"
};

database.Insert(calcSet);
```
The Id column definitely has a value and its not nullable anyway.

**Comment by worldspawn** [comment]
Think I got it with:

```
x.Columns.Named(z => z.Name == "Id" ? z.ReflectedType.Name.ToLower() + "id" : z.Name.ToLower());
                x.PrimaryKeysAutoIncremented(z => false);
```

**Comment by schotime** [comment]
Glad I could help ;)
