### ISSUE TITLE
Add link to official nuget package

### ISSUE THREAD

**Issue by petsuter** [schotime/NPoco#185]
I assume http://www.nuget.org/packages/NPoco/ is the official Nuget package of NPoco, controlled and maintained by you?
Please consider adding a link to the readme and / or wiki.

Optional: Add `[![Nuget](https://img.shields.io/nuget/v/NPoco.svg)](https://www.nuget.org/packages/NPoco/)` to get a nice [![Nuget](https://img.shields.io/nuget/v/NPoco.svg)](https://www.nuget.org/packages/NPoco/) shield.

Thanks.

**Comment by schotime** [comment]
Added the badge to the wiki home
