### ISSUE TITLE
Latest V3 compilation problem (.Net 4.6 issue) 

### ISSUE THREAD

**Issue by dheijl** [schotime/NPoco#186]
With VS2013 and only .Net 4.5.2 installed the following line in NewMappingFactory.cs does not compile with the latest source:

        public static List<IRowMapper> RowMappers { get; } 

Don't know if it's intentional or not. I added a private setter so that I could run some tests.

**Comment by schotime** [comment]
Hey. 
Thanks for catching that. Just did a quick push after the changes.
Adam

**Comment by dheijl** [comment]
Thanks!
