### ISSUE TITLE
Single does not fail when there are multiple records

### ISSUE THREAD

**Issue by JowenMei** [schotime/NPoco#187]
I have the following query:
`database.Query<QuestionnaireDb>().OrderBy(x => x.Year).Single(x => x.Year == year);`
There are multiple records, but only the first one is returned. Why does it **not** give me an error?

This is different behavior from the following query, which **does** give me an error.
`database.Single<QuestionnaireDb>("where Year = @0", year);`

**Comment by schotime** [comment]
Hi,
That's because it used to apply paging at the SQL query level, so when you did a Single() only one row would return.
If you upgrade to the latest you should get the expected behaviour.
Cheers,
Adam
