### ISSUE TITLE
Fluent Mappings a RowVersion complaint about IConvertible...

### ISSUE THREAD

**Issue by aleblanc70** [schotime/NPoco#188]
Good Day!

This is my class my problems is for the last field RecordVersion.

How can I replicate 
    [VersionColumn("Version", VersionColumnType.RowVersion)] 
attributes like the sample at:
    https://github.com/schotime/NPoco/wiki/Version-column-support

Thanks!
André

public class InvCountDetailMapping:Map<InvCountDetail>
    {
        public InvCountDetailMapping()
        {
            PrimaryKey(x => x.InvCountDetailId);
            TableName("InvCountDetail");
            Columns(x =>
            {
                x.Column(y => y.LotCD).Result();
                x.Column(y => y.LotDescr_Prm).Result();
                x.Column(y => y.SiteSectionCD).Result();
                x.Column(y => y.StorageUnitCD).Result();
                x.Column(y => y.CountedUnitCD).Result();
                x.Column(y => y.RecordVersion).Version();     <-----------
            });
        }
    }

**Comment by schotime** [comment]
```
x.Column(y => y.RecordVersion).Version(VersionColumnType.RowVersion);
```

**Comment by aleblanc70** [comment]
It's exactly what I tried before writing my issue.
But .Version(); has no overload to accept "VersionColumnType.RowVersion".

 I'm using NPoco 2.9.103 from NuGet.org

Thanks!
André

**Comment by schotime** [comment]
Ahhh...it was implemented but wasn't part of the interface so wasn't showing up.
WIll be in the latest. 2.10.8

**Comment by aleblanc70** [comment]
Great Adam thanks a lot.

You did a great product.
