### ISSUE TITLE
Postgres Jsonb with Npgsql 3.0.0

### ISSUE THREAD

**Issue by petsuter** [schotime/NPoco#189]
With Npgsql 2.2.5 I can use ``jsonb`` datatype in the PostgreSQL DB and NPoco successfully maps that to/from a C# ``string``.

If I try to do the same with Npgsql 3.0.0 I get ``NpgsqlException`` with a message ``column “XXX” is of type jsonb but expression is of type text’``. This is [mentioned in their FAQ](http://www.npgsql.org/doc/faq.html#jsonb), where they suggest that ``NpgsqlDbType.Jsonb`` should be used to make this work again.

I assume this would have to be fixed in NPoco?

**Comment by schotime** [comment]
Hey, this is not simple to do because I can't take a direct dependency but I may have a workaround. Its not too bad. It assumes you want the data persisted from a string.

Firstly if you are using the attributes then set the type to be JsonB. Where JsonB is a class I have created here to flow the value through.

```csharp
    public class MyObj
    {
        [ColumnType(typeof(JsonB))]
        public string MyData { get; set; }
    }

    public class JsonB
    {
        public string Value { get; set; }
    }
```

Then we need a mapper. This checks that the source type is a string that the column type is JsonB which we indicated above in the attribute. We then map the string to the JsonB object. Then we take the source JsonB object and map the value to a parameter with the NpgsqlDbType.Jsonb type.

```csharp
    public class Mapper : DefaultMapper
    {
        public override Func<object, object> GetToDbConverter(Type destType, MemberInfo sourceMemberInfo)
        {
            if (sourceMemberInfo.GetMemberInfoType() == typeof(string) && destType == typeof (JsonB))
            {
                return x => new JsonB {Value = (string) x};
            }
            return GetToDbConverter(destType, sourceMemberInfo);
        }

        public override Func<object, object> GetParameterConverter(Type sourceType)
        {
            if (sourceType == typeof (JsonB))
            {
                return x => new NpgsqlParameter()
                            {
                                NpgsqlDbType = NpgsqlDbType.Jsonb,
                                Value = x
                            };
            }

            return base.GetParameterConverter(sourceType);
        }
    }
```

I haven't actually run this but it should put you on the right track. Let me know if it doesn't go well and we'll see what else we can activate.

**Comment by petsuter** [comment]
Hey, thanks a lot for the example! Is this trick of inheriting ``DefaultMapper`` and setting ``db.Mapper`` considered stable? I didn't find it mentioned in the wiki documentation. (Something like ``dbFactory.AddMapper<JsonbMapper>();`` would be nice.)

I got a ``StackOverflowException`` in ``GetToDbConverter``. I assume this:
```` 
return GetToDbConverter(destType, sourceMemberInfo);
```
should really be calling ``base.`` as well:
``` 
return base.GetToDbConverter(destType, sourceMemberInfo);
````

With that change I get:
```
Npgsql.NpgsqlException was unhandled by user code
  HResult=-2147467259
  Message=22P02: invalid input syntax for type json
  Source=Npgsql
  ErrorCode=-2147467259
  Code=22P02
  Detail=Token "MyNamespace" is invalid.
  File=src\backend\utils\adt\json.c
  InternalPosition=0
  Line=1181
  MessageText=invalid input syntax for type json
  Position=0
  Routine=report_invalid_token
  Severity=ERROR
  Where=JSON data, line 1: MyNamespace...
  StackTrace:
       at Npgsql.NpgsqlConnector.DoReadSingleMessage(DataRowLoadingMode dataRowLoadingMode, Boolean returnNullForAsyncMessage)
       at Npgsql.NpgsqlConnector.ReadSingleMessage(DataRowLoadingMode dataRowLoadingMode, Boolean returnNullForAsyncMessage)
       at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior)
       at Npgsql.NpgsqlCommand.ExecuteScalarInternal()
       at Npgsql.NpgsqlCommand.ExecuteScalar()
       at NPoco.Database.ExecuteScalarHelper(IDbCommand cmd) in d:\Dev\NPoco\src\NPoco\Database.cs:line 1804
       at NPoco.DatabaseTypes.PostgreSQLDatabaseType.ExecuteInsert[T](Database db, IDbCommand cmd, String primaryKeyName, T poco, Object[] args) in d:\Dev\NPoco\src\NPoco\DatabaseTypes\PostgreSQLDatabaseType.cs:line 25
       at NPoco.Database.Insert[T](String tableName, String primaryKeyName, Boolean autoIncrement, T poco) in d:\Dev\NPoco\src\NPoco\Database.cs:line 1348
       at NPoco.Database.Insert[T](T poco) in d:\Dev\NPoco\src\NPoco\Database.cs:line 1218
````

I'm guessing ``Value = x`` should be something like ``Value = ((JsonB)x).Value``?

With those changes it seems to work. 

 Thanks again.

**Comment by schotime** [comment]
Awesome. 
Settings the Mapper is fine. You can do it in the constructor of an inherited Database as well.

**Comment by PeterN** [comment]
Had to update this slightly for current NPoco, but other than that this solution still works. :+1:
