### ISSUE TITLE
V3 question (Include and left join) 

### ISSUE THREAD

**Issue by dheijl** [schotime/NPoco#190]
.Include() and .IncludeMany() always use a left (outer) join. 

Is there another way to get an inner join besides adding:

     .Where (t => t.ForeignKey != null)

It's no big deal, just curious.

**Comment by schotime** [comment]
Not yet, however I will be adding it either before or during the alpha period.

**Comment by schotime** [comment]
ahhh screw it.
Its in.
https://github.com/schotime/NPoco/commit/ef6332cdb9329aed94a158106ca54eecc62a3921

**Comment by dheijl** [comment]
Thanks Adam!

**Comment by dheijl** [comment]
Just tested it, works as advertised.

**Comment by schotime** [comment]
How are you finding V3 in general so far

**Comment by dheijl** [comment]
Not using it in production yet but I regularly run some tests when you commit something new. It seems solid enough, but the lack of documentation can be annoying. For instance what's the use of ReferenceMappingType.Foreign, is it for internal NPoco use only, as it seems to cover both OneToOne and OneToMany. You sometimes have to weed through the unit tests or the issues or the sourcecode ... And I like the new features.

**Comment by schotime** [comment]
The ReferenceMappingType is needed, and ensures that the relationships are setup correctly and the defaults are correct. Foreign and OneToOne are closer than OneToMany.

Yeh...will try and update the doco when i think its ready enough for an alpha. I tried to put it into our big app the other day and i found some things (not as many as I thought), but it really only took about 5 min to upgrade, which was good. Most things just  That led to some better defaults that I have been pushing in this week. Found a huge bug that I would've never found in normal testing, so that was good. 

I still wanna try and make the mappers more SOLID and pluggable. Having one big mapper is not the best.

Any other things that can be improved while breaking changes are possible?

**Comment by dheijl** [comment]
I can not get ReferenceMappingType.Foreign to work, it always gives me a duplicate column exception in PocoDataBuilder, while OneToOne and OneToMany do work. Technically I don't see the difference between ManyToOne, OneToOne and OneToMany (except for the List in the OneToMany case), in all cases you just have the foreign key column that points to the prime key of one or more related records. What do I fail to see?

**Comment by schotime** [comment]
**OneToOne**: This is usually the primary key of one table to the primary key of the other table. When inserting there is no need to insert get the value from the foreign object. The object doesn't represent a column. eg. UserId (on Users) to UserId (UsersSecurity)
**Foreign**: This is linked from a column (not primary key) to the other tables primary key. eg. AddressId (on Users) to AddressId (pk on Addresses). In this case the object Address does represent a column. 
**Many**: Same as One to One but is used internally to look up details on how to map the columns.

**Comment by schotime** [comment]
Btw. If you are using Foreign you can't also have an int column representing the foreign value. This should only be the object. eg in the example above I couldn't have 

```csharp
public class Users {
    public int UserId {get;set;}
    public int AddressId {get;set;}
    [Reference]
    public Address Address {get;set;}
}
```
This would indeed cause an error in the mappings.

**Comment by dheijl** [comment]
Thanks, that makes it clear.

My problem with Foreign: I use a very simple T4 template to generate the Poco's as partial classes and in many cases I can get by with completing the partial class in a second source file with a couple of references and some static methods to get the data I need. 
In that case I have the foreign key Id column for the reference generated by the T4 template, and that causes the duplicate.

**Comment by dheijl** [comment]
All this caused me to read the following: http://www.dcs.warwick.ac.uk/~hugh/TTM/AllforOne.pdf
