### ISSUE TITLE
MySql Provider: Format of the initialization string does not conform to specification starting at index 0

### ISSUE THREAD

**Issue by EliotJones** [schotime/NPoco#191]
I'm trying to get up and running with NPoco using the following packages:

    <packages>
      <package id="MySql.Data" version="6.9.7" targetFramework="net46" />
      <package id="NPoco" version="2.10.9" targetFramework="net46" />
    </packages>

My connection string is as follows:

    <connectionStrings>
     <add name="Default" connectionString="Server=localhost;Uid=uglytoad;Pwd=password;Database=database-develop" />
    </connectionStrings>

This connection string works when querying using normal the MySqlCommand but not using NPoco:

        using (var db = new Database("Default", DatabaseType.MySQL))
        {
            var connstring = ConfigurationManager.ConnectionStrings["Default"].ConnectionString;
            var con = new MySqlConnection(connstring);
            con.Open();
                
            var a = new MySqlCommand("SELECT * FROM country", con);
            var r = a.ExecuteReader();
            while (r.Read())
            {
                var e = r.GetInt32(0);
            }

            var myCount = db.Execute("SELECT COUNT(*) FROM country");
            return myCount;
        }

I get the error in the title on the second to last line, it also fails using ```db.Fetch<Country>```:

An exception of type 'System.ArgumentException' occurred in NPoco.dll but was not handled in user code
Format of the initialization string does not conform to specification starting at index 0

The Data providers in my config are:

    <system.data>
      <DbProviderFactories>
        <add name="MySQL.Data.MySqlClient" 
             invariant="MySql.Data.MySqlClient" 
             description=".Net Framework Data Provider for MySQL" 
             type="MySql.Data.MySqlClient.MySqlClientFactory, MySql.Data, Version=6.9.7.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d" />
      </DbProviderFactories>
    </system.data>

I'm sure I'm missing something simple but can't find any documentation for getting set-up with MySql. Any ideas?

**Comment by schotime** [comment]
You are using the wrong overload.
The one you are using is for the full connection string.

Change your connection string to:

``
<connectionStrings>
 <add name="Default" connectionString="Server=localhost;Uid=uglytoad;Pwd=password;Database=database-develop" Provider="MySql.Data.MySQLClient" />
</connectionStrings>
```

And then just call it

```
var db = new Database("Default");
```

**Comment by EliotJones** [comment]
Thanks very much, added the providerName to the connection string and remove the provider specified in the constructor and it started working. Sorry for such a stupid question :)
