### ISSUE TITLE
FetchMultiple casting issue

### ISSUE THREAD

**Issue by rmotyka** [schotime/NPoco#192]
When using function like:
`db.FetchMultiple<TypeX, TypeX1, TypeX2, TypeX3>(sqlString, argumentId);`

There is an exception of casting `'System.Func`3[System.Data.IDataReader,System.Object,System.Object]'`
to 
`'System.Func`3[System.Data.IDataReader,TypeX,TypeX]'`

`NPoco.Database.FetchMultiple[T1,T2,T3,T4,TRet](Type[] types, Object cb, Sql Sql) w d:\Dev\NPoco\src\NPoco\Database.cs: row 1264`

It is an issue after upgrade to the newest version. In previous version that works ok.

**Comment by schotime** [comment]
Apologies and thanks for that. Have a fix and will be in NuGet 2.10.11 within the hour
Cheers

**Comment by schotime** [comment]
https://github.com/schotime/NPoco/commit/ee5b6adceb20b9621e4977a8be14c8878996349a

**Comment by rmotyka** [comment]
Thank you for the instant reaction. It works well now.
