### ISSUE TITLE
[VersionColumn] UpdateMany concurrency handling

### ISSUE THREAD

**Issue by jturcinovic** [schotime/NPoco#193]
Hi, 

Is there any mechanism which supports the concurrency handling when the UpdateMany is used?

Thanks, 
Jovica

**Comment by schotime** [comment]
How would you envisage this working?
UpdateMany doesn't have information about each row. It is about doing bulk updates (issuing an update statement)

**Comment by jturcinovic** [comment]
You are right, UpdateMany doesn't have information about each row. It doesn't make a sense to fetch all rows, so this should be solved in different way.
I was thinking about the solution. I think that it should be solved using the transactions and the Serializable isolation level (SQL Server).
