### ISSUE TITLE
IQueryable Compatibility

### ISSUE THREAD

**Issue by npbenjohnson** [schotime/NPoco#195]
I know there was already an issue for IQueryable support, and it won't be done. I'm making my own wrapper to replace an old PetaPoco project, and I'm wondering if you'd take a pull request to adjust the signature of the key selecting functions in IQueryProvider from

```
IQueryProvider<T> OrderByDescending(Expression<Func<T, object>> column);
```

to

```
IQueryProvider<T,Tkey> OrderByDescending(Expression<Func<T, TKey>> column);
```

because the object in Expression<Func<T, object> is smaller so it can't be easily mapped to, and TKey should be implied anyway.

**Comment by schotime** [comment]
You can have a look.
Not sure how this will affect the rest of the fluent api.
