### ISSUE TITLE
Refresh the column with VersionColumnType.RowVersion after an Update or Insert

### ISSUE THREAD

**Issue by aleblanc70** [schotime/NPoco#196]
Regarding this page:
https://github.com/schotime/NPoco/wiki/Version-column-support

If I use  [VersionColumn("Version", VersionColumnType.RowVersion)]
I think after an update or an insert the RowVersion of the database is not return.

ìf I look at issue #44 I see something was tried but not sure if it's finish... 

From the Update method I don't see it's done for VersionColumnType.RowVersion

Thanks, let me know what was tried maybe I can help :)

André

**Comment by schotime** [comment]
You will have to re-query the object.

**Comment by enriko-riba** [comment]
Any chance we get this feature or is there a large issue behind prevent the autorefresh to be implemented?
