### ISSUE TITLE
Query<> FirstOrDefault Error

### ISSUE THREAD

**Issue by npbenjohnson** [schotime/NPoco#197]
In current Master branch (8334a03ff06d2bbe8dcd4caf0c342cd4730202c7) 
Calling
```
    Database.Query<>.FirstOrDefault(i=>i.id) throws 
```
In SQLCE (and probably other providers although I didn't verify) generates
``` sql
SELECT...
WHERE ([A].[Id] = @0)
OFFSET @1 ROWS FETCH NEXT @2 ROWS ONLY
```
Which throws OFFSET clause is invalid unless ORDER BY clause is specified.

**Comment by schotime** [comment]
Branch dev2.0 is the latest on NuGet and this should not occur in that version.

**Comment by npbenjohnson** [comment]
Thanks
