### ISSUE TITLE
Error in "Database.GetPrimaryKeyValues()" when using composite primary keys

### ISSUE THREAD

**Issue by nickcoad** [schotime/NPoco#199]
Database.cs:1606 throws an exception for POCOs with composite primary keys.  The error seems to be that the line iterates over property names instead of the associated DB column names:

primaryKeyValues = dict ?? multiplePrimaryKeysNames.ToDictionary(x => x, x => primaryKeyValue.GetType().GetProperties().Single(y => string.Equals(x, y.Name, StringComparison.OrdinalIgnoreCase)).GetValue(primaryKeyValue, null), StringComparer.OrdinalIgnoreCase);

Notice the call to "GetProperties()" where it then compares each property's name to the primary key column name it is currently operating on.  So if you have a primary key of "USER_ID,BUSI_ID", the line would only work if the properties were also named USER_ID and BUSI_ID.  This seems to be a mistake, I assume it should be checking the database column names for those properties.

**Comment by schotime** [comment]
How are you calling the method that uses this? Its supposed to be passed an anonymous object. 
eg. 
```csharp
db.SingleById<User>(new { user_id = 1, busi_id = 2 });
```

**Comment by nickcoad** [comment]
I'm calling db.Save(), providing a POCO.  Looking at the "Master" branch:

1) Save calls IsNew at line 1685, sending the POCO as the argument.
2) IsNew calls Exists at line 1651, again sending the POCO as the argument.

I think that second step might be the problem, as from what you're saying it seems like "IsNew" is sending the incorrect object to Exists.  The parameter for exists is called "primaryKey" which makes me think it's not expecting a POCO, but is expecting a dynamic object like you've said.  This POCO then gets passed into GetPrimaryKeyValues creating the exception.

**Comment by schotime** [comment]
This has been fixed in the dev2.0 branch but I haven't released a nuget. Are you able to clone it from there and give it a test. Alternatively the 3.0 alpha has it in it also.
