### ISSUE TITLE
VB.NET - PetaPoco\NPoco - Fetch data from a database table with some unknown columns into a POCO object with a dictionary inside - Performance issue

### ISSUE THREAD

**Issue by asaf0000** [schotime/NPoco#200]
I have a specific situation to which I haven't found a solution yet.

I have several databases with the same structure where I have a table, (lets say Users), which has known columns such as: UserID, UserName, UserMail, etc... In the same table, I have dynamic custom columns which I can know only on runtime, such as: customField54, customField75, customField82, etc...

I have a screen where I must show a list of users, and there are thousands of records (Must show ALL the users - no question about it).

The Users table columns in database A look like this:

| UserID | UserName | UserMail | customField54 | customField55 |
and for the example, lets say I have another database B, and the table Users there looks like this:

| UserID | UserName | UserMail | customField109 | customField211 | customField235 | customField302 |
I have a single code which each time connects to another database. So I have a single code - > multiple databases, while the difference in each database is the custom fields of the Users table.

If I work with a DataTable, I can query:

    SELECT * FROM Users
And then, dynamically I can retrieve the custom fields values, like this:

Dim customFieldsIDs() As Integer = GetCustomFieldsIDs()
Dim dt As DataTable = GetUserListData() // All users data in a DataTable

For Each dr In dt.Rows
    Response.Write(dr.Item("UserID"))
    Response.Write(dr.Item("UserName"))
    Response.Write(dr.Item("UserMail"))

    For Each cfID in customFieldsIDs
         Response.Write(dr.Item("customField" & cfID))
    Next 
Next
My intention is not to work with DataTables. I want to work with strong typed objects. I cannot create a POCO of Users with the customFields as is inside, because for each database the Users table has different customFields columns, so I can't create an object with strongly typed variables.

Then, I decided to create a class Users with the known columns inside, and also a dictionary holding the customFields.

In VB.NET, I created a class Users, which looks as follows:

Public Class User
    Public Property UserID As Integer
    Public Property UserName As Integer
    Public Property UserMail As Integer

    Public Property customFieldsDictionary As Dictionary(Of Integer, String)
End Class
The class has the static values: UserID, UserName, etc... Also, it has a dictionary of the customFieldIDs and their values, so I can retrieve the values in a single action (in O(1) complexity)

I use MicroORM PetaPoco\NPoco to populate the values. The ORM allows me to fetch the Users data without me having to iterate the data by myself, by calling:

Dim userList As List(Of User) = db.Fetch(Of User)("SELECT * FROM Users")
But then the customFields dictionary is not populated. In order to populate I have to iterate the userList and for each user retrieve the customFields data. This is a very expensive way to fetch the data and results in a very bad performance.

I'd like to know if there is a way to fetch the data into the User class using PetaPoco\NPoco with a single command and manage to populate the known values and the custom fields dictionary for every user without having to iterate through the whole collection.

I hope it is understood. It is really difficult for me to explain and a very difficult issue to find a solution to.

Thank you in advance! Asaf

**Comment by schotime** [comment]
In V3 you can have properties that are dynamic.
https://github.com/schotime/NPoco/wiki/Version-3#dynamic-properties

Hope this solves your problem

**Comment by asaf0000** [comment]
Great! that sounds right I think!
Could you say when will version 3 be released?

**Comment by schotime** [comment]
Nope. But the more people using the alpha the quicker. ;)

**Comment by asaf0000** [comment]
Ok great! :)

Could you give me a link or something, I failed to find the alpha version?

**Comment by schotime** [comment]
It's on nuget. Need to use the -pre flag

**Comment by asaf0000** [comment]
Found it. Thanks!
