### ISSUE TITLE
Dispose transaction on Database dispose

### ISSUE THREAD

**Issue by huanacaraz** [schotime/NPoco#201]
I think this should be automatic to dispose transaction (if created on Database) in case the Database object is disposed. 
..In case you create the Database instance with custom connection instance, the dispose is not called, so the transaction remains..

**Comment by schotime** [comment]
Not sure what you mean?

**Comment by huanacaraz** [comment]
I mean this:
```
var db = new Database(existingConnection);
db.BeginTransaction();
db.Dispose();
```
In this case the transaction created on database is not disposed automatically. Question is, whether it should be?

**Comment by schotime** [comment]
Probably should dispose the transaction as well...I will have a look at it.

**Comment by schotime** [comment]
Is disposed now in V3
