### ISSUE TITLE
Contains method throws InvalidCastException when it is used in combination with another where clause

### ISSUE THREAD

**Issue by jturcinovic** [schotime/NPoco#202]
I am getting the error - InvalidCastException when I call something like this:
Db.Query<Tbl>().Where(t => statuses.Contains(t.StatusId) && t.Column2 == "ColumnValue").Count();

If I call:
Db.Query<Tbl>().Where(t => statuses.Contains(t.StatusId)).Count();
Everything is fine.

Please do let me know is it possible to overcome this issue?
Please check the screenshot for more details on the error.
![npoco_issue_contains](https://cloud.githubusercontent.com/assets/1102016/10135508/dff8a7e4-65ee-11e5-9e39-794a649e8c93.jpg)

**Comment by schotime** [comment]
What are the types of statuses and statusId?

**Comment by jturcinovic** [comment]
// declared before the Db.Query call:
var statuses = new List<Guid> {new Guid("2A6C333C-A3C4-433F-8DD5-67562348646C")};

// entity column definition
public Guid StatusId { get; set; }

**Comment by jturcinovic** [comment]
I've updated the solution to the latest NPoco version, and this issue seems to be solved!

When do you plan to release the new NPoco 3.0 version?

Kind Regards, 
Jovica

**Comment by schotime** [comment]
Thats good.
Hopefully this week there will be an alpha available on NuGet.
