### ISSUE TITLE
SingleById error with Oracle

### ISSUE THREAD

**Issue by dgodard** [schotime/NPoco#205]
Hi,

I have the same DB structure under an Oracle database and a SQL Server one.
 
I use Oracle.ManagedDataAccess.dll and Npoco to access to my data under Oracle.

I have several tables with composite PK, composed by a CHAR(15) and Int

If I use <MYTABLE>.SingleById( CHARCOLUM = "MyID", INTCOLUMN = 1) on a SQL SERVER it works.

But with Oracle i have to format my string myself : CHARCOLUM =  String.format("{0,-15}","MyID") to make SingleById to Work.

Is it normal ?

I thought that GetSingleById was making the mapping and formating the values for me.

Best regards.

**Comment by schotime** [comment]
I'm not really sure how you are calling SingleById there.
It is supposed to take an integer value.
Can you please provide more information of the exact use?
