### ISSUE TITLE
OneTimeCommandTimeout doesn't seem to work properly

### ISSUE THREAD

**Issue by jturcinovic** [schotime/NPoco#206]
I've tried to set the Db.OneTimeCommandTimeout to 300 before I call the Db.Execute, but even I set it to 300, it throws me a timeout exception after 30 seconds.

Am I doing something wrong? Do I need to set/setup something else?

**Comment by schotime** [comment]
Not usually. Can you post some more code?

**Comment by jturcinovic** [comment]
I've double checked the call - and found out that OneTimeCommandTimeout is working properly - there was some hidden call to the database which reset the value.

So, everything is fine - the property works well!
Sorry for inconvenience.
