### ISSUE TITLE
Has the best practice of using NPOCO to achieve UnitOfWork?

### ISSUE THREAD

**Issue by sxlvalue** [schotime/NPoco#207]
Has the best practice of using NPOCO to achieve UnitOfWork?I found the use of NPOCO to achieve very little.

**Comment by Mike737377** [comment]
What do you mean? NPoco can be used in a unit of work. 

You could easily achieve unit of work and test-ability.

```csharp
public class UnitOfWorkUpdateNameCommand
{
    public int Id {get;set;}
    public string Name {get;set;}
}

public class UnitOfWorkUpdateNameCommandHandler
{
    public void Execute(IDatabase db, UnitOfWorkUpdateNameCommand command)
    {
        var entity = db.Query<Entity>(x => x.Id = command.Id).First();
        entity.Name = command.Name;
        db.Update(entity);
    }
}
```

**Comment by sxlvalue** [comment]
Thank you I realized the following method.

public interface IUnitOfWork:IDisposable
    {
        void Commit();

        T GetRepository<T>();

    }

public class UnitOfWork: IUnitOfWork
    {
        private IDatabase DbContext { get; set; }

        public UnitOfWork()
        {
            DbContext = new Database(DbConfig.Default);
            DbContext.BeginTransaction();
        }

        public UnitOfWork(string connectionStringName)
        {
            DbContext = new Database(connectionStringName);
            DbContext.BeginTransaction();
        }

        public T GetRepository<T>()
        {
            var repository = IocManager.Instance.Resolve<T>();
            var pro=repository.GetType().GetProperty("DbContext");
            pro.SetValue(repository,DbContext);
            return repository;
        }

        public void Commit()
        {
            DbContext.CompleteTransaction();
        }
        public void Dispose()
        {
            DbContext.Dispose();
        }
    }

public interface IUnitOfWorkProvider
    {
        IUnitOfWork GetUnitOfWork();
        IUnitOfWork GetUnitOfWork(string connectionStringName);
        
    }

public class UnitOfWorkProvider:IUnitOfWorkProvider
    {
        public IUnitOfWork GetUnitOfWork()
        {
            return new UnitOfWork(DbConfig.Default);
        }

        public IUnitOfWork GetUnitOfWork(string connectionStringName)
        {
            return new UnitOfWork(connectionStringName);
        }
    }

Sample:
public class UserService : IUserService
    {
        private ILogger Logger { get; set; }
        private IUnitOfWorkProvider _unitOfWorkProvider;

        public UserService(ICache cache, IUnitOfWorkProvider unitOfWorkProvider)
        {
            _unitOfWorkProvider = unitOfWorkProvider;
            Logger=NullLogger.Instance;
        }
        
        #region UnitOfWork

        public virtual bool TestUow(RegisterUserInputDto dto)
        {
            using (var uow = _unitOfWorkProvider.GetUnitOfWork())
            {
                var user = UserMapper.MapToModel(dto);
                var userRepositoryUow = uow.GetRepository<IUsersRepository>();
                user.UserId = dto.Id;
                userRepositoryUow.Insert(user);

                var scoreRepositoryUow = uow.GetRepository<IScoresRepository>();
                scoreRepositoryUow.Increase(5);
                uow.Commit();
                return true;
            }
        }
        #endregion
    }
