### ISSUE TITLE
NPoco - Partial Insert

### ISSUE THREAD

**Issue by asaf0000** [schotime/NPoco#208]
Hi!

Is there a way to partially insert an object using NPoco? For example, in the DB I have a table called Users:
```
UserId | UserName | UserMail | UserCreationDate
```
Each one of these columns are NON NULLABLE and have a default value when they are left empty.

In ASP.NET I have a User class, and I use the ORM to insert a new record with only the name:
```
Dim userData As New User()
userData.UserName = "Jimmy Hendrix"
db.Insert(userData)
```
I expect the database to look as follows:
```
UserId |   UserName    |   UserMail  | UserCreationDate
  12   | Jimmy Hendrix | (DB default)|  (DB default)
```
I want the insert command to only insert the name, without inserting the other object properties with the object's default values.

Such as there is a partial update, I want a partial insert. Is that possible in NPoco?

Using SQL I can get the job done, but I need to use POCO objects, so I don't want to have to remember the database parameters. I want something like
```
user.UserName = "Michael"
user.Insert(user)
```
And it will insert only the UserName, ignoring the other variables. The SQL that I want to be generated in the background is:
```
"INSERT Users(UserName) VALUES(@UserName)"
```
(while the @UserName parameter holds the userData.FirstName value)

As you can see, it doesn't take in account the other variables in the class.
Today if I use the insert command, even if I give a value to a single property in the class, NPoco still tries to insert ALL the class variables into the db setting the variables I didn't want to set with the class's default values (which are different from the db default values)

Also, all of the properties are insertable/updateable, so there can't be any ResultColumn types in the class. I want to insert these values but only the ones I declare in that particular instance. All of the properties are available to update and insert but for each instance i insert only what i declare.

I hope the explanation is understandable. It is pretty hard for me to explain my problem.

Thanks in advance!
Asaf

**Comment by schotime** [comment]
Hi Asaf,

There is no such way at the moment.
Only thing that comes close is to have the DB default stored as the default value of the property in the object.

Cheers,
Adam

**Comment by asaf0000** [comment]
Hi Adam!

Ok, thanks. I'll be glad if you could consider it for the next versions.

I think it is a nice feature that allows you to work only with the object class properties instead of trying to remember the database variables, (that was what you were trying to avoid in the first place creating class objects and entities).

Thnik about it - that way you let the database constrains work for you instead of defining constrains two times: once in the code and also in the database itself (where the constrains should be)

Best regards,
Asaf

**Comment by warrenrumak** [comment]
Asaf, why do you want your database to define values for some of your columns?  Are you intending to allow the ORM to be circumvented by some users and having rows directly inserted into this table?  Can you trust your users will all do this correctly?

Default values for entities is 100% an application concern, not a data storage concern.  Splitting this between two layers increases complexity, reduces readability and enables creating inconsistent state between the in-memory & stored representations of the entity.  Think of it this way: letting SQL decide what your data will be, would be like letting NTFS decide what the font in an HTML page should be.  Yes, SQL and NTFS serve broadly the same purpose in your life: storage, retrieval, and organization of data.  Trying to push it beyond that will only slow down your productivity as a developer.

It's worth noting that the big ORMs like Entity Framework don't support what you're asking for, either.  

Have your application specify the initial values, it's just easier that way.

**Comment by enriko-riba** [comment]
I know I am kinda late but thats not always the case. e.g. the infamous created or lastmodified fields. You don't want the application to update those fields (especially not in solution with users all around the globe in different time zones).

I prefer having a DB default and decorating the poco properties with [ResultColumn]
Just be aware that you open another problem: resultcolumns are not included in autoselect.

It's not a big deal if you write your selects but if you use SingleOrDefaultById or FetchWhere and other autoselect dependent feature it is a real pain in the ***

@Adam, can we get this behavior parameterized with something like [ResultColumn(IncludeAutoselect = true)] ?

**Comment by schotime** [comment]
Use `[Computed]` if you want the autoselect ;)

**Comment by enriko-riba** [comment]
wow I never realized this was already implemented...You just generated me a day of refactoring work :-)
BTW would be nice to mention it on the wiki mapping or fluent mapping section.

**Comment by schotime** [comment]
Done.
Number 6.

https://github.com/schotime/NPoco/wiki/Mapping
