### ISSUE TITLE
Sql Async

### ISSUE THREAD

**Issue by svickers** [schotime/NPoco#209]
Not sure what I am missing but trying to do a simple async fetch and getting the exception from this line:
https://github.com/schotime/NPoco/blob/dev2.0/src/NPoco/DatabaseType.cs#L350

    using(var db = new Database("DefaultConnection")){
        var x = await db.FetchAsync<dynamic>(sql);
    }

Is async not implemented for sql server?

**Comment by schotime** [comment]
What provider is your connection string using?
Are u wrapping the connection in onconnectionopened?

**Comment by svickers** [comment]
Provider is System.Data.SqlClient, no wrapping of the connection.

**Comment by schotime** [comment]
The command must be not a SqlCommand. Are you using Glimpse or Miniprofiler? Can you reproduce in a small console app? I cannot.

**Comment by svickers** [comment]
Yup, looks like Glimpse was the problem.  Removed and no longer an issue.
