### ISSUE TITLE
ASP.Net 5 / CoreClr support timeframe?

### ISSUE THREAD

**Issue by Shazwazza** [schotime/NPoco#210]
Hi,

I  just wanted to know if you have any plans to start porting NPoco over to ASP.Net 5 with CoreClr support ? Would like to know if you've made any attempts at this yet or if you know of the challenges involved in it?

I'd be happy to help with this over the next few months!

**Comment by schotime** [comment]
Hey,
Thanks for raising this.
I have done preliminary work, and have found a couple things. Over the next week I will push up a new repo / branch (thoughts?) with what I have so far.

Here are some points.

- MemberInfo on CoreClr has an internal constructor. https://github.com/dotnet/coreclr/issues/2086. Not really a major roadblock (biggest we have) but it would mean abstracting a little further where this is used.
- SqlBulkCopy (DataTable/DataSet) hasn't been implemented as yet. DT and DS may not be.
https://github.com/dotnet/corefx/issues/1039
- IDbCommand etc. All the interfaces have been dropped in favour of base classes. Pretty easy switch. Will be a breaking change with people using NPoco https://github.com/dotnet/corefx/issues/3480
- FastJson. Was used internally for json serialization/deserialization/snapshotter. It would need some big changes. Switched to JSON.net for now. Might come back to this. Don't like this dependency.
- Tests. Haven't even tried so far.
- What version of NPoco will it be? Could be part of V3 as its only at alpha stage.

Once I get it in shape, I'll recomment and then we can divide and conquer.

Cheers,
Adam

**Comment by Shazwazza** [comment]
Great work on the prelim investigation! I Apparently Dapper has been ported already, so if required there might be some inspiration taken there as far as porting to CoreClr goes. 

I know that David Fowler was mentioning including a very small and faster Json lib with aspnet5, not sure what happened there but I also know this repo exists for aspnet5 https://github.com/aspnet/JsonPatch though there's very little information on this and/or if they implemented a smaller json lib.

I don't think there's much apart from xunit available for unit tests but I know the .Net Foundation people are trying to get community members to help port some of the base libraries out there to aid in helping other larger libraries get up to speed.

Anyways, would be good to keep this thread updated if/when you have time. If I hear of any updates that might help I'll be sure to post back here. And would be interesting in helping out for sure in the new year!

**Comment by schotime** [comment]
Got it all working but one test which is related to https://github.com/dotnet/coreclr/issues/2119

Pushed it to the dnx branch. We will have to make a decision on what we do as far as constructors go, now that DbProviderFactories does not exist. At the moment you just pass in the DbProviderFactory which is working, and might be the solution, its just another parameter (bleh).

The build should work by running build.bat.
The tests can be run by calling `dnx test` from the NPoco.Tests directory.

**Comment by Shazwazza** [comment]
Amazing :) 

I work for Umbraco and we use PetaPoco currently but are moving to NPoco with our v8 due out next year but are slowly working on a "v9" to run on aspnet5 so this is a wonderful start for us to be able to start progressing that. 

I'll have a look at testing this in a few weeks (have holidays first) and let me know if there's anything else I can help with.

**Comment by FransBouma** [comment]
DbProviderFactories seem to be planned for RC2: https://github.com/dotnet/corefx/issues/4571

**Comment by schotime** [comment]
This is all in the master branch now and released for 3.2 on Nuget.
Only waiting on SqlBulkCopy support due to DataTable unless this has changed.
Closing issue for now.
