### ISSUE TITLE
snapshot on interface

### ISSUE THREAD

**Issue by mia-san** [schotime/NPoco#212]
how can I take snapshot of entity class via interface?

suppose I have entity classes implimenting same interface:

    interface IEntity
    {
        int ID { get; set; }
        string Value { get; set; }
    };

    class Entity1 : IEntity
    {
        public int ID { get; set; }
        public string Value { get; set; }
        public DateTime Entity1Value { get; set; }
    };

    class Entity2: IEntity
    {
        public int ID { get; set; }
        public string Value { get; set; }
        public Double Entity2Value { get; set; }
    };

  now I want to update several columns only in existing entity in same manner:

        static void Main(string[] args)
        {
            DbProviderFactory factory = DbProviderFactories.GetFactory("System.Data.SqlClient");

            using (IDatabase db = new Database(@"Data Source=.\SQLExpress; Initial Catalog=Test; Integrated Security=True;", factory)) {
                IEntity entity1 = db.SingleById<Entity1>(1);  // assume entity exists
                DoUpdate(db, entity1);

                IEntity entity2 = db.SingleById<Entity2>(2);  // assume entity exists
                DoUpdate(db, entity2);
            }
        }

function DoUpdate does following:

        static void DoUpdate(IDatabase db, IEntity ientity)
        {
            Snapshot<IEntity> snapshot = db.StartSnapshot<IEntity>(ientity);    //  ArgumentNullException here.
            ientity.Value="somevalue";
            db.Update(ientity, snapshot.UpdatedColumns());
        }

  I got ArgumentNullException at StartSnapshot.
  While I'm workarounding by DoUpdate<T> for time being,
  is it possible to track updated columns in entity via interface ?

my environment is:
  Windows7 64bit Professional
  Visual Studio 2012
  .NET Framework 3.5 SP1
  NPoco 2.10.11
//

**Comment by schotime** [comment]
Will have to have a look at this.
Would only go into V3 if it were implemented.

**Comment by mia-san** [comment]
V3 works on .NET Framework 3.5 SP1 ?
my $(work) projects are 3.5 SP1 and will not migrate to 4.x.

**Comment by schotime** [comment]
Will not work. Snapshotting is based on the concrete types that are mapped.
