### ISSUE TITLE
using SQLite and memory consumption

### ISSUE THREAD

**Issue by mia-san** [schotime/NPoco#213]
I noticed some memory consumption issue.

simple entity class:

    class Test
    {
        public Int32 ID { get; set; }
        public string Value { get; set; }
    };

running function below for several hours, process takes slowly consuming more and more memory:

        static void do_sqlite()
        {
            DbProviderFactory factory = DbProviderFactories.GetFactory("System.Data.SQLite");

            string[] databases = {@"test1.db", @"test2.db", @"test3.db", @"test4.db"};

            foreach (string name in databases) {
                File.Delete(name);
                using (NPoco.IDatabase db = new NPoco.Database(@"Data Source=" + name, factory))
                {
                    db.Execute("CREATE TABLE Test(ID INTEGER PRIMARY KEY AUTOINCREMENT, Value TEXT NOT NULL DEFAULT '');");
                }
            }

            Random random = new Random();

            for (; ; )
            {
                using (NPoco.IDatabase db1 = new NPoco.Database(@"Data Source=test1.db", factory))
                using (NPoco.IDatabase db2 = new NPoco.Database(@"Data Source=test2.db", factory))
                using (NPoco.IDatabase db3 = new NPoco.Database(@"Data Source=test3.db", factory))
                using (NPoco.IDatabase db4 = new NPoco.Database(@"Data Source=test4.db", factory))
                {
                    NPoco.Sql sql = NPoco.Sql.Builder
                        .Select("*")
                        .From("Test")
                        .Where("ID = @0", random.Next());

                    foreach (var item in db1.Fetch<Test>(sql))
                    {
                        Console.WriteLine(string.Format("{0:d}: {1}", item.ID, item.Value));
                    }

                    foreach (var item in db2.Fetch<Test>(sql))
                    {
                        Console.WriteLine(string.Format("{0:d}: {1}", item.ID, item.Value));
                    }

                    foreach (var item in db3.Fetch<Test>(sql))
                    {
                        Console.WriteLine(string.Format("{0:d}: {1}", item.ID, item.Value));
                    }

                    foreach (var item in db4.Fetch<Test>(sql))
                    {
                        Console.WriteLine(string.Format("{0:d}: {1}", item.ID, item.Value));
                    }

                    Console.WriteLine(string.Format("---- {0:yyyy-MM-dd HH:mm:ss.fff} ----", DateTime.Now));
                    Thread.Sleep(250);
                }
            }
        }

running almost same function using SQLServer in a day does not exhibit memory consuption problem:

        static void do_sqlserver()
        {
            DbProviderFactory factory = DbProviderFactories.GetFactory("System.Data.SqlClient");

/*
CREATE TABLE Test(
    ID INT NOT NULL IDENTITY,
    Value NVARCHAR(MAX) NOT NULL DEFAULT ''
);
*/
            Random random = new Random();

            for (; ; )
            {
                using (NPoco.IDatabase db1 = new NPoco.Database(@"Data Source=.\SQLExpress; Initial Catalog=Test1; Integrated Security=True;", factory))
                using (NPoco.IDatabase db2 = new NPoco.Database(@"Data Source=.\SQLExpress; Initial Catalog=Test2; Integrated Security=True;", factory))
                using (NPoco.IDatabase db3 = new NPoco.Database(@"Data Source=.\SQLExpress; Initial Catalog=Test3; Integrated Security=True;", factory))
                using (NPoco.IDatabase db4 = new NPoco.Database(@"Data Source=.\SQLExpress; Initial Catalog=Test4; Integrated Security=True;", factory))
                {
                    NPoco.Sql sql = NPoco.Sql.Builder
                        .Select("*")
                        .From("Test")
                        .Where("ID = @0", random.Next());

                    foreach (var item in db1.Fetch<Test>(sql))
                    {
                        Console.WriteLine(string.Format("{0:d}: {1}", item.ID, item.Value));
                    }

                    foreach (var item in db2.Fetch<Test>(sql))
                    {
                        Console.WriteLine(string.Format("{0:d}: {1}", item.ID, item.Value));
                    }

                    foreach (var item in db3.Fetch<Test>(sql))
                    {
                        Console.WriteLine(string.Format("{0:d}: {1}", item.ID, item.Value));
                    }

                    foreach (var item in db4.Fetch<Test>(sql))
                    {
                        Console.WriteLine(string.Format("{0:d}: {1}", item.ID, item.Value));
                    }

                    Console.WriteLine(string.Format("---- {0:yyyy-MM-dd HH:mm:ss.fff} ----", DateTime.Now));
                    Thread.Sleep(250);
                }
            }
        }

I have tested almost same procedure with raw System.Data.SQLite as below, it does not exhibit the issue:

        static void do_sqlite_raw()
        {
            DbProviderFactory factory = DbProviderFactories.GetFactory("System.Data.SQLite");

            string[] databases = { @"test1.db", @"test2.db", @"test3.db", @"test4.db" };

            foreach (string name in databases)
            {
                File.Delete(name);
                using (IDbConnection conn = factory.CreateConnection())
                {
                    conn.ConnectionString = @"Data Source=" + name;
                    conn.Open();

                    using (IDbCommand cmd = conn.CreateCommand())
                    {
                        cmd.CommandText = "CREATE TABLE Test(ID INTEGER PRIMARY KEY AUTOINCREMENT, Value TEXT NOT NULL DEFAULT '');";
                        cmd.ExecuteNonQuery();
                    }
                }
            }

            Random random = new Random();

            for (; ; )
            {
                using (IDbConnection db1 = factory.CreateConnection())
                using (IDbConnection db2 = factory.CreateConnection())
                using (IDbConnection db3 = factory.CreateConnection())
                using (IDbConnection db4 = factory.CreateConnection())
                {
                    db1.ConnectionString = @"Data Source=test1.db";
                    db1.Open();

                    using (IDbCommand cmd = db1.CreateCommand())
                    {
                        cmd.CommandText = "SELECT * FROM Test WHERE ID = " + random.Next() + ";";
                        using (IDataReader rdr = cmd.ExecuteReader())
                        {
                            while (rdr.Read()) {
                                Console.WriteLine(string.Format("{0}: {1}", rdr["ID"], rdr["Value"]));
                            }
                        }
                    }

                    db2.ConnectionString = @"Data Source=test1.db";
                    db2.Open();

                    using (IDbCommand cmd = db2.CreateCommand())
                    {
                        cmd.CommandText = "SELECT * FROM Test WHERE ID = " + random.Next() + ";";
                        using (IDataReader rdr = cmd.ExecuteReader())
                        {
                            while (rdr.Read())
                            {
                                Console.WriteLine(string.Format("{0}: {1}", rdr["ID"], rdr["Value"]));
                            }
                        }
                    }

                    db3.ConnectionString = @"Data Source=test1.db";
                    db3.Open();

                    using (IDbCommand cmd = db3.CreateCommand())
                    {
                        cmd.CommandText = "SELECT * FROM Test WHERE ID = " + random.Next() + ";";
                        using (IDataReader rdr = cmd.ExecuteReader())
                        {
                            while (rdr.Read())
                            {
                                Console.WriteLine(string.Format("{0}: {1}", rdr["ID"], rdr["Value"]));
                            }
                        }
                    }

                    db4.ConnectionString = @"Data Source=test1.db";
                    db4.Open();

                    using (IDbCommand cmd = db4.CreateCommand())
                    {
                        cmd.CommandText = "SELECT * FROM Test WHERE ID = " + random.Next() + ";";
                        using (IDataReader rdr = cmd.ExecuteReader())
                        {
                            while (rdr.Read())
                            {
                                Console.WriteLine(string.Format("{0}: {1}", rdr["ID"], rdr["Value"]));
                            }
                        }
                    }

                    Console.WriteLine(string.Format("---- {0:yyyy-MM-dd HH:mm:ss.fff} ----", DateTime.Now));
                    Thread.Sleep(250);
                }
            }
        }

Am I doing anything wrong ?
As far as I see, I should have disposed any IDatabase object...

my environment:
  Windows7 64bit
  Visual Studio 2012
  .NET Framework 3.5 SP1
  NPoco 2.10.11
//

**Comment by mia-san** [comment]
I forgot to mention that number of entities in table not seems to matter.
Even empty table (as above), memory is keep consumed using SQLIte.

**Comment by schotime** [comment]
Try using parameterized queries in the raw one.
They are not identical to the NPoco ones.

Also what happens if you reuse the NPoco.Database object instead of newing it up each time. Then use can call OpenSharedConnection() and CloseSharedConnection() like the raw one does.

**Comment by mia-san** [comment]
thanks for your suggestions, and sorry for delay.

1. slightly modified test program as following to reuse NPoco.Datbase, run the program almost 1 day, and found that memory consumption is 'stable' (always below 12MB in my environment)
            using (NPoco.IDatabase db1 = new NPoco.Database(@"Data Source=test1.db", factory))
            using (NPoco.IDatabase db2 = new NPoco.Database(@"Data Source=test2.db", factory))
            using (NPoco.IDatabase db3 = new NPoco.Database(@"Data Source=test3.db", factory))
            using (NPoco.IDatabase db4 = new NPoco.Database(@"Data Source=test4.db", factory))
            {
                for (; ; )
                {

2. turned 'raw' SQLite query to be parameterized as following, run the program almost 1 day, found that memory consumption is also stable(below 10MB here)
                        cmd.CommandText = "SELECT * FROM Test WHERE ID = @Id;";
                        IDbDataParameter p = cmd.CreateParameter();
                        p.ParameterName = "Id";
                        p.Value = random.Next();
                        cmd.Parameters.Add(p);

It seems to me that disposing Database is not really, at least in SQLite case.


My requirement is
1. program is muti-threaded(10 or more threads)
2. program is supposed to be run without restarting/rebooting (at least 1 month or so)
3. DbProviderFactory may be changed by external configuration, I want to be 'database-independent' manner.

I think I have to create/destroy NPoco.Database on thread enter/exit,
or is it safe to share single (static) instance of NPoco.Database by multiple threads?

Any suggestions are appreciated.
NPoco is very suitable for my requirement except this issue...
//

**Comment by schotime** [comment]
It is safe to share but I normally use one per thread.
