### ISSUE TITLE
SqlCE - byte[] (> 8000) to image field truncate exception

### ISSUE THREAD

**Issue by Zbyloo** [schotime/NPoco#214]
For  BLOBs > 8000 bytes in SqlServerCE "Image" field type should be used.
When you try to insert/update poco with byte[] (> 8000) property mapped to Image db field, default mapping throw exception: "@0 : Byte array truncation to a length of 8000".  
Kind solution could be implementing IMapper like this:

```C#
    public class ImageMapper : DefaultMapper
    {
        public override Func<object, object> GetParameterConverter(DbCommand dbCommand, Type sourceType)
        {
            if (sourceType == typeof(byte[]))
            {
                return x =>
                {
                    SqlCeParameter param = new SqlCeParameter();
                    param.SqlDbType = SqlDbType.Image;
                    param.Value = x;
                    return param;
                };

            }
            return base.GetParameterConverter(dbCommand, sourceType);
        }
```

I saw in NPoco code that SqlCE NText truncate handling is hardcoded (Database.cs - line 466).
Just for consideration if binary/image issue could be fixed in main code.

**Comment by schotime** [comment]
Custom mapper will have to be used for now.
Happy to take a PR, but not want the code to be SqlCE specific
