### ISSUE TITLE
new string function request in Linq

### ISSUE THREAD

**Issue by williamlee1982** [schotime/NPoco#215]
usually, we use a sql like this:
select * from products where product_name >= 'ABC';
it will return not only the products for 'ABCD', 'ABCDE' but also 'BCD', 'EFG',
which means the StartsWith() function is not enough.
may I request some new string functions like GreaterThan(), LessThan(), GreaterOrEqualsTo(), LessOrEqualsTo() ?
thanks very much.

**Comment by schotime** [comment]
This will only be implemented if I could allow you to add them manually. Saying that....it may be possible in v3 with its new support. Checkout https://github.com/schotime/NPoco/blob/dnx/test/NPoco.Tests/NewMapper/NewMapperTests.cs#L557 on how it can be extended.
