### ISSUE TITLE
Attempting to switch to new ‘dotnet’ target framework monikers

### ISSUE THREAD

**Issue by Workshop2** [schotime/NPoco#216]
Hello,

Class Libraries are now meant to reference the new target framework things: move from dnxcore50 -> dotnet5.4. See https://github.com/aspnet/Announcements/issues/98

I have tried doing it on this branch, but alas I haven't had much luck. Not sure if you could help me?

https://github.com/Workshop2/NPoco/commits/dnx-net-standard

Many thanks,
Simon

**Comment by schotime** [comment]
Yeah...I haven't done this yet because its going to change again to netstandard in the next RC. 
It should still work as it is now. Or are you having issues?

**Comment by Workshop2** [comment]
I will just wait for the ground to stop shifting around this stuff and come back if I still have problems.

Thanks
