### ISSUE TITLE
V3 - projection to included entity

### ISSUE THREAD

**Issue by akarzazi** [schotime/NPoco#218]
Hi,
I'm absolutely in love with the V3 Api. i like the new fk attributes and `include<T>()` stuff.
I hope you'll get it to a beta release.

The issue (in V3) : 
``` 
 var ExtraUserInfosOfSomeUsers = Database.Query<User>()
                .Include(x => x.ExtraUserInfo)
                .ProjectTo(x => x.ExtraUserInfo);
``` 
Projection to an included entity does not work and fail with a cast exception (long to ExtraUserInfo).

**Comment by schotime** [comment]
Thanks.
I've found the issue. Will try and get a fix in this week.

**Comment by schotime** [comment]
https://www.nuget.org/packages/NPoco/3.1.0-beta3

Give that a try.
