### ISSUE TITLE
Parameter Types  (varchar vs nvarchar)

### ISSUE THREAD

**Issue by dblacklock** [schotime/NPoco#219]
Hi,

We have some queries that look like this.

 int entid =
               db.ExecuteScalar<int>(
                   "select top 1 entid from ent where custno > @0 and cid = @1 and active = 'y' order by custno asc",
                   custno, cid);

This generates this which is sent to the SQL server
exec sp_executesql N'select top 1 entid from ent where custno > @0 and cid = @1 and active = ''y'' order by custno',N'@0 nvarchar(4000),@1 nvarchar(4000)',@0=N'ABC1',@1=N'DEMO'

The issue is the nvarchar(4000) parameter types.  That query returns the wrong value in our data, but changing the nvarchar(4000) to varchar(4000) returns the correct data.

Using ansistring() changes the query to use varchar. 

   int entid =
               db.ExecuteScalar<int>(
                   "select top 1 entid from ent where custno > @0 and cid = @1 and active = 'y' order by custno asc",
                   new AnsiString(custno), new AnsiString(cid));

 Is there a way to force npoco to always use varchar instead of nvarchar without having to use the AnsiString on each query?

Thanks

**Comment by schotime** [comment]
Not really if you are writing queries manually.
However if you are using the LINQ provider then specifying the ColumnType as (typeof(AnsiString)) will automatically use varchar instead of nvarchar
