### ISSUE TITLE
Setup NPoco & PostgreSQL IN Asp5

### ISSUE THREAD

**Issue by Raika** [schotime/NPoco#220]
How can I setup `NPoco` for `PostgreSQL` in `Asp5`?
In 2.x wiki says I need add something to my `app.config/web.config`.
this means I must add this to `web.config` inside `wwwroot`?
or something else must be done?

**Comment by schotime** [comment]
Just use the constructor.
No need for app.config.

**Comment by Raika** [comment]
I'm using this constructor:
```csharp
new Database( _connectionString , DatabaseType.PostgreSQL );
```
first Im getting the 
`Unable to find the requested .Net Framework Data Provider. It may not be installed.`
then add `"Npgsql": "3.1.0-alpha6"` to my `project.json` and no luck
I even change change `"Npgsql": "2.2.7"` still same error

**Comment by schotime** [comment]
IDatabase db = new Database("connstring", DatabaseType.PostgreSQL, Npgsql.NpgsqlFactory.Instance);

**Comment by schotime** [comment]
You will need 3.1.0-alpha6 for CoreCLR.
I just tested and they both work with the above.

**Comment by Raika** [comment]
Thanks.
