### ISSUE TITLE
How I can use WITH(NOLOCK) sql statement

### ISSUE THREAD

**Issue by firatoltulu** [schotime/NPoco#221]
Hi,

I use IDatabase.Query method  greet method,
but i need before execute sql replace  WITH(NOLOCK) statement?

how i can?

Thanks for help

**Comment by schotime** [comment]
You can either write your query with the nolock in the statement, or set the transactions isolation level.

http://stackoverflow.com/questions/3550337/with-nolock-vs-set-transaction-isolation-level-read-uncommitted

**Comment by firatoltulu** [comment]
thanks i try that

**Comment by firatoltulu** [comment]
What i can set isolation-level-read?

Thats my configuration

var fluentConfig = FluentMappingConfiguration.Configure(new MicroMapping());
                var DbFactory = DatabaseFactory.Config(x =>
                {
                    x.UsingDatabase(() => new MicroCoverDatabase());
                    x.WithFluentConfig(fluentConfig)
                    .WithMapper(new Mapper());
                });
                

    public class MicroCoverDatabase : NPoco.Database
    {
        public MicroCoverDatabase() : base(DatabaseConnectionName.MicroCoverMaster.ToString()) { }
        protected override bool OnInserting(InsertContext insertContext)
        {
            var auth = EngineContext.Current.Resolve<Authentication.IAuthenticationService>();
            var user = auth.GetAuthenticatedUser();
            if (insertContext.Poco is TrackableEntity && user != null)
            {
                var context = insertContext.Poco as TrackableEntity;
                context.CreatedAt = DateTime.Now;
                context.CreatedBy = user.UserName;
                context.CreatedByLogId = user.LastAccessByLogId;
            }
            return base.OnInserting(insertContext);
        }

        protected override bool OnUpdating(UpdateContext updateContext)
        {
            var auth = EngineContext.Current.Resolve<Authentication.IAuthenticationService>();
            var user = auth.GetAuthenticatedUser();
            if (updateContext.Poco is TrackableEntity && user != null)
            {
                var context = updateContext.Poco as TrackableEntity;
                context.ModifiedAt = DateTime.Now;
                context.ModifiedBy = user.UserName;
                context.ModifiedByLogId = user.LastAccessByLogId;
            }
            return base.OnUpdating(updateContext);
        }
       
    }

**Comment by schotime** [comment]
You can pass it into the `GetTransaction()` method for each transaction or into the constructor of `Database`.
