### ISSUE TITLE
Npoco does not work with DBParameter(s)

### ISSUE THREAD

**Issue by danisiuss** [schotime/NPoco#222]
I  have tried to use  it  out of the box wo success. 
I am using Postgres and needed it for some of datatypes like arrays

I have found workarround  with modification of ParameterHelper.ProcessParams

                      //after  property section
                       'var pi = o.GetType().GetProperty(param);'
                        ........
                       //added following section
                        var dbparam = o as IDataParameter;
                        if(dbparam!=null && dbparam.ParameterName==param )
                        {
                            arg_val = o;
                            found = true;
                            break;
                        }`

**Comment by schotime** [comment]
Not sure about this. I've used this successfully many many times. How were you using it?
