### ISSUE TITLE
Database.Page generates invalid SQL if an "ORDER BY"-column contains the word "from"

### ISSUE THREAD

**Issue by raphaelr** [schotime/NPoco#223]
Assume the following table:
`create table paging_test(id int not null primary key, date_from datetime)`

with the following code:
```
public List<PagingTest> DoPagingTest(Database db, out long totalCount)
{
    var sql = new Sql()
        .Select("*")
        .From("paging_test")
        .OrderBy("date_from");
    var page = db.Page<PagingTest>(1, 10, sql);
    totalCount = page.TotalItems;
    return page.Items;
}

[TableName("paging_test")]
public class PagingTest
{
    [Column("id")]
    public int Id { get; set; }
    [Column("date_from")]
    public DateTime DateFrom { get; set; }
}
```

Then, on SQL Server, you will get the exception "System.Data.SqlClient.SqlException (0x80131904): The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP or FOR XML is also specified."

I believe the root cause to be commit 1ecfc5d12dc73da3b8c4e6989adb3919200dc807, in which PagingHelper.SplitSQL was modified to ignore order by clauses if the substring "from" appears afterwards: "(?!.*(?:FROM))ORDER\s+BY". Because of that, the SQLParts.sqlUnordered will still contain the ORDER BY clause which breaks SQLParts.sqlCount since it must not contain an ordering. Changing the SQL to
```
var sql = new Sql()
    .Select("*, date_from as date_frm")
    .From("paging_test")
    .OrderBy("date_frm");
```
is a workaround, but it's rather ugly, and this behaviour isn't documented anywhere.

I'm using NPoco 2.10.11.

Cheers,
Raphael

**Comment by schotime** [comment]
Here is a hotfix. Run the following in your Application_Start or at the start of your main method.

```csharp
PagingHelper.rxOrderBy = new Regex(@"(?!.*(?:\s+FROM\s+))ORDER\s+BY\s+([\w\.\[\]\(\) ""`,]+)(?!.*\))", RegexOptions.IgnoreCase | RegexOptions.Multiline | RegexOptions.Singleline | RegexOptions.Compiled);
```

**Comment by raphaelr** [comment]
Thanks a lot, works like a charm!

**Comment by schotime** [comment]
Awesome...will try and put it into a new nuget this week sometime.
