### ISSUE TITLE
Export and Import beetween 2 DB / Trying with Dynamic only 

### ISSUE THREAD

**Issue by aleblanc70** [schotime/NPoco#224]
Good Day,

Not sure if what I try do is acceptable by Npoco, maybe there is a workaround...

When the insert line is execute I have :
      An unhandled exception of type 'System.NullReferenceException' occurred in NPoco.dll 

I try to replicate a few information from one DB to an another via a messaging service.

This is code snippet to validate my use case...

Read the record I need
Send the record to the other site
Insert the record.

I try to avoid the declaration off all my class for all the Table I need to Export.
Thanks!
André

           using (var db = DbFactory.GetDatabase())
            {
                Guid lotId = Guid.Parse("79858BF4-DEE9-4B82-89FE-051FF113B472");
                var lot = db.FirstOrDefault<dynamic>("SELECT * FROM Lot WHERE LotID = @0", lotId);
                lot.LotID = Guid.NewGuid();

                db.Insert("Lot", "LotID", lot); -----> 'System.NullReferenceException' 

            }

**Comment by aleblanc70** [comment]
Do I try something supported or it is not a use case support ?

**Comment by schotime** [comment]
It should be, but I need more information. I'll see if i get a chance to run this case today.

**Comment by aleblanc70** [comment]
Thanks for the answer. I'm not use to try to compile source code from github. But now that I know It should work I will try to build and debug the issue also.

André

**Comment by schotime** [comment]
Give the latest Beta a go ;)

**Comment by aleblanc70** [comment]
The correction Work. 
But my table have a timestamp column and I have and issue of default value. :(

**Comment by schotime** [comment]
Yeah...not going to work. You're going to have to create a strongly typed object.
