### ISSUE TITLE
Fetching a struct causes InvalidCastException

### ISSUE THREAD

**Issue by JustinMorgan** [schotime/NPoco#226]
When trying to run `Fetch<T>(string, params object[])` or `First<T>(string, params object[])`, I get a `System.InvalidCastException` if T is a struct. If I make it a class without changing anything else, it works. It seems to be trying to cast the Primary Key to the model type, or vice versa.

Model type:

    public struct VersionModel
    {
        public short VersionId { get; set; }
        public int CodeTypeId { get; set; }
        public DateTime VersionDate { get; set; }
        public string Label { get; set; }
    }

Query:

    const string query =
        @";select top 1
            VersionId
            ,CodeTypeId
            ,VersionDate
            ,Label
        from [Version]
        where VersionDate <= @0
        order by VersionDate desc;";
            
    return _db.First<VersionModel>(query, now);

From the ASP.NET MVC error page (some identifying details removed as noted):

> Exception Details: 
> 
>     System.InvalidCastException: Invalid cast from 'System.Int16' to '((namespace)).VersionModel'.
> 
> Source Error: 
> 
>     Line 37:                 order by VersionDate desc;";
>     Line 38:             
>     Line 39:             return _db.First<VersionModel>(query, DateTime.Now);
>     Line 40:         }
>     Line 41: 
> 
> Stack Trace: 
> 
>     [InvalidCastException: Invalid cast from 'System.Int16' to '((namespace)).VersionModel'.]
>        System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider) +13709456
>        poco_factory_0(IDataReader , Object ) +115
>        NPoco.<Query>d__77.MoveNext() in d:\Adam\projects\NPoco\src\NPoco\Database.cs:1011
>        System.Linq.<CastIterator>d__94`1.MoveNext() +132
>        System.Linq.Enumerable.First(IEnumerable`1 source) +179
>        ((namespace)).CurrentVersionService.GetCurrentVersion(CodeType codeType) in ((path))\CurrentVersionService.cs:39
>        ((namespace)).DetailsService.FindByCode(String code) in ((path))\DetailsService.cs:35
>        ((controller)).Details(String code) in ((path))\((controller)).cs:155
>        lambda_method(Closure , ControllerBase , Object[] ) +139
>        System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +229
>        System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +35
>        System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +39
>        System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +71
>        System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42
>        System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72
>        System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
>        System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
>        System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
>        System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42
>        System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +38
>        System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +186
>        System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
>        System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
>        System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +67
>        System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
>        System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
>        System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
>        System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +44
>        System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +67
>        System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
>        System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +399
>        System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +137
> 
> Version Information: 
> 
>     Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0

**Comment by schotime** [comment]
Structs are not **currently** supported.
