### ISSUE TITLE
BulkInsert throwing ArgumentNullException

### ISSUE THREAD

**Issue by JobaDiniz** [schotime/NPoco#228]
This [line](https://github.com/schotime/NPoco/blob/master/src/NPoco/SqlBulkCopyHelper.cs#L21) uses `db.Connection` however *Connection* is always **null**:

```
using (var database = new Database("AppPortal"))
            {
                //database.Connection -> NULL
                SqlBulkCopyHelper.BulkInsert<CDR>(database, cdrs);
            }
```

**Comment by schotime** [comment]
Call opensharedconnection or begin a transaction before calling it.

**Comment by schotime** [comment]
or call 
```
database.InsertBulk<T>(cdrs)
```
