### ISSUE TITLE
[ComputedColumn] Not being ignored during Update

### ISSUE THREAD

**Issue by GACoder** [schotime/NPoco#229]
Columns decorated [ComputedColumn] are being added to update statement. 

`       [Key, Required]
        public string WidgetID { get; set; }
        [ComputedColumn]
        public string WidgetType { get; set; }
         ......   `

`        _dbNpoco.Update(entity);  `

Generates:

`    exec sp_executesql N'UPDATE [app].[vMyWidgets]
             SET [WidgetID] = @0, [WidgetType] = @1, .....`

v2.10.11

**Comment by schotime** [comment]
Where are you other attributes like `[TableName]`, `[PrimaryKey]`?

**Comment by GACoder** [comment]
Yes... they exist. 
`    [Table("app.Widgets")]
    [TableName("app.Widgets")]
    [PrimaryKey("WidgetID")]
    public partial class Widgets
    { .....`

**Comment by schotime** [comment]
No idea then.
https://github.com/schotime/NPoco/blob/dev2.0/src/NPoco/Database.cs#L1525
