### ISSUE TITLE
Async with MySQL

### ISSUE THREAD

**Issue by konstk** [schotime/NPoco#230]
I just downloaded latest Beta 4 of NPoco 3.1. Works like a charm with MS SQL, but when I try to do simple FetchAsync with MySQL, I get exception "Async is not supported... ". Is it something that is not yet implemented? If so, any possible estimates?

Thanks in advance

**Comment by schotime** [comment]
Give Beta5 ago.

**Comment by konstk** [comment]
Thanks, I will give it a go Monday!

**Comment by konstk** [comment]
Just quickly updated to Beta5 and reverted back to Beta4. My application thrown exception at the first Update ( Database.Update<Poco>(poco) statement).

```
An exception of type 'MySql.Data.MySqlClient.MySqlException' occurred in NPoco.dll but was not handled in user code

Additional information: Only MySqlParameter objects may be stored
```

**Comment by schotime** [comment]
Any other information? Stack trace?

**Comment by schotime** [comment]
Do you have a byte[] property?

**Comment by konstk** [comment]
Sorry, it was at the end of a very long day... Yes, I have ```byte[]``` property in the poco.

**Comment by schotime** [comment]
Ok. I know what it will be. Will have it fixed over weekend. Thanks.

**Comment by schotime** [comment]
Try Beta6

**Comment by konstk** [comment]
Yes, it seems to be working now! I will do some more testing Monday. Many thanks!!!!
