### ISSUE TITLE
3.0 roadmap

### ISSUE THREAD

**Issue by zpqrtbnk** [schotime/NPoco#233]
Hey,

Umbraco has been using PetaPoco for its data layer for some time, but we have been planning to migrate over to NPoco for our next (v8) version. We're now starting this migration and have to make a choice between targetting the 2.x or 3.0 branch.

I understand 3.1 is a "3.0 on Core" effort and probably depends on things you don't control (Core roadmap) so it's probably out of the equation for the moment. I understand that 2.x is stable and 3.x is work-in-progress, but it hasn't change for a few months and it seems you're mostly working in 3.1 now.

Considering there will be _some_ months before we release our version... our gut feeling would be to go with 3.0. Which leads us to:
* 3.0 stabilizes and ships within the next 2-3 months + brings worthy additions to 2.x: go for 3.0, _or_
* 3.0 is really work-in-progress / unstable at the moment / you would rather keep it a moving target / may be a Core-only (3.1) thing, we may end up in a dead-end: stick with 2.x, _or_
* ?

Thoughts?
Thanks!

**Comment by schotime** [comment]
Hey,

I would say 3.1 is the way to go. It is pretty much ready to be released. Just waiting for some more feedback and then its going to go live. There is only one outstanding issue with it as well.

There isn't really any compromises to enable dot net core, as I have just conditionally compiled things that aren't supported by .net core out.

The main difference is the project format (no csproj yay).

If you have any other questions let me know

Cheers,
Adam

**Comment by zpqrtbnk** [comment]
Wow, cool. Thanks for your answer. Going with 3.1 then!
Will let you know how it goes.

**Comment by schotime** [comment]
That would be great.
Here are some things to keep in mind if migrating.
https://github.com/schotime/NPoco/wiki/Version-3

**Comment by zpqrtbnk** [comment]
v3.1 not building because...
~~~~
Errors in C:\Projects\NPoco\src\NPoco\project.json
    Unable to locate Dependency Microsoft.Framework.Caching.Abstractions >= 1.0.0-rc1-15658
    Unable to locate Dependency Microsoft.Framework.Caching.Memory >= 1.0.0-rc1-15658
~~~~
These dependencies seem to be `Microsoft.Extensions.Caching...` now?
Rings a bell?

**Comment by dheijl** [comment]
I tested the latest 3.1.0 beta 6 nuget on .Net 4.6.1 with no issues. Have not tried building from the source yet.

**Comment by grehovm** [comment]
any news?

**Comment by zpqrtbnk** [comment]
FWIW we have Umbraco almost fully running on 3.1, built from source, no issues so far.

**Comment by grehovm** [comment]
With what database are you testing umbraco?
I was thinking of using PostgreSQL (npgsql 3+) may be you have experience?

**Comment by zpqrtbnk** [comment]
Testing against MS SQL at the moment, with plans to also support MySql. Not tested PostgreSQL.

**Comment by schotime** [comment]
Should we just do a release with what we have so that more people find any possible issues?

**Comment by schotime** [comment]
We have just moved 3.1 into prod, so unless anyone has any objections, or last minute issues i'm gonna create an official release this weekend/week. cc @zpqrtbnk @Shazwazza @grehovm @dheijl

**Comment by Shazwazza** [comment]
Great! I'm happy with the changes so long as @zpqrtbnk is

**Comment by schotime** [comment]
I have worked in mapping to c#6 get only properties as well thanks to dapper @marcgravell

```
class Getz {
    public string Name { get; }
}
```

**Comment by schotime** [comment]
Is there anything else we need to clean up/do before a release? 
Do we need anymore specific doco? Version 3 page need any more? What have people found?

**Comment by dheijl** [comment]
I think it's ready for a release, but perhaps the new "reference" stuff could use a couple of examples, like showing both the Fetch/FetchOneToMany/null alias and the (multiple)Include/IncludeMany implementation for the same query?

**Comment by schotime** [comment]
Cool. I already have this page, which has been up for 6 months. 
https://github.com/schotime/NPoco/wiki/Version-3
Will take pull requests on it, or suggestions to parts.

**Comment by schotime** [comment]
Shit just got real! Its live! 3.1

**Comment by schotime** [comment]
Updated some doco on fetchonetomany and the serialized attribute.
Closing this for now. 
V3.2 out.
