### ISSUE TITLE
[3.1] Cache Question

### ISSUE THREAD

**Issue by zpqrtbnk** [schotime/NPoco#235]
Hey,

It has to be obvious but I cannot understand it.

The `MemberAccessor` class creates get/set delegates. That happens when a `PocoDataBuilder` is initialized. Which seems to happen anytime a `PocoDataFactory` has to return a `PocoData` for a type for the first time. And each `Database`, when created, seems to create and own it own `PocoDataFactory`.

Which would mean that each `Database` instance ends up creating a data factory, builders, the get/set delegates, etc. Which sounds... bad.

What am I missing? ;-)

S.

**Comment by dwirawan** [comment]
@zpqrtbnk nice catch :), i just playing with NPoco to understand its internal mechanism, IMHO v3.1 introduce a lot of broken changes in its internal structure. I agree with you about ``PocoData`` that should be statically cached, but this behavior is intentionally changed since v2.11.10, any reason @schotime ?. There are also inconsistent behavior about using ``Attributes`` and ``FluentMapping`` especially for reference. Indeed v3.1 offer flexibility over mapping plan that is awesome in my opinion, but i think there are a lot of things that need to be clarified about those changes.

**Comment by zpqrtbnk** [comment]
Into PR mode ;-)

**Comment by schotime** [comment]
Hey guys,

There is indeed a caching issue that I'm working through at the moment.
It's quite complex so I'm trying to plan in out.

The pocodata's are rebuilt on each query now as they may need to mutate per
query, however they are very cheap to build. This is done to enable certain
scenarios with the linq queries.

Thanks for the feedback
Adam

**Comment by zpqrtbnk** [comment]
As I go through the code and try to understand and check changes vs v2, might submit PRs that mostly add comments, to begin with - if that's OK with you?

**Comment by dwirawan** [comment]
It is indeed quite complex :D, but i think once you traverse all member and built ``PocoData`` metadata is enough to support most query scenario, (except for dynamic, which need to be evaluated each run) or maybe i missed some scenario? My idea is moving ``PocoDataFactory`` outside the ``Database`` lifecycle and injected into database for mapping plan, therefore you can maintain static cache for typed poco, but im not sure if it is suitable for ``dynamic`` property.

**Comment by schotime** [comment]
That's what already happens with fluent config because you can have
multiple configs but you can only have one attribute mapping so I think I
have a solution. Bare with me.

**Comment by dwirawan** [comment]
@schotime about fluent mapping, have you read my comment https://github.com/schotime/NPoco/issues/232#issuecomment-193165931 ?

**Comment by schotime** [comment]
@dwirawan I have, and its on my list to have a look at tomorrow after I sort the caching out ;)

**Comment by dwirawan** [comment]
@schotime thanks, maybe i will start some contribution for small patch, since i am not familiar with git, so pardon me for some PR mistake ;)

**Comment by schotime** [comment]
@dwirawan Even if you can figure out the problem and can send me the snippet that fixes and a test or post it in the issue then I can always patch it from there ;)

**Comment by schotime** [comment]
Just committed up new changes and merged your other PR @zpqrtbnk

**Comment by schotime** [comment]
This one fixed now? Can i close?

**Comment by zpqrtbnk** [comment]
From what I've seen, using the new fluent factory et al, my original question is solved. Thanks!
Closing.
