### ISSUE TITLE
Using NPoco with Npgsql - 23502: null value in column "id" violates not-null constraint

### ISSUE THREAD

**Issue by nochristrequired** [schotime/NPoco#238]
Hi,

First of all, I've used NPoco with MySQL before, and it worked great. Recently, I tried to use it with Postgres using the Npgsql driver. It keeps telling me that "null value in column "id" violates not-null constraint" but my object has the primary key field set! I've been pulling my hair out. If I tried to .Execute RAW SQL, I get no exception, it looks like everything was inserted by the transaction, but Postgres does not show anything in the logs and the table remains empty. It's really puzzling - could this be an issue with Npgsql?

For reference, I have a Poco called Incidents which contains a list of Pocos - 
public List<Incident> items;

I've tried various things, and finally commented out all of my properties except the primary key, which I've explicitly mapped.
---
using NPoco;

namespace CloudLockTestApp
{
    [TableName("cloudlock.incidents")]
    [PrimaryKey("id")]
    public class Incident
    {
        public string id { get; set; }
    }
}
---

Here's a snippet from the procedure. The .Insert will throw the above error. The RAW .Execute (both of them) throw no errors at all. incident.id IS set to a string value. (string value for pkey is not my choice, this is inter-operating with vendor software)

Database database = new Database("LocalDB");

using(database)
 {
                using (var transaction = database.GetTransaction())
                {
                    foreach (Incident incident in incidents.items)
                    {
                        database.Insert(incident);

                        //database.Execute("INSERT INTO cloudlock.incidents (id) VALUES (@0);", incident.id);

                        //database.Execute("INSERT INTO cloudlock.incidents (id) VALUES ('" + incident.id + "');");
                    }
                }
 }

Thanks in advance!

**Comment by nochristrequired** [comment]
Thanks schotime! I did do that with Fluent Mappings and it still had problems where it would appear to insert but would not actually insert (no exceptions thrown, but no data in the pg_log). I will try using just the basic mapping as you've shown.

Also, quick question - is NPoco sophisticated enough to deal with a Poco that contain other Pocos with their own table mappings? Incidents contains a custom type called Entities which has it's own table mapping / structure. I have multiple of these custom types that are associated with their own table.

**Comment by schotime** [comment]
Are you creating a transaction and not completing it? I'm using Postgresql in production fyi.

**Comment by nochristrequired** [comment]
schotime, sorry for any confusion on my part. I am not committing the transaction in code. I have it in a using clause. Perhaps I am missing a final step to commit the transaction? It would make sense if i had to do say a database.Commit(transaction); or something. I have my using clause and then a database.Insert(poco);

**Comment by schotime** [comment]
Can you post a snippet of the code you are using?
