### ISSUE TITLE
PostgreSQL timestamp with time zone and NPoco ForceToUtc issue

### ISSUE THREAD

**Issue by mixerp** [schotime/NPoco#239]
I am having an issue because NPoco is 

1) enforcing the property "ForceToUtc" by default.

https://github.com/schotime/NPoco/blob/8334a03ff06d2bbe8dcd4caf0c342cd4730202c7/src/NPoco/PocoColumn.cs#L10

2) swallowing the timezone offset thus producing wrong result

https://github.com/schotime/NPoco/blob/8334a03ff06d2bbe8dcd4caf0c342cd4730202c7/src/NPoco/MappingFactory.cs#L385

in this line

```cs
if (pc != null && pc.ForceToUtc && srcType == typeof(DateTime) && (dstType == typeof(DateTime) || dstType == typeof(DateTime?)))
{
    converter = delegate(object src) { return new DateTime(((DateTime)src).Ticks, DateTimeKind.Utc); };
    return converter;
}
```

I am using fluent mapping:
https://github.com/frapid/frapid/blob/master/src/Libraries/Frapid.Configuration/DbProvider.cs

If you are unsure about what I mean, I can prepare a small test case and a fix (PR) as well. Please advise if I am missing a point here.

**Comment by schotime** [comment]
What version of Npgsql are you using?

**Comment by mixerp** [comment]
Thank you so much for answering. I am using `Npgsql 2.2.6` because I faced some issues with NPoco plus latest Npgsql version.

Similarly, I am using NPoco fluent mapping to keep the classes clean, which has worked wonders. It is possible to completely switch off `ForceToUtc` using fluent mapping?

**Findings**

Stepping through NPoco code in the debugger, I found out that [this line](https://github.com/schotime/NPoco/blob/8334a03ff06d2bbe8dcd4caf0c342cd4730202c7/src/NPoco/MappingFactory.cs#L385)

```cs
return new DateTime(((DateTime)src).Ticks, DateTimeKind.Utc);
```
is taking the tick info from `Local` timezone and converting it to `UTC`. Getting the tick info from `ToUniversalTime()` would solve the issue in my case:

```cs
return new DateTime(((DateTime)src).ToUniversalTime().Ticks, DateTimeKind.Utc);
```

Please let me know if you would like me to investigate and confirm the issue with all Npgsql versions (2.x onward).

**Comment by schotime** [comment]
The problem is that TimestampTZ actually converts its stored UTC date to local in the driver. This is stupid IMHO. I don't like that column type because of that now. Anyways....if that data was actually stored retrieved in UTC then this would be doing the right thing, so I can't go and change it cause then it won't work for DateTime and DateTimeOffset where the date is returned in UTC.

**Comment by mixerp** [comment]
Thank you for replying.

The only thing which works now (without changing anything) is to change the timezone of the server to UTC. But, that's not an option for me (and maybe many other people as well).

I totally understand that you are skeptical to change NPoco code because doing that may introduce new bugs and slipups.

We already have `ForceToUtc` attribute which addresses this issue to some extent, but the current mapping convention does not allow it be switched off. Wouldn't it be reasonable to keep all existing NPoco behavior unchanged, and add convention to map the attribute `ForceToUtc` to false?

I am saying this because currently NPoco returns wrong date time result in PostgreSQL Server with `timestamp with time zone` data type (not sure about other DBMS though).

Please advise what the option/solution/workaround is.

**Comment by schotime** [comment]
Use V3 and ForceToUtc can be set per column using the Column attribute

**Comment by frapid** [comment]
Can `ForceToUtc` be set to false on Fluent Mapping?
