### ISSUE TITLE
[3.1] Custom type/value converter on specific column

### ISSUE THREAD

**Issue by dwirawan** [schotime/NPoco#245]
@schotime For example ``enum`` in MySql is translated as string by the driver, somehow, it is used as true/false flag instead of using ``bit`` as the type, or maybe we want to translate the ``enum`` code to any other representation. Is it currently supported? If not, is it possible to add custom type/value converter per column definition?

**Comment by schotime** [comment]
You can use a custom attribute and then use a mapper where you can look up that attribute and then convert the value. Inherit from DefaultMapper and then override GetToDbConverter and look up the attribute off the sourceMemberInfo property. Then return a func of how you wish to convert the value. Return null if you want to fall through.

Let me know how you go. If you get stuck let me know and I'll post a better example.

**Comment by dwirawan** [comment]
Got the idea, it works but not an elegant solution i think, since maintain attributes and fluent mapping might be cumbersome :D. Gonna close it for now, will re-open if i have another idea ;). Thanks.
