### ISSUE TITLE
[3.1] Multiple IncludeMany and hierarchies

### ISSUE THREAD

**Issue by enrico-padovani** [schotime/NPoco#246]
Hi,

given SalesOrderHeader -- 1:n --> SalesOrderDetail -- 1:1 --> Product. It's possible to write a query that selects the whole hierarchy? As I see, you can concatenate multiple Include, but not IncludeMany and a single Include.

Thanks!

**Comment by dwirawan** [comment]
hi @enrico-padovani, this could be achieved by using null aliasing in your query, i tried this for my own cases, but it should be applicable for your case too. Supposed you already configure the mapping/reference correctly, you could write query like this.
```
select sh.*,null npoco_details,sd.*,npoco_details__product,p.* from salesorderheader sh left join salesorderdetail sd on sh.orderid=sd.orderid left join product p on sd.productid=p.productid order by sh.orderid
```
hopefully you get the idea. ;)

**Comment by enrico-padovani** [comment]
Hi,

thanks for the tip: writing a query with the new mapper convention works. You have to use FetchOneToMany<T> with null aliasing for * or by specifying the columns you want to get in select.

My question is more about to know if it's possible to achieve the same result by using the linq provider and .IncludeMany. Does everyone made that work?

**Comment by schotime** [comment]
I have a solution for this.
Will try and work it in for the next release.

**Comment by schotime** [comment]
This is in the latest beta92 (stupid nuget).
Anyways you should be able to do this.

```csharp
   .Include(x => x.SalesOrderDetails[0].Product) 
//or .Include(x => x.SalesOrderDetails.First().Product)
   .IncludeMany(x => x.SalesOrderDetails)
```

Let me know how you get on.

**Comment by enrico-padovani** [comment]
Hi,

if i'm using .Include(x => x.SalesOrderDetails[0].Product) it works

if I try .Include(x => x.SalesOrderDetails.First().Product) 
or .Include(x => x.SalesOrderDetails.FirstOrDefault().Product)
I got: "Sequence contains no matching element"

some info: the FK from SalesOrderDetail to Product is NOT NULL, what happen in case of nullabe FKs (alias 0:1)?

Thanks,
Enrico

**Comment by schotime** [comment]
What do you mean what happens in the nullable FK's?
It will do a left join by default so it will be null on the many if I understand correctly.

**Comment by enrico-padovani** [comment]
Ok for left joins, so if the ProductId is null on SalesOrderDetail it will not select the product but still select the sales order detail (the parent). I mean if calling a .First() or trying to access the [0] of a list with no elements it will throw an exception or not.

**Comment by schotime** [comment]
The First() or [0] or [1] or [2] or [n] doesn't matter at all. Its just a mechanism to get to the "Product" variable in your case.

I have fixed the issue with FIrst() and FirstAndDefautl() and it will be included in the 3.1.0 stable release out this week. Use the array syntax until then if you prefer First().

**Comment by enrico-padovani** [comment]
Ok nice to know! What if the Product is not a single item but a list of them?
It will still work a syntax like .Include(x => x.SalesOrderDetails.First().Products)

In general can you "chain" childrens as much as you want?

**Comment by schotime** [comment]
You can only have one 1:n relationship realised. It will make a query but
probably won't be right.

**Comment by tonag** [comment]
Hi, can you provide a full working sample?
I'm non able to find where and how to use include. I mean Fetch, Query Linq methods?
Thanks

**Comment by schotime** [comment]
@tonag Look at the tests

**Comment by lctjohn** [comment]
For future visitors, here are links to relevant files:

* [Fluent config](https://github.com/schotime/NPoco/blob/c534ebb008c6ef7dd19d8d09ad5bedbe7839d212/test/NPoco.Tests/Common/BaseDBFuentTest.cs#L253)
* [Decorated config](https://github.com/schotime/NPoco/blob/c534ebb008c6ef7dd19d8d09ad5bedbe7839d212/test/NPoco.Tests/NewMapper/Models/One.cs)
* [A query that populates the ListMany property](https://github.com/schotime/NPoco/blob/c534ebb008c6ef7dd19d8d09ad5bedbe7839d212/test/NPoco.Tests/NewMapper/NewMapperTests.cs#L218)
