### ISSUE TITLE
[3.1] Split Sql For Paging

### ISSUE THREAD

**Issue by zpqrtbnk** [schotime/NPoco#247]
Hey,

In previous versions, a query such as `SELECT t.* FROM table t` would be splitted and turned into a Sql _count_ expression looking like `SELECT COUNT(*) FROM table t`, whereas in 3.1 the `PagingHelper` creates an expression looking like `SELECT COUNT (*) FROM (SELECT t.* FROM table t)`.

I understand this is more robust and probably deals with complex queries (distinct, sub-queries, etc) in a better way. However it introduces an issue, when the initial query contains a `SELECT *` statement over joined tables with duplicate fields.

Say we have `Foo` objects with properties `Id` and `Name` and a reference to one `Bar` object with properties `Id` and `Email`. Say table `foo` has field `id` and `name`, and table `bar` has field `id` and `email`.

SQL is happy running `SELECT * FROM foo JOIN bar ON foo.id = bar.id` _but_ it cannot create a (temp) table containing the result of the query. That is, `SELECT * FROM SELECT (SELECT * FROM foo JOIN bar ON foo.id = bar.id) table` errors, because

> The column 'id' was specified multiple times for 'table'.

Which means we can fetch, but not do paged queries with wildcard columns. We would need to run `SELECT foo.id Id, foo.name Name, bar.id bar__Id, bar.email bar__Email FROM ...` ie listing all the fields explicitely _and_ providing distinct aliases.

Our app (Umbraco) uses `SELECT *` _a lot_ and this causes issues in various places -- however I cannot see how to support it in NPoco. Might be that we need to replace it all with explicit fields, using some helper inspired from `AutoSelectHelper`.

Wondering if you had another idea?

**Comment by schotime** [comment]
This was changed in bcb2cb85ebab4e891f60fa500b400eb1bcaab738 which was done almost 3 years ago now (v2.2.40), so I won't be changing it I don't think however I'm sure we can find a solution for you.
Happy to continue the discussion.
I'll think about it over the next few days and see what we can come up with. Happy to also work in a solution into NPoco to facilitate the scenario if we find a good one.

**Comment by zpqrtbnk** [comment]
Thanks. Understand we won't change it. Currently looking into adapting our code to generate proper SQL with qualified columns. At the moment, it is heavily inspired from `AutoSelectHelper` and lets me writes:
~~~~
var sql = new Sql()
  .Select<Foo>()
  .SelectReference<Bar>()
  .From...
~~~~
Which generates:
~~~~
SELECT Foo.Id, Foo.Name, Bar.Id AS Bar__Id, Bar.Email AS Bar__Email FROM...
~~~~
Which takes care of the duplicate `Id` field and loads the `Foo` object and its referenced `Bar` object quite nicely. Will keep experimenting and report.

**Comment by zpqrtbnk** [comment]
Works, including nested references, with code that looks like:
~~~~
var sql = new Sql()
  .Select<DocumentDto>(r =>
      r.Select<ContentVersionDto>(rr =>
        rr.Select<ContentDto>(rrr =>
          rrr.Select<NodeDto>())))
  .From(...)...
~~~~
(yes, our database and DTO structures are somewhat weird)

Happy if you close the issue.

**Comment by schotime** [comment]
Wouldn't mind seeing the code at some point in possible.

**Comment by zpqrtbnk** [comment]
See below.
Still not entirely happy with bits marked "fixme.npoco" where we retrieve the database from our global application context, just to access the (caching) PocoDataFactory.
But it works.

~~~~
public static Sql Select<T>(this Sql sql, Func<RefSql, RefSql> refexpr = null)
{
    Database database = ApplicationContext.Current.DatabaseContext.Database; // fixme.npoco
    var pd = database.PocoDataFactory.ForType(typeof(T));
    var tableName = pd.TableInfo.TableName;
    var columns = pd.QueryColumns.Select(x => GetColumn(database.DatabaseType,
        tableName,
        x.Value.ColumnName,
        string.IsNullOrEmpty(x.Value.ColumnAlias) ? x.Value.MemberInfoKey : x.Value.ColumnAlias));
    sql = sql.Select(string.Join(", ", columns));
     if (refexpr != null)
    {
        var nsql = new RefSql(sql, null);
        refexpr(nsql);
    }
    return sql;
}

public static RefSql Select<T>(this RefSql sql, Func<RefSql, RefSql> refexpr = null)
{
    return sql.Select<T>(null, refexpr);
}

public static RefSql Select<T>(this RefSql sql, string referenceName, Func<RefSql, RefSql> refexpr = null)
{
    Database database = ApplicationContext.Current.DatabaseContext.Database; // fixme.npoco
    if (referenceName == null) referenceName = typeof(T).Name;
    if (sql.Prefix != null) referenceName = sql.Prefix + PocoData.Separator + referenceName;
    var pd = database.PocoDataFactory.ForType(typeof(T));
    var tableName = pd.TableInfo.TableName;
    var columns = pd.QueryColumns.Select(x => GetColumn(database.DatabaseType,
        tableName,
        x.Value.ColumnName,
        string.IsNullOrEmpty(x.Value.ColumnAlias) ? x.Value.MemberInfoKey : x.Value.ColumnAlias,
        referenceName));
    sql.Sql.Append(", " + string.Join(", ", columns));
    if (refexpr != null)
    {
        var nsql = new RefSql(sql.Sql, referenceName);
        refexpr(nsql);
    }

    return sql;
}

public class RefSql
{
    public RefSql(Sql sql, string prefix)
    {
        Sql = sql;
        Prefix = prefix;
    }

    public Sql Sql { get; private set; }
    public string Prefix { get; private set; }
}

private static string GetColumn(DatabaseType dbType, string tableName, string columnName, string columnAlias, string referenceName = null)
{
    tableName = dbType.EscapeTableName(tableName);
    columnName = dbType.EscapeSqlIdentifier(columnName);
    columnAlias = dbType.EscapeSqlIdentifier((referenceName == null ? "" : (referenceName + "__")) + columnAlias);
    return tableName + "." + columnName + " AS " + columnAlias;
}
~~~~
