### ISSUE TITLE
[3.1] SqlServer BuildPageQuery

### ISSUE THREAD

**Issue by zpqrtbnk** [schotime/NPoco#248]
Hey,

Hitting an issue in `SqlServerDatabaseType.BuildPageQuery`. If the original query is
~~~~
SELECT [table].[id], [table].[name] AS [alias] FROM [table] ORDER BY [table].[name]
~~~~
The resulting query will be
~~~~
SELECT * FROM (SELECT poco_base.*, ROW_NUMBER() OVER (ORDER BY [name]) poco_rn
FROM (
SELECT [table].[id], [table].[name] AS [alias] FROM [table] ) poco_base ) poco_paged
WHERE poco_rn > @0 AND poco_rn <= @1
ORDER BY poco_rn
~~~~
Which will fail because `ORDER BY [name]` is invalid here as `[name]` is not a valid column in the `poco_base` column. It should be `ORDER BY [alias]`. As a consequence, it is not possible to paginate a query that has aliased columns that are _also_ used in the sort order.

**Comment by zpqrtbnk** [comment]
Have created PR https://github.com/schotime/NPoco/pull/249 which adds a test + a fix. The fix does work somehow, by looking for an `AS` statement for the `ORDER BY` columns. I am not entirely happy with it though, as I _think_ it still can fail on complex queries, plus it creates a new Regex, which is not optimal, perfs-wise.

**Comment by schotime** [comment]
Is there an issue ordering by the alias?

**Comment by zpqrtbnk** [comment]
No issue ordering by "alias" -- that is precisely what we want. The difficulty is to find "alias" since all we have is "name". So the code in my PR tries to look for the match in the rest of the query. No issue, it works, only I'm not 100% sure it will always work, depending on the complexity of the query (if it has inner select & things like that).

**Comment by schotime** [comment]
Sorry i meant. Cant the query be rewritten to use the alias?

**Comment by zpqrtbnk** [comment]
Uh... not sure we understand each other ;-) The original query is using the alias (and needs to). Then the SqlServerDataType, when building a paged query, extract the ORDER BY infos to bring them back into the OVER (ORDER BY ...) block. So it is SqlServerDataType that is writing that part of the query.

Unless... you imply that the original query could be written as
~~~~
SELECT [table].[id], [table].[name] AS [alias] FROM [table] ORDER BY [alias]
~~~~
Ie using "alias" in the ORDER BY clause. Mmm... that could work, but would require that we refactor how queries are generated. Looking into it.

**Comment by schotime** [comment]
Yeah i was referring to your last statement.

> Ie using "alias" in the ORDER BY clause. Mmm... that could work, but would require that we refactor how queries are generated. Looking into it.

**Comment by enriko-riba** [comment]
I think the same or similar problem arises if using multiple non aliased fields with same name.
Common scenario is paging over a join from multiple tables:
`select * from T1 inner join  T2 on T1.id = T2.parentid`
This will result in 
> The column 'Id' was specified multiple times for 'poco_base'.

**Comment by zpqrtbnk** [comment]
@enriko-riba in that type of situation, the only solution is to alias the fields

**Comment by zpqrtbnk** [comment]
Finally, it looks much cleaner to generate proper queries where ORDER BY uses the aliases. So I've closed the PR and also close this issue. It should be documented somehow, however, as that might confuse people.
