### ISSUE TITLE
Getting Returned Value from a Stored Procedure..

### ISSUE THREAD

**Issue by billrawlinson** [schotime/NPoco#252]
I asked this in another issue (#14) but perhaps that wasn't the right place so I'll ask it here:

Let's say I have a stored procedure that returns an integer (not a full model).

Is there a way to use nPoco to execute the stored procedure and get the integer result.

Here is the definition of the procedure:

```sql
CREATE procedure [dbo].[PurgeEventLog](@totalRecordsAffected INT OUTPUT)  as
...
```

I have tried a few different things; the most likely being:

```cs
            int result=0;
            var s = new Sql("EXEC dbo.[PurgeEventLog] @@totalRecordsAffected OUTPUT", result);
            db.Execute(s);
```

However, I get an exception each time:

```
System.Data.SqlClient.SqlException Must declare the scalar variable "@totalRecordsAffected ".
```

I've tried also just having the procedure return a value and using `db.ExecuteScaler<int>` but I just get back `0`.

I also tried using the guidance in @litera blog post but it didn't seem to work either:

```cs
            var totalRecordsAffected = new SqlParameter("@totalRecordsAffected", SqlDbType.Int);
            totalRecordsAffected.Direction = ParameterDirection.Output;

            Sql sql = Sql.Builder.Append("EXEC dbo.[PurgeEventLog] @@totalRecordsAffected out", new
            {
                totalRecordsAffected = totalRecordsAffected
            });

            int result = Database.SingleOrDefault<int>(sql);
            return (int)totalRecordsAffected.Value;

```

I still get the same error:

```
System.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable "@totalRecordsAffected".
```

Any help here would be appreciated.

**Comment by billrawlinson** [comment]
I can run it fine in SSMS and it both returns a value via a `RETURNS @totalRecordsAffected` and the out parameter is populated properly.

**Comment by schotime** [comment]
try 

```csharp
            var totalRecordsAffected = new SqlParameter("totalRecordsAffected", SqlDbType.Int);
            totalRecordsAffected.Direction = ParameterDirection.Output;

            Sql sql = Sql.Builder.Append("EXEC dbo.[PurgeEventLog] @totalRecordsAffected out", new
            {
                totalRecordsAffected = totalRecordsAffected
            });

            int result = Database.SingleOrDefault<int>(sql);
            return (int)totalRecordsAffected.Value;
```

**Comment by billrawlinson** [comment]
I used the double @@ becuase everything I saw on the subject suggested I needed to. Like [this comment](https://github.com/schotime/NPoco/issues/14#issuecomment-16858529) on #14 

I'll try @schotime  suggestion next; as removing just the one @ didn't seem to help (different error about an object not existing).

**Comment by billrawlinson** [comment]
Thanks.  Something is still wrong but I am not sure what.  I'll post a follow up in a bit (tomorrow).

**Comment by litera** [comment]
Just FYI. This is the code that I'm [generating using T4](http://erraticdev.blogspot.com/2014/04/npocopetapoco-stored-procedures-with.html) and creates these calls from analysing stored procedures on the server. The reason for auto generation is for me to avoid maginc values as I have to provide strong type parameters to my calls instead of providing an error prone string. String is being automatically generated as per below.
```csharp
public static Sql Create(string name, string email, string password, string url, out SqlParameter activationCode)
{
	activationCode = new SqlParameter("@ActivationCode", SqlDbType.Char);
	activationCode.Direction = ParameterDirection.Output;
	activationCode.Size = 32;

	Sql result = Sql.Builder.Append(";exec dbo.[Person_Create] @Name, @Email, @Password, @Url, @ActivationCode out", new {
		Name = name,
		Email = email,
		Password = password,
		Url = url,
		ActivationCode = activationCode
	});

	return result;
}
```

I'm then calling this in `db.Fetch<...>(StoredProcedures.Person.Create(...))` and getting the values I require.

**Comment by billrawlinson** [comment]
I had to provide a default value for @totalRecordsAffected to get to this new error:

```
System.InvalidOperationException: Invalid attempt to read when no data is present.
   at System.Data.SqlClient.SqlDataReader.CheckMetaDataIsReady(Int32 columnIndex, Boolean permitAsync)
   at System.Data.SqlClient.SqlDataReader.GetFieldType(Int32 i)
   at NPoco.MappingFactory.<>c__DisplayClass5.<GetFactory>b__0() in d:\Adam\projects\NPoco\src\NPoco\MappingFactory.cs:line 116
   at System.Lazy`1.CreateValue()
```


This is occurring when the `Database.SingleOrDefault`  (or, alternatively, `Fetch`) is called.

You guys did solve the `missing scaler value` problem so thanks!

I have to say, it has been substantially harder to call this stored procedure than I anticipated.

**Comment by billrawlinson** [comment]
I also tried to add the semi colon before `EXEC`:

Here is the current code.

```cs
            var totalRecordsAffected = new SqlParameter("totalRecordsAffected", SqlDbType.Int);
            totalRecordsAffected.Direction = ParameterDirection.Output;
            totalRecordsAffected.Value = 0;

            Sql sql = Sql.Builder.Append(";EXEC dbo.[PurgeEventLog] @totalRecordsAffected output", new
            {
                totalRecordsAffected = totalRecordsAffected
            });

            List<int> result = Database.Fetch<int>(sql);
```

**Comment by litera** [comment]
Ok. So what if you do provide a value? Like `SqlDBNull` and then also cast to something nullable?
```csharp
int? result = Database.SingleOrDefault<int?>(sql);
```

**Comment by billrawlinson** [comment]
I am providing a value for totalRecordsAffected (0) but I hadn't thought to cast the Fetch<int?>  but I still get the No Data Found error:


```
System.InvalidOperationException: Invalid attempt to read when no data is present.
   at System.Data.SqlClient.SqlDataReader.CheckMetaDataIsReady(Int32 columnIndex, Boolean permitAsync)
   at System.Data.SqlClient.SqlDataReader.GetFieldType(Int32 i)
   at NPoco.MappingFactory.<>c__DisplayClass5.<GetFactory>b__0() in d:\Adam\projects\NPoco\src\NPoco\MappingFactory.cs:line 116
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at NPoco.Cache`2.Get(TKey key, Func`1 factory) in d:\Adam\projects\NPoco\src\NPoco\Cache.cs:line 78
   at NPoco.MappingFactory.GetFactory(Int32 firstColumn, Int32 countColumns, IDataReader r, Object instance) in d:\Adam\projects\NPoco\src\NPoco\MappingFactory.cs:line 343
   at NPoco.Database.<Query>d__77.MoveNext() in d:\Adam\projects\NPoco\src\NPoco\Database.cs:line 999
   at System.Linq.Enumerable.<CastIterator>d__b1`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.Database.Fetch[T](Sql sql) in d:\Adam\projects\NPoco\src\NPoco\Database.cs:line 745
   at Aemis.Data.Repositories.EventLogRepository.Purge() in c:\dev\projects\AemisCloud\VisualStudio\Aemis.Data\Repositories\EventLogRepository.cs:line 70
```

I've also tried to use the word "output" and "out".  SSMS uses "output" when passing @totalRecordsAffected.

```cs
            Sql sql = Sql.Builder.Append(";EXEC dbo.[PurgeEventLog] @totalRecordsAffected out", new
```

and

```cs
            Sql sql = Sql.Builder.Append(";EXEC dbo.[PurgeEventLog] @totalRecordsAffected output", new
```

Here is the actual SQL I am executing via SSMS:

```sql
DECLARE	@totalRecordsAffected int

EXEC	[dbo].[PurgeEventLog] @totalRecordsAffected = @totalRecordsAffected OUTPUT

SELECT	@totalRecordsAffected as N'@totalRecordsAffected'

GO
```

and it works fine; returns `369`.

**Comment by litera** [comment]
Ok Ok. I think I get it...

Maybe you misunderstand the processing of stored procedure results.
If you stored procedure returns an output parameter you can't simply get it from `Fetch` or `SingleOrDefault` etc. You have to read it from your `SqlParameter`... You'll have to read value fvrom `totalRecordsAffected` variable.

If you SP doesn't return and resultset or value then you should simply call `Execute` on it and read your variable's value.

**Comment by billrawlinson** [comment]
It doesn't return a result set.  I guess I just need to know how I'm supposed to execute the stored procedure.  I have been trying to read it from the  totalRecordsAffected variable.

I tried `Database.Execute` a bunch (previously) with the double `@` syntax (which is what I initially thought I'd want to do).

It turns out that is what I wanted to do.  Thanks.   SO the final, working code, is:

```cs
            var totalRecordsAffected = new SqlParameter("totalRecordsAffected", SqlDbType.Int);
            totalRecordsAffected.Direction = ParameterDirection.Output;
            totalRecordsAffected.Value = 0;

            Sql sql = Sql.Builder.Append(";EXEC dbo.[PurgeEventLog] @Foo, @TotalRecordsAffected out", new
            {
                Foo = 0,
                TotalRecordsAffected = totalRecordsAffected
            });

            Database.Execute(sql);
            return (int)totalRecordsAffected.Value;
```

that darn `@` really sent me down a bad path!  Thanks for your patience and help.

**Comment by litera** [comment]
You can now likely omit initial parameter value setting if all works as expected. I also think that parameter name in constructor is irrelevant as Sql Builder builds upon anonymous object property names anyway. So having @ in `SqlParameter` constructor or not is likely irrelevant.

**Comment by billrawlinson** [comment]
You are correct; I didn't need to set the value  (though, not setting it did reveal a bug in my logging method!)

Also you are correct, I can have an `@` in the SqlParameter or not both work:

```cs
            var totalRecordsAffected = new SqlParameter("@totalRecordsAffected", SqlDbType.Int);
```
and

```cs
            var totalRecordsAffected = new SqlParameter("totalRecordsAffected", SqlDbType.Int);
```

Here is the final working code with all extraneous stuff removed:

```cs
            var totalRecordsAffected = new SqlParameter("totalRecordsAffected", SqlDbType.Int);
            totalRecordsAffected.Direction = ParameterDirection.Output;

            Sql sql = Sql.Builder.Append(";EXEC dbo.[PurgeEventLog] @TotalRecordsAffected out", new
            {
                TotalRecordsAffected = totalRecordsAffected
            });

            Database.Execute(sql);
            return (int)totalRecordsAffected.Value;
```

Thanks again for your help.

**Comment by litera** [comment]
@billrawlinson One more thing that help in the future of SP writing. Your SP apparently returns no results in the normal fashion but only returns a value via output parameter.

I suppose in such case it would be much easier if your SP didn't use output parameters and returned that same value as query result if that is indeed the only viable result of its processing.
```tsql
create procedure dbo.Test (...)
as
begin
    ...
    select @@rowcount;
end
```
In such case it would also be much easier to get this value simply ba calling:
```csharp
Sql sql = Sql.Builder.Append(";exec dbo.Test;");
int totalRecordsAffected = Database.ExecuteScalar<int>(sql);
```
Output parameters are much more useful (and also justify additional middle tier code complication) when a stored procedure returns other resultset and you want an additional value returned without using multiple resultsets.
An example of such stored procedure would be user registration that returns newly created `User` record and additional activation code as output parameter that middle tier would be sending via email to newly created user's email account. It wouldn't make much sense to have `class User { ... }` with activation code property as that's just used during user creation and nowhere else. So `SingleOrDefault<User>` would return user data and activation code would be returned using output parameter.

**Comment by billrawlinson** [comment]
@litera  that was actually my initial approach; my procedure returned the value but when I `ExecutedScalar` I only ever get back zero; which I assumed was a "success code".  

The problem was in my stored procedure though - I was using a `RETURN @totalRecordsAffected` syntax (which works fine in SSMS; but was not reflected back in C#)

I just tried it again, with a `SELECT @totalRecordsAffected` and the value is returned.

In SSMS if I use `SELECT` then the return value of the stored procedure is zero (which is what I expected).  I suspect this entire thing just spawns from my lack of understanding of how NPOCO works in relation to stored procedures.  

Anyway, thanks again for your help.
