### ISSUE TITLE
Unify generic type naming

### ISSUE THREAD

**Issue by GoranSiska** [schotime/NPoco#253]
The name of generic parameters differ in interface and implementation.
IDatabaseQuery.cs Line 55 :
Page<**TRet**> Page<**TRet**>(Type[] types, Delegate cb, long page, long itemsPerPage, string sql, params object[] args);

Database.cs Line 989 :
public Page<**T**> Page<**T**>(Type[] types, Delegate cb, long page, long itemsPerPage, string sql, params object[] args)

This causes an error when creating a mock Database using Moq. Related to:
https://github.com/castleproject/Core/issues/106

**Comment by schotime** [comment]
What version of the code are you referring to?
https://github.com/schotime/NPoco/blob/dev3.1/src/NPoco/IDatabaseQuery.cs

**Comment by GoranSiska** [comment]
master: https://github.com/schotime/NPoco/blob/master/src/NPoco/IDatabaseQuery.cs

I see it's fixed in dev branch.

**Comment by schotime** [comment]
Fixed in master as its been merged  now.
