### ISSUE TITLE
SqlContext?

### ISSUE THREAD

**Issue by zpqrtbnk** [schotime/NPoco#254]
Hello again,

For some reason, when we build a Sql expression using our own extensions, we end up having to pass some extra infos to those extensions. For example the following code cannot work because we need to figure out the columns for class Something, and then the proper way to escape the table and column names, in order to produce the `SELECT [column1], [column2]` fragment:
~~~~
var sql = new Sql().Select<Something>().From(...);
~~~~
At the moment this means that the `Select` method needs to accept a `Database` parameter, or an `IPocoDataFactory` _and_ a `DatabaseType`. Which is not convenient:
~~~~
var sql = new Sql().Select<Something>(pocoDataFactor, databaseType).From(...);
~~~~
So what we end up doing is something along:
~~~~
var sql = new Sql().With(context).Select<Something>().From(...);
~~~~
The `With` extension returns an "extended" Sql that has a "context" that carries whatever we need to carry. And it's used by our extensions all along. It works quite well _but_ we have to re-implement some of NPoco core methods (`Where` etc) in order to ensure we always handle our extended Sql.

And so the logical conclusion is... it would be nice if NPoco `Sql` would accept a "context" (say, anything implementing an empty `ISqlContext` interface) as a parameter, and carry it along. Our code would become:
~~~~
var sql = new Sql(context).Select<Something>().From(...);
~~~~
People can put whatever they want in the "context" and reuse it in their extension methods. Of course they'd need to cast to their own context class. The alternative would be to have a `Sql<TContext>` class and we could do:
~~~~
var sql = Sql.Builder(context).Select<Something>().From(...);
~~~~
But that _might_ be slightly more complex to implement.

All in all it would greatly simplify our work and it does not look too complex to implement. Willing to do it. Thoughts?

**Comment by schotime** [comment]
I like the last one, but I think we can do it with just extension methods.
Thoughts?
```csharp
    public static class StronglyTypedSql
    {
        public static Sql<T> Builder<T>(this Sql sql, T context)
        {
            return new Sql<T>(sql, context);
        }
        
        public class Sql<T>
        {
            private readonly Sql _sql;
            private readonly T _context;

            public Sql(Sql sql, T context)
            {
                _sql = sql;
                _context = context;
            }

            public Sql<T> Select<TModel>()
            {
                //Generate columns from TModel
                var cols = new object[] { "a", "b" };
                _sql.Select(cols);
                return this;
            }

            //Or have an implicit converter to Sql
            public Sql Build()
            {
                return _sql;
            }
        }
    }
```

and run like

```csharp
var sql = new Sql().Builder(context).Select<Something>().From(...).Build();
```

**Comment by zpqrtbnk** [comment]
I _think_ we need a little bit more than just extension methods to make it run properly. If we want the `Sql<T>` thing to be able to be used everywhere in place of `Sql`. I have experimented with the code and produced PR https://github.com/schotime/NPoco/pull/255 - which works quite well. We use it this way:
~~~~
var sqlContext = ...;
var sql = Sql.BuilderFor(sqlContext).Select(...).From(...);
~~~~
The Sql you obtain is an `Sql<T>` but can be used exactly as you would use `Sql`.

And then it becomes possible to define extension methods doing all sorts of things on the Sql - by manipulating the context. This is up for discussion of course, I am still reviewing it to make sure it makes sense.

Thoughts?

**Comment by schotime** [comment]
How is this working out for you? working as expected?

**Comment by zpqrtbnk** [comment]
Ah... our dev version runs on the code from the PR mentionned above and it's perfect. It allows us to inject our own "context" into a Sql and do whatever weird things we like with it ;-) without leaking any of our weird things into NPoco. All good.

**Comment by schotime** [comment]
Cool...I'll look at getting this in the next version. 3.2.1 possibly ;) 
3.3 will be RC2 support i'm hoping.

**Comment by zpqrtbnk** [comment]
PR has been merged, can close the issue.
