### ISSUE TITLE
Simulating between query expression 

### ISSUE THREAD

**Issue by dwirawan** [schotime/NPoco#256]
I'm trying to simulate between expression by using ``Where()``, my requirement is to query string between A and B. However, this code throws error
```
var r = db.Query<Person>().Where(c => string.Compare(c.Name, "A", StringComparision.OrdinalIgnoreCase) > 0 && string.Compare(c.Name, "G", StringComparision.OrdinalIgnoreCase) < 0);
```
How to do that?

**Comment by schotime** [comment]
I don't know that you can.

**Comment by dwirawan** [comment]
@schotime thanks
