### ISSUE TITLE
Question about Newtonsoft.Json dependency

### ISSUE THREAD

**Issue by enrico-padovani** [schotime/NPoco#258]
Since for .net web project the probability to use Newtonsoft.Json serializer is pretty high, due to this dependency it could lead to conflicts on serializer version.

I'm new to npoco, so I was just wondering why in v3 you've added such dependency. Can you explain?

Thanks,
Enrico

**Comment by schotime** [comment]
It is used for the serialized columns, where a complex (class) property can be serialized to json and stored in one column. Also used for snapshotting.

**Comment by enrico-padovani** [comment]
I see, those are surely interesting features. Is there a quick reference?

Can it be pluggable, so anyone can register the preferred serializer in order to avoid conflicts? Or you do use very specific features of Newtonsoft.Json?

Thanks!

**Comment by schotime** [comment]
If you mark a column with the [SerializedColumn] attribute it will be json'd into that column.

It is sort of pluggable but you still need to take a reference at the moment.
You really shouldn't run into any conflicts with JSON.NET. It only uses Serialize and Deserialize anyways.

**Comment by enrico-padovani** [comment]
I see that you've started a new branch using SimpleJson as default serializer. I think this is good first because Newtonsoft.Json It's bigger than this library and It feels that you're loosing the "easy to go" feeling. Second, having to integrate it in an existing project that uses Newtonsoft.Json 6.x I think that it will probably not compile well.

The best It will be to have it pluggable in the fluent database configuration, so you are free to use an existing version of Newtonsoft.Json or, for example, something like: https://github.com/mgholam/fastJSON

Thanks for watching into it!

**Comment by schotime** [comment]
fastJSON doesn't support CoreCLR just yet so that's out of the question.

**Comment by enrico-padovani** [comment]
Pay attention because SimpleJson maybe it's too "simple", for example: if you have a sql server timestamp colum mapped to a byte[] the deserialization will fail with an error like: System.InvalidCastException: Invalid cast from 'System.String' to 'System.Byte[]'.

Is it not enough to avoid putting serializers into the library and just throw an exception if there is no concrete implementation of the interface when using json-related features?

Just my opinion.

**Comment by Mike737377** [comment]
@schotime is right. SimpleJson doesn't support CoreCLR either and currently from the looks of it there is no plans to. For SimpleJson to be even thought about at this point of time, it will need to support .net core.

The reason why it is so important that CoreCLR is supported is the latest versions of NPoco currently run on .net core.

If you have concerns over JSON.Net versioning then IL merging might be the answer for you.

**Comment by enrico-padovani** [comment]
IL merge it's not an option, sounds more like an hack.

What about deploying two different nuget packages:
NPoco (no serializer depencencies so you have to manually configure the interface implantation, throws an exception when using json stuff and no serializer has been provided)
NPoco.Json (which has a dependency on Newtonsoft.Json or whatever library the maintainer has chosen as default serializer).

Simple and easy to understand, everyone is in control: no hacks.

**Comment by Mike737377** [comment]
Seperate library would be about the same level of "hack" but with more work. You could always fork NPoco and give it a go. If it's flexible enough and solves the problem and works with core clr you could always submit a PR.

**Comment by Mike737377** [comment]
Otherwise if you're currently having issues with version conflicts with Json.net then you could also try assembly binding redirection

**Comment by enrico-padovani** [comment]
Indeed I did: #261

**Comment by schotime** [comment]
Removed in 3.2.

**Comment by enrico-padovani** [comment]
Ok, glad to see a change of direction on this.... a much better setup!

Personally I've used fastJSON in some simple scenarios and works quite well. For complex objects maybe will have some problems, but at least you can replace it with a full fledged serializer if needed.

If I understood right, by replacing the serializer will affect no only the [SerializedColumn] but also the snapshoter, right?

Thanks

**Comment by schotime** [comment]
Will only affect the serialized columns. Fastjson hard coded for
snapshotter.
