### ISSUE TITLE
OneToMany documentation

### ISSUE THREAD

**Issue by tonag** [schotime/NPoco#260]
Good morning. I found, IMHO, an issue in documentation.
I tryed the code provided here: [OneTomany](https://github.com/schotime/NPoco/wiki/One-to-Many-Query-Helpers)
But I get compiler error. In effect the  working code for me is the following:
`var users = db.FetchOneToMany<UserDto>(x => x.Cars,y => y.UserId, 
    "select u.*, c.* from Users u inner join Cars c on u.UserId = c.UserId order by u.UserId");`
Thanks

**Comment by dheijl** [comment]
I suppose you are using version 3, while the documentation you are referring to is for version 2.
Version 3 documentation: [Version 3](https://github.com/schotime/NPoco/wiki/Version-3). There are some breaking changes.

**Comment by tonag** [comment]
Thanks for quick response. Yes i'm using version 3 and did not realize that documentation was for version 2.

**Comment by schotime** [comment]
I will try and get the doco updated. Feel free to submit a PR for it if u
want to help out.
