### ISSUE TITLE
Reference attribute a bit confusing!

### ISSUE THREAD

**Issue by enrico-padovani** [schotime/NPoco#262]
Hi,

I was struggling against a mapping that constantly thrown a "Sequence contains no matching element". In the end I got it.

My scenario is:
- Database table name != poco class name
- Database column names != poco property names
- MasterTable 0:n DetailTable mapped using ReferenceType.Many

Here is a sample mapping:

```
[TableName("mySchema.masterTable"), PrimaryKey("mm_id", AutoIncrement = true)]
public class MasterTable
{
    [Column(Name = "mm_id")]
    public int Id { get; set; }

    [Reference(ReferenceType.Many, ColumnName = "mm_id", ReferenceMemberName = "MasterTableId")]
    public List<DetailTable> Details { get; set; }      
}

[TableName("mySchema.detailTable"), PrimaryKey("dd_id", AutoIncrement = true)]
public class DetailTable
{
    [Column(Name = "dd_id")]
    public int Id { get; set; }

    [Column(Name = "dd_masterTableId")]
    public int MasterTableId { get; set; }  
}
```

Here is the query:

```
database.Query<MasterTable>()
        .IncludeMany(p => p.Details)
        .FirstOrDefault();
```

I've noticed that:
- For ColumnName you have to use the database column name
- For ReferenceMemberName you have to use the poco property name

Shouldn't be that aligned? I mean, for example, to always use poco property names? Maybe It could also be possible to add  a new property "MemberName" that takes the current poco property name to use for the relationship combined with "ReferenceMemberName". Just brainstorming ...

Enrico

**Comment by enrico-padovani** [comment]
I'm also trying to get the same mapping to work in a fluent way. But I cannot.

This is my first attempt but I don't find how to set the source column name "mm_id" and I get "Sequence contains no matching element".
```
Columns(p =>
{
    p.Column(x => x.Id).WithName("mm_id");
    p.Many(x => x.Details ).Reference(y => y.MasterTableId);`
}
```
It's possible to do that? Anyone?

**Comment by enrico-padovani** [comment]
I got it, somehow It's coherent with the initial described logic, so after Many() the "master" database column name has to be specified. I've figured it out by watching SQL profiler, the JOIN clause was wrong because of this. So the right mapping is:
```
Columns(p =>
{
    p.Column(x => x.Id).WithName("mm_id");
    p.Many(x => x.Details).WithName("mm_id").Reference(y => y.MasterTableId);
}
```

**Comment by schotime** [comment]
I wanted to use Lambda's in the fluent mappings so kept the same thing for the attributes. You only need to define it once (on the actual object) then as well.

**Comment by enrico-padovani** [comment]
Sorry I messed up  with close button ...

My only concern is about to have to use the real database column name for "Master" key and the poco defined alias for the foreign key. Since I've already defined that in the key column I'd be nice to just refere to the mapped propery.

In case of fluent config it will be nice to have fluent also in the master column, but maybe this involves in some concept changes that maybe you don't want to rethink.

Something like:

```
Columns(p =>
{
    p.Column(x => x.Id).WithName("mm_id");
    p.Many(x => x.Details).With(x => x.Id).Reference(x => x.MasterTableId);
}

```
Anyway, fill free to close this issue if you want. Maybe It's just enough to have a better docs.

Enrico

**Comment by schotime** [comment]
Yeah that probably does make more sense.
Not quite as easy cause it will have to do the lookup after all other configurations have run.

**Comment by ehajri** [comment]
Using FluentAPI, I am getting the same error: "Sequence contains no element".
Code:
```c#
For<User>().Columns(x =>
{
    x.Column(y => y.Username);
    x.Column(y => y.Password);
    x.Column(y => y.Salt);
    x.Column(y => y.ForcePasswordChange);
    x.Column(y => y.Guid);
    x.Column(y => y.ApiKey).WithName("Id").Reference(z => z.UserId, ReferenceType.OneToOne);
    x.Many(y => y.Claims).WithName("Id").Reference(y => y.UserId);
});
```
Exception:
```
System.InvalidOperationException
Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NPoco.PocoDataBuilder.<GetPocoMembers>d__28.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NPoco.PocoDataBuilder.<GetPocoMembers>d__28.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NPoco.PocoDataBuilder.<GetPocoMembers>d__28.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NPoco.PocoDataBuilder.<GetPocoMembers>d__28.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.PocoDataBuilder.Init()
   at NPoco.FluentPocoDataFactory.BaseClassFalbackPocoDataBuilder(Type type)
   at NPoco.Cache`2.Get(TKey key, Func`1 factory)
   at NPoco.FluentPocoDataFactory.ForType(Type type)
   at NPoco.Linq.QueryProvider`1..ctor(Database database, Expression`1 whereExpression)
   at NPoco.Database.Query[T]()
   at Hydra.Common.DefaultClaimRepository.Find(Int32 id) in d:\project\project\MyMappings.cs:line 27
```
