### ISSUE TITLE
IncludeMany and ResultColumn

### ISSUE THREAD

**Issue by gredondogc** [schotime/NPoco#263]
I have these two classes and I'm trying to use the IncludeMany function to acess the database:

	public class OrderDTO
	{
		public int OrderId { get; set; }
		public int UserId { get; set; }
		[Reference(ReferenceType.Many, ColumnName = "OrderId", ReferenceMemberName = "OrderId")]
		public List<OrderItemDTO> OrderItems { get; set; }

		public OrderDTO()
		{
			OrderItems = new List<OrderItemDTO>();
		}
	}

	public class OrderItemDTO
	{
		public int OrderItemId { get; set; }
		public int OrderId { get; set; }
		public int SkuId { get; set; }
		[ResultColumn]
		public string Sku { get; set; }
	}

When I make this call

	database.Query<OrderDTO>().IncludeMany(o => o.OrderItems).
	Where(o => o.OrderId == orderDto.OrderId).ToList();

the Sku column is included in the select:

	SELECT [OD].[OrderId] as [OrderId], [OD].[UserId] as [UserId],
		[OID].[OrderItemId] as [OrderItems__OrderItemId], 
		[OID].[OrderId] as [OrderItems__OrderId],
		[OID].[SkuId] as [OrderItems__SkuId],
		[OID].[Sku] as [OrderItems__Sku]
	FROM [Order] [OD]
	LEFT JOIN [Order_Item] [OID] ON [OD].[OrderId] = [OID].[OrderId] 
	WHERE ([OD].[OrderId] = @0) 

Is this by design? Or is it a Bug?
Am I doing something wrong?

Gonçalo

**Comment by schotime** [comment]
Could be a bug. Looks like a bug.
Be a couple of days before I can look at it.

**Comment by schotime** [comment]
Fixed with https://github.com/schotime/NPoco/commit/c83a5ba41573deecbf204ccd7287b745b2c16591 in next release in a couple days

**Comment by gredondogc** [comment]
Perfect. Thank you.

**Comment by schotime** [comment]
Thank you for finding :)
