### ISSUE TITLE
ComputedColumn and Snapshot<T>.UpdatedColumns()

### ISSUE THREAD

**Issue by gredondogc** [schotime/NPoco#264]
Using ComputedColumn and snapshot.UpdatedColumns() can lead to an "Empty" Update sql.

	[TableName("Order")]
	[PrimaryKey("OrderId", AutoIncrement = true)]
	public class OrderDateAsComputedColumn
	{
		public int OrderId { get; set; }

		[ComputedColumn]
		public DateTime? Date { get; set; }
		public DateTime? DeliveryDate { get; set; }
		public int UserId { get; set; }
	}

 

	var order = ctx.SingleById<OrderDateAsComputedColumn>(key);

	var snapshot = ctx.StartSnapshot(order);

	order.Date = order.Date.AddMonths(1);
	ctx.Update(order, snapshot.UpdatedColumns());
 
this can be corrected changing the Snapshot<T>.UpdatedColumns() to handle the ComputedColumn, or  changing the Database.UpdateImp<TRet> function:

	if (columns != null && columns.Any() && sb.Length == 0)
		throw new ArgumentException("There were no columns in the columns list that matched your table", "columns");

to
 
	if (columns != null && columns.Any() && sb.Length == 0)
		return defaultId;

The second option seems easy enough. Is there any problem with it?

**Comment by schotime** [comment]
Might be a bit more to it, because computed columns can be for update only / insert only now. Hmmm.

**Comment by schotime** [comment]
Will be in next build. Thanks
