### ISSUE TITLE
Table Class Hierarchy  - Inserts To Base Class Table

### ISSUE THREAD

**Issue by aramayowa** [schotime/NPoco#266]
Hey schotime,

First off, thank you for all your hard work on this library. It's been very helpful.

I've got some questions around using an abstract base class with npoco. Here's my setup.

I've got several derived classes all inheriting from an abstract Event class. This inheritance is mirrored in the database as a central Event table with common data and other separate/individual detail tables (depending on the event type). The PK of an Event record is the same as the PK of the detail record like so:

`public class Event 
    {
        public virtual int EventKey { get; set; }
    }

    public class RedEvent : Event
    {
        public int RedEventKey { get; set; }
        public override int EventKey
        {
            get { return RedEventKey; }
            set { RedEventKey = value; }
        }
    }

    public class BlueEvent : Event
    {
        public int BlueEventKey { get; set; }
        public override int EventKey
        {
            get { return BlueEventKey; }
            set { BlueEventKey = value; }
        }
    }`

As far as npoco config goes, i've got this configured fluently:

- The properties in the base class as marked as result columns on the derived classes. 
- These specific keys (e.g. redeventkey) are marked to not auto increment.
- I have  a mapper factory setup for the derived types like in your V3 documentation.

Here's where i'm stuck:

When i try to insert into the central events table like below, npoco ignores the generic type (Event) and uses the runtime/reflected type  which is the derived type. This results in the wrong columns being inserted into the tables. 

`await HrdDB.InsertAsync<Event>(derivedEvent as Event).ConfigureAwait(false);`

I've also tried it by specifying the exact table and pk names and that didn't work either.

I suspect that i am missing some key points in the configuration. As i understand it, what i am trying to achieve should be possible in v3. I'd appreciate any help at all that you can give.

Thanks again.

**Comment by schotime** [comment]
hey, thanks.

Abstract pocos are only supported for queries at the moment but you could create your own extension method pretty easily.

```
public static class AbstractClassExtensions 
{
     public static object InsertAbstract<T>(this IDatabase database, T poco)
     {
          var tableInfo = database.PocoDataFactory.TableInfoForType(typeof(T));
          return database.Insert(tableInfo.TableName, tableInfo.PrimaryKey, tableInfo.AutoIncrement, poco);
     }
}
```

This wasn't the default because if you wanted to pass a type in that was not known at compile time then it wouldn't work.

Let me know how you get on.

**Comment by aramayowa** [comment]
Thank you, schotime.

The reason for not making it the default makes sense to me, as does abstract pocos not being supported yet.  i've tried not making the Event class abstract and still ran into the issue which makes me think the issue might be with my configuration.

I have also tried something like the snippet you put above as a test,  although I didn't use the tableinfo. I just hardcoded the tablename, pk column etc, like:

`database.Insert("Event", "EventKey", false, redEvent);`

What it did was generate an insert into the Event table but with the columns from redEvent which of course, didn't work.

In the past i've used npoco with derived classes (but without a central table that matched the base class) so i know that works (and beautifully too). This is the first time i've tried to save to a central table that matches the base class ( the idea was to call an explicit insert for Event and then a subsequent insert for RedEvent).

Thoughts?

**Comment by schotime** [comment]
Yeah...just looked a bit further and it still calls getType() so thats why that or my extension won't work either.

Gonna need to think about how to do this. I think I have an idea, but would need to test to see how much it would break.

**Comment by aramayowa** [comment]
Sounds good. Thanks for taking the time to look into it.

**Comment by aramayowa** [comment]
Hi Schotime,

I've run into another issue. I'm not sure if it's related to this same inheritance structure or not so i'll just put it  here for starters.

After moving to V3,  mapping to nested objects is no longer successful for me (in addition to the issue above). I've primarily tried methods 2 and 3 from your documentation and neither works using Fetch<T> and FetchAsync<T>.

I don't know if it's relevant, but on classes that have nested objects, i usually have the key of the object (FK) and the object itself. Like this

`public class BlueEvent : Event
{
    public int BlueEventKey { get; set; }
    public override int EventKey
    {
        get { return BlueEventKey; }
        set { BlueEventKey = value; }
    }

   public int NestedObjectKey { get; set; }
   public NestedObjectType NestedObject { get; set; }

}`

In any case, these objects no longer come back populated. The old Fetch methods with generic parameters handled this scenario just fine (with the added benefit that i didn't have to worry about specifying aliases for each nested object). 

Any ideas on what could be wrong? Is it possible to get old overloads back? Apologies for the stream of questions but i've been dead in the water since the switch over to v3 last week.

**Comment by schotime** [comment]
What does your sql look like?

**Comment by schotime** [comment]
Here are the tests for it.

```csharp
        [Test]
        public void Test26()
        {
            var data = Database.Fetch<OldConv>("select 3 Id, 'Name1' Name, 'Name2' Name, 'Name4' Name, 'Name3' Name").Single();
            Assert.AreEqual(3, data.Id);
            Assert.AreEqual("Name1", data.Name);
            Assert.AreEqual("Name2", data.Nest1.Name);
            Assert.AreEqual("Name4", data.Nest1.Nest3.Name);
            Assert.AreEqual("Name3", data.Nest2.Name);
        }

        [Test]
        public void Test26_1()
        {
            var data = Database.Fetch<OldConv>("select 3 Id, 4 Id, 'Name2' Name, 'Name4' Name, 'Name3' Name").Single();
            Assert.AreEqual(3, data.Id);
            Assert.AreEqual(4, data.Nest1.Id);
            Assert.AreEqual("Name2", data.Nest1.Name);
            Assert.AreEqual("Name4", data.Nest1.Nest3.Name);
            Assert.AreEqual("Name3", data.Nest2.Name);
        }

        public class OldConv
        {
            public int Id { get; set; }
            public string Name { get; set; }

            public NestOldConv1 Nest1 { get; set; }
            public NestOldConv2 Nest2 { get; set; }

            public class NestOldConv1
            {
                public int Id { get; set; }
                public string Name { get; set; }
                public NestOldConv2 Nest3 { get; set; }
            }

            public class NestOldConv2
            {
                public string Name { get; set; }
            }
        }
```

**Comment by schotime** [comment]
Also, If you are using FluentMapping for this class you will need to define the column as ComplexMapping().

**Comment by aramayowa** [comment]
Hey schotime,

That might be the problem, I don't have those objects marked as complex mapping right now (I think I have them marked as results).

My sql is fairly straight forward (other than the duplicate column names) e.g.

SELECT ev.*, rev.*, no.*
FROM Event ev
INNER JOIN RedEvent rev ON rev.RedEventKey = ev.EventKey
INNER JOIN NestedObject no ON rev.NestedObjectKey = no.NestedObjectKey

I realize using SELECT * is Iffy, but it's been really useful while i'm in heavy new development mode (columns changing more frequently than usual).

Thanks again for looking into it. I'm going to try the Complex Column later today, i'll keep you posted.

**Comment by aramayowa** [comment]
Hey Schotime,

That (complex mapping for those properties) was the problem. I can't say thank you enough. That's gotten me unstuck for now. 

As far as the inserts/updates (original issue), i'm going to use raw sql for now until you (hopefully) save the day again.

I appreciate all the help.

**Comment by schotime** [comment]
Hi,
I have release 3.3.0-beta1 on NuGet. 
It includes a hopeful fix for the base class insert issue.
Here is a full example in one of the tests.
https://github.com/schotime/NPoco/blob/9ca424bb81b79ef9e8813af0bb5cb933101c50ad/test/NPoco.Tests/NewMapper/AbstractClassTests.cs

If you could test it and let me know how you get on that would be great.

**Comment by aramayowa** [comment]
Hey Schotime,

Thanks for working on this. Here's what i see.

The insert to the base event table is successful. The following insert (next line) to the derived class's table fails because it's trying to insert the columns for a nested child object (which is now marked as complex as per above).

The derived class looks like this

`public class Event 
{
     public virtual int EventKey { get; set; }
}

public class RedEvent : Event
{
    public int RedEventKey { get; set; }
    public override int EventKey
    {
        get { return RedEventKey; }
        set { RedEventKey = value; }
    }
    public NestedObject NestedObject { get; set; }
}
`
It looks like it isn't possible to mark the nested object as a result column and complex mapping at the same time (using fluent convention at least). The nested object never gets passed into the result column convention delegate if it is marked as complex.

Hope this is helpful. Let me know if there's anything else you'd like me to check.

**Comment by schotime** [comment]
Can you show me your fluent mapping?

**Comment by aramayowa** [comment]
Sure.  I've pasted the setup method below. 

`public static void Setup()
        {
            var fluentConfig = FluentMappingConfiguration.Scan(s => {
                s.Assembly(Assembly.Load("Hrd.Common"));
                s.IncludeTypes(type => type.Namespace.Contains("Hrd.Common.Model"));
                s.TablesNamed(type => Inflector.MakeSingular(type.Name));
                s.PrimaryKeysNamed(pk => GetPrimaryKeyConvention(pk));
                s.Columns.ResultWhere(cm => GetResultColumnConvention(cm));
                s.Columns.IgnoreWhere(cm => GetIgnoreColumnConvention(cm));
                s.PrimaryKeysAutoIncremented(GetAutoIncrementPrimaryKey());
                s.Columns.ComplexPropertiesWhere(cp => GetComplexColumnConvention(cp));
            });

            DbFactory = DatabaseFactory.Config(x =>
            {
                x.UsingDatabase(() => new HrdDatabase("DefaultConnection"));
                x.WithFluentConfig(fluentConfig);
                x.WithMapperFactory(GetEventMapperFactory());
            });
        }`

The called methods just do some checks on the member info type, declaring type etc. to decide what value to return. For example:

`private static bool GetComplexColumnConvention(MemberInfo mi)
        {
            if (mi.GetTheType().IsPrimitive)
            {
                return false;
            }

            var type = mi.DeclaringType;

            if (type.Namespace.Contains("Hrd.Common.Model"))
            {
                var members = type.GetMember(mi.Name + "Key");

                if (members != null && members.Any(x => ((PropertyInfo)x).PropertyType == typeof(int)))
                {
                    return true;
                }
            }

            return false;
        }`

**Comment by schotime** [comment]
You can always override these with a fluent config map.

```
s.OverrideMappingsWith(new OverrideMappings());

public class OverrideMappings : Mappings
{
    public OverrideMappings()
    {
         For<RedEvent>()
            .Columns(col => col.Column(x=>x.NestedObject).Result().Complex());
    }
}
```

**Comment by aramayowa** [comment]
That seems pretty doable. I'd have to be explicit with these overrides i take it (i.e. i won't be able to use reflection). I'll try it out and let you know how it goes.

As always, thanks for the help.

**Comment by schotime** [comment]
There probably is a way via reflection, but not sure the hook exists

**Comment by aramayowa** [comment]
It works with the override mappings. I'll look into the reflection approach tomorrow. Thanks again!

**Comment by schotime** [comment]
So i've found major issues with the current approach.
Hence I've gone down the explicit configuration approach where you need to specify what the persistence type of the class is. 

In your example.

```
public class Event 
{
     public virtual int EventKey { get; set; }
}

[PersistedType(typeof(Event)]
public class RedEvent : Event
{
    public int RedEventKey { get; set; }
    public override int EventKey
    {
        get { return RedEventKey; }
        set { RedEventKey = value; }
    }
    public NestedObject NestedObject { get; set; }
}
```

This will be available in fluent mappings and scanning.

**Comment by schotime** [comment]
3.3.0-beta2 is out with these changes.
It should properly handle your complex/result without the override too.

**Comment by aramayowa** [comment]
Hey schotime,

> This will be available in fluent mappings and scanning.

Did you mean that this would be available in 3.3.0-beta2? I just updated to that version to test this out and I don't see any scanning methods that would allow me to set this type. I also didn't notice anything new when using the OverrideMappings. I see the attribute though, but i'd like to keep using the fluent configuration/scanners.

On a more general note.  Does setting the persistence type to Event like in your example mean that i don't have to call Insert/Update twice (once for the Event table and once for the RedEvent table) anymore? 

Thanks.

**Comment by schotime** [comment]
Hey..good catch. Missed the method on the interface ;)

> On a more general note. Does setting the persistence type to Event like in your example mean that i don't have to call Insert/Update twice (once for the Event table and once for the RedEvent table) anymore?

So....this scenario does not support both inserting the RedEvent and the Event. Because as soon as you set RedEvent to PersistedType of Event you will never be able to insert RedEvent into a RedEvent table. Why would you insert both?

**Comment by aramayowa** [comment]
Heh, no biggie :)

I think we might have gotten our streams crossed in the back and forth (i should have explained what i was doing better). This scenario ([class table inheritance](http://stackoverflow.com/a/3579462)  --> base class with it's own table, derived classes with their own tables) is the whole reason for the issue. Performing inserts (and updates) for the base type  (.e.g InsertAsync<Event>(redEvent) and then the derived type (InsertAsync<RedEvent>(redEvent) resulted in the wrong sql being generated (tables were mixed up), I also had issues with Selects (the whole complex mapping thing).

i've been able to work around the inserts/updates with raw sql.  And after adding the complex properties, Selects are working now (thanks to you). So I should be able to keep going.

Long term, I think it might be worth it to support this scenario though. Class table inheritance is not the most common pattern, but it's one of the best ways to solve the [object relational mismatch](http://martinfowler.com/eaaCatalog/classTableInheritance.html). I've run into usage from enterprise scale systems used by the government to small startupy apps like my own. 

In any case, I'm super thankful for all your your help on this issue. Saved my bacon for sure.
