### ISSUE TITLE
"Operation could destabilize the runtime" exception on Save and Update methods call.

### ISSUE THREAD

**Issue by vbartolini** [schotime/NPoco#267]
This is my code snippet:

using (var tran = _database.GetTransaction())
            {
                var record = _database.SingleById<SellOutRecord>(id);
                if (record != null)
                {
                    record.MarkAsDead();
                    _database.Update(record);
                    AttachmentQueries.CalculateHasProductRecognitionErrors(_database, record.AttachmentId);
                    tran.Complete();
                    return RedirectToAction("Index", new { attachmentId = record.AttachmentId });
                }
            }

Code execution ends up with "Operation could destabilize the runtime" exception in version 3.1 and 3.2 but it works in version 2.6.88 very well. I can live with that version but it would be nice to have possibility use the last stable version ;).
Could you help me to solve my problem, please?
If you will have any question I'm ready to answer to.

**Comment by schotime** [comment]
Hmmm....
Would need to see the class you are updating. One of the properties must be
tripping it. Can u provide a full example of it failing?

**Comment by vbartolini** [comment]
Hi Adam,

 

    public abstract class RecordBase

    {

        public int Id;

        public int? RecordErrorTypeId { get; set; }

        public int? MaterialId { get; set; }

        public int? BundleId { get; set; }

        public int? ProductRecognitionTypeId { get; set; }

        public int AttachmentId { get; set; }

        public bool IsDead { get; set; }

        public int PartnerId { get; set; }

        public string EAN { get; set; }

public string SEC { get; set; }

 

        public void MarkAsDead()

        {

            IsDead = true;

        }

    }

 

 

    [TableName("SellOutRecords")]

    [PrimaryKey("Id")]

    public class SellOutRecord : RecordBase

    {

public string ClientCode { get; set; }

       public DateTime SellingDate{ get; set; }

public string NIP{ get; set; }

public string ClientHQCity{ get; set; }

public string ClientHQZipCode{ get; set; }

public string FullClientName{ get; set; }

public string UnitSerialNumber{ get; set; }

public decimal UnitPrice{ get; set; }

public string InvoiceNumber{ get; set; }

public int Quantity{ get; set; }

public string BusinessOportunityNumber{ get; set; }

public SellOutRecord() { }

    }

 

SellOutRecords table contains fields from RecordBase

 

The scenario is very simple:

1.  Get object

2.  Update IsDead property

3.  Save object.

 

Thank you for very fast reaction.

Bart

**Comment by schotime** [comment]
What if you make the ID field a property?

**Comment by vbartolini** [comment]
Oh, very good point :). I did not notice it :(.

It works like charm, thank you …

 

… but could you explain to me why it was working at earlier vesion?

 

Bart

**Comment by schotime** [comment]
The mapping mechanism changed fundamentally and I probably don't have
enough test cases around fields. I'll leave this issue open as a todo task.

Cheers

**Comment by schotime** [comment]
Fixed in https://github.com/schotime/NPoco/commit/ed8f1a8eae96e2ac24ecbfa7dadb7f5444166ada
