### ISSUE TITLE
PosgreSQL and booleans

### ISSUE THREAD

**Issue by dstarosta** [schotime/NPoco#268]
It looks like NPoco converts boolean parameters to integers (0/1). The following code

`db.Fetch<ProductDto>("SELECT * FROM t WHERE t.active = @0", true)`

throws the PostgreSQL error "42883: operator does not exist: boolean = integer". This error occurs if the generated query looks like 

`SELECT * FROM t WHERE t.active = 1` instead of `SELECT * FROM t WHERE t.active = true`

Make sure to use the latest Npgsql provider to reproduce it. Older versions performed magic conversions.

**Comment by dstarosta** [comment]
Looking into this more, the problem might be even more serious. I don't think the latest version of the provider likes parameter names that start with a digit.

**Comment by schotime** [comment]
It looks like the provider is not getting picked up possibly.
Try to pass in `DatabaseType.PostgreSQL` explicitly into the constructor of `Database` as the DatabaseType instead of it trying to auto locate it.

If it does still not work we can inherit the `PostgreSQLDatabaseType` type and override the prefix to add a letter in. 

Let me know how you get on.

**Comment by lerrand** [comment]
I am also getting this on Npgsql 3.0.6 with different parameter types (datetimes and strings get sent as ints). 

Done the DatabaseType thing to no avail, it should be [Npgsql issue 946](https://github.com/npgsql/npgsql/issues/946) causing this error (I see @dstarosta has already commented there!).

**Comment by dstarosta** [comment]
Extending the `PostgreSQLDatabaseType` and overriding `GetParameterPrefix` fixes the problem.

`            public override string GetParameterPrefix(string connectionString)
            {
                return "@p";
            }`

**Comment by schotime** [comment]
Awesome. Might just make the change in next release.

**Comment by schotime** [comment]
Released 3.3.0-beta1 which includes the fix mentioned by @dstarosta

**Comment by lerrand** [comment]
Npgsql 3.0.7 will apparently revert this behaviour (https://github.com/npgsql/npgsql/issues/1056), maybe a fix in NPoco won't be necessary after all?

**Comment by schotime** [comment]
Either way. This fix will work whatever they decide.

**Comment by schotime** [comment]
Fixed as of 3.3.3
