### ISSUE TITLE
Create inserts avoiding auto-increment. 

### ISSUE THREAD

**Issue by dannythemaster** [schotime/NPoco#269]
I'd like to do a sql table insert but not using the auto_increment functionality of SQL-Server.
If I set  
`[PrimaryKey("Id", AutoIncrement = false)] `
attribute of the MyEntityObject object still it does the autoincrement internally if I use

` _db.Insert<MyEntityObjectClass>("TableName", "IdName", MyEntityObject);`
Is there any way to enforce or inject the corresponding SQL Statement needed?
`"SET IDENTITY_INSERT MySqlTable ON;"`

for the NPoco insert method? (or similar method?)

I just want to avoid generating the sql statement manually.

Thanks a lot.
--Danny

**Comment by schotime** [comment]
This is not a supported feature sorry. You will have to write it manually.
