### ISSUE TITLE
VersionColumn column name not selected

### ISSUE THREAD

**Issue by firedog** [schotime/NPoco#271]
I am using the VersionColumn support and when I upgraded to 3.2.0 from 2.10.11 I noticed that the version column name wasn't in the generated SQL unless I added it to the attribute.

Using the following worked in 2.10.11... 
```C#        
[VersionColumn(VersionColumnType.Number)]
public long Version { get; set; }
```
... but in 3.2.0 it yields the following SQL (notice the missing column name: [T].[] as Version)

```SQL
SELECT [T].[Id] as [Id], [T].[] as [Version] 
FROM [MyTable] [T] 
```

If I change it to... 
```C#
[VersionColumn("Version", VersionColumnType.Number)]
public long Version { get; set; }
```
... it works as expected.

Don't know if it is a bug or by design.

**Comment by schotime** [comment]
Can you try 3.3.0-beta?

**Comment by firedog** [comment]
The problem is still there in 3.3.0-beta3

**Comment by schotime** [comment]
Hmmm....I'll need to look closer then. Have u got a full failing example?

**Comment by firedog** [comment]
Not one that I can share I'm afraid (client's code). If your initial investigation leads nowhere I can see if I can put something together...

**Comment by schotime** [comment]
Hi have tried to reproduce but works as expected. Going to need a concrete example from you.

**Comment by firedog** [comment]
I have made a failing example now. You'll find it here: https://github.com/firedog/versiontest

"Fails on my machine" ™

**Comment by schotime** [comment]
Ahhhhh...you didn't say you were using fluent conventions. The bug is in your named method. Should be.

```
.Named(mi => mi.GetCustomAttributes<ColumnAttribute>().Any() ? (mi.GetCustomAttribute<ColumnAttribute>().Name ?? mi.Name) : mi.Name)
```

VersionColumnAttribute inherits ColumnAttribute.

**Comment by firedog** [comment]
Alright, I see what I did there! :-D

Thanks for your help!
