### ISSUE TITLE
Is there a way to get One to Many to Many?

### ISSUE THREAD

**Issue by rogimenez** [schotime/NPoco#275]
I have: Clients -> List<Project> -> List<User>

With V3 one can  get Clients -> List<Project> with FetchOneToMany but I would love to be able to get the users in projects. It's not a rare case this level of nested lists.

Thanks for your great work!

**Comment by schotime** [comment]
This is not supported and won't be. Even a one to many and bring back too much data. 
If you really need to do this, then you can map it to a flat DTO then use LINQ to group them and project to your nested model.
Sorry.

**Comment by rogimenez** [comment]
Thanks for your answer.

Do I have to write a class for the flat DTO to get the results from the query or NPoco generates one by itself?

**Comment by schotime** [comment]
You have to write or you can use dynamic.
