### ISSUE TITLE
2.10.11 > MySQL > Database > OpenSharedConnectionImp > _shared.Open()

### ISSUE THREAD

**Issue by m4s1r0** [schotime/NPoco#279]
Hi, 

I´m having the following error:

Exception has been thrown by the target of an invocation. at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture) at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index) at MySql.Data.MySqlClient.NativeDriver.SetConnectAttrs() at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset) at MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset) at MySql.Data.MySqlClient.NativeDriver.Open() at MySql.Data.MySqlClient.Driver.Open() at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings) at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection() at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver() at MySql.Data.MySqlClient.MySqlPool.GetConnection() at MySql.Data.MySqlClient.MySqlConnection.Open() at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal) in d:\Adam\projects\NPoco\src\NPoco\Database.cs:line 207 at NPoco.Database.<Query>d__77.MoveNext() in d:\Adam\projects\NPoco\src\NPoco\Database.cs:line 982 at System.Linq.Enumerable.<CastIterator>d__b1`1.MoveNext() at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) at NPoco.Database.Fetch[T](Sql sql) in d:\Adam\projects\NPoco\src\NPoco\Database.cs:line 745 at NPoco.Database.Fetch[T](String sql, Object[] args) in d:\Adam\projects\NPoco\src\NPoco\Database.cs:line 740 at NPoco.Database.FetchBy[T](Func`2 expression) in d:\Adam\projects\NPoco\src\NPoco\Database.cs:line 764 at engenhartec.com.br.repository.Repositories.Base.RepositoryBase`2.Find(Expression`1 where) in ...

--

Does anybody knows what can be happening?

PS: Locally works fine.

Thx in advance.

**Comment by m4s1r0** [comment]
.NetConnector version 6.9.8.0

**Comment by eByte23** [comment]
@m4s1r0 What version of NPoco? 2.10.11? and running on clr or dotnet core?

**Comment by m4s1r0** [comment]
Hi @eByte23 ! The version is 2.10.11. The problem is in the host where application is allocated. For some reason, the only .NetConnector that runs normally is the 6.9.7 version. Atfer a deploy with updated references/dll´s, everything is fine!
