### ISSUE TITLE
Add SchemaName or DatabaseName to TableNameAttribute

### ISSUE THREAD

**Issue by BackInAction** [schotime/NPoco#280]
It would be great if I could define which Schema (often called Database on some platforms) a particular table resides.  Today if I have a connection to a database server that houses multiple Schemas (databases in SQL Server speak), I have to make a unique connection to each Schema to access tables.  For example...

    var dbProduct = new Database("product");
    var rows = dbProduct.Fetch<mytable>("where name = @0", ...);

But if I have access another table in a different schema on the same server instance, I have to make a new connection...

    var dbReport = new Database("report");
    var rows = dbReport.Fetch<othertable>("where.....");

Ideally I should be able to set a non-null/blank "SchemaName" or "DatabaseName" on the TableNameAttribute...

    [TableName(SchemaName = "report",...)]
    public class othertable....;

If this was done, I could perform this action...

    // fetch data from table not found in the originally connected schema but on the same server
    var rows = dbProduct.Fetch<othertable>("where ....");

Today I sort of work around this issue by using a fully defined select statement...

    // using a connection the product schema fetch data from a table in the report schema...
    var rows = dbProduct.Fetch<othertable>("select * from report.othertable where....");

However, this does not work with simple inserts/updates.

    // this would fail...
    dbProduct.insert<othertable>(sampleRowForOtherTable);

But if 'othertable' SchemaName was defined, nPoco would know it would need to include the explicit schema name when building its internal query.

Thoughts?  I can't be the only one that has to work with multiple Schemas/Databases/Users that reside on the same server instance.

**Comment by schotime** [comment]
This is already possible.
The table name is used.

eg.
```
[TableName("[myschema].[tablename]")]
```

The only thing to bear in mind is that you must escape it yourself, if needed

**Comment by BackInAction** [comment]
Hmmm, I thought I tried that once.  Maybe I need to try again and figure out why it was failing.

Thanks.

**Comment by BackInAction** [comment]
I'm not sure what I was doing before, but this seems to work.  Sorry about that.  I'll close the ticket.
