### ISSUE TITLE
Add "Insert" and "Values" methods to SqlBuilder

### ISSUE THREAD

**Issue by cojomojo** [schotime/NPoco#281]
I am currently using NPoco and have needed an Insert and Values method as part of the SqlBuilder, so I created my own. Do you think these methods would be worth integrating into NPoco?

Insert would just replace a `/**insert**/` with the column names provided, and `/**values**/` would be replaces with `(val1, val2, val3)`.

I can fork and add these methods and create a PR if this of interest.

**Comment by schotime** [comment]
Can I ask why you are doing this? What problem are you trying to solve?

**Comment by cojomojo** [comment]
I have a case where I need to build up a SQL statement manually because I have some models which I am persisting that are very dynamic. I am using the SqlBuilder class to help generate my SQL statement. 

Here is what my suggested `insert` and `values` methods could look like:

```c#
public SqlBuilder Insert(string[] columns)
{
    AddClause("insert", $"({string.Join(", ", columns)})", new object[] { }, ", ", "", "");
    return this;
}

public SqlBuilder Values(params object[] parameters)
{
    string[] values = new string[parameters.Length];

    for (var i = 0; i < parameters.Length; ++i)
        values[i] = $"@{i}";

    AddClause("values", $"({string.Join(", ", values)})", parameters, ", ", "", "");
    return this;
}
```

**Comment by schotime** [comment]
Hey thanks for getting back to me.
What I might do is expose AddClause as public then you can create extension methods augment the current functionality.

Then yours would just become.

```c#
public static class SqlBuilderExt {
    public static SqlBuilder Insert(this SqlBuilder sqlBuilder, string[] columns)
    {
        sqlBuilder.AddClause("insert", $"({string.Join(", ", columns)})", new object[] { }, ", ", "", "");
        return sqlBuilder;
    }

    public static SqlBuilder Values(this SqlBuilder sqlBuilder, params object[] parameters)
    {   
        string[] values = new string[parameters.Length];
  
        for (var i = 0; i < parameters.Length; ++i)
            values[i] = $"@{i}";
  
        sqlBuilder.AddClause("values", $"({string.Join(", ", values)})", parameters, ", ", "", "");
        return sqlBuilder;
    }
}
```

**Comment by cojomojo** [comment]
That would be even better!

**Comment by cojomojo** [comment]
Closing this issue, and hoping you expose AddClause as public. Related to #286.
