### ISSUE TITLE
Using public field instead of property in Poco triggers access exception

### ISSUE THREAD

**Issue by huronbikes** [schotime/NPoco#284]
In NPoco 3.1.0, we encounter a Windows Kernel error when trying to insert a poco with a Column mapped to a public field instead of a public property.

Expected behavior to see a reflection error or some other issue as opposed to an Invalid Access Exception from the Windows Kernel.  I don't know if it is expected functionality for mappings to work with fields, but we do not expect mappings to work with class fields as opposed to properties.

To reproduce, make a Poco:

```
[TableName("sometable")]
[PrimaryKey("Id")]
public class SomeClass
{
   [Column("Id")]
   public int Id {get;set;}
   
   [Column("a_date")]
   public DateTime ADate;
}
```

Inserting the Poco will trigger an Access Exception

OS is Windows 7
IIS 8.5
ASP.Net 4.6
Sql Server 2014

**Comment by schotime** [comment]
Can u you try this with 3.3.3.
I did a fix for fields recent.

**Comment by huronbikes** [comment]
It looks like 3.3.4 from Nuget no longer crashes.  I wouldn't expect that fields would work for mapping at all, but it appears that they do.  So long as that's desired behavior, it looks fine to me.

**Comment by schotime** [comment]
Fields have and are intended to be supported.
