### ISSUE TITLE
Change AddClause() from private to public in SqlBuilder

### ISSUE THREAD

**Issue by theosherman** [schotime/NPoco#286]
It'd be nice to use the `AddClause()` function in my code to compose some more customized SQL using the `SqlBuilder`. I find myself restricted by the existing functions and I think making this function public would solve most of them.

For example...
I want to have a single search input textbox. And with that search input, I want to write a select that checks multiple columns for that input value. I would write that like the following:
`SELECT * FROM User WHERE 1=1 AND (FirstName = @Search OR LastName = @Search OR Address = @Search)`

The Where() in SQL builder will `AND` them instead of `OR` them. `AddClause()` I think could achieve this with `AddClause("where", sql, parameters, " OR ", " ( ", " ) ");`

You might know of a way to get around this already. Please share your thoughts on this.

**Comment by schotime** [comment]
This has already been done and will be apart of the next release. 3.3.5+
