### ISSUE TITLE
Call functions and procedures

### ISSUE THREAD

**Issue by gaui** [schotime/NPoco#288]
What is the correct way to call functions and procedures in NPoco? I'm using Oracle.

I looked at the source in 2.0 and 3.0 and the `CommandType` on `IDbCommand` object is never changed, so I always get: `ORA-00900 invalid SQL statement`.

Why isn't it possible to override the `IDbCommand.CommandType` property to `CommandType.StoredProcedure` so it can be executed as a function or a procedure, and not as `CommandType.Text` (SQL query). I need to be able to execute a function and get the return value without having to execute it as a SQL query and in a PL/SQL block with `begin` and `end`.

Normally, without going through NPoco, I would do something like:

```
using (var connection = new OracleConnection())
{
	connection.ConnectionString = "MyConnectionString";
	connection.Open();

	using (var cmd = new OracleCommand())
	{
		cmd.Connection = connection;

		cmd.CommandText = "myFunction";
		cmd.CommandType = CommandType.StoredProcedure;

		cmd.Parameters.Add("Return_Value", OracleDbType.Varchar2);
		cmd.Parameters["Return_Value"].Direction = ParameterDirection.ReturnValue;
		cmd.Parameters["Return_Value"].Size = 20;

		cmd.Parameters.Add("param1", param1);
		cmd.Parameters.Add("param2", param2);

		cmd.ExecuteNonQuery();
	}
}
```

**Comment by schotime** [comment]
This has always worked for me.

```
db.Execute("call sp_mysp(@0)", "myparamdata");
```

or for a function

```
db.ExecuteScalar("select f_myfunc(@0) from dual", "myparamdata");
```

Note, that "myparamdata" can be an actual OracleParameter object as well.

**Comment by gaui** [comment]
@schotime If the function has some DML (insert, update, delete) it cannot be used like this: `select f_myfunc(@0) from dual`. You would have to mark the function with a `PRAGMA AUTONOMOUS_TRANSACTION` - but I wouldn't recommend it, because it creates a new nested transaction.

Why not give the possibility in NPoco to override the `CommandType` and use the built-in functionality of the Oracle Provider to run a sproc/func properly?

**Comment by schotime** [comment]
Suggest away....not easy without breaking everything.

**Comment by gaui** [comment]
Are you sure? How about creating an overloaded method that accepts `CommandType` as a parameter. Change `CreateCommand()` so it will accept it as an optional parameter, and pass it in. If passed (not null), assign it to the `IDbCommand` instance. If not, it's default `Text`.

This way, the default works, but you now have an option to choose a `CommandType`.

**Comment by schotime** [comment]
Go for it.

Firstly there would need to be 25+ overloads and then we would break all
the interceptors as they would need to take the command type as well.

Happy to take a PR though.

**Comment by schotime** [comment]
Might be able to get this in for the next release. For Execute and ExecuteScalar that take the `Sql` object.

**Comment by gaui** [comment]
@schotime That would be awesome and highly appreciated. This is the only thing that distincts NPoco from great micro-ORMs like Dapper. I insisted to my team to use NPoco, because the API is great, easy to mock in tests, has fluent mapping capability, query builder, etc. but the lack of this has been disappointing for me and my team, because we went from Dapper to NPoco and Dapper has this option. But NPoco is superior to Dapper, so I would hate to have to stop use it. 

However, I was going to contribute but was not able to run the tests because I'm not familiar with NUnit or. NET Core. It would be nice to add a contribution guide for those who are not familiar with the environment around the project.

I'm very much looking forward to this. Do you have some kind of release notes so I can know when this feature lands? Also would this only be in 3.x? We're still in 2.x but we'll upgrade as soon as this is added.

Thank you very much for your hard work. This is an awesome project.

**Comment by schotime** [comment]
This has landed in Nuget 3.4.0 with support for dotnet core 1.0.

To run tests navigate to `test\NPoco.Tests` and from the command prompt run `dotnet run`

I'll try and get this added somewhere.

**Comment by gaui** [comment]
Awesome, thank you! Does it also support .NET non-Core ?

**Comment by gaui** [comment]
One question, will this also be available for: `Execute(string sql, params object[] args)` and `ExecuteScalar<T>(string sql, params object[] args)` in next releases?

If the reason for not adding it was the `params` arguments then C# has had [named arguments](https://msdn.microsoft.com/en-us/library/dd264739.aspx) since version 4.0 and Dapper uses them for this purpose.

So the function could be specified as:

```
public int Execute(string sql, params object[] args, CommandType commandType)```

and called like this:

```
int result = Execute("someProc", arg1, arg2, arg3, commandType: CommandType.StoredProcedure);
```

What do you think?

**Comment by gaui** [comment]
Also, I looked at 79e1bc and I can't see that you're assigning the input parameter `commandType` to `cmd.CommandType` ... this doesn't do anything, except changes the public API for `Execute` and `ExecuteScalar<T>`  :confused: 

Going to reopen this.

**Comment by schotime** [comment]
Firstly, that is a bug. My bad.
Secondly, you can't have named and positional arguments. The example you have specified is not possible.

**Comment by gaui** [comment]
Sorry. Then how about an overload with `CommandType` infront of params:

```
public int Execute(string sql, CommandType commandType, params object[] args);
```

**Comment by gaui** [comment]
I'm going to close this issue, I see that this has been fixed in 3.4.1. Great job!

**Comment by gaui** [comment]
The only difference I can see is that the new `CreateStoredProcedureCommand()` method doesn't use the `AddParameter()` method like `CreateCommand()` does, so I can't use `@0, @1` parameters.

**Comment by tokzhee** [comment]
This doesnt work for Oracle.ManagedAccess.Client.

Got the following error: 
 Unable to cast object of type 'Oracle.ManagedDataAccess.Client.OracleParameter' to type 'Oracle.DataAccess.Client.OracleParameter'.

Find my snippet below: 
  var retVal = new RacDetailsResponse();
            try
            {
                using (var context = InternalDb.GetInstance())
                {
                    var param1 = new OracleParameter("P_ACCOUNT_NUMBER", OracleDbType.Varchar2, phone, ParameterDirection.Input);
                    var param2 = new OracleParameter("P_PROD_TYPE", OracleDbType.Varchar2, productType.ToUpper(), ParameterDirection.Input);


                    //var param3 = new OracleParameter("P_OUT", OracleDbType.RefCursor, DBNull.Value, ParameterDirection.Output);
                    var param3 = new OracleParameter("P_AMOUNT", OracleDbType.Decimal, 0, ParameterDirection.Output);
                    var param4 = new OracleParameter("P_REASON", OracleDbType.Varchar2, 3999 ,"" , ParameterDirection.Output);
                    string proc_name = "PKG_GH_LOAN_CALCULATOR.PRC_PAYDAYLOAN_CALCULATOR";
                    context.Execute(proc_name, CommandType.StoredProcedure, param1, param2, param3, param4);
                    var amt = param3.Value.ToString();
                    var reason = param4.Value.ToString();
                   
                    if (reason == "Eligible")
                    {
                        retVal.ResponseCode = "00";
                        retVal.amount = amt;
                    }
                    else
                    {
                        retVal.amount = "0";
                        retVal.ResponseCode = "02";
                        retVal.FullDescription = reason;
                    }
               
                }

**Comment by dark2201** [comment]
How to handle output parameters?
