### ISSUE TITLE
Cannot insert data into the Guid type to the database

### ISSUE THREAD

**Issue by JavaScript-zt** [schotime/NPoco#289]
"System.InvalidCastException" type of exception occurred in the NPoco.dll, but not in the user code for processing
Other information: from the "System.UInt64" to "System.Guid" mandatory conversion is invalid.

**Comment by slobber** [comment]
0. Please describe your database type(mssql, oracle or mysql....),
1. Please check your database table column type is guid,
2. Ensure your entity property type is guid? if any records has null guid value.

**Comment by JavaScript-zt** [comment]
database type  Mysql。
Mysql no Guid type, column type is char (36)。

**Comment by JavaScript-zt** [comment]
I solved this problem, thank you。Add this line of code on the Map： PrimaryKey(x => x.Id, false);
