### ISSUE TITLE
SingleById, Composite Keys and Properties names not equal to column names 

### ISSUE THREAD

**Issue by gredondogc** [schotime/NPoco#290]
I'm using Npoco 3.3.4.0 and postgresql npgsql 3.1.3.0

Considere the following table:

```
[TableName("\"public\".\"sale_fact\"")]
[PrimaryKey("client_id,saleperson_id,sku_id")]
[ExplicitColumns]
public partial class SaleFact 
{
    [Column("client_id")] public int ClientId { get; set; }
    [Column("saleperson_id")] public int SalepersonId { get; set; }
    [Column("sku_id")] public int SkuId { get; set; }
    [Column("qty")] public decimal Qty { get; set; }
    [Column("value")] public decimal Value { get; set; }
}
```

I expected to be able to used the following line:

```
var saleSingleById = ctx.SingleOrDefaultById<SaleFact>(
    new { SkuId = 1, ClientId = 2, SalepersonId = 3 });
```

but what works is:

```
var saleSingleById = ctx.SingleOrDefaultById<SaleFact>(
    new { sku_id = 1, client_id = 2, saleperson_id = 3 });
```

Is this expected? Doesn't it goes against the ORM principles by exposing the database columns names? How does it handle the event of column names with spaces and special characters?

This seems to be related to the issue #199

**Comment by dheijl** [comment]
You could also write:

    var saleSingleById = ctx.SingleOrDefaultById<SaleFact>(
        new SaleFact { SkuId = 1, ClientId = 2, SalepersonId = 3 });

to make it work as expected.

**Comment by gredondogc** [comment]
var saleSingleById = ctx.SingleOrDefaultById<SaleFact>(
		new SaleFact { SkuId = 1, ClientId = 2, SalepersonId = 3 });

did not work but it was a good idea. I checked the code and hacked the following function:

	private Sql GenerateSingleByIdSql<T>(object primaryKey)
	{
		var index = 0;
		var pd = PocoDataFactory.ForType(typeof (T));
		var primaryKeyValuePairs = GetPrimaryKeyValues(
			pd, pd.TableInfo.PrimaryKey, primaryKey,
			primaryKey is T);
		var sql = AutoSelectHelper.AddSelectClause(this, typeof(T), string.Format("WHERE {0}", BuildPrimaryKeySql(primaryKeyValuePairs, ref index)));
		var args = primaryKeyValuePairs.Select(x => x.Value).ToArray();
		return new Sql(true, sql, args);
	}

Were the line:

		var primaryKeyValuePairs = GetPrimaryKeyValues(
			pd, pd.TableInfo.PrimaryKey, primaryKey,
			primaryKey is T);

was originally:

		var primaryKeyValuePairs = GetPrimaryKeyValues(
			pd, pd.TableInfo.PrimaryKey, primaryKey,
			false);

i.e. it never handled the primaryKey as a POCO.

This was a quick hack and I don't know if it's the right approach. I would prefer using the 

	new { SkuId = 1, ClientId = 2, SalepersonId = 3 }

but this solution seems acceptable.
