### ISSUE TITLE
NPoco Assembly not signed

### ISSUE THREAD

**Issue by jansepke** [schotime/NPoco#294]
Could you sign the NPoco assembly so we can use it in environments that need signed dlls?

**Comment by schotime** [comment]
Sorry, won't be releasing a signed version. You can sign yourself if needed. Think there is even a nuget package that can do it on the fly for you now.

**Comment by alikalfaoglu** [comment]
Is it so hard for you to support this out of the box? Your are forcing me to update nuget folder to find and sign NPoco assemblies. Since nuget have some potential problems that forces us to clear local package cache regularly, you should have then suggest us a way to automate the process...

**Comment by chrisccc** [comment]
Where is the strong named nuget package?
