### ISSUE TITLE
It's not apparent that Save() performs an upsert

### ISSUE THREAD

**Issue by ryanvgates** [schotime/NPoco#295]
It's not obvious until you look at the source code that [Save()](https://github.com/schotime/NPoco/blob/79e1bc643753b6f857012aa655367866bbd937e1/src/NPoco/Database.cs#L1801) performs an upsert. I would like to propose the following remedies to this.

1. Change comment from "Insert new record or Update existing record" to "Insert new record or Update existing record (i.e. an upsert)"
2. Update the comment to be a proper xml comment so that VS intellisense will include this important bit as you're coding
3. Updated the [wiki](https://github.com/schotime/NPoco/wiki/Create-Read-Update-Delete) to include upsert

**Comment by schotime** [comment]
There are property xml comments. Use the interface and you will see them.

**Comment by ryanvgates** [comment]
I see what you mean now. The xml comment is [here](https://github.com/schotime/NPoco/blob/8328994e233a3b2dba3fbd4c5765e252ef33cebb/src/NPoco/IDatabase.cs#L191).
