### ISSUE TITLE
Release notes for NPoco 3?

### ISSUE THREAD

**Issue by petsuter** [schotime/NPoco#296]
Are there any big changes in NPoco 3.0+? https://github.com/schotime/NPoco/wiki/Revision-History doesn't mention anything newer than 2.10.11

**Comment by petsuter** [comment]
I now found https://github.com/schotime/NPoco/wiki/Version-3.
Should this be linked from the Revision History? What about 3.1, 3.2, 3.3 and 3.4?

Also the other wiki pages like https://github.com/schotime/NPoco/wiki/Mapping-to-Nested-Objects still seem to document NPoco 2.x.

Does that mean 3+ is still somehow experimental / beta?

**Comment by schotime** [comment]
3 is definitely not beta now. Being used in production by a lot of people. 

However I have not had much time to update documentation. 
Not much has changed in terms of API except for stuff mentioned in the https://github.com/schotime/NPoco/wiki/Version-3 page. 

Other than that the internals were changed for more flexibility and less magic.

I will try and get the revisions updated.

**Comment by schotime** [comment]
https://github.com/schotime/NPoco/wiki/Release-Notes
