### ISSUE TITLE
Nested object mapping does not work if property has ResultColumn attribute

### ISSUE THREAD

**Issue by mganss** [schotime/NPoco#301]
I'm migrating from v2 to v3 and having trouble getting nested mapping to work in v3. Here's a test case:

```C#
public class User
{
    public int UserId { get; set; }
    public string Name { get; set; }
    [ResultColumn]
    public Address Address { get; set; }
}

public class Address
{
    public int UserId { get; set; }
    public string StreetName { get; set; }
}

var sql = @"select U.*, A.* from ""User"" U join Address A on U.UserId = A.UserId";
var users = db.Fetch<User>(sql);
```

The `Address` property is always null. Removing the `ResultColumn` attribute makes the example work but is obviously not a solution because it causes problems in insert/update scenarios.

The [nested object mapping wiki page](https://github.com/schotime/NPoco/wiki/Mapping-to-Nested-Objects) says:

> If you are mapping to objects that are also used for inserting data then you will need to make sure you ignore the `Address` property using the [`[ResultColumn]`](https://github.com/schotime/NPoco/wiki/Mapping) attribute.

**Comment by benosman** [comment]
+1

Experiencing similar issues, in my case i'm using the [ExplicitColumns] directive, and the nested object property does not have a [Column] attribute set.

**Comment by schotime** [comment]
@mganss If you have an attribute on it you need the `[ComplexMapping]` attribute as well.
@benosman because you have explicitly mapping then you need the `[ComplexMapping]' attribute as well otherwise it will be ignored.

Let me know how you get on.

**Comment by benosman** [comment]
@schotime Thanks for your reply.

I tested this out, at first it wasn't working for me using ```[ComplexMapping]``` and ```[ExplicitColumns]```.

In the end I found out that if I pair ```[ComplexMapping]``` with ```[ResultColumn]``` whether i'm using ```[ExplicitColumns]`` or not, it works as desired.

Thanks.

**Comment by mganss** [comment]
Adding the `ComplexMapping` attribute works for me. I can't find anything in the wiki about it, though. What does it do?

**Comment by mganss** [comment]
I've added a note to the wiki pages [Version 3](https://github.com/schotime/NPoco/wiki/Version-3) and [Mapping to Nested Objects](https://github.com/schotime/NPoco/wiki/Mapping-to-Nested-Objects).
