### ISSUE TITLE
Database needs to be disposed to close the connection?

### ISSUE THREAD

**Issue by vnefedov** [schotime/NPoco#306]
Here (wiki start page)
https://github.com/schotime/NPoco/wiki 
there is a strange note
**Note:** Database needs to be disposed to close the connection (think of it as your connection object).

As I see every command has finally block
            finally
            {
                CloseSharedConnectionInternal();
            }
where connection is closed. 
So why we need to dispose database object for closing connection (e.g. using "using" statement)?
May be it's obsolete note?

**Comment by schotime** [comment]
CloseSharedConnectionInternal() wont always close the connection. It depends whether a connection has been passed in or OpenSharedConnection was manually called.
