### ISSUE TITLE
Run custom SqlServer query

### ISSUE THREAD

**Issue by mbdavid** [schotime/NPoco#307]
Hi @schotime, really nice ORM you made, thanks for that! I'm try run this custom query:

```
db.Query<Tree>(@"
    ;WITH x AS
    (
        -- anchor:
        SELECT ID, ParentID, Name, Nivel = 0
        FROM Tree WHERE ParentID = @0
        UNION ALL
        -- recursive:
        SELECT u.ID, u.ParentID, u.Name, Nivel = x.Nivel + 1
        FROM x INNER JOIN Tree AS u
        ON u.ParentID = x.ID
    )
    SELECT ID, ParentID, Name, Nivel FROM x
    ORDER BY Nivel, Name
    OPTION (MAXRECURSION 32)
    ", parentID);
```

But when NPoco runs this command is executed (NPoco insert this first SELECT before my query):

```
SELECT ID, ParentID, Name FROM Tree
;WITH x AS ....
```

I tried with `Fetch` command and result is the some. Has another way to run this kind of query or I missing something? I'm using 3.4.1 version from NuGet.

**Comment by schotime** [comment]
; has to be the first character where as yours is a new line. The regex
could probably be amended.

**Comment by mbdavid** [comment]
Yes, now it´s working. Thanks
