### ISSUE TITLE
Fluent configuration slow

### ISSUE THREAD

**Issue by mganss** [schotime/NPoco#309]
Example:

```C#
public class NullMappings: Mappings { }

...

var mappings = new NullMappings();
var fluentConfig = FluentMappingConfiguration.Configure(mappings);
var factory = DatabaseFactory.Config(x =>
{
    x.UsingDatabase(() => new NPoco.Database(...));
    x.WithFluentConfig(fluentConfig);
});

for (int i = 0; i < 1000; i++)
{
    using (var db = Factory.GetDatabase())
    {
        c = db.FirstOrDefault<Customer>(@"select C.* from Customers C where C.Id = @0", i);
    }
}
```

This takes ~5s on my machine and ~0.5s when the line `x.WithFluentConfig(fluentConfig);` is commented out. This does not occur in v2. Also, v2 is ~1.5 times faster (w/o fluent config).

**Comment by schotime** [comment]
Not sure about this one. 5s does seem way too long. We are not seeing that with our production instance.

**Comment by schotime** [comment]
Is it possible to create a console application which you can attach that reproduces this issue?

**Comment by mganss** [comment]
Sure: [NPocoTest.zip](https://github.com/schotime/NPoco/files/450373/NPocoTest.zip)

The included .mdf is a SQL Server 2016 LocalDB database file. You'll have to change the connection string in the app.config.

Here's the output on my machine (a different one from the one mentioned above, also 5000 iterations instead of 1000):

```
Fluent: 00:00:09.0168663
Non-fluent: 00:00:05.6720920
```

I'm not sure if the DB schema and the `Customer` POCO class were the same as in the initial comment. There may have been more columns/properties.

**Comment by schotime** [comment]
I have found the issue, however i'm not sure why you would be getting 1000 instances of database. I understand 1000 queries against a DB.  

Anyways, here was my results from your program with NPoco 3.4.3

![image](https://cloud.githubusercontent.com/assets/202923/18192768/66a5353c-711a-11e6-987a-99f0f7a6bf0e.png)

**Comment by mganss** [comment]
Thanks 👍 The example is just for illustration purposes. In a real single-threaded application you'd perform 1000 queries using a single `Database` instance, but I stumbled upon this problem when using NPoco 3 in a web application where you create a `Database` instance for each request.
