### ISSUE TITLE
Inserting List<int> Issue

### ISSUE THREAD

**Issue by Dissolution** [schotime/NPoco#311]
I'm using NpgSql with NPoco to connect to my Postgres instance.
I'm trying to insert a TradeItem:

```
public sealed class TradeItem
{
    public int Id {get; set; }
    public int TradeId { get; set; }
    public int ItemId { get; set; }
    public int Quantity { get; set; }
    public List<int> OtherIds { get; set; }
}
```

into my database using a custom SQL query (for bulk inserts):
`INSERT INTO "trade_item" (trade_id,item_id,quantity,other_ids) VALUES (@0,@1,@2,@3),(@4,@5,@6,@7) RETURNING id;`

When I send in a TradeItem with an empty (non-null) list of OtherIds, NPoco is throwing an exception with this message: 
`"syntax error at or near \"select\""`

When I dig in, I find that it's generating this SQL:
`"INSERT INTO \"trade_item\" (trade_id,item_id,quantity,other_ids) VALUES ($1,$2,$3,select 1 /*poco_dual*/ where 1 = 0),($4,$5,$6,select 1 /*poco_dual*/ where 1 = 0) RETURNING id"`

It seems to be replacing my empty list with 'select 1 /_poco_dual_/ where 1 = 0' and I cannot figure out why. None of the methods in the IMapper I have defined are getting a List<int> for a converter.

Also, the column in Postgres is defined as an INTEGER[]

**Comment by schotime** [comment]
Its used on the query side to represent no value in a list. 

eg.

```sql
select * from users where user_id in ( select 1 where 1 =0 )
```

Not sure how to solve it at the moment.
