### ISSUE TITLE
Consider supporting params array in the PrimaryKey attribute for composite primary keys

### ISSUE THREAD

**Issue by nathan-alden-sr** [schotime/NPoco#312]
The [wiki](https://github.com/schotime/NPoco/wiki/Composite-Primary-Keys) says to use a comma-delimited magic string containing the columns making up a composite primary key. However, I like to avoid magic strings whenever possible as they are not refactor-friendly. Instead, I want to do this:

```
[PrimaryKey(nameof(ProfileId), nameof(DictionaryId))]
public class ProfileDictionary
{
    public Guid ProfileId { get; set; }
    public Guid DictionaryId { get; set; }
}
```

**Comment by dheijl** [comment]
Looks like a good idea to me. 

But writing 

    [PrimaryKey(nameof(ProfileId), + "," + nameof(DictionaryId)]

would also avoid the magic strings, and the string concatenation will be done at compile-time, not at runtime.

**Comment by schotime** [comment]
Add an array overload to 3.4.2
