### ISSUE TITLE
NPoco forcibly casts enums to ints, preventing Npgsql from properly handling enum values

### ISSUE THREAD

**Issue by nathan-alden** [schotime/NPoco#313]
The latest version of Npgsql has support for automatically converting enum values to the underlying enum type. `NpgsqlDbType.Enum` can be used as the value of the `NpgsqlParameter.NpgsqlDbType` property along with the enum value itself in the `NpgsqlParameter.Value` property. Unfortunately, NPoco ensures that enum values never make it into the underlying `NpgsqlParameter` instances.

The latest version of NPoco's `Database.cs` has this code on line 512:
```
if (t.GetTypeInfo().IsEnum || (underlyingT != null && underlyingT.GetTypeInfo().IsEnum))        // PostgreSQL .NET driver wont cast enum to int
{
    p.Value = (int)value;
}
```
This code is executed after any extensibility point (e.g., `Database.GetParameterConverter`), meaning there is no simple way I can configure NPoco to simply pass through the enum value to the underlying `NpgsqlParameter`. The only workaround--and I use that term loosely, as it's not practical--is to re-set the `NpgsqlParameter.NpgsqlDbType` and `NpgsqlParameter.Value` properties in an overridden `Database.OnExecutingCommand`. I have yet to find another workaround for this.

It does not make sense to me why this arbitrary cast from enum to int is in `Database`. Shouldn't `Database.GetParameterConverter` have the last word on what the ultimate underlying type should be?

As it stands, this is blocking my further use of NPoco.

**Comment by nathan-alden** [comment]
It looks like much of `Database.SetParameterValue` contains provider-specific logic. That method really should be refactored. It's making too many assumptions about what certain parameter values mean. There is PostgreSQL-specific and SQL Server-specific code in there.

**Comment by nathan-alden** [comment]
For now, I will override `Database.AddParameter` and add custom conversion logic as necessary. However, doing it this way opts out of the mapper architecture.

**Comment by nathan-alden** [comment]
Here's my workaround:
```
public class PostgreSqlDatabase : Database
{
    public PostgreSqlDatabase(string connectionString)
        : base(connectionString, DatabaseType.PostgreSQL, NpgsqlFactory.Instance)
    {
    }

    // Necessary because NPoco forcibly converts enum values to ints
    public override void AddParameter(DbCommand cmd, object value)
    {
        var dbParameter = value as DbParameter;

        if (dbParameter == null)
        {
            dbParameter = cmd.CreateParameter();
            dbParameter.Value = value ?? DBNull.Value;
        }
        dbParameter.ParameterName = $"@p{cmd.Parameters.Count}";

        cmd.Parameters.Add(dbParameter);
    }
}
```

**Comment by schotime** [comment]
You can use the mappers to do this. By returning something that implements DbParameter it will be passed straight through.

So given the following mapper.

```csharp
    public class PostgreSQLEnumMapper : DefaultMapper
    {
        public override Func<object, object> GetParameterConverter(DbCommand dbCommand, Type sourceType)
        {
            var underlyingT = Nullable.GetUnderlyingType(sourceType);
            if (sourceType.GetTypeInfo().IsEnum || (underlyingT != null && underlyingT.GetTypeInfo().IsEnum))
            {
                return x =>
                {
                    var p = dbCommand.CreateParameter(); //Create NPgsqlParameter here if you need to
                    p.Value = x;
                    return p;
                };
            }

            return base.GetParameterConverter(dbCommand, sourceType);
        }
    }
```

You can add it my saying.

```
database.Mappers.Add(new PostgreSQLEnumMapper());
```

**Comment by nathan-alden** [comment]
I'm not using PostgreSQL enums anymore due to their horrible limitations, but it looks like your solution works. Thanks!
