### ISSUE TITLE
Parse binary(16) to guid 

### ISSUE THREAD

**Issue by korowiev** [schotime/NPoco#316]
how to convert a binary(16) with mysql for guid?

**Comment by eByte23** [comment]
@korowiev you should use CHAR(36) for it work by default as a .net GUID.
other wise refer to http://stackoverflow.com/questions/12976303/what-column-type-of-mysql-will-return-as-system-guid-in-c-sharp I'm not sure if this is still supported adding 'old guids=true;' to your connection string

@schotime can close.
