### ISSUE TITLE
[question] access fluent mapping config

### ISSUE THREAD

**Issue by enrico-padovani** [schotime/NPoco#319]
Hey @schotime 

I'm working on a component that turns OData query string into a plain SQL string. In order to integrate that feature with micro ORMs like NPoco, I need a way to read the mappings in order to access the underlying table and column names.

I've managed to explore the configuration of Pocos (given type of T) made using NPoco attributes like this:
```
var tableNameAttribute = typeof(T).GetCustomAttributes(true).FirstOrDefault(p => p is TableNameAttribute) as TableNameAttribute;
if (tableNameAttribute != null)
{
	var sqlTableName = tableNameAttribute.Value;
}
foreach (var prop in typeof(T).GetProperties())
{
	var columnAttribute = prop.GetCustomAttributes(true).FirstOrDefault(p => p is ColumnAttribute) as ColumnAttribute;
	if (columnAttribute != null)
	{
		var sqlColumnName = columnAttribute.Name;
	}
}
```

Since I don't know much about NPoco internals, do you have some tips in how to get the same info out of fluent config?

Thanks!!

**Comment by schotime** [comment]
You can access `PocoDataFactory.ForType(typeof(T))` which will give you the internal config.

**Comment by enrico-padovani** [comment]
Ok, thanks!

So it'll look like this:

```
var pocoData = database.PocoDataFactory.ForType(typeof(T));
if (pocoData != null)
{
    options.TableName = pocoData.TableInfo.TableName;
    foreach (var column in pocoData.QueryColumns)
    {
        options.ColumnsAs.Add(column.Value.ColumnName, column.Value.ColumnAlias ?? column.Value.ColumnName);
     }
}
```

Last question: if I need to retrieve the SELECT only columns, It's ok to use `QueryColumns`? There are other properties here, like: `AllColumns `and `Columns`.

**Comment by schotime** [comment]
Thats correct. QueryColumns is for selects.

**Comment by enrico-padovani** [comment]
Nice, thank you!
