### ISSUE TITLE
Database.Fetch() and Query() prepend invalid SQL with Oracle/Cursor

### ISSUE THREAD

**Issue by kcragin** [schotime/NPoco#320]
When I do something like `db.Query<Thing>(sql)` where `sql` is a cursor:

    declare
        cursor c
    is
        select col1, col2 from table1 where rownum < 100
        for update of col1 skip locked
    begin
        for r in c loop
           update table1 set col1 = col1 + 1 where current of c;
        end loop
        commit;
    end;

NPoco prepends a `SELECT` clause to the SQL resulting in invalid SQL:

    SELECT "COL1" AS "COL1", "COL2" AS "COL2" declare
        cursor c
    is
        select col1, col2 from table1 where rownum < 100
        for update of col1 skip locked
    ...

For now I am getting around it by stripping the generated SQL of the invalid part in `OnExecutingDbCommand()`. Should I be using something other than `Fetch()` or `Query()`?

**Comment by schotime** [comment]
You can escape the auto select by pretending a ; as the first character in
your query. It will be stripped before it runs.

**Comment by kcragin** [comment]
Thanks!
