### ISSUE TITLE
Oracle float(126) column --> decimal results in InvalidCastException

### ISSUE THREAD

**Issue by kcragin** [schotime/NPoco#321]
Title says it all. The particular case I was trying was a `db.Fetch<dynamic>()` from inside the `DictionaryMapper`.

**Comment by kcragin** [comment]
It's not an NPoco problem per se. From http://docs.oracle.com/cd/B19306_01/win.102/b14307/OracleDecimalStructure.htm:

> OracleDecimal can store up to 38 precision, while the .NET Decimal datatype can only hold up to 28 precision. When accessing the OracleDecimal.Value property from an OracleDecimal that has a value greater than 28 precision, loss of precision can occur. To retrieve the actual value of OracleDecimal, use the OracleDecimal.ToString() method. Another approach is to obtain the OracleDecimal value as a byte array in an internal Oracle NUMBER format through the BinData property.

That said you may want to consider a couple of alternatives: 1) limiting the precision using the [OracleDecimal](http://docs.oracle.com/cd/B19306_01/win.102/b14307/OracleDecimalStructure.htm).SetPrecision, or 2) converting it using `OracleString` as mentioned above.

For now, I ended up having to do a `ROUND` in the SQL.

**Comment by kcragin** [comment]
@schotime, this bit me yet again, but in a place where I am unable to rely on the `ROUND` in the SQL, and I do think it is something that can be taken up in NPoco.

A few things that would ease this: support for `OracleDecimal` in the DTO and/or access to the underlying `DbDataReader` so it can be cast to an `OracleDataReader` so someone could do the mapping to `OracleDecimal` rather than NPoco handling. it.

The only way I was able to get around this was to replace the problematic `DictionaryMapper` with one that used an `OracleDecimal`:

    MappingFactory.RowMappers[0] = () => new DictionaryMapperEx();

The above seems kind of hackish though. Thoughts?

**Comment by schotime** [comment]
yeah...this is a tough one.
What you have done is not hackish. That's probably the only way to solve this, with out taking a direct reference to the Oracle driver.
