### ISSUE TITLE
DbProviderFactory failure with NPoco?

### ISSUE THREAD

**Issue by Spilarix** [schotime/NPoco#322]
Hello,

I'm switching from PetaPoco to NPoco but I have a connection problem with my PostgreSQL instance using Npgsql.

- Configuration is in web.config of a Web project
- NPoco/Npgsql are in a DAL assembly.
- ConnectiongString works properly

The problem seems to come from the DbProviderFactory using NPoco (because it works with PetaPoco).

```
<add name="Npgsql Data Provider"
           invariant="Npgsql"
           support="FF"
           description=".Net Framework Data Provider for Postgresql Server"
           type="Npgsql.NpgsqlFactory, Npgsql, Version=3.1.7.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7" />
```

- Using "invariant="Npgsql", I get this error message on database instantiation : "Unable to find the requested .Net Framework Data Provider. It may not be installed."

- Using "invariant="Npgsql2" (as indicated in NPoco's Wiki, even if I use NPoco v3), I get this error message at any query (but after DB instantiation) : "Format of the initialization string does not conform to specification starting at index 0"

Is it a bug or do I need to fix something ?

**Comment by schotime** [comment]
You may be using the wrong overload in the constructor. eg. you may be invoking the connectionString one rather than the connectionstringname one.

Verify that you are indeed using the correct one.

**Comment by Spilarix** [comment]
I tried both overload : (ConnectionStringName) and (ConnectionString, DatabaseType.PostgreSQL) but it doesn't work.

**Comment by schotime** [comment]
using this config.

```xml
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6" />
    </startup>
  <connectionStrings>
    <add name="mydb" connectionString="server=localhost;port=5432;database=;uid=;pwd=" providerName="Npgsql"/>
  </connectionStrings>
  <system.data>
    <DbProviderFactories>
      <add name="Npgsql Data Provider"
                 invariant="Npgsql"
                 support="FF"
                 description=".Net Framework Data Provider for Postgresql Server"
                 type="Npgsql.NpgsqlFactory, Npgsql, Version=3.1.7.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7" />
    </DbProviderFactories>
  </system.data>
</configuration>
```

then

```csharp
var db = new Database("mydb");
var data = db.Fetch<dynamic>("select id from table");
Console.WriteLine(data.Count);
```

or you can skip that and do.

```csharp
var db = new Database("server=localhost;port=5432;database=;uid=;pwd=", DatabaseType.PostgreSQL, Npgsql.NpgsqlFactory.Instance);
var data = db.Fetch<dynamic>("select id from table");
Console.WriteLine(data.Count);
```
