### ISSUE TITLE
FetchMultipleAsync

### ISSUE THREAD

**Issue by yilativ** [schotime/NPoco#323]
Any plans for that? I think that would be great as that's the most IO intensive with multiple results and thus longer running queries

Thanks!!

**Comment by schotime** [comment]
We take pull requests

**Comment by gideonkorir** [comment]
I'm also interested in this + I'm willing to work on a PR for this. @schotime I've dug through the code from what I see, ```IDatabase.FetchMultiple(Type[] types, object cb, Sql sql)``` seems to be the method called eventually, if I make an ```async``` version of that I could implement the rest of the ```FetchMultiple``` methods on top of it, is that about right?

**Comment by gideonkorir** [comment]
Please check out [this changes](https://github.com/schotime/NPoco/compare/master...gideonkorir:pr-323?expand=1) if you are ok with them I can add more tests and submit the PR
