### ISSUE TITLE
About paging perfomance

### ISSUE THREAD

**Issue by vnefedov** [schotime/NPoco#324]
As I see, NPoco makes two queries for pagination. 
The first to arrive the total number of rows 
`result.TotalItems = ExecuteScalar<long>(sqlCount, args);`
and the second to actually retrieve the page. So, when I have a "heavy" query, the performance drops significantly. 
Why the first query? You know the total number of rows when you select the page (between startRow and endRow).

**Comment by schotime** [comment]
That tells you the total number of rows for that page, but not the total, so that you can work out how many pages there are.

If you don't care about that information you can use the `Fetch` overload that takes a page number and page size and just returns those rows.

**Comment by vnefedov** [comment]
Yes, I need to know total number of rows.
The question is why NPoco make two queries instead of one, something like this:

```
declare @PageNum int = 2
declare @PageSize int = 10

select Top(@PageSize) * from
(
	select S.*, 
	RowID=row_number() over (order by Name),
	TotalRows=count(*) over() 
	from [STATE] S
) A
where A.RowId > ((@PageNum-1) * @PageSize)
```

**Comment by schotime** [comment]
How do you handle it when using 2012's offset syntax?

**Comment by vnefedov** [comment]
This is original query (for example)
`SELECT * FROM STATE ORDER BY NAME`

As I see NPoco v3.4.1 do not use OFFSET/FETCH syntax for paging. It transform original query to:

```
DECLARE @0 int = 10
DECLARE @1 int = 20
SELECT * 
FROM 
(
	SELECT 
	poco_base.*, 
	ROW_NUMBER() OVER (ORDER BY name) poco_rn
	FROM (
		SELECT * FROM STATE 
	) poco_base 
) poco_paged
WHERE poco_rn > @0 AND poco_rn <= @1
ORDER BY poco_rn
```

It is very simple to modify this query to return number of total rows:
```
SELECT * 
FROM 
(
	SELECT 
	poco_base.*, 
	ROW_NUMBER() OVER (ORDER BY name) poco_rn,
	**COUNT(*) OVER() AS poco_totalrows**
	FROM (
		SELECT * FROM STATE 
	) poco_base 
) poco_paged
WHERE poco_rn > @0 AND poco_rn <= @1
ORDER BY poco_rn
```

Also it's not a problem to use OFFSET/FETCH syntax
```
SELECT
*,
COUNT(*) OVER() AS poco_totalrows
FROM
(
	SELECT * FROM STATE 
) poco_base
ORDER BY NAME
OFFSET 10 ROW
FETCH FIRST 10 ROWS ONLY
```

**Comment by schotime** [comment]
The sql2012 dbtype does use offset.

I dont mind your suggestions however the whole way we do the mappings would
need to be redesigned. Extracting the total rows from the first/last row
would need to be a fundamental concept. I will have a look.

**Comment by vnefedov** [comment]
Well, it’s not a problem. I just wrote for myself some extension methods for Database and Page classes for "performance optimized" paging.
But I think that it’s good to have this ability "out of the box". Anyway NPoco is awesome :)

**Comment by schotime** [comment]
Care to share them in here?

**Comment by vnefedov** [comment]
Nothing special (I use CTE. It provide best perfomance in my case)

```
public static Page<T> Paged<T>(this Database db, int? page, int itemsPerPage, Sql sql) where T : class
{
    Page<T> result = new Page<T>();
    result.Items = new List<T>();
    result.SetCurrentPage(page);
    result.ItemsPerPage = itemsPerPage > 0 && itemsPerPage < 301 ? itemsPerPage : 20;
    var resultSql = Sql.Builder;
    resultSql.Append("; ");
    resultSql.Append("WITH TotalResults AS ( ");
    resultSql.Append(sql);
    resultSql.Append(") ");
    resultSql.Append(@"SELECT *, (SELECT COUNT(*) FROM TotalResults) AS _TotalRows FROM TotalResults WHERE _ResultSetRowNumber BETWEEN @0 AND @1 ORDER BY _ResultSetRowNumber", result.StartRow(), result.EndRow());

    List<QueryWrapper<T>> items = db.Fetch<QueryWrapper<T>>(resultSql);
    if (items != null && items.Count > 0)
    {
        result.Items = items.Select(x => x.Obj).ToList();
        result.TotalItems = items[0].Spec._TotalRows;
        result.GetTotalPages();
    }
    return result;
}
```

And QueryWrapper is:

```
public class QueryWrapper<T>
{
    public T Obj { get; set; }
    public Service Spec { get; set; }
    public class Service
    {
        public int _ResultSetRowNumber { get; set; }
        public int _TotalRows { get; set; }
    }
}
```

BUT! Original query must have _ResultSetRowNumber column.
Instead of 
`SELECT * FROM STATE ORDER BY NAME`
I need to modify query to 
`SELECT *, ROW_NUMBER() OVER (ORDER BY name) _ResultSetRowNumber FROM STATE`
It's not problem for me, but of course its not a good (universal) solution.
