### ISSUE TITLE
DefaultMapper doesn't use custom converter method?

### ISSUE THREAD

**Issue by dario-l** [schotime/NPoco#327]
Everything works perfectly in 2.10 after upgrading to 3.4.3 - throws **NullReferenceException**.

I have custom mapper which inherits from DefautlMapper:

``` c#
public override Func<object, object> GetFromDbConverter(Type destType, Type sourceType)
{
    return ShouldBeSerialized(destType)
        ? (o => Deserialize(o, destType)) // **this is never invoked**
        : base.GetFromDbConverter(destType, sourceType);
}

private static bool ShouldBeSerialized(Type type)
{
    return typeof(ValueObject).IsAssignableFrom(type);
}
```

Model looks like this:

``` c#
public class Model : ValueObject
{
    public string Name { get; set; }
    public Address MainAddress { get; set; }
}
```

Loading object via SingleInto throws NullReferenceException:

``` c#
   at NPoco.RowMappers.PropertyMapper.MapValue(GroupResult`1 posName, DbDataReader reader, Func`2 converter, Object instance, PocoColumn pocoColumn, Object defaultValue)
   at NPoco.RowMappers.PropertyMapper.<>c__DisplayClass8_2.<BuildMapPlans>b__3(DbDataReader reader, Object instance)
   at NPoco.RowMappers.PropertyMapper.<>c__DisplayClass7_0.<BuildMapPlan>b__1(DbDataReader reader, Object instance)
   at NPoco.RowMappers.PropertyMapper.Map(DbDataReader dataReader, RowMapperContext context)
   at NPoco.MappingFactory.Map(DbDataReader dataReader, Object instance)
   at NPoco.Database.<Read>d__148`1.MoveNext()
   at NPoco.Database.<QueryImp>d__156`1.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at NPoco.Database.SingleInto[T](T instance, String sql, Object[] args)
```

**Comment by schotime** [comment]
What exception was actuay thrown?

**Comment by dario-l** [comment]
Ups. Sorry about that. This is NullReferenceException.

**Comment by schotime** [comment]
Any more information? Line numbers?

**Comment by dario-l** [comment]
NPoco.3.4.3 nuget package doesn't contains any pdb files, so... no line numbers :(

**Comment by schotime** [comment]
I think it could be your MainAddress property. It doesn't ignore these by default anymore.
But if you can create a sample application then I should be able to debug it a bit better.

**Comment by dario-l** [comment]
I checked that my delegate Deserialize is not invoked becouse MainAddress column is NULL but if it is NOT NULL (contains json string {}) Deserialize invokes, returns deserialized intance of Address value object but it throws NullReferenceException anyway.

**Comment by dario-l** [comment]
I try to initialize MainAddress property in constructor and then invoke SingleInto but it doesn't change anything.

**Comment by schotime** [comment]
How is the mapping configured. What happens if you put the Result attribute
on it. Check the sql that is actually run too.

**Comment by dario-l** [comment]
Yeah. First success. Putting Result attribute helps. How to move that behaviour to mapper? I don't want to annotate any props with it where my custom mapper is for.

**Comment by schotime** [comment]
Are these only for querying? or do you insert them also?

**Comment by dario-l** [comment]
Also for inserting/updating:

``` c#
public override Func<object, object> GetToDbConverter(Type destType, MemberInfo sourceMemberInfo)
{
    var sourceType = sourceMemberInfo.GetTheType();

    return ShouldBeSerialized(sourceType)
        ? (o => o == null ? null : Serialize(o))
        : base.GetToDbConverter(destType, sourceType);
}
```

**Comment by dario-l** [comment]
I'm stuck with this and can't go further with my project.

What should I do to fix this? Is it my buggy implementation or maybe version 3.x requires different configuration than 2.x?

**Comment by dario-l** [comment]
@schotime When I add SerializedColumnAttribute instead of ResultAttribute then everything works but then I have this convention in two places.
