### ISSUE TITLE
NPOCO + MySql in .NET Core

### ISSUE THREAD

**Issue by edikep2000** [schotime/NPoco#328]
Hello everyone, 
I learnt that the official MySQL Driver by Oracle does not yet support .NET Core. However, I have seen the following attempts to provide .NET Core Support for MYSQL, 

https://github.com/bgrainger/MySqlConnector
https://github.com/SapientGuardian/mysql-connector-net-netstandard.

However what is the recommended approach towards integrating anyone of these drivers and which of them is recommended

**Comment by schotime** [comment]
What about it? People are using it already.

**Comment by edikep2000** [comment]
Pray, Tell how because I am unable to find out the correct approach

**Comment by eByte23** [comment]
@edikep2000 it should be exactly the same as previously in .NET full framework.
As .netcore does not support the old configFiles and connectionStrings, you will need to supply your connection string. Most standard way of doing this is to put it into the appsettings.json file per environment your running under and retrieve it with

```Configuration.GetConnectionString("Default")```

```
//basic setup
var database =  new Database("connectionStringHere", DatabaseType.MySQL, MySql.Data.MySqlClient.MySqlClientFactory.Instance));
```

```
//use Dependency Injection 
//In Startup ConfigureServices

 services.AddScoped<IDatabase>(x =>
            {
                return new Database(Configuration.GetConnectionString("Default"), DatabaseType.MySQL, MySql.Data.MySqlClient.MySqlClientFactory.Instance));
            });
```
I'll post a sample app shortly implementing this exact example

**Comment by edikep2000** [comment]
That would be very nice. Looking forward to the sample app. Many Thanks

**Comment by eByte23** [comment]
@edikep2000 please see the sample here https://github.com/eByte23/NPoco-Mysql-NetCore-Sample
