### ISSUE TITLE
mapping not working

### ISSUE THREAD

**Issue by hammadabbas** [schotime/NPoco#332]
Hi,

`context.Fetch<opportunity__c>("SELECT * from opportunity__c");` does not map the result set, all the properties of opportunity__c are NULL.

However;
`context.Fetch<Dictionary<string, object>>("SELECT * from opportunity__c");` works and i can access the property by result[0]["somecolumnname"]

Happens only with this table/object and it has ~600 fields

There is no exception or anything in Debug log.

**Comment by schotime** [comment]
Yeh. Gonna need more info than that.
What's the columns of the tables? What properties are on the class you are
mapping to?

**Comment by hammadabbas** [comment]
Hi Adam,

Thank you for your prompt response.

Well, just to test things i downgraded to NPoco 2.10.11 and it seems to work here.

I got the NPoco source as well, will debug and keep you updated on it.

Regards
