### ISSUE TITLE
Using DbFactory to create ConnectionString, but it gets overridden by the original constructor one

### ISSUE THREAD

**Issue by yilativ** [schotime/NPoco#333]
I found that if this was only set when DbFactory had return a connection string that was null that we use the original one set in the constructor: 

https://github.com/schotime/NPoco/blob/master/src/NPoco/Database.cs#L224

Is there a reason why we set the connection string even though a DbFactory was provided?

Thank you!

**Comment by yilativ** [comment]
Hopefully to clarify. I wasn't able to find away to subclass the Database.cs and add my own methods (like more of the FetchMultiple<T1, T2, ... T8>) and also have a delay in passing the ConnectionString, but that would only be known at run time. I was able to see that Database.cs generated the SharedConnection string via factory. So I thought great! This delayed connection string construction is exactly what I needed. 

But it looks like my connection string gets overridden by the line I mentioned [above](https://github.com/schotime/NPoco/blob/master/src/NPoco/Database.cs#L224).

**Comment by schotime** [comment]
Sorry, I'm not sure what you mean in this issue?

**Comment by yilativ** [comment]
I pass in my own DbFactory in the constructor. Inside my own DbFactory, whenever the CreateConnection method is called, I have my own logic to generate the Db Connection which contains the proper connection string. However in this line: 
https://github.com/schotime/NPoco/blob/master/src/NPoco/Database.cs#L224

NPoco overrides with what was passed in originally.
 _sharedConnection.ConnectionString = _connectionString;

My connection string is overridden by the original one that was passed via the constructor. So is there a way to only set that connection string when the _sharedConnection.ConnectionString is null or empty?

**Comment by schotime** [comment]
Sounds like a good pull request

**Comment by yilativ** [comment]
Sweet! I'll give it a shot. Never have before.

**Comment by yilativ** [comment]
Which branch should I be using?

**Comment by schotime** [comment]
master
