### ISSUE TITLE
Is it possible to support .Count or .Any() for nested collections in NPoco? 

### ISSUE THREAD

**Issue by andrei-traktatovich** [schotime/NPoco#334]
example: 
select all collections with NO items 

```
`database.Query<collection>().IncludeMany(x => x.items).Where(p => !p.items.Any())` 
```

currently throws InvalidOperationException "variable p referenced from scope but it is not defined"

and 
    `database.Query<collection>().IncludeMany(x => x.items).Where(p => p.items.Count > 0)`

throws Exception "Did you forget to include the property eg. Include(x => x.items)"

**Comment by schotime** [comment]
You would have to do it on the client side, by calling toenumerable() first.

**Comment by schotime** [comment]
You would have to do it on the client side, by calling toenumerable() first.
