### ISSUE TITLE
DbGeometry not working in Mysql

### ISSUE THREAD

**Issue by RobbieBerghan** [schotime/NPoco#336]
When performing a simple select \* from a table that has a DbGeometry col the following error is returned: 

Error trying to create type System.Data.Entity.Spatial.DbSpatialServices System.InvalidOperationException: Instances of abstract classes cannot be created.\r\n   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)\r\n   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType)\r\n   at NPoco.FastCreate.GetCreateDelegate()

How can I fix this error?

**Comment by pauloanalista** [comment]
I am also having several problems with DbGeometry.

The entity framework support for MySql is not legal.

Someone here has worked with DbGeometry in Mysql with Entity?
