### ISSUE TITLE
Is it possible to support building .UpdateMany<T> where expression including some nest entity?

### ISSUE THREAD

**Issue by hin-longkid** [schotime/NPoco#349]
for example: 
`database.UpdateMany<User>()`
`       .Include(x => x.Department)  //include some nest entity`
`       .Where(x => x.Deparment.Name == "some department")`
`       .Execute(entity);`

then the sql (MySQL) goes:
`UPDATE User u`
`JOIN Department d ON u.departmentid = d.id`
`SET u.somefield = 'some vule'`
`WHERE d.name = 'some department';`

**Comment by schotime** [comment]
Not at this stage. 
Firstly the syntax is different in most databases and secondly I wanna keep it as simple as possible.

**Comment by hin-longkid** [comment]
Hey schotime
Sorry for too late to reply, i just write sql for this situation right now, however, i hope Npoco will offer more ORM features in the furture :), thanks.
