### ISSUE TITLE
NPoco query with Npgsql - Reset() called on connector with state Executing

### ISSUE THREAD

**Issue by andrei-traktatovich** [schotime/NPoco#350]
In our web application, we have configured a SimpleInjector DI container which injects an instance of NPoco Database as a singleton.

When running web app in multi user environment, we occasionally get an exception when executing NPoco query in code such as 

`     _db.Query<TObject>().Where(filterExpression).ToList()`

The exception is:

    System.InvalidOperationException: Reset() called on connector with state Executing\r\n   в Npgsql.NpgsqlConnector.Reset()\r\n   at Npgsql.ConnectorPool.Release(NpgsqlConnector connector)\r\n   at Npgsql.NpgsqlConnection.ReallyClose(Boolean wasBroken)\r\n   at Npgsql.NpgsqlConnection.Close()\r\n   в NPoco.Database.CloseSharedConnection()\r\n   at NPoco.Database.<QueryImp>d__156`1.System.IDisposable.Dispose()\r\n   at NPoco.Database.<QueryImp>d__156`1.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at NPoco.Linq.QueryProvider`1.ToList()\r\n   

Apparently NPoco is trying to close a shared connection while it is still in use.

Any suggestions how this issue can be fixed?

**Comment by schotime** [comment]
NPoco Database should be created once per request. It is not thread safe.
