### ISSUE TITLE
Error in mapping to DTO

### ISSUE THREAD

**Issue by agnerbo** [schotime/NPoco#351]
When having a column named CompanyName and a column named Company_Name the wrong property is populated.

Example
var result= Db.Fetch<CompanyDTO>("select id, companyName, company_name from MyTable")

public class CompanyDTO
{
 public int Id{get;set;}
public string CompanyName {get;set;}
public string Company_Name {get;set;}
}

The property Company_Name is always null and the property CompanyName has been populated with the column Company_name from MyTable.

**Comment by schotime** [comment]
This is an interesting scenario. As far as NPoco is concerned those two columns are the same and both columns will get mapped to CompanyName.

Not really sure what the solution is here other than aliasing one of your columns and changing the name of the property.

**Comment by agnerbo** [comment]
It would be nice I could do 
public class CompanyDTO
{
public int Id{get;set;}
[Column("CompanyName",force=true)]
public string CompanyName {get;set;}
[Column("Company_Name",force=true)]
public string Company_Name {get;set;}
}

And npoco would be force to find an exact match.
