### ISSUE TITLE
One to Many Query Helper - multiple one-to-many relationships

### ISSUE THREAD

**Issue by mboehm** [schotime/NPoco#353]
Good afternoon,

Amazing project!

It says here:
https://github.com/schotime/NPoco/wiki/One-to-Many-Query-Helpers
_5. FetchOneToMany cannot be used to fetch nested one-to-many relationships, or multiple one-to-many relationships. For example, if UserDto also had a list of BoatsDto, only the CarDto list or the BoatsDto list can be loaded and mapped with one query._ 

Once I have mapped a single one to many (i.e. UserDto to CarDto), are there any helpers so that I can then merge in BoatsDto (from a separately populated List<BoatsDto >) to the already populated UserDto, or do I need to do it manually in a loop?

Thanks!

**Comment by schotime** [comment]
A manual loop is required.
