### ISSUE TITLE
Exception while executing script containing variables (@variable1) and cursor (@@FETCH_STATUS)

### ISSUE THREAD

**Issue by Waleed-Iqbal** [schotime/NPoco#356]
I have a lot of scripts that contain variables like `@variable1` and cursors like `@@FETCH_STATUS` and I trying to execute them using NPoco.
I don't want to escape all variables and cursors (like `@@variable1` and `@@@FETCH_STATUS`respectively) in all of my scripts. Does NPoco provide some way to execute such scripts without escaping them?

**Comment by schotime** [comment]
It does not sorry. You could easily write something to wrap around your query to do the escaping before it gets passed to NPoco.
