### ISSUE TITLE
Autogenerated query fails for TEIID database.

### ISSUE THREAD

**Issue by jacekbator** [schotime/NPoco#357]
Hi,
I'm trying to user Npoco to connect to TEIID database. For that it needs PostgreSQL ODBC driver. Configured it but it works only if I write full query myself. If NPOCO produces select arguments it fails because select columns are enclosed in square brackets ex. SELECT [sample_id] AS [sample_id] FROM ......
TEIID throws parsing error on first bracket.
Is there a way I could influence query generation to skip enclosing columns in brackets?

Regards
Jacek

**Comment by schotime** [comment]
Make sure you use the Postgresql database type and it will enclose them in quotes.

```
var db = new Database(..., DatabaseType.PostgreSQL)
```
