### ISSUE TITLE
Current state of SQLite support?

### ISSUE THREAD

**Issue by rhegner** [schotime/NPoco#359]
What is the current state of SQLite support of NPoco? I wanted to change the underlying database from MySQL to SQLite and I ran into the following problems:

**Isolation Level:**
The default isolation level for SQLite seems to be `ReadCommitted`. But when I want to create a transaction I get a `System.ArgumentException` saying "The IsolationLevel 'ReadCommitted' is invalid.". Here is the relevant part of the stack trace:

    at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel, Int32 commandTimeout)
    at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel)
    at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)
    at NPoco.Database.GetTransaction()

When I manually set the isolation level to `Serializable`, I can create a transaction.

**InvalidCastException**
When I do a `FetchAsync` I get a `System.InvalidCastException` exception saying "Object must implement IConvertible." with the following stack trace:

    at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
    at NPoco.RowMappers.PropertyMapper.MapValue(GroupResult`1 posName, Object[] values, Func`2 converter, Object instance, PocoColumn pocoColumn, Object defaultValue)
    at NPoco.RowMappers.PropertyMapper.<>c__DisplayClass8_2.<BuildMapPlans>b__3(DbDataReader reader, Object[] values, Object instance)
    at NPoco.RowMappers.PropertyMapper.<>c__DisplayClass7_0.<BuildMapPlan>b__1(DbDataReader reader, Object[] values, Object instance)
    at NPoco.RowMappers.PropertyMapper.Map(DbDataReader dataReader, RowMapperContext context)
    at NPoco.MappingFactory.Map(DbDataReader dataReader, Object instance)
    at NPoco.Database.<Read>d__137`1.MoveNext()
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    at NPoco.Database.<FetchAsync>d__19`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---

**Setup**
I'm working on an application targeting version 1.1 of .Net Core (.Net Standard 1.6.1). I'm using the following Nuget packages:

- NPoco 3.4.8
- Microsoft.Data.Sqlite 1.0.0, which references SQLite 3.12.2

**Comment by rhegner** [comment]
I just noticed that there are newer versions of Microsoft.Data.Sqlite available, but I cannot install them for some reason (see [this issue](https://github.com/aspnet/Microsoft.Data.Sqlite/issues/310)).

I could imagine that the problems described above are because I'm using a very early version of Microsoft.Data.Sqlite, and are not related to NPoco at all.

**Comment by rhegner** [comment]
I finally managed to install the newer versions of Microsoft.Data.Sqlite. I have the same problems with version 1.1.0 and with the preview of 1.2.0.

**Comment by rhegner** [comment]
I created a short self-contained example which allows to reproduce both of these problems. Just create a new Console Application (.NET Core) containing the following code:

	using System;
	using Microsoft.Data.Sqlite;
	using NPoco;
	using System.Data;

	namespace SQLiteTest
	{

		[TableName("TestTable")]
		[PrimaryKey("TestPocoId", AutoIncrement = false)]
		public class TestPoco
		{
			public Guid TestPocoId { get; set; }
		}

		public class Program
		{
			public static void Main(string[] args)
			{
				const string ConnectionString = "Data Source=Test.db";

				// set up database

				using (var connection = SqliteFactory.Instance.CreateConnection())
				using (var command = SqliteFactory.Instance.CreateCommand())
				{
					connection.ConnectionString = ConnectionString;
					connection.Open();
					command.Connection = connection;
					command.CommandText = "CREATE TABLE IF NOT EXISTS TestTable (TestPocoId char(36) NOT NULL PRIMARY KEY)";
					command.ExecuteNonQuery();
				}

				// test with NPoco

				using (var database = new Database(ConnectionString, null, SqliteFactory.Instance))                                 // this is how I create it in my real application
				//using (var database = new Database(ConnectionString, null, SqliteFactory.Instance, IsolationLevel.Serializable))    // this is how transactions work
				{
					using (var transaction = database.GetTransaction())
					{
						database.Insert(new TestPoco() { TestPocoId = Guid.NewGuid() });
						transaction.Complete();
					}

					// this doesn't work
					var data = database.Fetch<TestPoco>();
				}

			}
		}
	}

My project.json looks like this:

	{
	  "version": "1.0.0-*",
	  "buildOptions": {
		"emitEntryPoint": true
	  },

	  "dependencies": {
		"Microsoft.Data.Sqlite": "1.1.0",
		"Microsoft.NETCore.App": {
		  "type": "platform",
		  "version": "1.0.1"
		},
		"NPoco": "3.4.8"
	  },

	  "frameworks": {
		"netcoreapp1.0": {
		  "imports": "dnxcore50"
		}
	  }
	}

**Comment by nhaberl** [comment]
Why you don't use https://system.data.sqlite.org/index.html/doc/trunk/www/index.wiki ?

**Comment by rhegner** [comment]
@nhaberl thanks for your input.

I realized only a couple of days ago that both System.Data.SQLite and Microsoft.Data.Sqlite exist.

System.Data.SQLite is older and it seems to be the one that is supported by NPoco, but it does not seem to support .Net Core.

I'm working on a cross-platform .Net Core project, that's why I can't use System.Data.SQLite.

**Comment by nhaberl** [comment]
Absolutely right, that's why Microsoft implemented it :-)
So let's see if there are any plans to NPoco to support .NET Core officially.

**Comment by schotime** [comment]
@nhaberl .NET Core has been supported since 3.0.

**Comment by schotime** [comment]
yeah....if you can't get a first implementation done then we can have a look at the Guid problem.

**Comment by rhegner** [comment]
I just created a pull request (which does not solve the Guid problem).
See also these relevant issues of Microsoft.Data.Sqlite:
https://github.com/aspnet/Microsoft.Data.Sqlite/issues/191
https://github.com/aspnet/Microsoft.Data.Sqlite/issues/214

**Comment by rhegner** [comment]
I was able to solve the Guid problem using a custom mapper like this:

    class CustomMapper : DefaultMapper
    {
        public override Func<object, object> GetFromDbConverter(Type destType, Type sourceType)
        {
            if (destType == typeof(Guid) && sourceType == typeof(byte[]))
                return (value) => new Guid((byte[])value);
            return base.GetFromDbConverter(destType, sourceType);
        }
    }

It's kind of strange that the Guid comes as a byte[16] value from the DB, even though the column was defined as CHAR(36).....

Not directly related to this issue, but I also noticed some problems with Guids when working with MySQL: When the Guid is stored in a CHAR(36) column it works fine with MySQL, but if it is stored as a VARCHAR(40) I need the following custom mapper to make it work:

    class CustomMapper : DefaultMapper
    {
        public override Func<object, object> GetFromDbConverter(Type destType, Type sourceType)
        {
            if (destType == typeof(Guid) && sourceType == typeof(string))
                return (value) => Guid.Parse((string)value);
            return base.GetFromDbConverter(destType, sourceType);
        }
    }
