### ISSUE TITLE
Snapshotting question

### ISSUE THREAD

**Issue by plsft** [schotime/NPoco#362]
Great work adding so much flexibility and functionality to NPoco @schotime. I'm an original PetaPoco user and have customized the Database.cs class heavily for my projects for over 3 years now. As I just started new project work, I began adding Async support to my version of PetaPoco and recalled having seen your NPoco and took a look. Very impressed with all the work! 

One challenge early on that I ran into with PetaPoco was partial updating of data. I've reviewed the wiki and if I understand this correctly, the procedure for partially updating an object (i.e. not updating actual data with NULLs) is to use the Snapshot class, pass that to the update and NPoco will compare the snapshot to the partial object and then only update those fields. 

While I can see other uses for the Snapshot feature, IMO this is a lot of overhead. I've cloned the repo and implemented the same custom solution I used for the original PetaPoco. Basically, I created a new column-attribute called "UpdateIfNullColumn." 

In the Database.UpdateImp<T> method, I added a conditional that checks the value of the property. If null and the UpdateIfNull flag is set, I allow that column to be added to the UPDATE statement, otherwise I just continue thereby skipping the UPDATE statement and the column won't be touched. 

Its a simple and subtle way to handle the partial update without a Snapshot. I'd be curious to hear your thoughts. Am I missing some easier way to do this?

**Comment by schotime** [comment]
There is a method called `UpdateMany<>` which can be used like so.

```cs
_database.Advanced.UpdateMany<UserSession>()
     .OnlyFields(x => x.LastSeen)
     .Where(x => x.UserId == userid)
     .Execute(new UserSession { LastSeen = _clock.UtcNow });
```

This is how we update particular columns without the snapshot which may help you
