### ISSUE TITLE
Using NPoco.SqlAzure with the DatabaseFactory

### ISSUE THREAD

**Issue by TomSteer** [schotime/NPoco#367]
Hey,

Is there a way to use the NPoco.SqlAzure package by davidsavagejr with the DatabaseFactory and fluent mappings in npoco? 

From what I can tell this isn't possible due the fact the DatabaseFactory is tightly coupled with the npoco Database implementation rather than just IDatabase. So you aren't able to do the following:

```
DbFactory = NPoco.DatabaseFactory.Config(x =>
            {
                x.UsingDatabase(() => new SqlAzureDatabase(connectionString));
                x.WithFluentConfig(fluentConfig);
            });
```

Cheers, 

Tom

**Comment by schotime** [comment]
I'll have a look and see if it can use IDatabase instead

**Comment by schotime** [comment]
Uses IDatabase in the latest.
