### ISSUE TITLE
Configuration Option - VARCHAR/NVARCHAR

### ISSUE THREAD

**Issue by tbasallo** [schotime/NPoco#368]
I just migrated a rather large project from PetaPoco to NPoco . Then I quickly remembered (when all the errors starting coming in) that I had changed PetPoco to use VARCHAR instead of NVARCHAR by default since all columns were VARCHAR . Otherwise, indexes are not used and we have a bad situation.

I am working on a fork to do the same in NPoco for my project. Would there be interest to include in NPoco an option to use VARCHAR instead of NVARCHAR for all strings as a flag or configuration option?

I think it's definitely a handy option for those projects that use varchar exclusively.

**Comment by hhmultimediallc** [comment]
I think as long as the default is NVARCHAR that'd be cool.

**Comment by tbasallo** [comment]
I agree, I would not want to change the expected behavior.

Ideally, it would either be a property on Database or a constructor option that would configure a flag to use VARCHAR instead of NVARCHAR for that Database instance.

**Comment by schotime** [comment]
You can override the type by creating your own database type instance like so.

```cs
    public class MySqlServerDbType : SqlServer2012DatabaseType
    {
        public MySqlServerDbType()
        {
            AddTypeMap(typeof(string), DbType.AnsiString);
        }
    }
```

Then pass this instance into the constructor of `Database` when you new it up.

**Comment by tbasallo** [comment]
This is perfect. I didn't see this in the docs, guess I need to search better :)

Thanks
