### ISSUE TITLE
Benchmark about NPoco

### ISSUE THREAD

**Issue by Sunzhuokai** [schotime/NPoco#369]
Benchmark from https://github.com/InfoTechBridge/OrmBenchmark
why the performance is poor when I test select and map a row to a  poco object?
![Code](http://p1.bpimg.com/567571/e69cd369de826e60.png)
![Benchmark](http://i1.piimg.com/567571/c0a79ee8fd3b1a42.png)

**Comment by schotime** [comment]
It won't be as fast on a single run because it no longer caches on a per query basis but only for multiple rows, but it compares on my tests.

https://twitter.com/schotime/status/801246756981719040
