### ISSUE TITLE
Problem with Dates below year 1753 (mssql)

### ISSUE THREAD

**Issue by huanacaraz** [schotime/NPoco#370]
There is missing DateTime2 support. I cant insert row with date less then 1753-1-1 because of NPoco creates parameter with dbtype DateTime. Probably you should change it by default to DateTime2 db type? at least for mssql database version 2008+.
Or Im missing something?

(DateTime2 should work for any column - tested with code:)
var cmd = conn.CreateCommand();
cmd.Transaction = tran;
cmd.CommandText = "INSERT INTO test (date1, date2, date3, date4, date5) values (@0, @0, @0, @0, @0)";
var p = cmd.CreateParameter();
p.ParameterName = "@0";
p.DbType = DbType.DateTime2;
p.Value = DateTime.Now; //new DateTime(1500, 1, 1); - to use this value, you cant insert to cols 2 and 3...
cmd.Parameters.Add(p);
cmd.ExecuteNonQuery();

Where table definition was:
CREATE TABLE [dbo].[test](
	[date1] [date] NULL,
	[date2] [smalldatetime] NULL,
	[date3] [datetime] NULL,
	[date4] [datetime2](0) NULL,
	[date5] [datetime2](3) NULL
)

when you try with npoco, it raises exception.. test code:
class test
{
	public DateTime? date1 { get; set; }
	public DateTime? date2 { get; set; }
	public DateTime? date3 { get; set; }
	public DateTime? date4 { get; set; }
	public DateTime? date5 { get; set; }
}

db.Insert(row);

**Comment by schotime** [comment]
Hmmm...i'm sure we have datetime2, but maybe we don't because of this issue. You can override it like so.

```cs
    public class MySqlServerDbType : SqlServer2012DatabaseType
    {
        public MySqlServerDbType()
        {
            AddTypeMap(typeof(DateTime), DbType.DateTime2);
        }
    }
```
Then pass this instance into the constructor when you create your `Database` instance.

**Comment by huanacaraz** [comment]
Thanks for code, because my temporary solution was to insert the value as string :)

**Comment by schotime** [comment]
Let me know how it goes.

**Comment by huanacaraz** [comment]
yes, your code works. Im using one static instance of the type, is it ok? (in your code you are using Singleton<>)

**Comment by schotime** [comment]
Yeh that's fine.
