### ISSUE TITLE
SELECT @@IDENTITY ->SELECT @IDENTITY

### ISSUE THREAD

**Issue by zhaoyingju** [schotime/NPoco#371]
===code
string sqlStr = "INSERT INTO TK_ContextQuestions(ContextContent,ContextTitle,PaperId,CreateDate,OrderNum) VALUES(@ContextContent,@ContextTitle,@PaperId,@CreateDate,@OrderNum) SELECT @@IDENTITY";  
            return DB.ExecuteScalar<int>(sqlStr, tKContextQuestionsEntity);
===code
"SELECT @@IDENTITY"  was replaced "SELECT @IDENTITY" when runing code.why has words "sql=sql.Replace('@@','@')"  in the method 'CreateCommand' of the file 'Database.cs'

**Comment by schotime** [comment]
You need to encode @ symbols so use select @@@identity

**Comment by zhaoyingju** [comment]
@schotime thanks,but why replaced,if so,i will modify all exists sql  ,because  i use Npoco instead of sqlHelper。

**Comment by schotime** [comment]
Otherwise it assumes they are parameters.
