### ISSUE TITLE
in sql has  greater than 2 the same Named parameter error

### ISSUE THREAD

**Issue by zhaoyingju** [schotime/NPoco#372]
==code
select * from T where p=@p and p1=@p
==code

the above sql will replace to ' select * from T where p=@0 and p1=@1' ,then no result

**Comment by schotime** [comment]
did you pass `new { p = "Value" }` as the first parameter?

**Comment by zhaoyingju** [comment]
@schotime  yes

**Comment by zhaoyingju** [comment]
@schotime it's error when pass new { p = "Value" } or a class instance such as  new Class(){p="Value"}

**Comment by schotime** [comment]
What error? You aren't really giving me much information.

**Comment by zhaoyingju** [comment]
@schotime  I 'm very sorry,It has error in  my data of database.
