### ISSUE TITLE
ResultColumnAttribute is sometimes randomly silently ignored if a ColumnAttribute also exists

### ISSUE THREAD

**Issue by petsuter** [schotime/NPoco#376]
I had a property that is annotated with both a `ColumnAttribute` and a `ResultColumnAttribute`:

    [Column("timestamp_utc")]
    [ResultColumn]
    public DateTime? TimestampUtc { get; set; }

This worked fine, until some totally unrelated change caused it to stop working.

It turns out that:

* NPoco only uses the ["first"](https://github.com/schotime/NPoco/blob/rel-3.4.0/src/NPoco/ColumnInfo.cs#L80) `ColumnAttribute`
* and `ResultColumnAttribute` is also a `ColumnAttribute`
* and the order of attributes is not defined and can change for totally unrelated reasons.

I guess the fix is that I should merge the two attributes:

    [ResultColumn("timestamp_utc")]
    public DateTime? TimestampUtc { get; set; }

Right?

You might still consider somehow warning the user about multiple attributes which get just ignored randomly. That would be very helpful and safe someone a lot of debugging time.

**Comment by schotime** [comment]
That is correct. 
Not sure how to warn the user. Its a tough one.
Ideas?

**Comment by petsuter** [comment]
Thanks for the confirmation.

Ideas:

* The simplest approach seems changing `var colattr = colAttrs.First();` to `var colattr = colAttrs.Single();`, so an `InvalidOperationException` is raised if multiple `ColumnAttribute` are present.
* Nicer would be to throwing the exception explicitly to include an explanatory message.
* If you don't like exceptions, I guess writing the warning to `Debug.WriteLine` is an alternative?
* Alternatively (or additionally?) just mention it in the documentation: https://github.com/schotime/NPoco/wiki/Mapping
* (Even nicer would have been if there was a way to make the `AttributeUsage.AllowMultiple = false` metadata turn this into a compile-time check, but apparently that's not possible for subclasses attributes.)

**Comment by schotime** [comment]
What about this logic?

```
var resultAttr = colAttrs.OfType<ResultColumnAttribute>().FirstOrDefault();
var versionAttr = colAttrs.OfType<VersionColumnAttribute>().FirstOrDefault();
var computedAttr = colAttrs.OfType<ComputedColumnAttribute>().FirstOrDefault();

ci.ColumnName = colAttrs.FirstOrDefault(x => !string.IsNullOrEmpty(x.Name))?.Name ?? mi.Name;
ci.ForceToUtc = colAttrs.Select(x => x.ForceToUtc).Aggregate((x, y) => x && y);
ci.ResultColumn = resultAttr != null;
ci.VersionColumn = versionAttr != null;
ci.VersionColumnType = versionAttr?.VersionColumnType ?? ci.VersionColumnType;
ci.ComputedColumn = computedAttr != null;
ci.ComputedColumnType = computedAttr?.ComputedColumnType ?? ComputedColumnType.Always;
```

**Comment by petsuter** [comment]
Ah, so instead of warning you would try to "make it work"?
But `ResultColumn`, `VersionColumn` and `ComputedColumn` would still be mutually exclusive?
Sounds good.

    ci.ForceToUtc = colAttrs.Select(x => x.ForceToUtc).Aggregate((x, y) => x && y);

Using `&&` here would mean all the attributes must specify `ForceToUtc = true`, right? Wouldn't `||` make more sense? Or just `colAttrs.Any(x => x.ForceToUtc)`.

**Comment by schotime** [comment]
Yeah I thought about `Any` however, its defaulted to true so if you do set one of them explicitly to false then it should be false was my reasoning here? Makes sense?

**Comment by petsuter** [comment]
Ah, makes sense yes. For some reason I assumed `ForceToUtc` was false by default. How about `colAttrs.All(x => x.ForceToUtc)` then?

**Comment by schotime** [comment]
That's exactly what I have with aggregate.

**Comment by schotime** [comment]
Nuget 3.6.0
