### ISSUE TITLE
missing csproj files

### ISSUE THREAD

**Issue by BackInAction** [schotime/NPoco#378]
It looks like you switched to csproj files but I don't see them in the repo.

NOTE:  I cloned the work space so I can try to figure out why XXXAsync doesn't seem to be working (it is synchronous not asynchronous) with MySQL (or at least our setup of MySQL).

**Comment by schotime** [comment]
Good find. Whoops.
Committed.

**Comment by BackInAction** [comment]
Now when I open the solution in VS 2015, it still won't load.  So, I dropped the NPoco project and re-added the project file.  When I re-add it I get pop-up that reads...

The default XML namespace of the project must be MSBuild XML namespace.  If the project is authored in MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element.  if the project has been authored in the old 1.0 or 1.2 format, please convert to MSBuild 2003 format.

Do I need to use VS 2017?

**Comment by schotime** [comment]
Yes. The new msbuild is only supported by vs2017.

**Comment by BackInAction** [comment]
Got, thanks.
