### ISSUE TITLE
how to use update method?

### ISSUE THREAD

**Issue by newyhj** [schotime/NPoco#379]
method: public int Update<T>(T poco, Expression<Func<T, object>> fields)

how to use?have a demo?

public class article{
 public int id{get;set;}
 public string name{get;set;}
 ...
 public int view{get;set;}
}
exclude view field,others field need update,Have a quick way?

**Comment by schotime** [comment]
```
Update(new article { .... }, x => new { x.id, x.name })
```

**Comment by newyhj** [comment]
thank you very much
