### ISSUE TITLE
How can I get table name from Model

### ISSUE THREAD

**Issue by mojinxun** [schotime/NPoco#381]
I want get table name by Entity, Can I?

**Comment by pa-kos** [comment]
Please make an effort to solve such easy questions yourself: [Retrieving Information Stored in Attributes ](https://msdn.microsoft.com/en-us/library/71s1zwct(v=vs.110).aspx)  
`string tableName = ((TableNameAttribute)typeof(T).GetCustomAttributes(typeof(TableNameAttribute), true)[0]).Value;`  
But note it`s using reflection.
Please close this issue.

**Comment by schotime** [comment]
`db.PocoDataFactory.ForType(typeof(Model)).TableInfo.TableName` or something very similar

**Comment by mojinxun** [comment]
Thank you

**Comment by k-yaobo** [comment]
How to Sharding MYSQL Table;
my table like , table_2017, table_2018, ....
How can I set a new table name from Model
