### ISSUE TITLE
How to paging with Query<T> and ProjectTo

### ISSUE THREAD

**Issue by enrico-padovani** [schotime/NPoco#382]
Hi,

I see there is a Limit method in order to get a particular page on IQueryProvider<T> but it has no page result. There is also a ToPage method that you can call on IQueryResultProvider<T>. I was looking if there is a way to combine ToPage and ProjectTo.

Something like:

```
database.Query<MyClass>()
        .Include(p => p.RelatedObject)
        .ProjectTo(p => new MyNewClass
        {
            Field1 = p.Field1,
            Field2 = p.RelatedObject.Field2
        })
        .ToPage(2, 10);
```

**Comment by hin-longkid** [comment]
I met the same problem, and so i make a tittle modification on interface `Page<T> ToPage(int page, int pageSize, Func<IQueryProvider<T>, List<T>> itemsFunc = null)`
and the implement below
```cs
public Page<T> ToPage(int page, int pageSize, Func<IQueryProvider<T>, List<T>> itemFunc = null)
{
    return ToPage(page, pageSize, (paged, action) =>
    {   
        var list = itemFunc == null ? ToList() : itemFunc(this);
        action(paged, list);
        return paged;
    });
}
```
and use below
```cs
database.Query<MyClass>()
    .Include(p => p.RelatedObject)
    .ToPage(2, 10, query => query.ProjectTo(p => new MyNewClass
    {
        Field1 = p.Field1,
        Field2 = p.RelatedObject.Field2
    });
```
btw, i don't think my implement is good, i just expose the page items getting func, i also hope @schotime will improve it :)

**Comment by jcspader** [comment]
+1
