### ISSUE TITLE
Database & Schema

### ISSUE THREAD

**Issue by tbasallo** [schotime/NPoco#387]
I am working on a project that has a SQL Server with a lot of databases and schemas. In the past, I have either created config entries where the desired database was the default, executed a USE statement or used a fully qualified name - FROM misc.sales.Items 

Is there a way, like we do with TableName attribute, to add the database and schema to the query, to make this easier and less tedious? Something like:

```
[Database("misc"), Schema("sales"), TableName("Items")]
public class SalesItem{ ...  }
```
Which woud allow me to still do **.Fetch<SalesItem>("WHERE...")**

Or is it there already and I can't seem to find it in the docs anywhere.

**Comment by schotime** [comment]
If you output the full thing in the table name it shoukd work. Eg. 

`[TableName("[sales.items]"]`

**Comment by tbasallo** [comment]
That worked.
