### ISSUE TITLE
ComplexMapping Prefix is overwritten/ignored in combination with FluentMappingConfiguration.Scan

### ISSUE THREAD

**Issue by jmc-comitas** [schotime/NPoco#388]
I've tested this as many ways as I can figure and even now have the source code, but haven't been able to track down the exact problem. When using FluentMappingConfiguration.Scan, the prefix given for ComplexMapping is ignored and it always uses the default of the property name.

**When using a prefix with ComplexMapping**:
- If a type contains a ComplexMapping attribute and it is provided to the scanner, the resulting prefix is always the default (property name).
- If a type does not contain a ComplexMapping attribute and it is provided to the scanner with a fluent mapping override containing ComplexMapping() for the appropriate property, the resulting prefix is always the default (property name).

The only way it seems to work when using FluentMappingConfiguration.Scan is when using the ComplexMapping attribute (with prefix) and not giving the type to the scanner. In that case the prefix is not overwritten.

It can be duplicated in the NPoco tests project using the User object:

        public class FluentMappingOverrides : Mappings
        {
            public FluentMappingOverrides()
            {
                For<User>().Columns(x =>
                {
                    x.Column(y => y.Address).ComplexMapping("CM");
                });
            }
        }

        [Fact]
        public void NestedClassShouldBeMappedAsAComplexObject()
        {
            var dbFactory = new DatabaseFactory();
            var config = FluentMappingConfiguration.Scan(s =>
            {
                s.Assembly(typeof(User).GetTypeInfo().Assembly);
                s.IncludeTypes(t => t == typeof(User));
                s.Columns.ComplexPropertiesWhere(y => ColumnInfo.FromMemberInfo(y).ComplexMapping);
                s.OverrideMappingsWith(new FluentMappingOverrides());
            });
            dbFactory.Config().WithFluentConfig(config);

            var pocoData = dbFactory.GetPocoDataFactory().ForType(typeof(User));

            Assert.Equal(true, pocoData.Columns.ContainsKey("CM__Street"));
        }
`

**Comment by schotime** [comment]
Nuget 3.6.0
