### ISSUE TITLE
UpdateMany() and multiple columns

### ISSUE THREAD

**Issue by mdawson67** [schotime/NPoco#390]
Is there a way to bulk update multiple columns. I thought UpdateMany() was my answer, but it seems not after trying variations of the following including chaining OnlyFields().  Can this be a accomplished via UpdateMany(), or perhaps some other way?  

var db = _dbfactory.GetDatabase();
var updater = new UpdateQueryProvider<Record>(db);
updater.OnlyFields(r => r.SomeField);
updater.OnlyFields(r => r.AnotherField);
updater.OnlyFields(r => r.AThirdField);  // only this field gets updated

foreach (var record in records) updater.Execute(record);

**Comment by schotime** [comment]
Onlyfields takes multiple lambda expressions.

**Comment by mdawson67** [comment]
Thanks.  It seems UpdateMany() is for applying to all records a set of values from a single Execute(poco).  While I do have a use for that, I may be looking at the wrong feature.  I need to efficiently batch update the table from a list of updated pocos.  Something like a batch version of Database.Update(), like db.Update(records, cols) or db.Update<T>(records, cols).  Is there a way to do this sort of batch updating with NPoco?

**Comment by schotime** [comment]
If they need to be individual values then not really. Just use a foreach and call update.

**Comment by mdawson67** [comment]
Thanks.  I'm calling Update on tens of thousands of records at times so I'm looking for ways to speed this up.  

I'd like to request a Batch Update feature, similar to Batch Insert.  This is assuming update statements can be joined together in a similar manner.  Something like db.UpdateBatch(pocos, cols) would be awesome.

**Comment by aalex675** [comment]
Just wanted to bump this issue, @schotime you commented and said that OnlyFields takes multiple lambda expressions, but the method signature only takes one. Is this something that was changed?

**Comment by schotime** [comment]
```
.OnlyFields(x => new { x.Field1, x.Field2 })
```

**Comment by themagnet** [comment]
Hi,

I just started using NPoco and like it as an alternative to EFCore and others.

What about the implementation of BulkUpdate suggested in https://stackoverflow.com/questions/6595105/bulk-insert-update-with-petapoco ?

A simple test use of that BulkUpdate in my project did the job.

**Comment by schotime** [comment]
This already exists.

https://github.com/schotime/NPoco/blob/master/test/NPoco.Tests/DecoratedTests/CRUDTests/UpdateTests.cs#L161-L173
