### ISSUE TITLE
IDatabase interface returns DbCommand instead of IDbCommand

### ISSUE THREAD

**Issue by slaneyrw** [schotime/NPoco#391]
To assist in mocking IDatabase can you please return IDbCommand from the CreateCommnd functions.

Would also be nice if you could take a dependency on IDbConnection instead of DbConnection as well.
AddParameter would also need fixing

**Comment by schotime** [comment]
To support the .NETStandard 1.3 the interfaces cannot be used. Mocking the abstract classes is just as easy as the interfaces with a decent mock library.
