### ISSUE TITLE
WHERE ... IN query with array parameter

### ISSUE THREAD

**Issue by rhegner** [schotime/NPoco#393]
I try to do the following with NPoco 3.5.1

    query = query.Where("EXISTS (SELECT * FROM device_tag WHERE device_tag.device_id = D.device_id AND device_tag.tag_name IN (@0))", tagFilters);

where `tagFilters` is a string array.

This doesn't work as expected. NPoco uses only the first array element in the `IN` clause.

So if `tagFilters` is `[ "tag1", "tag2" ]` the resulting query looks like this:

    SELECT ...
    FROM `device` `D` 
    WHERE EXISTS (SELECT * FROM device_tag WHERE device_tag.device_id = D.device_id AND device_tag.tag_name IN (@0)) 
    ORDER BY `DeviceId` ASC
    LIMIT @1 OFFSET @2
    	 -> @0 [String] = "tag1"
    	 -> @1 [Int64] = "100"
    	 -> @2 [Int64] = "0"

How can I pass a string array with all its elements to the `IN` clause?

**Comment by schotime** [comment]
Don't make it an array. Try a list otherwise it uses the params overload. Or pass in an array of arrays.

**Comment by rhegner** [comment]
That helped! Thanks a lot!

**Comment by enkelmedia** [comment]
This one is quite strange, don't see why this "smartness" is going on inside the Sql-class?

Reg. the solution, I've tried passing a list but this does not work for me, how did you solve this @rhegner ?

Cheers!
