### ISSUE TITLE
Question on DI setup, lifecycle, scope

### ISSUE THREAD

**Issue by jsodeman** [schotime/NPoco#394]
I'm setting up NPoco for dependency injection on a Web API + MVC 5 project (using StructureMap) and I'm not sure what the best practice is for managing the database connection.  Should I use a singleton, or a per-request scope, something else? The database isn't really being used by the API/MVC controllers themselves, instead it is ultimately being injected into CQRS handlers using Mediatr.

Currently I'm using a setup class
```
public static class DbFactory
{
    public static DatabaseFactory Factory { get; set; }

    public static void Setup()
    {
        Factory = DatabaseFactory.Config(x =>
        {
            x.UsingDatabase(() => new Database("con"));
            //x.WithFluentConfig(fluentConfig);
            //x.WithMapper(new Mapper());
        });
    }
}
```
which is configured with StrucureMap like this
```
// called from global.asax
    
DbFactory.Setup();

var container = new Container(cfg =>
{
    // ... other stuff
    
    cfg.For<IDatabase>().Use(() => DbFactory.Factory.GetDatabase());
});
```

**Comment by schotime** [comment]
One `Database` per request is the recommended.
