### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by enrico-padovani** [schotime/NPoco#395]
Hi Adam,

I see that the releases on github are not aligned with nuget. In particular, It would be really nice just to have a brief summary of what is included in the new releases in terms of bug fixing, features and breaking changes. In that way people can update safely.

Thanks

**Comment by schotime** [comment]
Sure.
It follows semantic versioning in terms of function breaking changes requiring a major version.
Release notes have always been available here.

https://github.com/schotime/NPoco/wiki/Release-Notes

**Comment by enrico-padovani** [comment]
Ok, thanks for the explaination. I didn't find the release note in the wiki at the first look. I think it deserves a better positioning. Maybe just above home link?
