### ISSUE TITLE
Stored procedure helpers

### ISSUE THREAD

**Issue by enrico-padovani** [schotime/NPoco#396]
Hi,

I'm currently using [this](https://github.com/Workshop2/NPoco.StoredProcedures) implementetion in order to call sp nicely.

Do you think something like this would be helpful to include in the NPoco core?

Thanks,
Enrico

**Comment by schotime** [comment]
I would use this overload

`int Execute(string sql, CommandType commandType, params object[] args);`

where you can specify the command type.

```
db.Execute("mysp", CommandType.StoredProcedure);
```

Don't have a fetch overload, but that can be done at some point.

**Comment by dheijl** [comment]
You can fetch a resultset from a stored procedure too using the "exec" work-around in Sql Server:

      var p1 = "somevalue%";
      var result = db.Query<SomeType>("exec SomeProc @param1", new { param1 = p1 });
 
Works for Query() and Fetch().

But it might have a small performance penalty vs using the CommandType StoredProcedure.

**Comment by enrico-padovani** [comment]
What if you have to read multiple resultset from the sp?

**Comment by schotime** [comment]
`FetchMultiple` should work, but its not something we endeavor to support.

**Comment by enrico-padovani** [comment]
I've used FetchAsync this way like @dheijl suggested:

```
var p0 = "test";
var result = await database.FetchAsync<MyType>(@"EXEC myProc @0", p0);
```

Pagination could be done inside the procedure or in memory in case of small set o data, so I'm good with it.

In case I need more result I'll let you know how I ended up!

Thanks
