### ISSUE TITLE
Question:About Page Method Join Query!

### ISSUE THREAD

**Issue by newyhj** [schotime/NPoco#398]
class code:
public class Product : Entity
    {
        .....
        [ResultColumn]
        public List<ProductAttribute> AttributeList { get; set; }
    }
_repository.DbContext.Page<Product>(20,1,"select a.*,b.* from product a left join productattribute b on a.id=b.productid")
I want to populate the data with the fetchonmany method and implement the paging.How do I operate?

**Comment by schotime** [comment]
With care.....

This is not something that is supported automatically.
