### ISSUE TITLE
Insert Poco with UUID as PK erroring

### ISSUE THREAD

**Issue by grofit** [schotime/NPoco#399]
I hope this is just me being an idiot but I have a poco like so:

```
[TableName("sometable")]
[PrimaryKey("id")]
public class SomePoco
{
	[Column("id")]
	public Guid Id { get; set; }

	[Column("version")]
	public int Version { get; set; }

	[Column("createdDate")]
	public DateTime CreatedDate { get; set; }

	// .. other fields
}
```

It is populated like so:

```
 var someInstance = new SomePoco
{
	 Id = Guid.NewGuid(), // Setting ID manually as I read you need to do this with UUID fields
	 CreatedDate = DateTime.Now,
	 Version = 1
};
```

Then I insert it like so:

```
myIDatabaseInstance.Insert(someInstance);
```

And I get the error:

```
"ExceptionMessage": "Cannot insert the value NULL into column 'id', table 'something.dbo.sometable'; column does not allow nulls. INSERT fails.\r\nThe statement has been terminated.",
```

The odd thing is in the debugger I can see the `Id` property in the instance has a value, so am I doing something wrong here?

**Comment by schotime** [comment]
You need to put autoincrement=false on the primary key attribute.

**Comment by grofit** [comment]
ah ok thanks will give that a try.

**Comment by grofit** [comment]
Huzzah works, is this documented anywhere as I couldnt find anything related to this, and a quick "gotcha" or something somewhere would be super helpful.

Thanks for quick response.
