### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jpbertles** [schotime/NPoco#40]
Please add licensing information to this project. Based on your nuget package, it's APL2, but you should have a license file in your repo.

**Comment by nathan-alden** [comment]
@schotime Was this ever done? I don't see a `LICENSE` file in the repository. I may want to use NPoco here at work but they won't even consider it if there is no license.

**Comment by ryanvgates** [comment]
@schotime What is the license for NPoco?

**Comment by schotime** [comment]
It's on nuget and in repo. 
Press t then type licence.
Anyways, its Apache 2.

**Comment by ryanvgates** [comment]
@schotime Thank you for replying. Here's the link for anyone else looking https://github.com/schotime/NPoco/blob/master/src/NPoco/License.txt
