### ISSUE TITLE
Distinct Async

### ISSUE THREAD

**Issue by enrico-padovani** [schotime/NPoco#400]
Hi,

I'm trying to retrieve distinct data in async way, but I cannot find the right combination of methods to use.

Here is what is allowed with non async:

```
response.Result = database.Query<MyType>()
    .Where(p => p.Prop1.Contains("test"))
    .OrderBy(p => p.Prop1)
    .Limit(10)
    .Distinct(p => p.Prop1);
```

Any suggestion? I'd expect something like `DistinctAsync `in` IQueryResultProvider<T>`

**Comment by enrico-padovani** [comment]
Hi,

is that on NuGet?

**Comment by schotime** [comment]
Not yet. will be 3.7.3

**Comment by schotime** [comment]
Version 3.8.0
