### ISSUE TITLE
FetchOneToMany with Left Join?

### ISSUE THREAD

**Issue by grofit** [schotime/NPoco#401]
I have 2 POCOs which are different tables, which are interacted with separately for the most part, so lets pretend we have `player` and `messages`, and a player may have many messages, but they may also have none.

So in one place I want to get all players and if applicable a list of messages with them, so the SQL would look something like:

```
SELECT p.*, m.* FROM players p LEFT JOIN messages m ON p.id = m.associatedPlayerId
```

Then I was using something like:

```
db.FetchOneToMany<PlayerWithMessages>(x => x.Messages, sqlShownAbove);
```

Which looks something like:

```
public class PlayerWithMessages
{
   public Player Player { get;set; }
   public IEnumerable<Message> Messages {get;set;}
}
```

With the `Player` model having attributes describing its links to the `players` table, and `Message` model describing its links to the `messages` table.

Problem is although it returns, it will only return a result when there is a player with >= 1 message, if a player has no messages then there will be no player returned, which is not what I want, I am wanting the player to ALWAYS be returned and the messages to be empty or populated, here is a simple example:

So if we were to assume 10 players, and 5 of them have messages, I would expect `FetchOnetoMany` to return 10 players with messages, and 5 would have populated `Messages`, 5 would be empty or null.

So am I misunderstanding how this should work, and if so is there a better way to do this?

**Comment by schotime** [comment]
Hmmm...this should work. I'll need to look into it.

**Comment by dheijl** [comment]
Could this be related to the warning ino note 4 in the wiki on one to many queryhelpers?

> If you are using an outer join for your query and you are expecting that some of the many's will not be populated, make sure to use the second lambda in the FetchOneToMany call. This should return the property of the primary of the many object. In the above example this might be x => x.CarId.

>

**Comment by grofit** [comment]
Potentially, I didn't see that note, I also have a scenario where I want to join on 2 tables too which I don't think would be supported either as you can only give 1 lambda for the many right?

**Comment by dheijl** [comment]
I think you can have only one many at a time...

**Comment by schotime** [comment]
Couple of points.
This is indeed working as intended.
It will definitely give you one row back even if the join returns no results.

IEnumerable<T> cannot be used though. It has to be IList<T>.

**Comment by grofit** [comment]
Thanks for verifying behaviour, it must have been the note 4 that was my problem.

**Comment by hylixtseng** [comment]
I have the same problem.
It will not give one row back even if the join returns no results.

**Comment by Shazwazza** [comment]
Just a side note regarding the docs:

> If you are using an outer join for your query and you are expecting that some of the many's will not be populated, make sure to use the second lambda in the FetchOneToMany call. This should return the property of the primary of the many object. In the above example this might be x => x.CarId

This statement i think is referring to the "v2" API, whereas for "v3" I've had success by just duplicating the first func. I don't really know if that is the correct way it is supposed to work?
