### ISSUE TITLE
Feature Request: Allow join in DeleteMany

### ISSUE THREAD

**Issue by rhegner** [schotime/NPoco#402]
I tried the following

    await MyDatabase.DeleteMany<Child>().Where(c => c.Parent.SomeField == "SomeValue").ExecuteAsync()

with `Child` something like this:

    public class Child
    {
        public int ParentId { get; set; }

         [Reference(ReferenceType.OneToOne, ColumnName = "ParentId", ReferenceMemberName = "ParentId")]
         public Parent Parent { get; set; }
    }

This does not seem to be supported at the moment. I get an exception saying "Invalid column name 'SomeField'".

**Comment by schotime** [comment]
This probably won't be supported anytime soon. We try and keep things super simple. 
PR's always welcome though.
