### ISSUE TITLE
Support of SQL 2016 in .NetStandard

### ISSUE THREAD

**Issue by petriceko** [schotime/NPoco#403]
Hi all,
if I try to open db connection using DatabaseType, there is not able to select DatabaseType.SqlServer2016. Does it mean that NPoco does not support SQL 2016?

**Comment by schotime** [comment]
Just use SQLServer2012. It's only useful for dialect changes.

**Comment by petriceko** [comment]
Thanks for response, I think, it could be great to specify that in documentation.

**Comment by schotime** [comment]
Its really the minimum version, but will look at a wiki update
