### ISSUE TITLE
FetchMultiple and IN statement

### ISSUE THREAD

**Issue by david-rey** [schotime/NPoco#405]
I recently upgraded my project to version 3.6.1 of NPoco.  The sql statements being created for FetchMultiple seem to have changed.

These are the individual sql statements.

var stringValueSql = "SELECT * from tblConfigPropertyString WHERE ConfigPropertyDefinitionId IN (@1) AND AggregateId = @0";
var datetimeValueSql = "SELECT * from tblConfigPropertyDateTime WHERE ConfigPropertyDefinitionId IN (@1) AND AggregateId = @0";
var decimalValueSql = "SELECT * from tblConfigPropertyDecimal WHERE ConfigPropertyDefinitionId IN (@1) AND AggregateId = @0";

With this FetchMutliple

var data = database.FetchMultiple<ConfigPropertyStringDto, ConfigPropertyDatetimeDto, ConfigPropertyDecimalDto>($"{stringValueSql};{datetimeValueSql};{decimalValueSql};", id, propertyDefinitionIds);

It produces this.						
				
SELECT * from tblConfigPropertyString WHERE ConfigPropertyDefinitionId IN (@0,@1,@2,@3,@4,@5,@6,@7,@8,@9,@10,@11,@12,@13,@14,@15) AND AggregateId = @16;
SELECT * from tblConfigPropertyDateTime WHERE ConfigPropertyDefinitionId IN (@0) AND AggregateId = @16;
SELECT * from tblConfigPropertyDecimal WHERE ConfigPropertyDefinitionId IN (@0) AND AggregateId = @16;

In 3.3.3 - which was the version I upgraded from it produced this.

SELECT * from tblConfigPropertyString WHERE ConfigPropertyDefinitionId IN (@0,@1,@2,@3,@4,@5,@6,@7,@8,@9,@10,@11,@12,@13,@14,@15) AND AggregateId = @16;
SELECT * from tblConfigPropertyDateTime WHERE ConfigPropertyDefinitionId IN (@0,@1,@2,@3,@4,@5,@6,@7,@8,@9,@10,@11,@12,@13,@14,@15) AND AggregateId = @16;
SELECT * from tblConfigPropertyDecimal WHERE ConfigPropertyDefinitionId IN (@0,@1,@2,@3,@4,@5,@6,@7,@8,@9,@10,@11,@12,@13,@14,@15) AND AggregateId = @16;

**Comment by schotime** [comment]
This is related to the bug fixed in https://github.com/schotime/NPoco/issues/374
I'll see what we can do to make these work together.
