### ISSUE TITLE
FirstOrDefaultAsync

### ISSUE THREAD

**Issue by 79it** [schotime/NPoco#406]
Looking through the source code I can see that FirstOrDefaultAsync exists for queries but it doesn't exist in its own right like FetchAsync etc. Are there any plans to add it or should I create a pull request?

**Comment by schotime** [comment]
It hasn't been added because you can always just call QueryAsync(sql) and then call FirstOrDefault on the result.

```cs
var result = (await db.QueryAsync<User>("select top 1 * from users")).FirstOrDefault();
```

Happy to take a PR.

**Comment by flyliao** [comment]
Hi,schotime,Different database returns the first item is not the same.
such as :mysql select * from users limit 1
mssql:select top 1 * from users

**Comment by schotime** [comment]
yeah, so write the query for the database you support.

**Comment by flyliao** [comment]
var user = await db.Query<User>().Where(m => m.Account == account && m.Pwd == pwd).FirstOrDefaultAsync();

**Comment by clausjensen** [comment]
@schotime https://github.com/schotime/NPoco/pull/422
