### ISSUE TITLE
InvalidOperationException in VB.NET

### ISSUE THREAD

**Issue by mia-san** [schotime/NPoco#408]
hi.
might be already answered though...

we have upgrading our older VB.NET project and decided to use NPoco.
however, we get weird InvalidOperationException in some cases, like

```
            Using c As New Database("Data Source=.\SQLExpress; Initial Catalog=SampleDb; Integrated Security=True", "System.Data.SqlClient")

                c.UpdateMany(Of TestEntity)() _
                .ExcludeDefaults() _
                .OnlyFields(
                    Function(item) New With {
                        .Value = "XXXXXXXX"
                    }
                ) _
                .Where(Function(item) item.Key = Me.TestEntity.Key) _
                .Execute(Me.TestEntity)

            End Using
```
throws InvalidOperationException like

>    System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
>    System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
>    System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
>    System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
>    System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>    System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
>    System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
>    System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
>    NPoco.Expressions.SqlExpression`1.VisitMethodCall(MethodCallExpression m)
>    NPoco.Expressions.SqlExpression`1.VisitBinary(BinaryExpression b)
>    NPoco.Expressions.SqlExpression`1.VisitLambda(LambdaExpression lambda)
>    NPoco.Expressions.SqlExpression`1.ProcessInternalExpression()
>    NPoco.Expressions.SqlExpression`1.And(Expression`1 predicate)
>    NPoco.Expressions.SqlExpression`1.Where(Expression`1 predicate)
>    NPoco.Linq.UpdateQueryProvider`1.Where(Expression`1 whereExpression)

but syntactically equivalent C# code doesn't throw.

```
            using (var c = new Database(@"Data Source=.\SQLExpress; Initial Catalog=SampleDb; Integrated Security=True", "System.Data.SqlClient"))
            {
                c.UpdateMany<TestEntity>()
                    .ExcludeDefaults()
                    .OnlyFields(item => new
                    {
                        Value = "XXXXXXXX"
                    })
                    .Where(item => item.Key == this.TestEntity.Key)
                    .Execute(this.TestEntity);
            }

```

perhaps VB.NET is doing something tricky, it would be nice if we could workaround.

NPoco 3.7.1, VS2015, Windows 10, 64bit.
//

**Comment by schotime** [comment]
Can you try this? Use Is instead of =

```
          Using c As New Database("Data Source=.\SQLExpress; Initial Catalog=SampleDb; Integrated Security=True", "System.Data.SqlClient")

                c.UpdateMany(Of TestEntity)() _
                .ExcludeDefaults() _
                .OnlyFields(
                    Function(item) New With {
                        .Value = "XXXXXXXX"
                    }
                ) _
                .Where(Function(item) item.Key Is Me.TestEntity.Key) _
                .Execute(Me.TestEntity)

            End Using
```

**Comment by mia-san** [comment]
@schotime thank you very much for looking into this.

as you suggested, using 'Is' works as expected, great!

btw, above code produces following SQL query:
`UPDATE [TestEntity] SET  WHERE ([Key] is null)`

I was expecting something like:
`UPDATE [TestEntity] SET [Value] = @0 WHERE ([Key] is null)` with @0 = 'XXXXXXXX'.

am I misunderstanding how OnlyFields works?

thanks again.

**Comment by schotime** [comment]
Yes. Only Fields should specify what fields you want to update.
```
using (var c = new Database(@"Data Source=.\SQLExpress; Initial Catalog=SampleDb; Integrated Security=True", "System.Data.SqlClient"))
            {
                c.UpdateMany<TestEntity>()
                    .ExcludeDefaults()
                    .OnlyFields(item => item.Value)
                    .Where(item => item.Key == this.TestEntity.Key)
                    .Execute(this.TestEntity);
            }
```
