### ISSUE TITLE
Where clause is incorrect in 3.7.1

### ISSUE THREAD

**Issue by mia-san** [schotime/NPoco#409]
hi.

3.7.1 seems to execute query with incorrect where clause.
3.6.1 works as expected.

To reproduce, create SampleDb, execute code below, break at 'return' line and see what c.LastCommand says.

```
using (var c = new Database(@"Data Source=.\SQLExpress; Initial Catalog=SampleDb; Integrated Security=True", "System.Data.SqlClient"))
{
    var n = c.Query<TestEntity>()
        .Where(item => 0 < item.Id)
        .ToArray();
}
```

3.6.1
`SELECT [TE].[Id] as [Id], [TE].[Key] as [Key], [TE].[Value] as [Value] \nFROM [TestEntity] [TE] \nWHERE (@0 < [TE].[Id])\n\t -> @0 [Int64] = \"0\"
`

3.7.1
`SELECT [TE].[Id] as [Id], [TE].[Key] as [Key], [TE].[Value] as [Value] \nFROM [TestEntity] [TE] \nWHERE ([TE].[Id] < @0)\n\t -> @0 [Int64] = \"0\"
`

Visual Studio 2015, .NET Framework 4.6, Windows 10, if that matters.

thanks.
//

**Comment by schotime** [comment]
To work around swap the where so that its `item.Id > 0`

**Comment by mia-san** [comment]
thanks for comment.
ok, I will for time being.
NPoco works very well for our needs, we like it.
thanks again.
