### ISSUE TITLE
SingleOrDefaultById and ID column

### ISSUE THREAD

**Issue by mia-san** [schotime/NPoco#410]
hi.

SingleOrDefaultById seems to compare against ID column only, no matter if entity/table have property/column like 'Id'.
I know I could use SingleOrDefault with giving condition myself, but It would be nice if SingleOrDefaultById etc consider entity's identity.

thanks.

**Comment by schotime** [comment]
You need to set the PrimaryKey via the attribute for it to be different. ID is the default.

**Comment by mia-san** [comment]
ah, thank you !!
we now put PrimaryKey attribute to every entity class and works fine.
well what if property 'ID', 'Id' or 'id' is automatically considered to be an 'identity'...?
