### ISSUE TITLE
Query.Where and SqlBuilder.Where

### ISSUE THREAD

**Issue by mia-san** [schotime/NPoco#411]
hi

following code builds incorrect query:
```
using (var c = new Database(@"Data Source=.\SQLExpress; Initial Catalog=SampleDb; Integrated Security=True", "System.Data.SqlClient"))
{

var n = c.Query<TestEntity>()
    .Where(
        Sql.Builder
            .Where("Key = 'KEY'")
            .Where("Id = 0")
    )
    .ToArray();
}
```
c.LastCommand has duplicate WHERE keyword as following:
`SELECT [TE].[Id] as [Id], [TE].[Key] as [Key], [TE].[Value] as [Value] \nFROM [TestEntity] [TE] \nWHERE WHERE (Key = 'KEY')\nAND (Id = 0)
`

simply changing Where to Append does not work:
`SELECT [TE].[Id] as [Id], [TE].[Key] as [Key], [TE].[Value] as [Value] \nFROM [TestEntity] [TE] \nWHERE WHERE (Key = 'KEY')\n (Id = 0)
`

I know add necessary AND keyword would work, but Where would be easier.

thanks.

**Comment by schotime** [comment]
ummm...not sure why you are mixing the sql builder here. Either of these two are supported.

```cs
var n = c.Query<TestEntity>()
    .Where(x => x.Key == "KEY" && Id == 0)
    .ToArray();
```

or

```cs
var n = c.Query<TestEntity>()
    .Where("Key = @0 and Id = @1". "Key", 1)
    .ToArray();
```

**Comment by mia-san** [comment]
thanks for comments.

while we were trying various way to workaround #409 , we preferred to use SqlBuilder which is supposed to be more robust and readable.
therefore, this case might be rather impractical, but Where() takes SqlBuilder, someone might do similar thing...

**Comment by schotime** [comment]
This probably won't be fixed.
