### ISSUE TITLE
custom DatabaseType with DateTime2

### ISSUE THREAD

**Issue by mia-san** [schotime/NPoco#412]
we are using custom DatabaseType class to enable DateTime2 as follows:
(sorry that our project is written in VB.NET...)

```
Public Class SqlServerDatabaseTypeWithDateTime2
    Inherits NPoco.DatabaseTypes.SqlServer2008DatabaseType

    Public Sub New()

        Call MyBase.New()

        Me.AddTypeMap(GetType(DateTime), DbType.DateTime2)
        Me.AddTypeMap(GetType(DateTime?), DbType.DateTime2)

    End Sub

End Class
```

this works well, though, this is boilerplate and DateTime2 is available since SQLServer 2008, is it possible to provide DatabaseType with DateTime2 enabled out-of-box?
e.g. extend existing SqlServer2008DatabaseType etc, add SqlServer2008DatabaseTypeWithDateTime2 or such for compatibility ?

thanks.

**Comment by schotime** [comment]
This means that all dates would need to be DateTime2 in your system. If that is the case then creating this override isn't that big a deal.
