### ISSUE TITLE
Problem with reference field

### ISSUE THREAD

**Issue by vbartolini** [schotime/NPoco#413]
Hi,

I have classes:
    [PrimaryKey("Id")]
    [TableName("Sheets")]
    public class Sheet
    {
        public int Id { get; set; }
        public int YearId { get; set; }
        public List<SheetSection> Sections { get; set; }
        
        public Sheet()
        {
            Sections = new List<SheetSection>();
        }        
    }
	
    [PrimaryKey("Id")]
    [TableName("SheetSections")]
    public class SheetSection
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [Reference(ReferenceType.Foreign, ColumnName = "SheetId", ReferenceMemberName = "Id")]
        public Sheet Sheet { get; set; }
    }
	
During insert I got exception:
Conversion from Sheet to Int is not possible - translation from polish.

What am I doing wrong?

**Comment by schotime** [comment]
I would have said the Result attribute but looks like u have removed it.

**Comment by vbartolini** [comment]
Yeah, I was trying with Result attribute and without it. It does not wokr and I finished with regular int field persisting reference object Id. But I still hope that somebody tell me what I am doing wrong

**Comment by vbartolini** [comment]
If I use "inner join for reference field the property is properly fullfilled. I don't need Reference Attribute.
But another question is: when I should use Reference Attribute?
