### ISSUE TITLE
Navigation properties with ICollection.

### ISSUE THREAD

**Issue by oruchreis** [schotime/NPoco#418]
Hi,
We are using Entity Framework, Entity Core and NPoco in the same repo, some methods use NPoco, others use EF. But all of these methods use same poco entity which generated by EF. EF generates navigation properties as ICollection<> and creates in ctor as HashSet<>, but NPoco check these properties that if they are IList or not. 
So when we use the poco classes that generated by EF, we can't use join queries with NPoco. Could you consider to change default behavior of NPoco to check the property is ICollection instead of IList. So we can use EF generated pocos.

**Comment by schotime** [comment]
Hi,
This is possible however i need to consider whether changing the lambda from a `Func<T, IList>` to `Func<T, IEnumerable>` is breaking or could produce unexpected results. If only `ICollection<T>` inherited `ICollection`.
I will push a branch up today to have a look.
