### ISSUE TITLE
Releases on NuGet vs Releases on GitHub

### ISSUE THREAD

**Issue by AZDeveloper777** [schotime/NPoco#419]
So the latest release on this project's GitHub is Nov 1, 2016.
2 days ago NPoco showed up on NuGet with a version 3.8.0
There's no info I can find about 3.8.0 on this GitHub repository.  It doesn't show up in Tags or Releases.
So, my request is:
1) Please start posting Release Notes for each version here. (I found the release notes on this Wiki, but they aren't updated for 3.8.0)
2) Please Tag each release so that when we get a new package on NuGet, we can find the associated source code here.

Thanks

**Comment by schotime** [comment]
The link to the release notes from NuGet are as shown:
![image](https://user-images.githubusercontent.com/202923/31258856-fe283726-aa8d-11e7-8be4-f8bc80c6d5ed.png)

They have always been here:
https://github.com/schotime/NPoco/wiki/Release-Notes

When in doubt look at the commits.

**Comment by AZDeveloper777** [comment]
Thanks !
