### ISSUE TITLE
Impossible to insert Datetime value

### ISSUE THREAD

**Issue by ghost** [schotime/NPoco#420]
Hello,

I have this sample with a valid connectionString inside the config file : 
`using System;
using NPoco;

namespace MySample
{
    class Program
    {
        /// <summary>
        /// Defines the entry point of the application.
        /// </summary>
        static void Main()
        {
            var sqlB = MySQLBridge.Instance;
            sqlB.SetEnvironnement();
            var u = new History { logId = "42017100622", idRdv = "SOG171000001", beginTransactionDate = DateTime.Now};
            sqlB.InsertHistory(u);
            Console.ReadKey();
        }
    }

    public class MySQLBridge
    {
        public static IDatabase db;

        #region Singleton
        private static MySQLBridge instance = null;
        private static readonly object padlock = new object();

        MySQLBridge() { }

        public static MySQLBridge Instance
        {
            get
            {
                lock (padlock)
                {
                    return instance ?? (instance = new MySQLBridge());
                }
            }
        }
        #endregion

        public void SetEnvironnement() =>
            db = new Database("PetaExample");

        public void InsertHistory(History u)
        {
            db.Insert("History", "logId", false, u);
        }
    }

    /// <summary>
    /// Employee class, using properties for PetaPoco
    /// </summary>
    [TableName("History")]
    [PrimaryKey("logId")]
    public class History
    {
        public string logId { get; set; }
        public string idRdv { get; set; }
        public DateTime beginTransactionDate { get; set; }
    }
}
`

I have this error : System.Data.SqlTypes.SqlTypeException: Must be btween 1/1/1753 12:00:00 AM and 31/12/9999 11:59:59 PM.

I Execute the sample directly from a server, the insert is working, but when I call the sample from a foreign server (in english), the format is maybe different.

I want to try this : ALTER SESSION SET NLS_DATE_FORMAT ='YYYY-MM-DD HH:MI:SS'
But I can't find the alter method to do it.

Is it possible to help me to fix it ?

Regards

**Comment by mia-san** [comment]
db.Execute maybe?

something like
```
    class Program
    {
        const String ConnectionString = @"Server=myServerAddress;Database=myDataBase;Uid=myUsername;Pwd=myPassword;";
        const String ProviderName = "MySql.Data.MySqlClient";

        static void Main(string[] args)
        {
            using (var db = new Database(ConnectionString, ProviderName)) {
                db.Execute(@"ALTER SESSION SET NLS_DATE_FORMAT ='YYYY-MM-DD HH:MI:SS'");
            }
        }
    }
```
