### ISSUE TITLE
GetToDbConverter gets wrong destination type

### ISSUE THREAD

**Issue by rok7** [schotime/NPoco#421]
Hi,
I have to deal with a legacy database in which booleans are mainly strored as 'VARCHAR2' of size 1.
To get in C# still bool values, I'm using a custom mapping, which should, for example, convert 'Y' to true on readings and true to 'Y' on updates.
The conversion works correctly on reading (GetFromDbConverter), but on writing (GetToDbConverter) the passed destType is Boolean instead of String.

I can see that 'dataReader.GetFieldType(groupedName.Key.Pos)' is passed as type on reading but PocoColumn.ColumnType on writing. After this I'm lost.

**Comment by schotime** [comment]
Can you show me the model and configuration?

**Comment by rok7** [comment]
Here are extracts of the model and configuration:

Model class:
`
using System;
using System.Linq;
using System.Collections.Generic;
using log4net;
using NPoco;
using SAir.Common.ServerBase.PocoHelper;
using SAir.Common.Communication.DataContracts.BSSysger.BaseDO;

namespace SAir.BSSysger.BasePoco
{
    [TableName("PREISAENDERUNGSGRUPPE")]
    [PrimaryKey("ID", SequenceName = "S_PREISAENDERUNGSGRUPPE")]
    public class PreisaenderungsgruppePoco 
    {
        #region properties
        [Column("ID")]
        public int Id { get; set; }
 
        [Column("NAME")]
        public string Name { get; set; }
 
        [Column("DESCRIPTION")]
        public string Description { get; set; }
 
        [Column("ID_GERAETETYP")]
        public int? IdGeraetetyp { get; set; }
 
        [Column("GUELTIG_AB")]
        public DateTime? GueltigAb { get; set; }
 
        [Column("AKTIV")]
        public bool Aktiv { get; set; }
        #endregion properties

        // ...

        /// <summary>
        /// Updates a PREISAENDERUNGSGRUPPE record.
        /// </summary>
        /// <param name="connectionString"></param>
        /// <param name="preisaenderungsgruppeDO"></param>
        /// <returns>the primary key id</returns>
        public static int Update(string connectionString, PreisaenderungsgruppeDO preisaenderungsgruppeDO)
        {
            PreisaenderungsgruppePoco preisaenderungsgruppePoco = new PreisaenderungsgruppePoco(preisaenderungsgruppeDO);
            int id = preisaenderungsgruppePoco.Id;
            Database db = null;

            log.Debug("Updating Preisaenderungsgruppe");

            try
            {
                using (db = NPocoFactory.Connect(connectionString))
                {
                    if (db.IsNew<PreisaenderungsgruppePoco>(preisaenderungsgruppePoco))
                        id = (int)Convert.ChangeType(db.Insert<PreisaenderungsgruppePoco>(preisaenderungsgruppePoco), typeof(int));
                    else
                        db.Update(preisaenderungsgruppePoco);
                }
                log.Debug("One record updated");
            }
            catch (Exception ex)
            {
                log.Error("Update failed, SQL=" + db?.LastCommand, ex);
                throw new Exception("Update von Preisaenderungsgruppe ist fehlgeschlagen, SQL=" + db?.LastCommand, ex);
            }
            return id;
        }
    }
}
`

My NPocoFactory class:
`
using NPoco;

namespace SAir.Common.ServerBase.PocoHelper
{
    /// <summary>
    /// Factory to configure our NPocoMapper for all database operations
    /// </summary>
    public class NPocoFactory
    {
        public static Database Connect(string connectionString)
        {
            var dbFactory = DatabaseFactory.Config(x =>
            {
                x.UsingDatabase(() => new Database(connectionString, DatabaseType.OracleManaged));
                x.WithMapper(new NPocoMapper());
            });
            return dbFactory.GetDatabase();
        }
    }
}
`

and finally my NPocoMapper class:
`
using System;
using System.Reflection;
using NPoco;

namespace SAir.Common.ServerBase.PocoHelper
{
    public class NPocoMapper : DefaultMapper
    {
        public override Func<object, object> GetFromDbConverter(MemberInfo destMemberInfo, Type sourceType)
        {
            var destType = destMemberInfo.GetMemberInfoType();
            if (destType == typeof(bool) && sourceType == typeof(string))
            {
                return x => (string)x == "Y" || (string)x == "y" ? true : false;
            }

            return base.GetFromDbConverter(destMemberInfo, sourceType);
        }

        public override Func<object, object> GetToDbConverter(Type destType, MemberInfo sourceMemberInfo)
        {
            var sourceType = sourceMemberInfo.GetMemberInfoType();
            if (destType == typeof(string) && sourceType == typeof(bool))
            {
                return x => ((bool)x) ? "Y" : "N";
            }
            if (destType == typeof(string) && sourceType == typeof(bool?))
            {
                return x => ((bool?)x).HasValue && ((bool)x) ? "Y" : "N";
            }

            return base.GetToDbConverter(destType, sourceMemberInfo);
        }
    }
}
`
