### ISSUE TITLE
Unable to build a netStandard2 project due to duplicate SqlDbType definition

### ISSUE THREAD

**Issue by dampee** [schotime/NPoco#424]
If you try to build a netstandard2.0 project with npoco you might have issues when using this: 

    var x = new SqlParameter("x", System.Data.SqlDbType.BigInt);

The error thrown is:
Error	CS0433 The type 'SqlDbType' exists in both 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'	

This is caused by NPoco referencing the System.Data.SqlClient as a dependency while netstandard2 has it by default.

**Comment by schotime** [comment]
Works fine for me.
![image](https://user-images.githubusercontent.com/202923/32150423-aaf018da-bd66-11e7-9d2f-bce79e092f5a.png)
