### ISSUE TITLE
root objects get duplicated after applying ToList to a query

### ISSUE THREAD

**Issue by andrei-traktatovich** [schotime/NPoco#427]
[NPocoBug.zip](https://github.com/schotime/NPoco/files/1407088/NPocoBug.zip)
As shown in the project attached, a query seems to produce different results in the following cases:
- querying root objects with a collection of related objects:
case A:  filter applied to query, the result is converted to list (correct result)
case B: query is converted to list, then filter is applied (root object is duplicated several times, and each duplicate contains a single related object).
(db dump is in the Backup folder)

**Comment by schotime** [comment]
What are the two queries that get produced?

**Comment by andrei-traktatovich** [comment]
Query 1: SELECT "DV"."id" as "Id", "DV"."classifier_id" as "ClassifierId", "DR"."id" as "Rules__Id", "DR"."version_id" as "Rules__VersionId" FROM classifiers_app.dal_classifier_version "DV"  
  LEFT JOIN classifiers_app.dal_classifier_rule "DR" ON "DV"."id" = "DR"."version_id" 
WHERE ("DV"."classifier_id" = @p0) 
	 -> @p0 [Guid] = "6bba11fd-95b9-490e-93d6-c47340f2e3b3"

Query 2: SELECT "DV"."id" as "Id", "DV"."classifier_id" as "ClassifierId", "DR"."id" as "Rules__Id", "DR"."version_id" as "Rules__VersionId" FROM classifiers_app.dal_classifier_version "DV"  
  LEFT JOIN classifiers_app.dal_classifier_rule "DR" ON "DV"."id" = "DR"."version_id"

**Comment by andrei-traktatovich** [comment]
After some debugging we identified the issue. 

NPOCO seems to rely on the order of records returned by SELECT.  When a select with a join is mapped to a graph in Npoco.Database, it is based on primary key of prevPoco being equal to or different from the next record. 
This works only provided that the records with same same root primary key are always in adjacent rows. 
If they are not, the logic breaks and duplicate root objects are created.
A workaround is to always place .OrderBy(root => root.Id) in a query to guarantee that root entities are always in adjacent rows; however, I think it's a good idea to resolve this issue in NPOCO itself.
