### ISSUE TITLE
Unexpected behavior when combining different overloads of IQueryProvider<>.Where()

### ISSUE THREAD

**Issue by rhegner** [schotime/NPoco#428]
This works as expected:

    MyDatabase.Query<MyPoco>()
        .Where(p => p.MyProperty == myValue)
        .Where("EXISTS (SELECT * FROM myTable)")
        .ToList();

But when I reverse the order of the two where clauses like this, 

    MyDatabase.Query<MyPoco>()
        .Where("EXISTS (SELECT * FROM myTable)")
        .Where(p => p.MyProperty == myValue)
        .ToList();

the condition from the string overload ("EXISTS ...") is completely missing from the generated SQL. This is definitely not what I would expect.

This is with NPoco v3.9.0, but we also discovered this behavior with older versions.

**Comment by schotime** [comment]
yeah looks like its a bug. 
Will try and have a look over the weekend, otherwise it will be monday.

**Comment by schotime** [comment]
Ahhh screw it. Fixed.

**Comment by rhegner** [comment]
That was quick! :) Thank you!
