### ISSUE TITLE
Update LastCommand to be easily Pasted

### ISSUE THREAD

**Issue by tbasallo** [schotime/NPoco#429]
@schotime I was wondering if you would be open to a change that displays LastCommand (like in the VS debug windows) to be copy&paste friendly. This would allow for debugging generated SQL with parameters a bit easier.

Something like this:
https://github.com/tbasallo/NPoco/commit/d94e72e2a4ce5701db96d175b453db58b1bf91fe

If you're open to the idea, I would provide the tests and all that good stuff, of course.

Also, if you rather not mess with LastCommand, how about a new property that would display the paste friendly semantics.

**Comment by schotime** [comment]
Sounds like a good idea. In theory we would need to support all databases with this so there would need to be sometype of format command on the dbtype itself like on `DatabaseType`

`FormatCommand(DbCommand command);`

**Comment by tbasallo** [comment]
OK, I'll look into how the others do it, I'm not that familiar with some of the supported DBs.

Would you prefer to use LastCommand or crate a new property? My only concern being that there is a dependency on the current format and changing that would be breaking.

**Comment by schotime** [comment]
I think i new property.

**Comment by schotime** [comment]
or no property at all and from Database, you can say  DatabaseType.FormatDbCommand(LastCommand)

**Comment by tbasallo** [comment]
But that would require to either put in a logging method or open up the immediate window to run the method. Versus a property that has the value already set. 

Though I guess the argument to that would be, why waste resources if it's not normally be used.

I'll go with that and see how it goes.

**Comment by tbasallo** [comment]
Is there a branch you would prefer this go into?

**Comment by schotime** [comment]
Branch off dev

**Comment by tbasallo** [comment]
@schotime - it's been a while, but, here I am. Not sure you feel this would best be done in the lib and if you want multiple tests for SqlServer DBs versus other DBs and if you want multiple tests for different DB types.

I preface the code with - I did not study the entire code base :)

I looked a little closer at the code LastCommand is only used on some debug lines and when explicitly GET on the fly. So I do not think the below is too heavy handed since yu probably want this when debugging. I used SetParameterValue since I couldn't find a better way to get the underlying db type.

To recap, when accessing LastCommand AND SqlServer is the DB type, the formatting is returned with the variables on top in DECLARE statements to allow for quick copy & paste and to see the DB types that the library assigned (nvarchar vs. varchar anyone??)

IF you rather not use, want to make changes, etc. let me know. and we can get issue closed and wrapped up.

Code:
https://github.com/tbasallo/NPoco/blob/master/src/NPoco/Database.cs#L1958

Tests:
https://github.com/tbasallo/NPoco/commits/f4b1b6a3e25a9ba538e33dc6b3103478a6f424e5/test/NPoco.Tests/FormatCommandTest.cs

Sample image

![image](https://user-images.githubusercontent.com/270673/64222686-fa3d8080-ce9e-11e9-8075-bac082eede35.png)

**Comment by tbasallo** [comment]
@schotime any thoughts on this? If you're interested in the changes I would send a PR

**Comment by schotime** [comment]
Yeh i'm happy to take a PR, but the code itself should be abstracted into the SQL Server Database Type so that each DB provider can implement there own.

**Comment by tbasallo** [comment]
> Yeh i'm happy to take a PR, but the code itself should be abstracted into the SQL Server Database Type so that each DB provider can implement there own.

To make sure, is this how you see it done:

Create a new method in DatabaseType (e.g., FormatCommand). The current implementation is performed in the abstraction and and overrides will have custom formatting.

In Databse.cs we would use
```
public string FormatCommand(string sql, object[] args)
{
    DatabaseType.FormatCommand();
}
```

The abstraction would have [this code](https://github.com/schotime/NPoco/blob/ec4d3d7808c8ce413b2d61f756d6d7277039c98d/src/NPoco/Database.cs#L1921)

**Comment by schotime** [comment]
The abstraction would have the current code and your new code would go in the SqlServerDatabaseType

**Comment by tbasallo** [comment]
Do you want to go with FormatCommand in DatabaseType?

And (to make sure), do you call the command from Database.cs using `DatabaseType.FormatCommand();`

**Comment by schotime** [comment]
yes that is correct, but you should pass the relevant information into the Databasetype FormatCommand

**Comment by schotime** [comment]
In fact, use the FormatCommand(DbCommand cmd) override instead.

**Comment by tbasallo** [comment]
If we move the formatting to the DatabaseType there is one method in Database that is needed. [SetParameterValue](https://github.com/schotime/NPoco/blob/ec4d3d7808c8ce413b2d61f756d6d7277039c98d/src/NPoco/Database.cs#L499). It's used to correctly set the type when declaring the variables.

Would you prefer:

1 - Duplicate what's needed into DatabaseType
2 - Refactor into a helper that both classes could use (maybe ParameterHelper)

**Comment by tbasallo** [comment]
Jump a bump.
With a lot going on I know it's easy to forget and lose sight of.
:)

**Comment by schotime** [comment]
Sorry, missed it.
Let's go for number 2.

**Comment by schotime** [comment]
@tbasallo Was there a new PR for this, I'm going through finalising stuff for v5 and thought this could make it

**Comment by tbasallo** [comment]
No, but I'll put it together for v5.

Want me to do it on the v5 branch?

**Comment by schotime** [comment]
That would be great.
