### ISSUE TITLE
SqlBuilder may fail if template has more than one clause on a line

### ISSUE THREAD

**Issue by edwardaskew** [schotime/NPoco#432]
```c#
public IEnumerable<IDictionary<string, object>> GetStatistics(params string[] columns)
{
    var builder = new SqlBuilder();
    var template = builder.AddTemplate("SELECT /**select**/, COUNT(*) FROM my_table /**groupby**/");

    builder.select(columns);
    foreach(var col in columns)
    {
        builder.OrderBy(col);
    }

    return _db.fetch<Dictionary<string, object>>(template);
}
```
(slightly simplified, used to grab statistics split by a dynamically chosen set of columns)

This should return a single record containing the total number of rows in "my_table" if no columns are passed in but actually fails with an sql syntax error because the database is receiving the string `SELECT 1, COUNT(*) FROM my_table /**groupby**/`. 

This is being caused by the whole string `/**select**/, COUNT(*) FROM my_table /**groupby**/` matching the regex `(\/\*\*.+\*\*\/)` in [SqlBuilder.ReplaceDefaults](https://github.com/schotime/NPoco/blob/master/src/NPoco/SqlBuilder.cs#L96) causing only a single replace to be performed. 

I eventually worked around it by adding in newline characters to the template between clauses (as the regext is declared multiline) but the regex should probably be something like `(\/\*\*[^*/]+\*\*\/)`.

While trawling the source code to work out wtf was going on, I also noticed that anyone that uses [WhereNamed](https://github.com/schotime/NPoco/blob/master/src/NPoco/SqlBuilder.cs#L218) with a name containing regex special characters is going to have an equally confusing time (although in that case I feel they may deserve it). 

To quote an old Usenet signature:

> Some people, when confronted with a problem, think “I know, I'll use regular expressions.”   Now they have two problems.

**Comment by schotime** [comment]
Included in build 3.9.2
