### ISSUE TITLE
FetchOneToMany using OFFSET & FETCH and a CTE

### ISSUE THREAD

**Issue by jme71** [schotime/NPoco#434]
The following code produces a list of "Call" objects, with each Call object containing a list of CallDetails objects. 

```
        int accountId = 10000;
        var sql = new NPoco.Sql(@"
            SELECT Calls.*, CallDetails.* 
            FROM Calls 
                LEFT OUTER JOIN CallDetails ON Calls.Id = CallDetails.CallId 
            WHERE AccountId = @0 
            ORDER BY Calls.CreatedOn DESC", accountId);
        var calls = db.FetchOneToMany<Call>(x => x.Details, sql);
```

That works great and all the object mapping works well. But I really need to add paging to the query, and because this is a parent/child query, I only want the paging to apply to the parent rows, while the child table is allowed to return as many matching rows as are present in the database. The best I've found to do that is to apply the OFFSET FETCH statement to a CTE on the parent table ("Calls" in this case) and then join to that CTE to restrict the results of the parent/child joined query. It works really well, but as you'll see below, NPoco doesn't handle it. Here is the modified query with paging added for the parent table:

```
        int accountId = 10000;
        int perPage = 10;
        int page = 1;
        var sql = new NPoco.Sql(@"
                    ;WITH pg AS 
                    (
                        SELECT Id
                        FROM Calls
                        WHERE AccountId = @0 
                        ORDER BY CreatedOn DESC 
                        OFFSET " + (perPage * (page - 1)) + @" ROWS
                        FETCH NEXT " + perPage + @" ROWS ONLY
                    )
                    SELECT Calls.*, CallDetails.* 
                    FROM Calls 
                        INNER JOIN pg ON Calls.Id = pg.Id
                        LEFT OUTER JOIN CallDetails ON Calls.Id = CallDetails.CallId 
                    ORDER BY Calls.CreatedOn DESC", accountId);
        var calls = db.FetchOneToMany<Call>(x => x.Details, sql);

```

The above SQL works perfectly when I run it directly against the database - it returns about 70 rows, but only a total of 10 unique records from the Calls table. This is as expected. The problem is that NPoco doesn't map the query results to the objects correctly - I'm guessing because of the CTE at the beginning of the query. I couldn't find anything in the NPoco docs about this, so I'm stumped.

Any ideas how to get this to work?

**Comment by schotime** [comment]
All I can think of is that the order has been messed up.
eg. The many rows aren't coming directly under their parent rows.

**Comment by schotime** [comment]
if it is messed up ordering then try this.

```
SELECT Calls.*, CallDetails.* 
                    FROM pg 
                        INNER JOIN Calls ON Calls.Id = pg.Id
                        LEFT OUTER JOIN CallDetails ON Calls.Id = CallDetails.CallId 
                    ORDER BY Calls.CreatedOn DESC", accountId);
```

**Comment by jme71** [comment]
Unfortunately, that didn't work.

**Comment by schotime** [comment]
So what is the difference between the results?

**Comment by jme71** [comment]
No difference at all. NPoco loads all the Call objects but none of the details. The Details property for each Call object is null.

**Comment by schotime** [comment]
No the results of the raw SQL queries. From names of columns to order of rows.

**Comment by jme71** [comment]
The SQL query results are exactly the same with both variations of the FROM clause. One thing I just noticed that might be a helpful clue is that when the query is run through NPoco, **all** of the records from the Calls table are returned. There are 17 records in that table, but the join to the CTE should restrict the results to only 10 calls. That **is** what happens when running the SQL query directly against the SQL database, but now that I realize it's returning all of the records from the Calls table, I'm thinking that NPoco might be ignoring the CTE entirely.

**Comment by schotime** [comment]
Npoco knows nothing of the CTE, only the results set.

**Comment by jme71** [comment]
If I remove the CTE and the JOIN to it, the query works fine.
If I remove the JOIN to the CTE, but keep the CTE in the SQL statement (even though it has no purpose without the JOIN), NPoco doesn't load the objects properly.
It has to be the CTE.

**Comment by schotime** [comment]
I cannot reproduce this.
Could you please put together a full but simple sample with scripts to create tables which recreates this?
thx,
