### ISSUE TITLE
Async and Transaction?

### ISSUE THREAD

**Issue by zhangb99** [schotime/NPoco#435]
There're various Sync and Async options on IDatabase.  Do I have to treat transaction differently?  I'm opening/closing transaction in a MVC async TypeFilter, if that matters.

Thanks.

            public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
            {
                using (var transaction = _database.GetTransaction())
                {
                    var excuted = await next();

                    if (excuted.Exception == null)
                        transaction.Complete();
                }
            }

**Comment by schotime** [comment]
This is fine.
