### ISSUE TITLE
xml comments/javadocs

### ISSUE THREAD

**Issue by EdLichtman** [schotime/NPoco#442]
I'd like to get started helping this project since I utilize it so heavily. I've noticed myself only using it one way though, and I think it's because the methods aren't well documented. Would this be something beneficial that I could help with?

**Comment by vitordeatorreao** [comment]
I second this.

I only understood how to use the `NPoco::Database.Update<Poco>(Poco, Expression<Func<Poco, object>>)` method when I read the issue 379.

I'm also willing to help.

**Comment by EdLichtman** [comment]
So change in plan... I just got engaged and found out I won't have as much free time. but I'm programming our wedding announcement website and using MySql and therefore depending on the functional aspect of this more intensely so I'll start learning the software better to be able to provide explanations when I have the time.

**Comment by makingbloke** [comment]
Congratulations :) weddings do take up a lot of time but there’s always
lots of unexpected ways to get a computer involved :)

**Comment by sgf** [comment]
if XML comment this Project will be better.
