### ISSUE TITLE
ForceToUtc

### ISSUE THREAD

**Issue by vnefedov** [schotime/NPoco#443]
Since 3.6.0
Fix ForceToUtc on attribute mapping to be true by default

Is there any way to setup ForceToUtc = false (as it was prior 3.6.0) for all datetime columns?
The problem is "Z" in datetime column values when model converts to json.
Before 3.6.0 - "Created": "2017-06-15T13:45:30"
After 3.6.0 - "Created": "2017-06-15T13:45:30Z"
This leads to mismatched hash (MD5)

**Comment by vnefedov** [comment]
**UPDATE**. Let me show a simple example

[TableName("LOG_Events")]
[PrimaryKey("EventId", AutoIncrement = true)]
public class Event
{
    public int EventId { get; set; }
    public string EventType { get; set; }
    public DateTime Created { get; set; }
}

class Program
{
    static void Main(string[] args)
    {
        Database db = new Database("mydb");
        DateTime dateTime = DateTime.Now;
        Event ev1 = new Event { EventType = "test", Created = dateTime };
        db.Save<Event>(ev1);
        Console.WriteLine($"ev1.Created : {ev1.Created}, Kind={ev1.Created.Kind}"); // ev1.Created : 06.01.2018 13:03:37, Kind=Local
        Console.WriteLine($"dateTime == ev1.Created : {dateTime == ev1.Created}"); // dateTime == ev1.Created : True
        Event ev2 = db.SingleById<Event>(ev1.EventId);
        Console.WriteLine($"ev2.Created : {ev2.Created}, Kind={ev2.Created.Kind}"); // ev2.Created : 06.01.2018 13:03:37, Kind=Utc
        Console.WriteLine($"ev1.Created == ev2.Created : {ev1.Created == ev2.Created}"); // ev1.Created == ev2.Created : FALSE !!!!!
    }
}

I think this is incorrect behavior! (bug?)

**Comment by Killerkiwi2005** [comment]
You can fix this at the convert to the JSON level
https://www.newtonsoft.com/json/help/html/DatesInJSON.htm

You really **should** use UTC dates in storage, (dates... so much pain)
https://zachholman.com/talk/utc-is-enough-for-everyone-right
