### ISSUE TITLE
Limit the number of open db connections

### ISSUE THREAD

**Issue by rhegner** [schotime/NPoco#445]
I'm using NPoco in the data layer of my new ASP.NET Core web application. I followed closely [ the factory pattern you suggest in your wiki](https://github.com/schotime/NPoco/wiki/Fluent-mappings-including-conventional#database-factory-setup). This means a new database objects gets created for every service scope (i.e. for every request).

The database (MySQL) is hosted by an external hoster and the maximum number of connections per user is very limited (maximum 10).

Even though I carefully dispose all connections as soon as I don't need them anymore, I pretty soon got a "User 'xxx' has exceeded the 'max_user_connections' resource (current value: 10)" exception from MySQL. 

Connection pooling is enabled by default for the [MySqlConnector](https://mysql-net.github.io/MySqlConnector/) I'm using.

So the question is what is a good design pattern for a data layer using NPoco that allows me to limit the number of open connections to the database?

**Comment by schotime** [comment]
Disposing the `Database` should close the connection, otherwise its your connection pooling settings on your connection string
