### ISSUE TITLE
Query.Include.Where.where = bad where.!

### ISSUE THREAD

**Issue by leviatanMX** [schotime/NPoco#447]
Please HelpME..!

using (IDatabase db = DBContext.GetInstance())
                {
                    result = db.Query<GastosEmpresa>().Include(x => x.CatGastos)
                                                .Where(x => x.Mes == mes).Where(x => x.Year == year)
                                                .ToList();
                }

**generate this sql...**

exec sp_executesql N'SELECT [GE].[Id] as [Id], [GE].[FechaGasto] as [FechaGasto], [GE].[CatGastoId] as [CatGastoId], [GE].[Observacion] as [Observacion], [GE].[Importe] as [Importe], [GE].[Mes] as [Mes], [GE].[Year] as [Year], [CG].[Id] as [CatGastos__Id], [CG].[Nombre] as [CatGastos__Nombre] FROM [GastosEmpresa] [GE]  
  LEFT JOIN [CatGastos] [CG] ON [GE].[CatGastoId] = [CG].[Id] 
WHERE (**[GE].[Mes]** = @0) AND ((**[GE].[Mes]** = @1) AND ([GE].[Year] = @2)) ',N'@0 int,@1 int,@2 int',**@0=12,@1=12**,@2=2017

**Comment by leviatanMX** [comment]
haha ok I found the error

**Wrong**
result = db.Query().Include(x => x.CatGastos).Where(x => x.Mes == mes).Where(x => x.Year == year)
.ToList();

**OK**
result = db.Query<GastosEmpresa>().Include(x => x.CatGastos)
                                                .Where(**x => x.Mes == mes && x.Year == year**)
                                                .ToList();

**Comment by schotime** [comment]
This is a bug. Will get it fixed for the next release.
