### ISSUE TITLE
Failed to Query by sql and linq to get the nested object.

### ISSUE THREAD

**Issue by daguang080710** [schotime/NPoco#449]
public class Complex {
        public int Id { get; set; }
        public int Age { get; set; }
        public int OrderId { get; set; }
        [ResultColumn]
        [ComplexMapping]
        public Order Order { get; set; }
    }
    public class Order {
        public int Id { get; set; }
        public int Num { get; set; }
    }
I tried to get the nested Order by OrderId which is related to Order.Id.But,i failed with sql and linq in NPoco.However,i succeeded  in mysql with sql command.Can you show me how to make it work in NPoco.In mysql command window,i used this sql: select * from complex left join Order on Complex.OrderId=Order.Id where Complex.Id=1;

**Comment by schotime** [comment]
`ComplexMapping` should be`Reference`  specifying the type as many to one.
