### ISSUE TITLE
NPoco.Database("CONNECTION STRING" and DbProviderFactory

### ISSUE THREAD

**Issue by ErcinDedeoglu** [schotime/NPoco#450]
Hello,
when I try with connection string it needs DbProviderFactory at 3rd parameter.

new NPoco.Database("sql connection string", DatabaseType.SqlServer2012, **DbProviderFactory**)

I couldnt resolve this one. Any help will be fantastic!
(.NET std 2.0)

**Comment by schotime** [comment]
DbProviderFactory is this instance `System.Data.SqlClient.SqlClientFactory.Instance`

`new NPoco.Database("sql connection string", DatabaseType.SqlServer2012, System.Data.SqlClient.SqlClientFactory.Instance)`

**Comment by mchomem** [comment]
I was also not able to connect, since the Wiki examples are all with a string in the constructor.

Thank you @schotime !

**Comment by mchomem** [comment]
Good night!

I made the adjustment you indicated but even so when trying to connect to the bank, I am receiving the following exception from the application:

System.Exception: 'No database type found for the type string specified:' SqlServerDatabaseType '. Make sure the relevant assembly NPoco.SqlServer is referenced. '

Could you tell me what I'm doing wrong?

Follow my code:

`public List<Employee> Retreave(Employee entity)
{
	using (IDatabase db = new Database(@"Server=SERVER\SQL2019; Database=tEST;User Id=sa;Password=sa@2019;", DatabaseType.SqlServer2012, System.Data.SqlClient.SqlClientFactory.Instance))
	{
		return db.Fetch<Employee>("select * from Employee");
	}
}`

**Comment by csharpforevermore** [comment]
This should be updated in the documentation as it threw me the first time I used it.
