### ISSUE TITLE
InsertBulk => SqlBulkCopy Question

### ISSUE THREAD

**Issue by hhmultimediallc** [schotime/NPoco#451]
Hi Adam,

I've been using NPoco for about three years and love it!!  I've used it to two places so far and it's been absolutely wonderful for both of those dev teams.

Anyway,  I seem to have a problem with InsertBulk when an entity is named "Plan" 
Is this a reserved keyword?   How does one tell InsertBulk to use [Plan] instead of Plan?

**Comment by schotime** [comment]
Looks like the table name hasn't been escaped here. I thought it would escape it internally.

Don't think there is a work around atm.

```
        private static DataTable BuildBulkInsertDataTable<T>(IDatabase db, IEnumerable<T> list, SqlBulkCopy bulkCopy)
        {
            var pocoData = db.PocoDataFactory.ForType(typeof (T));

            bulkCopy.BatchSize = 4096;
            bulkCopy.DestinationTableName = pocoData.TableInfo.TableName;
            ......
```

**Comment by hhmultimediallc** [comment]
K.  I just went ahead and named my table and entity CompanyPlan.  I was just curious.

User entity that I had to change to Person for the same reason.

Thanks for the quick response.
