### ISSUE TITLE
question : best way to manage multiple schemas

### ISSUE THREAD

**Issue by carlopiersanti** [schotime/NPoco#454]
Hello,

I am using npoco for a project where I have the same tables in multiple schemas of the same database.

One I have found is redefining the classes
https://github.com/schotime/NPoco/issues/387
but this is not acceptable for me since I have a large number of schemas

I could redefine the database factory (thus creating a new connection)
https://github.com/schotime/NPoco/wiki/Fluent-Mappings-including-Conventional
but this would force me to create a new connection.

Is there a lighter way ?

Thanks and regards

**Comment by tbasallo** [comment]
Another way, just pointing out, is not to use the table attribute and just have your SQL code use full dot notation using some kind of helper.

` $"FROM {GetSchema()}.TABLENAME WHERE...`

You could also create another helper that gets the table name attribute from the class:

` $"FROM {GetSchema()}.{GetTable(obj)}WHERE...`
or
` $"FROM {GetSchemaAndTable(obj)} WHERE...`

Just a couple options...

**Comment by mrpepito** [comment]
How could I implement this for an add record?
For the select I can easily use a Fetch customized but for the Add I haven't found a way.
Could you point me to some doc/code ?

**Comment by TonyBurnettSchoola** [comment]
You could define a base POCO and derive per schema POCOs and place the table attribute on the derived class.

public class BasePOCO {}

[TableName("schema1.poco")]
public class Schema1POCO : BasePOCO {}

[TableName("schema2.poco")]
public class Schema2POCO : BasePOCO {}
