### ISSUE TITLE
Multiple CRUD operations in a transaction causing Deadlock

### ISSUE THREAD

**Issue by RDeveloper1** [schotime/NPoco#455]
using (var transaction = Conn.GetTransaction())
    {
        await Conn.DeleteMany<M1>().Where(x => (x.d == dId).ExecuteAsync();
        foreach (var l in listData)
        {
            await Conn.InsertAsync(l);
        }
        transaction.Complete();
    }

When a method with this logic is called multiple times [>25 times] in a loop. It actually causes a deadlock and few of the records are not inserted.

**Comment by schotime** [comment]
Are you running this method in parallel?
Need some more information, because what you are doing above won't cause a deadlock by itself

**Comment by RDeveloper1** [comment]
I am calling the method which contains the above code from a foreach loop. The loop runs more than 20 times. And I am getting deadlock message for some inserts.

**Comment by RDeveloper1** [comment]
This error does not occur when I write like this. Or if this method is called only 1 or 2 times

```
  await Conn.DeleteMany<M1>().Where(x => (x.d == dId).ExecuteAsync();  
  using (var transaction = Conn.GetTransaction())
    {
       
        foreach (var l in listData)
        {
            await Conn.InsertAsync(l);
        }
        transaction.Complete();
    }
```

**Comment by tbasallo** [comment]
I think what might be happening is as the number of inserts and deletes increases, the DB has less of a chance (the seconds in between each of the commands) to complete the transaction, eventually causing the deadlock.

As a test, keep the delete in the transaction, but remove the async. If it runs (all 20) without deadlocking, then it's the async (parallel) nature ('d bet). Really, more of a DB/threading issue than a NPoco issue.

**Comment by RDeveloper1** [comment]
@schotime Yes, I am running it async.

**Comment by RDeveloper1** [comment]
@tbasallo I have removed async for delete, but still getting deadlock issue.

**Comment by RDeveloper1** [comment]
```
public async Task<T> Method1(int did){      
    using (var transaction = Conn.GetTransaction())
            {
                await Conn.DeleteMany<M1>().Where(x => (x.d == dId).ExecuteAsync();
                foreach (var l in listData)
                {
                    await Conn.InsertAsync(l);
                }
                transaction.Complete();
            }
    }


public async Task<T> callerMethod(){
   var res = await serivce.Method1();
}

for(int i = 0; i <25; i++){
    callerMethod();
}

```

@schotime , @tbasallo  Please check the code, I have added some more info

**Comment by schotime** [comment]
```
for(int i = 0; i <25; i++){
    callerMethod().Wait();
}
```

**Comment by tbasallo** [comment]
Or, you can await callerMethod()

`for(int i = 0; i <25; i++){
    await callerMethod();
}`

**Comment by RDeveloper1** [comment]
Is there anyway we can do without changing the for loop.

**Comment by tbasallo** [comment]
Without changing what's in the loop?

You can remove the async code from the SQL portion and make it synchronous. Just make it normal .Insert() and .Delete().
