### ISSUE TITLE
v3 One to Many

### ISSUE THREAD

**Issue by flyliao** [schotime/NPoco#457]
public class OrderDto
{
    public long Id { get; set; }
    public List<OrderItemDto> Items{get;set;}
    public List<OrderLogDto> Logs{get;set;}
}
public class OrderItemDto
{
    public long Id { get; set; }
    public long OrderId {get;set;}
}

public class OrderLogDto
{
    public long Id { get; set; }
    public long OrderId {get;set;}
}
var sql = @"
SELECT o.Id,o.AgentId,o.CreateTime,o.EnterpriseId,o.ExpressAmt,o.PayTime,o.Status,o.TotalAmt,
	i.Id OrderItemId,i.OrderId,p.AgentPrice,b.Name BrandName,c.Name CategoryName,e.Name EnterpriseName,p.IsOnline,
	p.Name,pack.Name PackageName,p.Qty,p.SalePrice,s.Name SeriesName,
	u.Name UnitName,
	l.Id OrderLogId,l.OrderId,Content,LogTime
FROM `Order` o
INNER JOIN OrderItem i ON i.OrderId = o.Id
INNER JOIN Product p ON p.Id = i.ProductId
INNER JOIN Enterprise e ON e.Id = p.EnterpriseId
LEFT JOIN Brand b ON b.Id = p.BrandId
LEFT JOIN Category c ON c.Id = p.CategoryId
LEFT JOIN Package pack ON pack.Id = p.PackageId
LEFT JOIN Series s on s.Id = p.SeriesId
LEFT JOIN Unit u on u.Id = p.UnitId
LEFT JOIN OrderLog l ON l.OrderId = o.Id
WHERE o.Id = 1
                ";
var re = db.FetchOneToMany<OrderDto>(x => x.Items,  sql); ??

**Comment by svickers** [comment]
Not sure what question you are asking, but it looks like you are trying to get multiple lists in the same parent object, which is not supported.  See note #5 in the docs:
https://github.com/schotime/NPoco/wiki/One-to-Many-Query-Helpers
