### ISSUE TITLE
Support for interfaces? Or better yet full Dipendency Inection and IoC?

### ISSUE THREAD

**Issue by ravensorb** [schotime/NPoco#458]
I was curious if there are anything to support DI and IoC? This is becoming more and more of a common pattern and i could see a lot of value of it being support in this library.

Consider the following

```
public interface IAnimal
{
     int TagId { get;set}
     int Age {get;set;}
     int Weight {get;set;}
}

public interface IDog : IAnimal
{   
    string Breed {get;set;}
}

public interface Owner
{
   string Name {get;set;}
   IList<IDogs> Dogs {get;set;}
}
```

If you think about it, everything that you need to create tables and insert data can be found in the interfaces at least when it comes to creating the tables and writing the data. The fun comes with reading and this could be handled via DI or and IoC pattern with a resolver.

Now I admit those interfaces are rather a simplistic use case is all. For my actually use case, I have a very large scale enterprise application that is 100% based on the Design by Contract pattern to allow for 100% separation of concerns. This allows for different teams to work on different part of the application without impacting each other during releases (different pieces have different release schedules). We have a set of "contract resolvers" using Autofac (right now although we may switch), that we use through out the application to get a specific instance of what ever contract we need.

Ex:
```var instance = Resolver.Resolve<IAnnualContract>();```

this allows someone to work create an annual contract without needing to know much about it (they really shouldn't even need to care if you think about it)

So we are looking for a way to do something like

```db.Save<IAnnualContract>(instance)```
or
```db.FetchAll<IAnnualContract>()```

The first one is easy (several ORM frameworks handle that). The second one seems to be the difficult one. If you look at what json.net does it has a concept of a contract resolver that is used to create a concrete instance of the object based on the type (it uses the resolver pattern above as well) and then hydrates the properties. This allows for the developers loading the data to again not have to really care or worry about the concrete instance, they just know that it will have the properties defined on the contract loaded correctly from the rdbms.

Thoughts?

**Comment by schotime** [comment]
This is not on the roadmap unfortunately.
