### ISSUE TITLE
Unit testing when using Snapshotter

### ISSUE THREAD

**Issue by svickers** [schotime/NPoco#461]
We are trying to write some unit tests around a method that uses `IDatabase.StartSnapshot()`.  We are mocking the IDatbase interface but this is causing problems because of PocoData.Columns being null, specifically this line:
https://github.com/schotime/NPoco/blob/ee1db7e42cf8a8dc8777fbf78aa4f478f64e64f2/src/NPoco/Snapshotter.cs#L37
So an exception is thrown.

The setter for `PocoData.Columns` is protected internal, so we can't mock it.  Any ideas how we might work around it?

**Comment by aalex675** [comment]
I'm sure you've figured this out by now, but for future readers: You need to initialize the PocoDataFactory for the snapshotter to work. Here is the method I use to create a substitute for the database using NSubstitute:

        public static IUserDatabase CreateDatabaseSubstitute()
        {
            var db = Substitute.For<IUserDatabase>();

            // We need to do this so that the Snapshot extension methods work correctly.
            db.PocoDataFactory = new PocoDataFactory(new MapperCollection());

            return db;
        }
