### ISSUE TITLE
Can't we fetch many data without sql

### ISSUE THREAD

**Issue by karlosRivera** [schotime/NPoco#463]
see this code
```
public class User 
{
    public int UserId { get;set; }
    public string Email { get;set; }
}

using (IDatabase db = new Database("connStringName")) 
{
    List<User> users = db.Fetch<User>("select userId, email from users");
}
```

here we have to write sql to fetch data. can't we avoid writing sql when using NPOCO?

looking for reply. thanks

**Comment by tbasallo** [comment]
@karlosRivera , Yes, you can.

If you don't add a table attribute to your class and the name of your table is the same as your class you can just do:
`db.Fetch<User>();`

This will execute:
`SELECT UserId, Email FROM User`

If your table name is different than your class name, you'll then have to add the TableName attribute to the class to do the same (and let NPoco know the table name).

Once you have the table part figured out, you can add a where clause just doing:

`db.Fetch<User>("WHERE` Id = @0", id);

Go thru the Wiki, there's a lot of this in there. Make sure you expand the pages.
