### ISSUE TITLE
.NET Standard 2.0

### ISSUE THREAD

**Issue by miseeger** [schotime/NPoco#465]
Is there a plan on making NPoco available under .NET Standard 2.0 so that it is possible to also address the newest .NET Framework versions (4.7.1, as of today)? My Intention is to put some of my libraries under .NET Standard 2.0 and I'm heavily using NPoco.

**Comment by schotime** [comment]
Yes. Aim is for the next major version V4 within the month.

**Comment by bradbamford** [comment]
Should probably target 4.7.2 given that Microsoft fixed the known run time issues with .NET Standard 2.0 and prior versions of the Framework.

**Comment by calfrei** [comment]
Any updates on this?

**Comment by schotime** [comment]
There is an alpha out that I've been using in prod for a few months so, I'll probably release it officially next week. Apologies.

**Comment by miseeger** [comment]
Thank you, Adam. I already decieded to use the latest alpha in my newest project. Works for me like a charm.
