### ISSUE TITLE
Using Replacement Args Affecting Round-Trip Performance?

### ISSUE THREAD

**Issue by hhmultimediallc** [schotime/NPoco#466]
Hi Adam,

I got a piece of code from another developer where they didn't use any replacement tokens in their query.  The query is extremely fast running naked but of course we need to avoid potential SQL Injection attacks.  I went to modify the code to add the args and I saw a significant drop in perf with round-trip times literally slightly more than an order of magnitude in degradation.  The results are very consistent as I ran these queries on a "hot" API about 15 consecutive times.   Is there anything that explains this?  Am I missing something very basic here?  I've always used parameterized queries so I've never had the chance to notice this before.  I guessing that whatever the problem is, it's most likely in the underlying IDatabase lib.

Example with Round-trip Times:
This particular table is a ticker symbol lookup table with over 8.5 million rows (but it's very narrow and only has about 6 columns of data per row).
```
.NET Framework 4.6.2
/////////////////////
// Parameterized
query = "SELECT * FROM [DailySummary] WHERE [Symbol]=@0 AND [Date] >= @1 AND [Date] < @2";
var summaries = db.Fetch<DailySummaryItem>(query, ticker, startDate, endDate);
// 249 rows returrned
// d1	{00:00:00.6464881}	System.TimeSpan

/////////////////////
// Naked
summaries = db.Fetch<DailySummaryItem>("SELECT * FROM [DailySummary] WHERE [Symbol]='" + ticker + "' AND [Date] >= '" + startDate + "' AND [Date] < '" + endDate + "'");
// 249 rows returrned
// d2	{00:00:00.0430318}	System.TimeSpan
```

**Comment by schotime** [comment]
My guess is that the types don't match so they aren't using an index. 

What is the type of the symbol column. My guess is a varchar and strings by default are nvarchar. 

You will need to wrap the ticker variable in the AnsiString type. Eg. `new AnsiString(ticker)`

**Comment by hhmultimediallc** [comment]
Right you are, sir.  The Symbol column is in need an VARCHAR(10)  I'm altering that column now to NVARCHAR(10).  This one got by us as we are supposed to be defining all of our string columns NVARCHAR.  Thanks!

**Comment by tbasallo** [comment]
I got burned so many times by this one it embarrasses me :(

As an FYI: Remember that you can also do a new database type if you want to or need to keep varchar as the column type: https://github.com/schotime/NPoco/issues/368 for reference.

**Comment by hhmultimediallc** [comment]
Thanks @tbasallo.  This is a new design so we have the flexibility to create our own world. :)
