### ISSUE TITLE
LINQ Joins not supported

### ISSUE THREAD

**Issue by mladenb** [schotime/NPoco#467]
Hi,

I'm not sure if I'm doing something wrong or not, and I also searched the NPOCO docs for the answer and couldn't find it, so I'd rather ask here. Is it possible to use LINQ's Join() to create a query which inner/outer joins two tables in 1 sql statement? In other words, is it possible to start with database.Query(Sql) to start from the IEnumerable (to avoid performing a real DB query until it's really needed), then append some Where() statements and finally do a Join() to inner-join the table with another table (and still keep the IEnumerable). Later on, when we decide to actually perform this query, we might do a .ToList() or something, to start materializing it, or abandon it completely if not needed.

What I tried so far is something like this:
```
using (var db = new Database(new SqlConnection(connectionString)))
{
    var promise1 = db
        //.Query<Organization>("SELECT * FROM Organization WHERE productId IN ? AND countryId IN ?")
        .Query<Organization>("SELECT * FROM Organization")
        .Where(o => GivenProductIds.Contains(o.ProductId))
        .Where(o => GivenCountryIds.Contains(o.CountryId));

    var promise2 = db
        .Query<Country>("SELECT * FROM Countries")
        .Where(c => c.Continent == GivenContinent));

    var join = promise1.Join(promise2,
        o => o.CountryId,
        c => c.Id,
        (o, c) => new { Organization = o, Country = c },
    );

    var newPromise = join
        .Where(...)
        .ToList();
}

```

But, doing it like this, I got an exception, basically saying that an sql connection must first be closed before another one can be opened. Am I doing something wrong or is this approach not supported at all?

**Comment by schotime** [comment]
This is not supported and never will be. 
If you want to do complex joins then you need to write the sql yourself. 
Or
ToList() both queries then do the join in memory.

**Comment by hhmultimediallc** [comment]
@mladenb 
Additionally you can do what I've in re-designing the app architecture at my current company:  Take those complex in-code queries and turn them into views.  Makes your API code much cleaner but more importantly gives you a ton of selectivity over various results sets where each "kind" of result set can be represented by a query method in your query class.   This is a bit of a CQRS-light approach but it really helps in organizing your API code.

Example:
```
public class QueryOrganization : QueryBase
{
	private string query
	{
		get { return "SELECT * FROM [getOrganizationList] WHERE 0=0 "; }
	}

	public IQueryResult ByProductId(int productId)
	{
		try
		{
			var result = db.Fetch<OrganizationModelView>(query + "AND [ProductId] = @0", productId);
			AssignQueryResult(result);
		}
		catch (Exception e)
		{
			AddFailureMessage(e.Message, EventCode.Reallocation);
		}
		return queryResult;
	}
	public IQueryResult ByProductCountryId(int countryId = 1)
	{
		try
		{
			var result = db.Fetch<OrganizationModelView>(query + "AND [CountryId] = @0", countryId);
			AssignQueryResult(result);
		}
		catch (Exception e)
		{
			AddFailureMessage(e.Message, EventCode.Reallocation);
		}
		return queryResult;
	}
}
```

**Comment by schotime** [comment]
Also, use the `SqlBuilder` to compose the where queries safer. @hhmultimediallc 

https://github.com/schotime/NPoco/wiki/Sql-Templating

**Comment by hhmultimediallc** [comment]
Sweet,  @schotime!

**Comment by mladenb** [comment]
Thanks a lot guys for a very fast responses!
I'll try to re-design the architecture a bit, since this seems to make sense to me.
Thanks again, a lot! :)
