### ISSUE TITLE
Why does Database require abstract DbConnection instance, instead of IDbConnection?

### ISSUE THREAD

**Issue by hanssens** [schotime/NPoco#470]
Is there a reason why the [constructors of the Database class](https://github.com/schotime/NPoco/blob/master/src/NPoco/Database.cs#L34-L44) all have a dependency on `DbConnection`, instead of `IDbConnection`? 

Accepting the base interface would make it a bit more clean and DI-friendly. For example, this currently fails:

```
        public DataFactory(IDbConnection conn)
        {
            if (conn.State != ConnectionState.Open)
                conn.Open();

            _db = new Database(conn, DatabaseType.PostgreSQL); // <-- IDbConnection not possible here
            _db.OpenSharedConnection();
        }
```

There probably is a good reason, but just in case there is none - I'd like volunteer to make a PR for it.

**Comment by schotime** [comment]
Firstly because the interfaces don't exist in . netstandard 1.3.
Abstract classes work just as well with DI as interfaces do. 

Saying that. For V4 I might bring them back in . netstandard 2.0 and the full framework versions.

**Comment by hanssens** [comment]
Thanks @schotime. Makes sense about the lack in netstandard1.3. Indeed, working with the abstract class works but I'd definitely give a +1 for the option to add it with netstandard2.0 support. 

Simply because I'd rather reference and pass along a contract, than a concrete implementation.

**Comment by schotime** [comment]
Will explore for v5

**Comment by schotime** [comment]
None of the async methods are on the interfaces so not worth the change
