### ISSUE TITLE
Inserting NULL values instead of DEFAULT

### ISSUE THREAD

**Issue by mladenb** [schotime/NPoco#476]
Hi,

I read [here](https://github.com/schotime/NPoco/issues/161) that "NPoco does not set the values for any column if they are they are null", but I have a case where I'm trying to do an INSERT of an object, with a property (bool?) with a NULL value (in the DB the column is of type BIT, with NOT NULL set and with a DEFAULT value of false) and that insert fails with an SqlException:
Cannot insert the value NULL into column 'is_visible', table 'TestDb.dbo.TestTable'; column does not allow nulls. INSERT fails.
The statement has been terminated.

Is there any place I should take a look at (some config value in NPoco or something similar) to make sure I get the standard behavior (when a property is null, that a default value is set in the table)?

UPDATE:
I followed [this article](https://github.com/schotime/NPoco/wiki/Debugging-and-Profiling) for troubleshooting and have overridden OnExecutingCommand() to get this command (not important fields obscured):

```
INSERT INTO [TestDb.dbo.TestTable] ([a],[b],[c],[d],[e],[is_visible],[f],[g],[h]) VALUES (@0,@1,@2,@3,@4,@5,@6,@7,@8);SELECT SCOPE_IDENTITY();
	 -> @0 [Int32] = "2"
	 -> @1 [Int32] = "1"
	 -> @2 [String] = "test 1"
	 -> @3 [String] = "test 2"
	 -> @4 [String] = "test 3"
	 -> @5 [DBNull] = ""
	 -> @6 [DBNull] = ""
	 -> @7 [DateTime] = "sre., 21. mart 2018. 15:17:30"
	 -> @8 [DBNull] = ""

```

**Comment by tbasallo** [comment]
Unless I missed something, I think you do have the standard experience. But there are a couple things you could change:

- Update your DB to set a default value
- Change bool? to bool. In this case it will always have a value, which I think is what you need and the default will be false.

Hope that helps.
