### ISSUE TITLE
Any example of ComputedColumn? Handling relations, few beginner questions

### ISSUE THREAD

**Issue by bugproof** [schotime/NPoco#478]
How should I handle relationships with NPoco. Let's say I have 

```csharp
public class Player
{
    public int PlayerID { get; set; }
}

public class Item
{
    public int ItemID { get; set; }
    public int PlayerID { get; set; } // foreign key
}

```
How can I get all items of specified player.

I can do 

```csharp
var playerItems = db.Query<Item>().Where(item => item.PlayerID == playerId);
```

Can you explain how to query it in some other way?

I saw there are things like [ComputedColumn], [ResultColumn], [Ignore] but I don't know where to use them as they're not well documented.

What is the difference between [Ignore] and [ResultColumn]? If in both cases they're not mapped?

I use NPoco with the existing database. Is it possible to also use it in code-first databases? Will it generate tables for me?

Can NPoco auto generate Joins?

**Comment by schotime** [comment]
Have you looked here.
https://github.com/schotime/NPoco/wiki/Mapping

**Comment by enemyofthedawn** [comment]
Yeah but I don't quite understand how does it handle relations
