### ISSUE TITLE
The problem of adding large files to fields

### ISSUE THREAD

**Issue by wo19191** [schotime/NPoco#479]
A field type of the design table is CLOB, which is used to store the base64 bit string of the file。

When the file size is more than 5M, an exception occurs when an object is added to the Insert or InsertBulk. Is this the reason why?

**Comment by schotime** [comment]
Without the exception I'm unable to help here.

**Comment by wo19191** [comment]
The problem has been solved because of the problem of using transaction and setting transaction level too high.
