### ISSUE TITLE
Insert Parent-Child (One to Many) Object

### ISSUE THREAD

**Issue by AZDeveloper777** [schotime/NPoco#480]
Using VS2017, C#, SQL Server 2017 and NPoco 3.7.2.0:

I followed the instructions at:
https://github.com/schotime/NPoco/wiki/One-to-Many-Query-Helpers

for my two classes that have a one to many relationship in the database.

I've verified it works for queries by manually inserting data into both tables and using the db.FetchOneToMany<T> call to get the data into my POCO. I get both the parent and child objects back from the query.

When I try to do a db.Insert(object), only the parent (one) object gets inserted into the database, none of the child (many) objects are inserted and no error is raised.

I've Googled, reviewed the issues in this GitHub project and looked in the Wiki and I've not found an example of how I'm supposed to do this.

Any help would be much appreciated !

**Comment by schotime** [comment]
You have to insert each of the them individually.
