### ISSUE TITLE
How to check if insert failed

### ISSUE THREAD

**Issue by enemyofthedawn** [schotime/NPoco#481]
How should I check if insert has failed, should I catch the exception or it will return some value?

```csharp
_db.Insert(mypoco);
if (mypoco.Id != 0)
{
 // ok
}
```

is this correct? Insert returns id too, but in object, the real type of it is decimal, so when it fails it returns 0?

**Comment by schotime** [comment]
It will exception

**Comment by enemyofthedawn** [comment]
Thanks man!
