### ISSUE TITLE
IncludeMany with predicates?

### ISSUE THREAD

**Issue by grofit** [schotime/NPoco#482]
I have a scenario where I am doing a join on a table and then a where on a column of that table... like so:
```sql
var sql = @"SELECT *
	FROM Table1 as t1
	JOIN Table2 as t2 ON t2.Id = t1.SomeLinkedId
	WHERE t2.Something = @0";
```

Now I have tried to express this as LINQ through 2 avenues:

```csharp
return _database.Query<Table1>()
	.IncludeMany(x => x.Table2.Where(y => y.Something == someValue).ToList())
	.ToList();
```

This just seems to join on everything and doesnt constrain on `someValue`, the other avenue was:

```csharp
return _database.Query<Table1>()
	.IncludeMany(x => x.Table2)
	.Where(x => x.Table2.Any(y => y.Something == someValue))
	.ToList();
```

This blows up saying that `x` is not in scope with an exception.

So there a way to achieve what I am after here?

**Comment by schotime** [comment]
You have already written the query. 
So execute it without Linq.

**Comment by grofit** [comment]
Ok thanks for your time buddy, will stick with the SQL
