### ISSUE TITLE
How to properly insert nested records

### ISSUE THREAD

**Issue by jme71** [schotime/NPoco#483]
I have the following classes.

    [TableName("Schedules")]
    [PrimaryKey("Id")]
    public class Schedule
    {
        public long Id { get; set; }
        public string Name { get; set; }
        [Reference(ReferenceType.Many, ColumnName = "ScheduleId", ReferenceMemberName = "ScheduleId")]
        public List<ScheduleUser> Users { get; set; }
    }

    [TableName("ScheduleUsers")]
    [PrimaryKey("ScheduleId,UserId")]
    public class ScheduleUser
    {
        public long ScheduleId { get; set; }
        public long UserId { get; set; }
    }

I've created a Schedule object, added a couple of ScheduleUser objects to its "Users" property. When I save the schedule, as follows:

    using (var db = Data.Database.GetDatabase())
    {
        db.Insert(mySchedule);
    }

the schedule is added to the Schedules table in the database, but nothing is added to the ScheduleUsers table. How do I get NPoco to automatically insert the records into ScheduleUsers table?

Also, once hooked up properly, can NPoco automatically handle updating an existing schedule object if its "Users" are changed?

**Comment by tbasallo** [comment]
I do not think this can happen as is today. That's EF territory.. If I am wrong I have a bunch of unneeded code :P

You'd have to do it yourself with some code. Insert and then iterate and insert children after setting the parent ID.

**Comment by schotime** [comment]
Yeh, this is not supported a probably never will be.
