### ISSUE TITLE
How to override the sql type for a column?

### ISSUE THREAD

**Issue by jesulink2514** [schotime/NPoco#485]
Hi @schotime, 
I've been struggling with this requirement, cause my database model contains some columns `varchar` and other of type `nvarchar` so DBAs alert me that querying with casting between these types has an impact on performance.

I've explored the `IColumnBuilder` specification and the `DatabaseType` class but I'm not sure how I should implement this change.

Could you guide me a bit around?

**Comment by schotime** [comment]
If you wrap your parameter in an `AnsiString` it will do this automatically.
eg. `new AnsiString("my value")`

**Comment by schotime** [comment]
How is that a problem?

`Db.Query<User>().Where(x=>x.username == new AnsiString ("user")).Single()`

There is another way I'll post later.

**Comment by jesulink2514** [comment]
Ohh I've got it, but you can't specify in the Table mapping the database type, right?, so we need to move our model from using `string` to `AnsiString` wherever we need the adjustment.

**Comment by schotime** [comment]
As I said, I'll let you know another way later.
