### ISSUE TITLE
String comparison with Underscore not working

### ISSUE THREAD

**Issue by radloori** [schotime/NPoco#487]
```
var a = "test_underscore";
sample.Where(i => i.Col1.ToLower().Contains(a);
```

This doesn't return any records even the database has the string (test_underscore) in Col1. This is because of underscore char. Without underscore it works perfectly fine. 

Update:

I am also trying to replace the underscore ( _ ) with pipe ( | ) and do comparison like below, but I cannot use Replace method. 

```
var a = "test_underscore";
a = a.Replace("_", "|");
sample.Where(i => i.Col1.ToLower().Replace("_", "|").Contains(a);
```

**Comment by schotime** [comment]
This is related to this.

https://stackoverflow.com/a/5822
