### ISSUE TITLE
Cache usage example

### ISSUE THREAD

**Issue by ErcinDedeoglu** [schotime/NPoco#490]
I couldn't find an example for how to use cache. Could you share a  code example for this?
https://github.com/schotime/NPoco/blob/master/src/NPoco/Cache.cs

**Comment by schotime** [comment]
It is for internal use only.

**Comment by ErcinDedeoglu** [comment]
Automatically doing it?

**Comment by schotime** [comment]
That's correct.  Reflection etc is cached.

**Comment by ErcinDedeoglu** [comment]
Awesome. Thank you.
