### ISSUE TITLE
Where clause does not return results when data has Underscore char

### ISSUE THREAD

**Issue by radloori** [schotime/NPoco#492]
I have a table with some data with underscore char

Details
```
Id     Name
1      test_test
```

I have tried to search for test_test, but NPoco does not return anything.

Sample Query 
```
var searchString = "TEST_TEST";
IQueryProvider<Details> query = DbConnection.Query<Details>();
query.Where(d=> d.Name.Contains(searchString))
```
Actual Output:
`[]`

Expected Output:
```
[
    {
        "Id" : 1,
        "Name": "test_test"
    }
]
```
I am using MySQL version: 5.7.20

NPoco generated sql query
```
SELECT `D`.`Id` as `Id`, `D.Name` as `Name` 
WHERE upper(`D`.`Name`) like @0 escape '\\'
LIMIT @1 OFFSET @2
	 -> @0 [String] = "%TEST\\_TEST%"
	 -> @1 [Int64] = "10"
	 -> @2 [Int64] = "0"
```

**Comment by schotime** [comment]
https://stackoverflow.com/a/17102616

**Comment by radloori** [comment]
@schotime NPoco is already doing the escaping part right? still I am not getting any results. 

If you see the NPoco generated query, it escapes "_" but still I can't get any results back, but when I try to run the same query on Mysql directly I get results.

**Comment by schotime** [comment]
What if you run the generated query directly?

**Comment by radloori** [comment]
@schotime  I can run it directly, but just wanted to know why NPoco doesn't get any results even though the generated query is correct.

**Comment by schotime** [comment]
Well that's the 1 millions dollar question.

**Comment by radloori** [comment]
I am attaching a sample project to reproduce this issue. 

Note: Please change the Mysql connection string 

[ConsoleApp5.zip](https://github.com/schotime/NPoco/files/2120443/ConsoleApp5.zip)

**Comment by radloori** [comment]
@schotime  With the below changes to MySqlSqlExpression.cs, the search worked fine. 

```
protected override string EscapeParam(object par)
{
    var param = par.ToString().ToUpper();
    param = param
            .Replace("\\", EscapeChar)
            .Replace("_", "\\_")
            .Replace("%", "\\%");
    return param;
}
```

Please let me know your thoughts on this.

**Comment by radloori** [comment]
Hi @schotime 

Here are the queries executed by NPoco and MySQL:

**NPoco:** 
SELECT `P`.`Id` as `Id`, `P`.`SearchTerm` as `SearchTerm` 
FROM `Product` `P`
WHERE upper(`P`.`SearchTerm`) like @0 escape '\\\\'
	 -> @0 [String] = "%TEST\\\\_TEST%"


**MySQl Query from logs:**
SELECT `P`.`Id` as `Id`, `P`.`SearchTerm` as `SearchTerm` 
FROM `Product` `P` 
WHERE upper(`P`.`SearchTerm`) like '%TEST\\\\\\\\_TEST%' escape '\\\\'

Mysql appends extra backslashes when executing the query passed by NPoco only for the searchTerm and the escape sequence looks fine. 

Please let me know what I can do here?

Thanks.

**Comment by schotime** [comment]
@radloori I've pushed this in. It will be in the alpha-3 released later today.
