### ISSUE TITLE
Custom DatabaseType

### ISSUE THREAD

**Issue by asherber** [schotime/NPoco#493]
I'd like to write a custom `DatabaseType` to support an oddball legacy db I work with. One problem I'm running into is that the `Database.ExecuteXxxHelper()` methods are marked as `internal`. (I need to override `DatabaseType.ExecuteInsert()` because this db doesn't support `SELECT @@IDENTITY`, but then I have no way of calling `ExecuteNonQueryHelper()` myself.)

Would it be possible to change these methods to `public`? Or to add `protected` methods on `DatabaseType` that are facades over them? I can prepare a PR if one of these approaches is acceptable.

**Comment by schotime** [comment]
This has been done in the latest 3.9.4
You can cast `Database` to `IDatabaseHelpers` and you will get the methods.

**Comment by asherber** [comment]
Nice, thanks!
