### ISSUE TITLE
Azure support

### ISSUE THREAD

**Issue by makingbloke** [schotime/NPoco#495]
Is there any plans to add Azure SQL support?

Thanks

**Comment by schotime** [comment]
Not by me atm but have to take pull requests. Not sure what the differences even are,  but I'm assuming that it's similar to sqlserver. Have you tried it and it doesn't work?

**Comment by makingbloke** [comment]
I’ll be honest I’ve only just started researching it, I just wondered if
there are any plans at this stage. (This is for a personal project so it’s
time permitting). I guess the biggest change would be the need to retry
things when certain exceptions occur.

Thanks

**Comment by gunnim** [comment]
https://github.com/davidsavagejr/NPoco.SqlAzure

**Comment by makingbloke** [comment]
Thanks. I’ll have a look

**Comment by AZDeveloper777** [comment]
I've been using schotime/NPoco with SQL Azure in multiple production apps for quite some time, perhaps a year at least.
AFAIK, so far I've not been bitten by the problem of transient exceptions.
YMMV.

**Comment by tbasallo** [comment]
@AZDeveloper777  Agreed. 

@makingbloke  If you need to handle transient type errors, it's probably best to use something like Polly, which has a plethora of configurations.
