### ISSUE TITLE
First query on a table needs much time

### ISSUE THREAD

**Issue by VangelisAlSghir** [schotime/NPoco#496]
Hello there

I have a table with many foreign keys, so I have like 10 of these in my Poco class:
```
[ResultColumn]
[Reference(ReferenceType.OneToOne, ColumnName = "CreatedById", ReferenceMemberName = "Id")]
public UserDto CreatedBy { get; set; }
``` 
Now we have the problem that the first query we do on this table (after we start the server with the code) needs about 10 seconds until we receive a response. I already checked the network and the database which both aren't the problem.

As soon as I remove the properties in the poco class with the reference attribute, it gets much faster (from about 10 seconds to about 0.1 seconds). 

The point is that even if we don't load the references (so the query has no include) it needs so much time. If I do another query on the same table just afterwards, it is much faster again.

Any ideas where the problem is or what I'm doing wrong?

This is the query I run:
```
IDatabase db = new Database("test");
var bla = db.Fetch<ArticleDto>("SELECT * FROM Article");
```
If the ArticleDto contains no references, this takes about 100ms for 10000 entries on the first time and about 17ms on the second time.
If the ArticleDto contains something like this:
```
[ResultColumn]
[Reference(ReferenceType.OneToOne, ColumnName = "CreatedById", ReferenceMemberName = "Id")]
public UserDto CreatedBy { get; set; }
```
it takes about 9800ms on the first time and about 138ms on the second.

EDIT: I just saw that it's slightly faster without the [ResultColumn] and it seems like it's not needed anyways because references aren't loaded by default too. The problem stimm exists though since it's only about 0.2 seconds faster.

**Comment by schotime** [comment]
Does the UserDto have other UserDtos on it?

**Comment by VangelisAlSghir** [comment]
No it doesn't. But it contains a FranchiseeDto, which contains a List of ConcurrentUserDtos, which also contains a FranchiseeDto. Is this a problem?

**Comment by schotime** [comment]
Well it could be because it has to recurse all the way down. If u can post an example of the model then I can have a look.

**Comment by VangelisAlSghir** [comment]
Do you have any help for me or tips, how I can make this faster? I'm glad for every help I get.

**Comment by schotime** [comment]
Haven't had any time to look at this yet.

Heres my tip though. Don't use recursive models with References. 
You are calling them DTO's so treat them as DTOS.

**Comment by VangelisAlSghir** [comment]
Okay, thank you.

But shouldn't there be a way to have these References in the DTOs and be ignored if I don't explicitly say "Please load the data from this and this reference"?

**Comment by schotime** [comment]
Its not loading the data, but it has to grab all the meta data, and theres probably heaps cause you have recursive references, and my check for recursiveness probably doesn't cover many's. Thats my thinking anyways.

**Comment by VangelisAlSghir** [comment]
Well then I'll first remove the manys and look what's happening. If it gets faster with only removing the manys, I'm fine with that since the effort to work around them is not big. I'll write my results here so it may helps other people.

**Comment by schotime** [comment]
This test runs in 1.7ms so unless you can add more information here I can't reproduce.

```csharp
    public class PerfTestMetadataTests : BaseDBDecoratedTest
    {
        [Test]
        public void Test()
        {
            var sw = Stopwatch.StartNew();
            Database.PocoDataFactory.ForType(typeof(ArticleDto));
            sw.Stop();
            Console.WriteLine(sw.ElapsedTicks);
        }
    }

    [PrimaryKey("IdArticle", AutoIncrement = true)]
    public class ArticleDto : BaseDto
    {
        [Column("IdArticle")]
        public override int Id { get; set; }

        public int CreatedById { get; set; }

        //[Reference(ReferenceType.OneToOne, ColumnName = "CreatedById", ReferenceMemberName = "Id")]
        //public UserDto CreatedBy { get; set; }

        public int? CustomerContactId { get; set; }

        //[Reference(ReferenceType.OneToOne, ColumnName = "CustomerContactId", ReferenceMemberName = "Id")]
        //public ContactDto CustomerContact { get; set; }

        public int FranchiseeId { get; set; }

        [Reference(ReferenceType.OneToOne, ColumnName = "FranchiseeId", ReferenceMemberName = "Id")]
        public FranchiseeDto Franchisee { get; set; }

        public int? PostageId { get; set; }

        //[Reference(ReferenceType.OneToOne, ColumnName = "PostageId", ReferenceMemberName = "Id")]
        //public PostageDto Postage { get; set; }

        public int StatusId { get; set; }

        //[Reference(ReferenceType.OneToOne, ColumnName = "StatusId", ReferenceMemberName = "Id")]
        //public StatusDto Status { get; set; }

        public int SupplierContactId { get; set; }

        //[Reference(ReferenceType.OneToOne, ColumnName = "SupplierContactId", ReferenceMemberName = "Id")]
        //public ContactDto SupplierContact { get; set; }

        //[Reference(ReferenceType.Many, ColumnName = "IdArticle", ReferenceMemberName = "ArticleId")]
        //public List<JournalDto> JournalEntries { get; set; }

        //[Reference(ReferenceType.Many, ColumnName = "IdArticle", ReferenceMemberName = "ArticleId")]
        //public List<TaskDto> Tasks { get; set; }

        //[Reference(ReferenceType.Many, ColumnName = "IdArticle", ReferenceMemberName = "ArticleId")]
        //public List<ToDoDto> ToDos { get; set; }
    }

    [PrimaryKey("IdFranchisee", AutoIncrement = true)]
    public class FranchiseeDto : BaseDto
    {
        [Column("IdFranchisee")]
        public override int Id { get; set; }

        [ResultColumn]
        [Reference(ReferenceType.Many, ColumnName = "IdFranchisee", ReferenceMemberName = "FranchiseeId")]
        public List<ConcurrentUserDto> ConcurrentUsers { get; set; }

        //[ResultColumn]
        //[Reference(ReferenceType.Many, ColumnName = "IdFranchisee", ReferenceMemberName = "FranchiseeId")]
        //public List<FranchiseeActivationDto> Activations { get; set; }
    }

    public class BaseDto
    {
        public virtual int Id { get; set; }
    }

    [TableName("ConcurrentUser")]
    [PrimaryKey("IdConcurrentUser", AutoIncrement = true)]
    public class ConcurrentUserDto : BaseDto
    {
        [Column("IdConcurrentUser")]
        public override int Id { get; set; }

        [ResultColumn]
        [Reference(ReferenceType.OneToOne, ColumnName = "FranchiseeId", ReferenceMemberName = "Id")]
        public FranchiseeDto Franchisee { get; set; }
    }
```

**Comment by schotime** [comment]
Post the full example so I can have a look why.
