### ISSUE TITLE
SqlClient V4.5.0 Upgrade in V4?

### ISSUE THREAD

**Issue by eNettMattD** [schotime/NPoco#497]
We're facing an issue with TransactionScope in .Net Core 2.1. There is a bug in SqlClient V4.4.0 (https://github.com/dotnet/corefx/issues/24282). Are there plans to upgrade to V4.5 of SqlClient in V4 of NPoco?

**Comment by schotime** [comment]
https://github.com/StackExchange/Dapper/issues/1026#issuecomment-390473120
