### ISSUE TITLE
Serialized column and data compression feature

### ISSUE THREAD

**Issue by enrico-padovani** [schotime/NPoco#498]
Hi,

I'm ware of Serialize feature which allows you to treat a column as a class that will be serialized as string into the database, this is great.

However I'm in the need of compressing data, so I was wondering if I could take advantage of some hook / interceptor in order to execute my Compress / Decompress function during serialization / deserialization.

Note: I'm using sqlite.

**Comment by schotime** [comment]
Would have to have a look but I dont think there is a way. It is already using the mapper hook to accomplish this. 

What you could do is setup your own attribute and then have a mapper that uses it, instead of using the built in serialize.
