### ISSUE TITLE
A question about new Database("connStringName")?

### ISSUE THREAD

**Issue by carvinchen** [schotime/NPoco#499]
Hello everyone,

I am trying to connect a remote database by using IDatabase db = new Database("connStringName"); and not sure what kind of "connStringName" should i give...

MyModel is a table of remote database

My Code:
`
            string password = "mypw";
            string connStr =
                "server=myserver.net;user=user;database=mydb;port=3306;password=" + password;

            IDatabase db = new Database(connStr);
            List<MyModel> myList = db.Fetch<MyModel>("select id, ort, partner from
            MyModel");

`

I dont get any results...Can anyone give me any suggestions and tips? 

Cheers!

Carvin

**Comment by schotime** [comment]
That would be the name of the connection string in web.config.
Use the other overloads if you want to pass the action connection string.

**Comment by carvinchen** [comment]
Thank you for your anwser! Would you like to show me a example about new Database() function? 

Cheers!

**Comment by schotime** [comment]
https://github.com/schotime/NPoco/wiki/Database-Constructor-Alternates
