### ISSUE TITLE
Where Lambda expression ignoring NULLs

### ISSUE THREAD

**Issue by hmvella** [schotime/NPoco#501]
Hi,

Our team is currently in the final stages of migrating a large solution from Entity Framework to NPoco and we stumbled upon some quirky behaviour:

If the Appointments table has the following rows

| id                 | hidden         | 
| ------------- |:-------------:| 
| A                  | True             | 
| B                  | False            |  
| C                  | NULL           |  

**Query 1.** [_Entity Framework_] var appointments = new DBEntities().Appointments.Where(c=> c.hidden != true).ToList();

**Query 2.** [_NPoco_] var appointments = new QueryProvider< Appointment>(db1).Where(c => c.hidden == null || c.hidden != true).ToList()

 **Query 3.** [_NPoco_] var appointments = new QueryProvider< Appointment>(db1).Where(c => c.hidden != true),ToList();

Query 1 will return **2** rows;
Query 2 will return **2** rows; 
Query 3 will return **1** row; 

We were expecting all three queries to return 2 given null is also not equal to true. Is this by design? 

Thanks, and keep up the great work!

**Comment by schotime** [comment]
NPoco directly translates LINQ to sql. It doesn't try and be all fancy like EntityFramework. Its actually scares me that this is the case. As can be seen below, only 1 result is return when running this against SQL Server.

```sql
select * from (
	select 1 as id, 1 as value
	union
	select 2 as id, 0 as value
	union
	select 3 as id, null as value
) a
where value != 1
```

**Comment by hmvella** [comment]
Fair enough. Alright, thanks.
