### ISSUE TITLE
.IncludeMany and OrderBy

### ISSUE THREAD

**Issue by vllama** [schotime/NPoco#506]
I have the following code:
```chsarp
var resultWithO2M = Database.Query<AssetType>()
                 .IncludeMany(x => x.Assets, NPoco.Linq.JoinType.Left)
                 .OrderBy( x => x.Id)
           .ToList();
```

It generateds SQL like below:
```sql
SELECT "AT"."id" as "Id", "AT"."id_asset_category" as "IdAssetCategory"
--... ommited for brevity
FROM asset_types "AT"  
  LEFT JOIN assets "A32" ON "AT"."id" = "A32"."id_asset_type"  
ORDER BY "Id" ASC
```

1. IMO the  ORDER BY Should be : "AT"."Id" (*especially since my assets table also has an Id field*)
2. The query seems to require the OrderBy to function properly. Maybe OrderBy shold be automatically added when using IncludeMany otherwise you will duplicate the Master table in the relationship depending on the natural order the database returns rows in.

**Comment by vllama** [comment]
Just realized this is probably related to [#496](https://github.com/schotime/NPoco/issues/496)

**Comment by fnktastic** [comment]
I faced the same problem and was wondering why so basic thing is not implemented here. Also if you want, for example, get top 10 items,  the includemany will fail. Generated SQL will return top 10 from left join and that means that if the first item from our top 10 will have 15 nested assets you will have 1 item with 10 assets, so limitation completely fails.

**Comment by 0shi** [comment]
> The query seems to require the OrderBy to function properly. Maybe OrderBy shold be automatically added when using IncludeMany otherwise you will duplicate the Master table in the relationship depending on the natural order the database returns rows in.

We also had this issue with IncludeMany, took a bit of debugging to work out that NPoco required contiguous blocks of results associated with each parent object.

**Comment by schotime** [comment]
Yeh, SQL Server does this automatically, whereas others don't. 😞
