### ISSUE TITLE
Where().When()

### ISSUE THREAD

**Issue by shervinw** [schotime/NPoco#507]
Does there exist the possibility to add conditional statements within the fluent interface with chaining and without SQL templating. for example:

```
db.Query<ProjectPartner>().Include(p => p.project).Include(p => p.project.customer)
  .Where(p => p.inviteStatus == paramProjectPartnerInviteStatus)
    .When(p => paramProjectPartnerInviteStatus != ProjectPartnerInviteStatus.Undefined)
  .Where(p => p.assignedTo == paramAssignedTo)
    .When(p => paramAssignedTo != null)
```

**Comment by schotime** [comment]
Create your own where extension method called WhereWhen etc that check the first parameter and if true appends the where statement.

**Comment by shervinw** [comment]
Thanks, here is my code
`public static class CustomExtensions
    {
        public static IQueryProvider<T> WhereWhen<T>(this IQueryProvider<T> source, Expression<Func<T, bool>> whereExpression, bool append)
        {
            if (append)
                return source.Where(whereExpression);
            else
                return source;
        }
    }`

` var result = db.Query<Project>()
                .WhereWhen(p => p.budgetMin >= pBudgetMin, pBudgetMin != null)
                .WhereWhen(p => p.budgetMax <= pBudgetMax, pBudgetMax != null)
                .ToPage(pageNumber, pageSize);`
