### ISSUE TITLE
IDatabaseHelpers

### ISSUE THREAD

**Issue by mzy666888** [schotime/NPoco#509]
I can't find IDatabaseHelpers this file.

**Comment by zpqrtbnk** [comment]
Confirmed - recent commit added references to `IDatabaseHelpers` but the interface is nowhere to be found (forgot to commit), thus breaking the build. Kinda critical ;-)

**Comment by schotime** [comment]
Oops....will have a look in the morning. Soz

**Comment by schotime** [comment]
Sorry for the delay, but its back.

**Comment by zpqrtbnk** [comment]
Thanks!
