### ISSUE TITLE
How update PrimaryKey value

### ISSUE THREAD

**Issue by josejavieroverline** [schotime/NPoco#513]
I am a user of NPoco. Thanks for this great tool !!!

I have problems when I try to update the value of the primary key. For example:

_var db = new DataBase("constr");
db.Insert(new User { UserId = 1, Email = "contact@dom.com" });
var u = db.SingleById< User>(1);
u.UserId = 2;
u.Email = "newcontact@dom.com";
db.Update(u, 1);_

The LastSQL is:
            LastSQL = "UPDATE [User] SET [Email] = @0 WHERE [UserId] = @1"

**SQL not include SET [UserId] = .....**

How to update the UserId value?
Thank's 
José Javier Villar

**Comment by schotime** [comment]
```
db.Execute("update users set userid = @1 where userid = @0", userIdOld, userIdNew);
```

Sorry but not something thats currently supported.

**Comment by josejavieroverline** [comment]
Mil gracias.

**Comment by josejavieroverline** [comment]
Hi Adam, 
Forgive my daring, it would be possible to update primary key only when indicated by modifying this:
In Database.cs ?
Method
private TRet UpdateImp<TRet>(string tableName, string primaryKeyName, object poco, object primaryKeyValue, IEnumerable<string> columns, Func<string, object[], Func<int, int>, TRet> executeFunc, TRet defaultId)

**Original**:
`...
// Don't update the primary key, but grab the value if we don't have it
                if (primaryKeyValuePairs.ContainsKey(pocoColumn.ColumnName))
                { 
                    if (primaryKeyValue == null)
                         primaryKeyValuePairs[pocoColumn.ColumnName] = this.ProcessMapper(pocoColumn, pocoColumn.GetValue(poco));
                    continue;
                }

				
...`

**Suggestion:**

`// Don't update the primary key, but grab the value if we don't have it
                if (primaryKeyValuePairs.ContainsKey(pocoColumn.ColumnName))
                {
                    if(primaryKeyValue == null) {
                        primaryKeyValuePairs[pocoColumn.ColumnName] = this.ProcessMapper(pocoColumn, pocoColumn.GetValue(poco));
                        continue;
                    }                    
                }
...`

Thank's
