### ISSUE TITLE
Delete with Join

### ISSUE THREAD

**Issue by rhegner** [schotime/NPoco#514]
The `IDeleteQueryProvider<T>` does not seem to support building join statements (using something like `IDeleteQueryProvider<T>.Import(...)`.

Is that something which is on the roadmap? Is there a workaround for this?

I'm currently using hand-written SQL (ExecuteAsync) which works fine for MySQL and MSSQL, but now I also need to support Postgres which needs different SQL. Would be nice if NPoco would abstract these differences.

**Comment by schotime** [comment]
Sorry but this is not on the road map and is not something this library needs as core functionality.

**Comment by schotime** [comment]
Yes. V4 is pretty stable there are just some breaking API changes.
