### ISSUE TITLE
use Update  set where id=@0 more '

### ISSUE THREAD

**Issue by mzy666888** [schotime/NPoco#515]
I use
`Context.Update<GovernmentPolicy>("update governmentPolicy set IsDelete='Y' where id=@0 ", id);`
the mariadb bug 

> "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'update governmentPolicy set IsDelete='Y' where id=1' at line 1"

I find  id=1 more "'" in the sql

**Comment by schotime** [comment]
You don't specify the update statement if using `Update`.

`Context.Update<GovernmentPolicy>("set IsDelete='Y' where id=@0 ", id);`
