### ISSUE TITLE
Where is source code for v3.9.4?

### ISSUE THREAD

**Issue by rhegner** [schotime/NPoco#516]
In my project I'm currently referencing NPoco 3.9.4.
Where can I find the source code for this version? The latest version tag I can see in this repository is rel-3.8.0.

**Comment by schotime** [comment]
The latest master

**Comment by rhegner** [comment]
Thank you!
I just realized that I can find the sources for a given version pretty easily by looking at the [history of NPoco.csproj](https://github.com/schotime/NPoco/commits/master/src/NPoco/NPoco.csproj)
