### ISSUE TITLE
SqlCE wants null parameters to have a type

### ISSUE THREAD

**Issue by zpqrtbnk** [schotime/NPoco#517]
In `Database.SetParameterValue` when the `value` parameter is `null` we currently just set the database parameter value to `DBNull.Value`:

```
if (value == null)
{
  p.Value = DBNull.Value;
  return;
}
```

It turns out that Sql CE does not like this. If the parameter is used, for instance, in a `COALESCE(@0, -1)` expression, Sql CE throws an error about invalid function arguments. Sql CE wants the parameter to have a type. The type itself does not seem to matter, since the value is null. All in all, this seems to fix the issue:

```
if (value == null)
{
  p.Value = DBNull.Value;
  p.DbType = DbType.String; // SQL CE wants a type
  return;
}
```

Can do a PR if you want me to.

**Comment by zpqrtbnk** [comment]
Workaround: currently running with an override to `Database.CreateCommand`:

```
public override DbCommand CreateCommand(DbConnection connection, CommandType commandType, string sql, params object[] args)
{
  var command = base.CreateCommand(connection, commandType, sql, args);

  if (!(DatabaseType is DatabaseTypes.SqlServerCEDatabaseType)) return command;

  foreach (DbParameter parameter in command.Parameters)
    if (parameter.Value == DBNull.Value)
      parameter.DbType = DbType.String;

  return command;
}
```

**Comment by schotime** [comment]
DbType doesn't seem to be able to be null. By default it would be AnsiString, so i'm gonna close this for now as you have a work around anyways.
