### ISSUE TITLE
sqlite 8 hours difference

### ISSUE THREAD

**Issue by newyhj** [schotime/NPoco#519]
var sourceCategory = DbContext.SingleOrDefaultById<Category>(entity.Id);
                entity.NodeList = sourceCategory.NodeList;
                entity.Depth = sourceCategory.Depth;
                **entity.CreateTime = sourceCategory.CreateTime;**  //here
                entity.EditTime=DateTime.Now;   
                result = DbContext.Update(entity)
ex:
sourceCategory.CreateTime is 2018/12/7 16:38:25
update after:
database record createtime is 2018/12/8 0:38:25
test sqlce/sql server is ok,but sqlite value difference. orm mistake?

**Comment by dampee** [comment]
Sounds like a timezone difference which is sounds like a configuration issue on the SQL engine. To prove the error, I think it's best to supply create scripts for both of the table which you have.  And also have a few lines of code where you insert a record and retrieve a record proving it is not working.  Or maybe a stripped down console application which you share using a repo or gist. Don't forget to mention the version of Npoco you are using.

As a sidenode, our "best practice" we have in our company: store create dates as UTC to be sure we do not have timezone issues. For other dates we use DateTimeOffset to be sure that we store the offset.
