### ISSUE TITLE
Where in the code do you parameterize your sql queries

### ISSUE THREAD

**Issue by ryanvgates** [schotime/NPoco#520]
Some of the code that references NPoco for my project was flagged as vulnerable to SQL Injection. Where in the code do the arguments get parameterized? I need something to provide evidence that it's a false positive. For example, the call looks like the following.

    var db = new Database("mydb");
    var user= db.FirstOrDefault<User>("Select id, email from Users where username = @0", username);

Please let me know if you need any additional information. Thank you.

**Comment by schotime** [comment]
https://github.com/schotime/NPoco/blob/4292173cb8616808e93385d4642d861621547424/src/NPoco/Database.cs#L473
