### ISSUE TITLE
Where like clause doesn't return results

### ISSUE THREAD

**Issue by skartknet** [schotime/NPoco#522]
I'm creating a Sql object and conditionally adding clauses to it:
` Sql sql = new Sql("SELECT *, count(*) over() as totalRows FROM customMemberData as md RIGHT JOIN AspNetUsers as u ON md.id = u.Id");`

One of the clauses breaks the query and it doesn't return results (item is a Tuple<string,string>):
`sql.Where("@0 LIKE N'%@1%'", item.Item1, item.Item2);`

If I do it without parameterised query it works as expected:
` sql.Where($"{item.Item1} LIKE '%{item.Item2}%'");`

then my query is just like this: 
`database.Fetch<MemberData>(sql);`

Any ideas what might be happening?

thanks.

**Comment by schotime** [comment]
You need to put the % inside the parameter.

```cs
sql.Where("@0 LIKE @1, item.Item1, "%"+item.Item2+"%");
```

**Comment by skartknet** [comment]
Of course!. thanks for that.

**Comment by schotime** [comment]
you will probably need to make sure the types of the parameters are the same when using them. The second one will implicitly cast to the type of the right i'm guessing. Try this out using sql parameters in a query window and see what the results are.
