### ISSUE TITLE
How to setup all Datetime Colomn ForceToUtc = false?

### ISSUE THREAD

**Issue by ko300** [schotime/NPoco#524]
How to setup all Datetime Colomn ForceToUtc = false?

**Comment by schotime** [comment]
You can do it I believe using the fluent conventoons

**Comment by schotime** [comment]
And why aren't you storing datetime in UTC. *Naughty naughty*

**Comment by ko300** [comment]
database saved is  localtime。So all ColumnAttribute need set ForceToUtc = false

**Comment by schotime** [comment]
yes unless fluent conventions are used.
