### ISSUE TITLE
DEFAULT NOT NULL constraint and INSERT

### ISSUE THREAD

**Issue by dark2201** [schotime/NPoco#528]
It's not possible to skip such columns in `Insert` (i.e. value has to be explicitly set)

**Comment by handsome-b-wonderful** [comment]
If your schema defines the column as NOT NULL what would you expect the behaviour to be if you don't provide a value? I'm not sure how this would work. Can you provide more detail?

**Comment by dark2201** [comment]
It works if executed directly on the database (SQL server) when you skip NOT NULL DEFAULT column in the statement.

**Comment by schotime** [comment]
Mark them as `Result` columns and they will only be returned when querying, not inserting.

**Comment by MakiseKurisu** [comment]
We are currently having the same issue. Marking as ```ResultColumn``` does not work as the user can still provide their value should they have one. From the [wiki](https://github.com/schotime/NPoco/wiki/Mapping) they "will not be included in inserts or updates" which is not what we want. We only want it to be excluded if the value is null.

There are a few issues that is related to this (like #476). Unfortunately our field is a varchar, which is mapped to string in C# and cannot be changed to a non nullable type (we can't move to C# 8 yet).

Some other compliants on this issue with string type (including PetaPoco): [[1]](https://stackoverflow.com/questions/32758489/petapoco-npoco-partial-insert) [[2]](https://samsaffron.com/archive/2012/01/16/that-annoying-insert-problem-getting-data-into-the-db-using-dapper) So this is a common scenario that worth to look at.

I think #572 is a good candidate to solve this problem. @schotime
