### ISSUE TITLE
Returned JSON from MS SQL gets cut off in length

### ISSUE THREAD

**Issue by ZwapKillrath** [schotime/NPoco#531]
I have an MS SQL table and a stored proc returning a JSON string (FOR JSON PATH). The results are ok in length in Management Studio but when NPOCO has had its way with the string-data it clips the result to 2033 chars. Is there a max length on the returned value from an ExecuteScaler method or is this an error?

Stored proc in MS SQL:
...
	SELECT		CityId,
				ZipCode,
				CityName
	FROM		Cities
	WHERE		RegionId = @RegionId
	ORDER BY	CityName
	FOR JSON PATH
...

.NET Core code:
...
        return db.ExecuteScalar<string>(Sql.Builder.Append(statement, args));

**Comment by schotime** [comment]
It seems this is a SQL client driver thing. In this case you are probably better off writing the raw reader code. The connection, and command can be used from NPoco to make it a little easier.

https://social.msdn.microsoft.com/Forums/en-US/982edf0e-e3e2-4fe4-87b0-6eaca7296152/truncated-string-returned-by-stored-procedure?forum=adodotnetentityframework

**Comment by ZwapKillrath** [comment]
Ok. I will try another driver against the MS SQL server.
As a note: When using the Oracle.ManagedDataAccess.Core v. 2.18.3 against an Oracle DB which delivers the result as a clob then there is no problem. Just tried with 20k of chars.
