### ISSUE TITLE
OneToMany query order problem

### ISSUE THREAD

**Issue by jornvl90** [schotime/NPoco#534]
Hello,

I came into the following situation:

I have a class ClubMember with multiple CareerItems as children.
Doing this query :
FetchOneToMany<Member>(x => x.CareerItems, "select p.*, m.* from \"ClubMembers\" p left join \"CareerItems\" m on p.\"Id\" = m.\"MemberId\"");

NPoco doesn't seem to merge the correct Members together if they are not returned in correct order by the database.

If I run the query on the database I get these results:
![image](https://user-images.githubusercontent.com/33755790/56644688-7667c200-667c-11e9-9e71-90f05128d495.png)

The members are not next to eachother.

Database.cs in the NPoco sourcecode has the function
private IEnumerable<T> ReadOneToMany<T>(T instance, DbDataReader r, DbCommand cmd, Expression<Func<T, IList>> listExpression, Func<T, object[]> idFunc)

In the function it seems like only the previous poco is considered, which means the function only works if the parents would be next to eachother in the query result..?

**Comment by schotime** [comment]
Yeh, Sql Server always puts them in order. If you're using another db, which it looks like Postgres then you will need to include an order by statement.
