### ISSUE TITLE
CTE WITH clause in template

### ISSUE THREAD

**Issue by tonag** [schotime/NPoco#538]
Hi all, 
I'm trying to use a CTE in a template added to a sqlbuilder in a paged fetch.
Is it any way to make it work? I mean that the generated query wraps the template code (starting with the WITH clause)  with another select involving pagination that is sintattically wrong (due to the ";WITH" part).
Thanks for any attention.

GT

**Comment by schotime** [comment]
Sorry, you will have to write the paging code yourself if on old SQL.

It possibly might work if you are using the SQL server 2012 database type passed to the constructor cause it just appends the paging info.
