### ISSUE TITLE
AnsiString error when passing null

### ISSUE THREAD

**Issue by FastTI** [schotime/NPoco#539]
I'm getting an error when trying to wrap item to **AnsiString** ( http://prntscr.com/nrv8hu ) for prevent implicit conversion to nvarchar (I need varchar instead)  when passing **null** to execute

Should I check if my item is null then return null without Ansi wrapping or better way exists for prevent error?

Npoco version 3.1.0.0

**Comment by schotime** [comment]
Yes I would say check for null before but I will see if we can do something better in future.
