### ISSUE TITLE
How to Sharding MYSQL Table

### ISSUE THREAD

**Issue by k-yaobo** [schotime/NPoco#540]
my table like , table_2017, table_2018, ....

**Comment by k-yaobo** [comment]
How can I set a new  table name from Model

**Comment by schotime** [comment]
you could have multiple database implementations that used different conventions, otherwise you could always replace a placeholder in sql in `OnCommandExecuting`

**Comment by k-yaobo** [comment]
When a table data more than 10 million records.I need a table.Read to optimize performance NPOCO needs to support table, read and write function

**Comment by k-yaobo** [comment]
like this :https://github.com/2881099/FreeSql/wiki/%E5%88%86%E5%8C%BA%E5%88%86%E8%A1%A8
![QQ截图20190524094111](https://user-images.githubusercontent.com/21329253/58296882-25c4bf80-7e08-11e9-8e25-f39b082b9af7.png)

`var logRepository = fsql.GetGuidRepository<Log>(null, oldname => $"{oldname}_201903");`
