### ISSUE TITLE
'42P08: inconsistent types deduced for parameter $4'

### ISSUE THREAD

**Issue by ChembanKuthira** [schotime/NPoco#542]
Using Npoco with Npgsql in C#  (Update)

When null values are passed as parameters , Npoco will pass only a single parameter=null  instead of separate parameters with same value.  Here it will throw the error : '42P08: inconsistent types deduced for parameter $4' .   

Beacause Npoco will get confused on datatype when same parameter is passed  to interger and text datatype column

**Comment by schotime** [comment]
What version of NPoco are you using. This doesn't do this by default in the latest version.

**Comment by ChembanKuthira** [comment]
Npoco version = 2.0.0.0 , Runtime Version =v4.0.30319

**Comment by ChembanKuthira** [comment]
As a workaround , im using the below code.

public static int UpdateWhere<T, TKey>(this IDatabase database, T obj, Expression<Func<T, bool>> where, Expression<Func<T, TKey>> onlyFields)
        {
            var ev = database.DatabaseType.ExpressionVisitor<T>(database);
            ev.Update(onlyFields);
            ev.Where(where);
            var tableName = obj.GetTheType().Name.ToLower();
            string sql = "SELECT column_name,data_type FROM information_schema.COLUMNS WHERE TABLE_NAME = '" + tableName+"'";
            var tabDetails = database.Fetch<TableDetails>(sql);
            var updateStatement = ev.Context.ToUpdateStatement(obj, false, onlyFields == null);
            var tempUpdateStmnt = updateStatement;
            foreach (var Item in tabDetails)
            {
                if (tempUpdateStmnt.Contains(Item.Column_Name))
                {
                    int index =tempUpdateStmnt.IndexOf(Item.Column_Name);
                    int comaIndex = -1;
                    if (index < tempUpdateStmnt.IndexOf("WHERE"))
                    {
                        comaIndex = tempUpdateStmnt.IndexOf(',', index);
                        if (comaIndex < 0)
                        {
                            comaIndex = tempUpdateStmnt.IndexOf("WHERE", index);
                        }

                        string castType = "::" + Item.Data_Type+" ";
                        tempUpdateStmnt = tempUpdateStmnt.Insert(comaIndex, castType);
                    }
                    
                }
            }
            return database.Execute(tempUpdateStmnt, ev.Context.Params);
        }

**Comment by schotime** [comment]
This has been fixed in the for a few years. Upgrade to v4.
