### ISSUE TITLE
using Sql Builder with Postgres

### ISSUE THREAD

**Issue by statementiq** [schotime/NPoco#545]
I am trying to build custom SQL from an advanced search form. I have a typed object that I'm trying to bind to with the correct data types that match the data types in the Postgres DB. 
The SQL is generated correctly, but when it executes, I get this error: 

No operator matches the given name and argument type(s). You might need to add explicit type casts. 

It appears its trying to cast ints to strings or vice-versa. Is there a way to specify the data types in Where(string, args[]) method, or some where else?

**Comment by schotime** [comment]
You can use `NpgsqlParameter`s as values if they're not working with the defaults
