### ISSUE TITLE
SqlBuilder Where(string, args) makes object null

### ISSUE THREAD

**Issue by plsft** [schotime/NPoco#546]
Using this code: 

```
var finalArgs = args.ToArray();
var sql = new NPoco.Sql(string.Empty, finalArgs);

sql.Select(parser.SelectClause); 

if (!parser.FromClause.IsNullOrEmpty())
   sql.From({$" from {parser.FromClause} ");

if (!parser.WhereClause.IsNullOrEmpty())
   sql.Where(parser.WhereClause, finalArgs);
```

When the Where method is executed, it makes the object null. During the .Select call and .From call the object updates normally. It also doesn't seem to import the "finalArgs" I'm passing in. This is a blocker for me as I cannot get proper Sql object back from this call. 

![null-npoco-builder](https://user-images.githubusercontent.com/13736152/59159520-c1a52b00-8a98-11e9-8321-620244ad1aff.jpg)

**Comment by schotime** [comment]
Its working as expected.

```cs
var sql = new Sql();

sql.Select("blah, boo, bar");
sql.From("mytable");
sql.Where("test = @0", "1");

Console.WriteLine(sql.SQL);
Console.WriteLine(sql.Arguments);
```

```sql
SELECT blah, boo, bar
FROM mytable 
WHERE (test = @0)
```

```cs
["1"]
```
