### ISSUE TITLE
Version column and DBConcurrencyException

### ISSUE THREAD

**Issue by enrico-padovani** [schotime/NPoco#550]
Hi,

I'm updating a record with a version column mapped as `p.Column(x => x.Version).Version(VersionColumnType.Number).WithName("db_version");`

when UpdateAsync with a version mismatch it throws an Exception instead of DBConcurrencyException. I'm on NPoco 3.9.4 with .net core 2.2.0

It used to work on .NET 4.7. Any difference?

**Comment by schotime** [comment]
It probably got to do with it selecting the wrong version of it. v5 will only be netstandard2.0 and only uses DBConcurrencyException
