### ISSUE TITLE
IQueryProviderWithIncludes.Include doesn't populate Description column in the referenced Poco

### ISSUE THREAD

**Issue by MakiseKurisu** [schotime/NPoco#554]
In our program we have 2 classes. One is called Order, which contains a field called "Description". The other one is called Ticket, which contains a reference to Order. They look like this:
```
    [TableName("Tickets"), PrimaryKey("TID", AutoIncrement = true, UseOutputClause = true)]
    public class Ticket
    {
        public Guid TID { get; set; }
        public Guid? OID { get; set; }
        [ComputedColumn]
        [Reference(ReferenceType.OneToOne, ColumnName = "OID", ReferenceMemberName = "OID")]
        public Order Order { get; set; }
    }

    [TableName("Orders"), PrimaryKey("OID", AutoIncrement = true, UseOutputClause = true)]
    public class Order
    {
        public Guid OID { get; set; }
        public string Description { get; set; }
    }
```
We have recently switched our code from running raw SQL to using Linq provided by Database.Query(). However, when executing the following code, y.Order.Description is null, while x.Description is properly populated:
```
                var x = db.Query<Order>()
                          .Where(i => i.OID == new Guid("3686a4b6-75a6-e911-8e46-5cc5d488af58"))
                          .First();
                var y = db.Query<Ticket>()
                          .Include(i => i.Order)
                          .Where(i => i.TID == new Guid("8440F7B5-F1A6-E911-8100-005056833617"))
                          .First();
```
Other fields in y.Order are having the correct value. We are still investigating this issue.

Edit: We are using NPoco 4.0.1 with Sql Server 2014.

**Comment by MakiseKurisu** [comment]
NPoco generated SQL for y:
```
SELECT [T].[TID] as [TID], [T].[OID] as [OID], [O3].[OID] as [Order__OID], [O3].[Description] as [Order__Description] FROM [Tickets] [T]  
  LEFT JOIN [Orders] [O3] ON [T].[OID] = [O3].[OID] 
WHERE ([T].[TID] = @0) 
```

**Comment by MakiseKurisu** [comment]
I built a debug build of NPoco Nuget package, however that only get me to QueryProvider.ExecuteQuery() and I cannot step into Database.QueryImp(). If anyone can help me on this that would be great.

**Comment by coleSil** [comment]
I'm running into the same problem. If I end up figuring it out I'll leave an update.

**Comment by schotime** [comment]
Can't reproduce this. Either the data is null in the description field or something else isn't quite right.
https://github.com/schotime/NPoco/commit/f5e3d745ae026e81b373f7f57a5af3cacab9a0ac#diff-98cd766e139224fa87103526d509dbdb shows your example that works.
