### ISSUE TITLE
Joining to the same table multiple times and using select *

### ISSUE THREAD

**Issue by tonlap** [schotime/NPoco#555]
There is a particular scenario that we are encountering when using NPoco and joining to the same table multiple times. When this scenario is encountered it seems that data is incorrectly mapped to the associated poco objects. 

The scenario is as follows:

Given a table Product and the associated poco object Product. To simplify the scenario, the Product table contains the columns: 
ProductId int, 
ProductName varchar(128), 
IsActive bit

Given a table ProductNote and the associated poco object ProductNote. The ProductNote table contains the columns:
ProductNoteId int, 
ProductNoteTypeCode varchar(20), 
ProductId int,
Notes nvarchar(max),
IsActive bit

The pocos used for each are:

```
[TableName("Product")]
[PrimaryKey("ProductId")]
public class Product
{
    public Product()

    public int ProductId { get; set; }
    public string ProductName { get; set; }

    // Purposely commented out to cause issue with mapping.
    //public bool IsActive { get; set; }

    [ComplexMapping, ResultColumn]
    public ProductNote ProductNoteDescription { get; set; }

    [ComplexMapping, ResultColumn]
    public ProductNote ProductNoteWarning { get; set; }

    [ComplexMapping, ResultColumn]
    public ProductNote ProductNoteInstruction { get; set; }
}


[TableName("ProductNote")]
[PrimaryKey("ProductNoteId")]
public class ProductNote
{
    public ProductNote()

    public int ProductNoteId { get; set; }
    public int ProductId { get; set; }
    public string ProductNoteTypeCode { get; set; }
    public string Notes { get; set; }
    public bool IsActive { get; set; }
}
```

The SQL to load the data within the Product poco is as follows:

```
SELECT Product.*, ProductNoteDescription.*, ProductNoteWarning.*, ProductNoteInstruction.*
FROM Product
LEFT OUTER JOIN ProductNote ProductNoteDescription 
ON ProductNoteDescription.ProductId = Product.ProductId AND ProductNoteDescription.ProductNoteTypeCode = 'Description'
LEFT OUTER JOIN ProductNote ProductNoteWarning 
ON ProductNoteWarning.ProductId = Product.ProductId AND ProductNoteWarning.ProductNoteTypeCode = 'Warning'
LEFT OUTER JOIN ProductNote ProductNoteInstruction 
ON ProductNoteInstruction.ProductId = Product.ProductId AND ProductNoteInstruction.ProductNoteTypeCode = 'Instruction'
```

For this scenario, assume that only a product description and product warning exists within the ProductNote table.

When the Product poco is loaded with data, the ProductNote pocos within the Product poco are not being loaded properly as a result of the "IsActive" property within the Product poco not existing (i.e., purposely commented out to cause the issue). It seems that the IsActive property within the ProductNoteDescription is being used and thus the mapping for the ProductNoteWarning and ProductNoteInstruction is not longer being mapped properly.

Maybe this is a use case that should be avoided or is there some other approach that can be used to properly load the data within the Product poco. 

Another concern is also when using select "*" to load data into pocos that contain complex pocos with the same column names. It seems that the mapper may not correctly map data when a column (with the same name) exists within the associated poco table but does not exist as a property within the poco object but exists within the nested complex poco objects.

Any help to resolve this particular scenario is appreciated.

Thanks

**Comment by schotime** [comment]
The below should work. Checkout https://github.com/schotime/NPoco/blob/master/test/NPoco.Tests/NewMapper/NewMapperTests.cs for more ways

```sql
SELECT Product.*, null npoco_ProductNoteDescription, ProductNoteDescription.*, null npoco_ProductNoteWarning, ProductNoteWarning.*, null npoco_ProductNoteInstruction, ProductNoteInstruction.*
FROM Product
LEFT OUTER JOIN ProductNote ProductNoteDescription 
ON ProductNoteDescription.ProductId = Product.ProductId AND ProductNoteDescription.ProductNoteTypeCode = 'Description'
LEFT OUTER JOIN ProductNote ProductNoteWarning 
ON ProductNoteWarning.ProductId = Product.ProductId AND ProductNoteWarning.ProductNoteTypeCode = 'Warning'
LEFT OUTER JOIN ProductNote ProductNoteInstruction 
ON ProductNoteInstruction.ProductId = Product.ProductId AND ProductNoteInstruction.ProductNoteTypeCode = 'Instruction'
```
