### ISSUE TITLE
Alias problem: oracle error: ORA-00972: Name too long.

### ISSUE THREAD

**Issue by Caipus** [schotime/NPoco#557]
Hi all,

I updated NPoco to the latest version (my old version was 2.0...) today and run into following issue:

NPoco generates select statements with aliases which are too long for oracle

SELECT "XYTI"."XY_NAME" as "NAME", "XYTI"."XY_PARENT_ID" as **"THE_NAME_OF_MY_CSHARP_PROPERTY"**, ....

Which leads into an oracle error: ORA-00972: Name too long.

In the old version the aliases were not the property names of my entity, it were more cryptic like XY_1, XY_2 ... so numbered and very short.

I am using fluent mapping:
x.Column(y => y.My_Very_Long_CSharp_Property).WithName("MY_PROP");
I also tried .WithAlias ... which didn't work.

Thanks for any help.

Markus

**Comment by schotime** [comment]
Possible bug that `WithAlias` didn't work
