### ISSUE TITLE
Do you have a plan to support OleDb like Access?

### ISSUE THREAD

**Issue by joeries** [schotime/NPoco#560]
Do you have a plan to support OleDb like Access?

**Comment by schotime** [comment]
No sorry

**Comment by joeries** [comment]
I've made some changes to NPoco for my project uses Access.I appended an extra parameter presenting primary key name to the method named "DatabaseType.BuildPageQuery".Can I make a pull request to make NPoco support OleDb like Access?

**Comment by AZDeveloper777** [comment]
@schotime I'm thinking about incorporating @joeries OleDb changes into a fork (not just a copy like he did) and track you as upstream.  Before I dig into it, would you mind explaining why you didn't want to support OleDB ?
