### ISSUE TITLE
Adding BulkCopyTimeout parameter to BulkInsert

### ISSUE THREAD

**Issue by tbasallo** [schotime/NPoco#563]
I am looking for some feedback before a PR.
I have been using SqlBulkCopy lately. On this one table, I needed a larger timeout than the default. After using my local version for some other work I have done, here's my ask.

1 - willing to make change
2 - Overloaded with a null value and default value of null (no change to current consumers)
3 - New function with third parameter

I like option 2. But either way works.

Here'a n example of option 2 :

https://github.com/schotime/NPoco/blob/d707af2bf59f5c70c1d147bc6974d3cdd52bb05b/src/NPoco/SqlBulkCopyHelper.cs#L30

```
 public static void BulkInsert<T>(IDatabase db, IEnumerable<T> list, SqlBulkCopyOptions sqlBulkCopyOptions, int? bulkCopyTimeout = null)
        {
                .....
                if (bulkCopyTimeout.HasValue)
                {
                    bulkCopy.BulkCopyTimeout = bulkCopyTimeout.Value;
                }
                ....            
        }
```

**Comment by schotime** [comment]
Will be available for testing as of v5 alpha3
