### ISSUE TITLE
Snapshot and Poco events not working together?

### ISSUE THREAD

**Issue by dario-l** [schotime/NPoco#566]
I use [snapshoting](https://github.com/schotime/NPoco/wiki/Change-tracking-for-updates) and [Poco events](https://github.com/schotime/NPoco/wiki/Performing-Operations-during-Poco-events-(Insert,-Update,-etc)) and it seems not working properly.

Every change on Poco is not reflected in database.

Should I manually change `UpdateContext` and add changed column names to the `ColumnsToUpdate`?

**Comment by dario-l** [comment]
Nope. Context manually changed doesn't improve. :(

**Comment by dario-l** [comment]
I moved all my code from events to overridden method `Update`.
On every changed property I add column name to the `ColumnsToUpdate`.

Now works. :)

**Comment by schotime** [comment]
I don't quite understand the issue, so closing for now unless you can provide some more details.
