### ISSUE TITLE
FetchAsync throws error when dbenableautoselect is set to false

### ISSUE THREAD

**Issue by MohanVijayakumar** [schotime/NPoco#568]
Hi,

When DbEnableAutoSelect is set to false then database.FetchAsync throws the following error
"System.InvalidOperationException: 'BeginExecuteReader: CommandText property has not been initialized'"
if we don't set to false then works fine

Npoco Version : 4.0.2
.Net Core Version : 2.2

Thanks for this great ORM

**Comment by schotime** [comment]
You will need to pass sql in then.
