### ISSUE TITLE
Is there a way to mock _database.StartSnapshot(user)?

### ISSUE THREAD

**Issue by ThisNoName** [schotime/NPoco#570]
Tried everything I can, but couldn't make it through.  Need it for unit testing.

Any ideas?  Any working examples using any mocking framework?  Thanks.

**Comment by schotime** [comment]
Shouldn't need to Mock it. Just use as is.

**Comment by zhangb99** [comment]
Need the following, keeping record in case I forgot.

    _database.PocoDataFactory = new PocoDataFactory(new MapperCollection());

All hail @aalex675 [https://github.com/schotime/NPoco/issues/461](url)
