### ISSUE TITLE
Data is not available when a column name contains an underscore

### ISSUE THREAD

**Issue by naariah** [schotime/NPoco#576]
Data is not available when a column name contains an underscore。
For example：
class{
public string  transtime ;
public string  trans_time ;
}

the trans_time can not get data

**Comment by naariah** [comment]
> Data is not available when a column name contains an underscore。
> For example：
> class{
> public string transtime ;
> public string trans_time ;
> }
> 
> the trans_time can not get data

i find this in source ;
// find pocomember by property name
            var pocoMember = pocoMembers.FirstOrDefault(x => IsEqual(groupedName.Item, x.Name));

`       public static bool IsEqual(string name, string value)
        {
            return string.Equals(value, name, StringComparison.OrdinalIgnoreCase)
                || string.Equals(value, name.Replace("_", ""), StringComparison.OrdinalIgnoreCase);
        }`

this place ,you set the column is same setting with  the underline column

**Comment by schotime** [comment]
Yes this is correct. This is a convention NPoco has and isn't going to change.
