### ISSUE TITLE
Bug on mapping for FetchOneToMany with complex entities in children and workaround

### ISSUE THREAD

**Issue by dsancho** [schotime/NPoco#580]
I have the following situation:
Table1:
Id
Field1

Table2
IdTable1 -> FK to Table1.Id
Child__UUID
Child__Type
ExtraData

class ObjTable1:
Id,
Field1
ChildEntities: List< ObjTable2 >

class ObjTable2
IdTable1
Child: TypedUUID
ExtraData

class TypedUUID
UUID
Type

FetchOneToMany< ObjTable1 >(arg => arg.ChildEntities, "SELECT Table1.*, Table2.* FROM ... INNER JOIN...");

What happens it's that the field ExtraData it's not filled. BUT if I change the SQL sentence to "SELECT Table1.*, Table2.IdTable1, Table2.ExtraData, Table2.Child__UUID, Table2.Child__Type ---" then it works fine. The problem it's on ConvertFromOldConvention method of PropertyMapperNameConvention. More precisely on this line: var unusedPocoMembers = members.Where(x => !used.ContainsKey(x.PocoMember) && x.Level >= level). The problem it's the level filter. As before the ExtraData fields there are two fields that map to a complex object (TypedUUID), then the level it's increased and it's supposed that following fields will be of child entity.
In my case the workaround (put first non complex properties in the query) works because I only have one complex property but with more complex properties in the same object, there is a problem.

**Comment by schotime** [comment]
The most reliable way to write this query is using the following hints so that the sql would look like this. The other way only works for limited scenarios and supports the old way of doing it.

```sql
SELECT Table1.*, null npoco_ChildEntities, Table2.* ...
```

What ends up happening is the npoco_ChildEntities then ends up prefixing each value after it with "ChildEntities__" which leaves no ambiguity for the mapper.

Apologies for the delay.
Here is some of the crazyness

```cs
public void Test28()
{
    var data = Database.Fetch<Test28Class>("select 3 Id, 'Name' Name, 'dyn' Dynamic__Value1, 'dict' Dict__Value2, null npoco_Nest1__Dict2," +
                                           " 'dictnested' Value3, null npoco_Dict2__Value4, 'my string' S, 5 I, null npoco, 'oh my' DictHell__Key1__Dict2__Key2__S, 99 DictInt__ints," +
                                           " 'z' NestMe__Nested__Nest3__Z, 'dictsupernesed' NestMe__Nested__Dict4__MyKey__S").Single();
    Assert.AreEqual(3, data.Id);
    Assert.AreEqual("Name", data.Name);
    Assert.AreEqual("dyn", data.Dynamic.Value1);
    Assert.AreEqual("dict", data.Dict["Value2"]);
    Assert.AreEqual("dictnested", data.Nest1.Dict2["Value3"]);
    Assert.AreEqual("my string", data.Dict2["Value4"].S);
    Assert.AreEqual(5, data.Dict2["Value4"].I);
    Assert.AreEqual(99, data.DictInt["ints"]);
    Assert.AreEqual("oh my", data.DictHell["Key1"].Dict2["Key2"].S);
    Assert.AreEqual("z", data.NestMe.Nested.Nest3.Z);
    Assert.AreEqual("dictsupernesed", data.NestMe.Nested.Dict4["MyKey"].S);
}
```
