### ISSUE TITLE
Is there any document about connection dispose?

### ISSUE THREAD

**Issue by naughtyGitCat** [schotime/NPoco#581]
When `IDatabase` was added as singleton service:
```c#
string mysqlSetting.ReadWriteURI = "**********";
return new Database(mysqlSetting.ReadWriteURI, DatabaseType.MySQL, MySqlClientFactory.Instance);
```
Thinking of the performance lost of open/close conn, should I  inherit from IDisposable and call `db.Dispose` in the implementation of Dispose() method in the  transient service?

the MySQL.Data driver says 
https://dev.mysql.com/doc/connector-net/en/connector-net-connections-pooling.html
```
To work as designed, it is best to let the connection pooling system manage all connections. Do not create a globally accessible instance of MySqlConnection and then manually open and close it. This interferes with the way the pooling works and can lead to unpredictable results or even exceptions.
```
if I do not inherit from IDisposable or don't manually call `db.Dispose()`, does the NPOCO use the MySQL.Data connection pooling system?

**Comment by schotime** [comment]
`Database` should not be used as a singleton across threads.
NPoco uses the underlying `DbConnection` objects of the driver, which you would have to check your connection string for whether it does pooling for your driver. 
Remembering, this is just a wrapper around the primitives.
