### ISSUE TITLE
Fixed nvarchar length to optimize SQL Server query plan caching?

### ISSUE THREAD

**Issue by kylefisher** [schotime/NPoco#582]
Lately, as we've run into SQL Server performance issues, I've noticed that the same query is in SQL Server's query plan cache over and over. I think this is due to the nvarchar length from parameterized queries in NPoco. Is there a way to fix the nvarchar length so that SQL Server can properly cache and optimize the query?

Here's an example from our production plan cache. Notice that each declared nvarchar has a different length. This query has three parameters, all nvarchars. The potential, worst case number of cache entries is 25,000 entries for this query.

```
(@fieldName nvarchar(41),@category nvarchar(11),@environment nvarchar(3))SELECT pc.KeyId, pc.FieldName, CASE WHEN
(@fieldName nvarchar(11),@category nvarchar(7),@environment nvarchar(3))SELECT pc.KeyId, pc.FieldName, CASE WHEN 
(@fieldName nvarchar(19),@category nvarchar(7),@environment nvarchar(3))SELECT pc.KeyId, pc.FieldName, CASE WHEN 
```
It seems that NPoco sets the nvarchar length based on the length of the C# string. Is there a way to force this length, or have NPoco pull the value from the database schema?

Thanks!

**Comment by schotime** [comment]
This should already be happening as can be seen here.
https://github.com/schotime/NPoco/blob/master/src/NPoco/Database.cs#L540

So I'm not quite sure whats happening.
