### ISSUE TITLE
NPOCO error: 'uuid' type currently unknown to Npgsql 

### ISSUE THREAD

**Issue by bhavyabhatj** [schotime/NPoco#583]
Hi,
We are using NPoco (**Version 4.0.2**) for querying data from cockroach database.  
On of the tables has 'Uid' as a column which is of type "**uuid**". We see that randomly we get following error while querying for the data from that table. 
**Exception:System.NotSupportedException: The field 'Uid' has a type currently unknown to Npgsql (OID 2950).** 
**NPoco version: 4.0.2
Npgsql version: 4.1.3.1
asp.net core version: 3.1**
Could you please help us on how we can fix this error?

**Comment by schotime** [comment]
Seems like an Npgsql error.
