### ISSUE TITLE
Fetchwhere is missing in latest update

### ISSUE THREAD

**Issue by anandanatarajan** [schotime/NPoco#591]
Hi, 
I recently updated one of my project which is having npoco 2.0 to latest commit 4.0.2, and it started to throw error on Fetchwhere which i used lavishly, does it deprecated or am i missing something?

**Comment by schotime** [comment]
Yes it is deprecated, but its easy to create your own version that will use the existing API.

```cs
public static class DbExt
{
  public static List<T> FetchWhere(this Database db, Expression<Func<T, bool>> expression)
  {
    return db.Query<T>().Where(expression).ToList();
  }
}
```

**Comment by twelvedogs** [comment]
I think this should be 
`
public static List<T> FetchWhere<T>(this Database db, Expression<Func<T, bool>> expression)
`
you're missing a <T>

> 
> Yes it is deprecated, but its easy to create your own version that will use the new API.
> 
> ```cs
> public static class DbExt
> {
>   public static List<T> FetchWhere(this Database db, Expression<Func<T, bool>> expression)
>   {
>     return db.Query<T>().Where(expression).ToList();
>   }
> }
> ```
