### ISSUE TITLE
How to use storedprocedure.tt 

### ISSUE THREAD

**Issue by myalo** [schotime/NPoco#594]
As I understand this template can create an object based on the results of a stored procedure. I do not understand how to use it and how does it do it. 
Thank you for your help
Moshe

**Comment by schotime** [comment]
These were originally for PetaPoco and not maintained in this project.

**Comment by myalo** [comment]
Thank you.
Does NPoco project has similar template / app that can create Objects and CRUD c# methods from a database including stored procedures?
Best
Moshe
