### ISSUE TITLE
Why IDatabaseQuery doesn't implement IDisposable?

### ISSUE THREAD

**Issue by dario-l** [schotime/NPoco#596]
I have special case for reporting only and want to return IDatabaseQuery but it is not IDisposable. :(

``` c#
using(IDatabaseQuery db = _databaseFactory.GetReporting())
{
    db.Fetch ...
}
```

As I saw on repo there is no reason to not do this. :)
Am I right?

**Comment by schotime** [comment]
Slated for v5.

**Comment by schotime** [comment]
Fixed in https://github.com/schotime/NPoco/commit/42fb1254671a845cfba2db97ddd9b3c143f95a50
