### ISSUE TITLE
Support for Core 3

### ISSUE THREAD

**Issue by kjjpfeiffer** [schotime/NPoco#597]
Would you consider making a version that uses Microsoft.Data.SqlClient instead of system.data.sqlclient?  The "Breaking Changes" doc from MS claims that it's a drop-in replacement.

**Comment by makingbloke** [comment]
I’m using a 6 month old version of NPoco with no problems albeit my usage
is very simple. I stopped using System.Data.SQLite because when I asked
there was no plans to support EF Core in the near future (I use a mix of
NPoco and EF Core) and the encryption support was poor unless you had money
to spend (I don’t ;) !).

**Comment by makingbloke** [comment]
Forgot to add, this is the code I use to create an instance of NPoco using the MS Drivers:

`            NPoco.Database db = new NPoco.Database(new SqliteConnectionStringBuilder()
            {
                DataSource = dataSource,
                ForeignKeys = true
            }.ConnectionString,
            DatabaseType.SQLite,
            SqliteFactory.Instance);
`

**Comment by kjjpfeiffer** [comment]
The issue is that system.data.sqlclient is a reference within the nPoco code. If it is deprecated then we'll have to add that dll and its dependencies to the deployment.  I'll soon find out how "breaking" it is, but it'd be nice to have a new nPoco build.

I'm trying to avoid EF as it is a monster and a bit much for a CRUD webservice.

**Comment by makingbloke** [comment]
I have to use EFCore for work and I use NPoco at home. EF Core is not the
monster that the original EF used to be (sorry for mentioning a competitor
and going OT :) ).

**Comment by kjjpfeiffer** [comment]
No sorry needed as far as I'm concerned, that's good info for those that might need to use it due to corporate practice or policy.

**Comment by makingbloke** [comment]
Apologies, I've withdrawn my comments as I misread your original post to be the SQLite client not SqlClient. Sorry :(

**Comment by schotime** [comment]
This will be coming in NPoco v5. 
Will just support netstandard 2.0 and will have a separate SqlServer package that references Microsoft.Data.SqlClient.

Progress can be tracked here. https://github.com/schotime/NPoco/commits/v5

**Comment by kjjpfeiffer** [comment]
Thank you very much.

**Comment by schotime** [comment]
Started in https://github.com/schotime/NPoco/commit/42fb1254671a845cfba2db97ddd9b3c143f95a50
