### ISSUE TITLE
.First(Expression) does not respect the Where clause

### ISSUE THREAD

**Issue by bryanboettcher** [schotime/NPoco#598]
https://github.com/schotime/NPoco/blob/master/src/NPoco/Linq/SimpleQueryProvider.cs#L238

My assumption is that "AddWhere(null);" should be "AddWhere(expression)".

Current workaround is .Where(expression).First()

**Comment by schotime** [comment]
You are correct, not sure how this was missed. Its already been fixed in v5 branch, what version you using?

**Comment by bryanboettcher** [comment]
> You are correct, not sure how this was missed. Its already been fixed in v5 branch, what version you using?

We are using 4.0.2 as that is the latest available in NuGet.

**Comment by schotime** [comment]
Fixed in 4.0.3
