### ISSUE TITLE
Possible escaping issue

### ISSUE THREAD

**Issue by doublej42** [schotime/NPoco#599]
I don't know the code base but I was doing a security review on something that used it and I noticed
https://github.com/schotime/NPoco/blob/2f41c21af8e8bfa13558b28b2cdbecd604d16655/src/NPoco/DatabaseType.cs#L186

This won't stop input like  ']; delete * from users; --' from causing an SQL injection. I'm not sure if this code is use anywhere there bad data might get passed.

**Comment by schotime** [comment]
It never gets data passed into a query from external data, its only used internally to escape columns. I mean, you could inject yourself if you configured your column names wrong.
