### ISSUE TITLE
Something in v5 is not thread-safe around Database objects

### ISSUE THREAD

**Issue by bryanboettcher** [schotime/NPoco#601]
This is a placeholder for right now as I am trying to figure out my pattern and the smallest reproduction possible.  In the meantime, if there are any samples of how to properly do multi-threaded code with async/await, I am very interested!

**Comment by bryanboettcher** [comment]
Repro code (causes connection pool exhaustion, one of the many things I've been combating).  I realize I've got "KeepConnectionAlive = true" set, but my expectation is that it would reuse connections instead of continuously opening new ones.  What am I missing?

```
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
using NPoco;
using NPoco.FluentMappings;

namespace NPocoAsync
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var e = new Example();
            await e.Run();
        }
    }

    public class Example
    {
        public async Task Run()
        {
            var factory = DatabaseFactory.Config(conf =>
            {
                conf.UsingDatabase(() => BuildDatabase());
                conf.WithFluentConfig(FluentMappingConfiguration.Configure(new SchemaTableMapper()));
            });

            Parallel.For(0, 10000, async i => 
            {
                var repo = new SchemaRepository(factory);
                await repo.GetItemsAsync("master");
            });

        }

        private static Database BuildDatabase()
        {
            var database = new Database(
                Settings.ConnectionString, 
                DatabaseType.SqlServer2012, 
                SqlClientFactory.Instance
            );
            
            database.KeepConnectionAlive = true;

            return database;
        }
    }

    public class SchemaTable
    {
        public string TableCatalog { get; set; }
        public string TableSchema { get; set; }
        public string TableName { get; set; }
        public string TableType { get; set; }
    }

    public class SchemaTableMapper : Map<SchemaTable>
    {
        public SchemaTableMapper()
        {
            TableName("information_schema.tables");
            Columns(c =>
            {
                c.Column(x => x.TableCatalog).WithName("TABLE_CATALOG");
                c.Column(x => x.TableName).WithName("TABLE_NAME");
                c.Column(x => x.TableSchema).WithName("TABLE_SCHEMA");
                c.Column(x => x.TableType).WithName("TABLE_TYPE");
            });
        }
    }

    public class SchemaRepository
    {
        private readonly DatabaseFactory _factory;

        public SchemaRepository(DatabaseFactory factory)
        {
            _factory = factory;
        }

        public async Task<IEnumerable<SchemaTable>> GetItemsAsync(string catalog)
        {
            using var database = _factory.GetDatabase();
            return await database
                .QueryAsync<SchemaTable>()
                .Where(t => t.TableCatalog == catalog)
                .ToList()
                .ConfigureAwait(false);
        }
    }
}

```

**Comment by schotime** [comment]
The best way is to manage the connection outside of `Database` and pass an DbConnection directly into the constructor.

**Comment by bryanboettcher** [comment]
The Database object is showing itself quite unsuitable for multi-threaded applications.  I am trying to make it play nicely with Lamar (which does scoped containers).

- Is the DatabaseFactory expensive to create?
- Is the Database object expensive to create?
- Are there advantages to using KeepConnectionAlive vs SQL's Connection Pooling?

Are there any canonical examples or samples of using NPoco in a threaded manner?

**Comment by schotime** [comment]
> Is the DatabaseFactory expensive to create?

Yes

> Is the Database object expensive to create?

No

> Are there advantages to using KeepConnectionAlive vs SQL's Connection Pooling?

KeepConnectionAlive is designed to keep the first opened connection alive until the `Database` object is disposed. Thats all, so in theory one connection per `Database`. 
If you pass the connection into the Database, then you could reuse the same connection across Databases. You will have to still be careful about having multiple readers open, but that is a connection string property if needed.

> Are there any canonical examples or samples of using NPoco in a threaded manner?

Not really, but one `Database` per thread is recommended, as its not thread safe across instances. 
If you want to share a connection between threads so you don't exhaust threads, you'll need to manually create your `SqlConnection` outside of `Database` and pass it into the constructor. You could then pass the same connection to multiple `Database` instances.
