### ISSUE TITLE
Add DataTable methods

### ISSUE THREAD

**Issue by tmatous** [schotime/NPoco#61]
First of all, thank you for taking over PetaPoco and continuing the great work it started.

I am trying to use NPoco in the DL for a simple project, but have run into a few use cases where a DataTable would be much more useful. An example is exporting data to a CSV file. I understand that NPoco is designed for POCOs, but it would be a small change to add a DataTable method, while it would be a lot more difficult to build my own, including the factory/database agnostic pieces.

BTW: I tried to just extend the Database class, but some required pieces are marked "private", making extension impossible. The items I needed "protected" access to were CreateCommand() and _factory.

I can add this functionality if you accept pull requests.

**Comment by dazinator** [comment]
Just thought I would mention that this issue (ToDataTable method) seems to overlap with #113

**Comment by schotime** [comment]
You can always map to a `object[]` using `Fetch<object[]>` or `Fetch<Dictionary<string, object>>` if you want dynamic mappings.
