### ISSUE TITLE
Database.InsertAsync returns 0 on insert failure without an exception. (postgress)

### ISSUE THREAD

**Issue by vllama** [schotime/NPoco#612]
Sometimes when inserts fail in postgres this function returns id of 0, but there is no exception thrown.

I would expect the Npgsql exception to be bubbled up.  It seems to happen if you are missing a non null column in your poco.

`var id = await Database.InsertAsync(entity); `

Might be related to InsertAsync not returning the right ID #361

**Comment by schotime** [comment]
What version are you using?

**Comment by vllama** [comment]
Sorry I missed that, Latest 4.0.2

**Comment by schotime** [comment]
Could you try 5.0.0-rc1? otherwise provide a small sample that reproduces the issue.
