### ISSUE TITLE
v5: Parameter Exception from NPoco.ParameterHelper.ProcessParam

### ISSUE THREAD

**Issue by tbasallo** [schotime/NPoco#615]
I'm getting parameter exception with any SQL with a parameter. It's coming from NPoco.ParameterHelper.ProcessParam. I can't take a look now to offer more help, but I'll try to if no one else gets a chance tomorrow morning.

This is true whether I use

     var db = new Database(conn, DatabaseType.SqlServer2012, SqlClientFactory.Instance);                        

or

     var db = new SqlServerDatabase(conn, null);                        

```
return await Db.FirstOrDefaultAsync<Employee>("WHERE Uid = @0 ", uid);

{"Specified argument was out of the range of valid values. 
(Parameter 'Parameter '@0' specified but only 0 parameters supplied (in `WHERE Uid = @0 `)')"}
```

Named parameters:
`{"Parameter '@uid' specified but none of the passed arguments have a property with this name (in 'SELECT * FROM Employees WHERE Uid = @uid')"}`

**Comment by tbasallo** [comment]
So, apparently I have some code somewhere that's causing this. Which is very strange since I am not sure there's anything I could do.

I'll test some more and close once I find the issue - in case it helps anyone else.

**Comment by redarccoder** [comment]
> 
> 
> So, apparently I have some code somewhere that's causing this. Which is very strange since I am not sure there's anything I could do.
> 
> I'll test some more and close once I find the issue - in case it helps anyone else.

There is no bug on your part, I ran into the same issue (I already reported it here: https://github.com/schotime/NPoco/issues/616), also, this has already been closed.

Now, we just have to wait for it to be pushed over the repository, in the meantime, you can execute it like this:

(await Db.FetchAsync<Employee>("WHERE Uid = @0 ", uid)).FirstOrDefault();

Greetings

**Comment by redarccoder** [comment]
> 
> 
> > So, apparently I have some code somewhere that's causing this. Which is very strange since I am not sure there's anything I could do.
> > I'll test some more and close once I find the issue - in case it helps anyone else.
> 
> There is no bug on your part, I ran into the same issue (I already reported it here: #616), also, this has already been closed.
> 
> Now, we just have to wait for it to be pushed over the repository, in the meantime, you can execute it like this:
> 
> (await Db.FetchAsync("WHERE Uid = @0 ", uid)).FirstOrDefault();
> 
> Greetings

BTW, it has already been posted on the repository, update your package and it should work (working on my environment right now)

**Comment by tbasallo** [comment]
Yep!. Thanks!
