### ISSUE TITLE
FirstAsync and FirstOrDefaultAsync not working on MySql and Net. Core

### ISSUE THREAD

**Issue by redarccoder** [schotime/NPoco#616]
I'm trying to query unique values from my MySql 8 Server, but I keep on getting errors, telling me that I didn't specify the parameters, neither @0 nor object array parameters works.

Calling First<T>, Fetch<T>, FetchAsync<T> works  using the same query and parameters.

![Error1](https://user-images.githubusercontent.com/3534955/99463112-aa5ba580-28fa-11eb-81d4-47c06ee0b052.jpg)
![error2](https://user-images.githubusercontent.com/3534955/99463119-adef2c80-28fa-11eb-916e-ed669fa41f06.jpg)
![error_3](https://user-images.githubusercontent.com/3534955/99463132-b2b3e080-28fa-11eb-8294-555d526c1fb0.jpg)

I can get around with FetchAsync then getting my first result (since I know it's unique), but it would be useful to have this available for other functions

**Comment by schotime** [comment]
Found the issue.
Somehow missed passing the args. Oops.

**Comment by redarccoder** [comment]
> 
> 
> Found the issue.
> Somehow missed passing the args. Oops.

Thank you for this amazing job dude, wish you all the luck in the world.

Greetings
