### ISSUE TITLE
Add "Scaldfold DB" support (Like Entity Framework)

### ISSUE THREAD

**Issue by redarccoder** [schotime/NPoco#617]
I was wondering if you're interested into adding scald folding capabilities to this project, since it increases the overall productivity of a developer to just write a command in Visual Studio (or the terminal in VSCode) and having all the changes of your database mapped into your code. Adding (basic) support to this isn't as hard.

Also, I made a little project to scald fold my MySQL Database (running 8.15) and I can share/optimize my code with you.

Running this program generates the basic structure for the DB and adds a "dbContextClass" to it, making it easier to use it (for example) in API and Web projects

![1](https://user-images.githubusercontent.com/3534955/100387196-19b55180-2fed-11eb-8283-de9d4bb4dbb9.jpg)
![2](https://user-images.githubusercontent.com/3534955/100387234-318cd580-2fed-11eb-9f8f-2d4564528b06.jpg)
![3](https://user-images.githubusercontent.com/3534955/100387451-c0015700-2fed-11eb-95d8-b0b9247f716b.jpg)

**Comment by schotime** [comment]
I won't be adding this sorry but you are most welcome to create your own package or global tool.
