### ISSUE TITLE
BulkInsert doesn't serialize columns marked as serialized

### ISSUE THREAD

**Issue by Rensvind** [schotime/NPoco#619]
If this line
https://github.com/schotime/NPoco/blob/master/src/NPoco.SqlServer/SqlBulkCopyHelper.cs#L82
is changed to
`var value = db.ProcessMapper(cols[i].Value, cols[i].Value.GetValue(item!));`
everything works as expected

**Comment by schotime** [comment]
In NPoco.SqlServer 5.1.1
