### ISSUE TITLE
.Net IoC failed?

### ISSUE THREAD

**Issue by zhangb99** [schotime/NPoco#621]
I have this IoC .NET Core API, and it has been working for years, Core3 NET5.

            services.AddScoped<IDatabase>(x => new Database(connection,
                DatabaseType.SqlServer2012, SqlClientFactory.Instance));

After upgrading to 5.0.1, I got

Register your handlers with the container. See the samples in GitHub for examples.
 ---> System.Exception: No database type found for the type string specified: 'SqlServerDatabaseType'. Make sure the relevant assembly NPoco.SqlServer is referenced.

Did I miss something?  Thanks

**Comment by schotime** [comment]
Yep. You missed referencing the NPoco.SqlServer package as mentioned in exception.

**Comment by zhangb99** [comment]
Duh!  I swear I read that error messages 5 times but nothing ring the bell ... must the covid thing
