### ISSUE TITLE
Multi-tenant application with separated databases

### ISSUE THREAD

**Issue by dario-l** [schotime/NPoco#622]
I need to create multi-tenant application with separated databases. Each tenant will have own connection string. Should I create as many database factories as connection strings (tenants) or there is another way to take new instance of IDatabase with other connection string?

**Comment by plsft** [comment]
I am looking at the same requirement. Any input/guidance would be great.

**Comment by schotime** [comment]
Hey sorry for the delay. Below is something like I generally do. If you have the same schema you only want one `DatabaseFactory`.

```c#
public class MyDatabaseFactory
{
    public DatabaseFactory MyFactory { get; }

    public MyDatabaseFactory()
    {
        MyFactory = DatabaseFactory.Config(x =>
        {
            x.WithFluentConfig(...);
            x.WithMapper(...);
        });
    }

    public IDatabase GetDatabase(string dbname /*or whatever you distinguish by*/)
    {
        return MyFactory.Build(new SqlServerDatabase($"Server=.;Database={dbname};Integrated Security=true"));
    }
}

public interface IMyDatabaseFactory
{
    IDatabase GetDatabase(string dbname);
}
```

Then you can inject that into where you need by adding the below to your startup in `ConfigureServices`

```c#
services.AddSingleton<MyDatabaseFactory, MyDatabaseFactory>();
```

And in a controller use like.

```c#
public class HomeController : Controller 
{
    IMyDatabaseFactory _myFactory;

    public HomeController(IMyDatabaseFactory myFactory) 
    { 
        _myFactory = myFactory;
    }

    public ActionResult Index() 
    {
         var db = _myFactory.GetDatabase("dbname");
    } 
}

**Comment by plsft** [comment]
Thanks @schotime that makes sense. What about using Postgres?

**Comment by schotime** [comment]
Exactly the same just replace SqlServerDatabase with Database as you normally would construct it, passing connection string, DatabaseType.PostgreSQL, and NPgsqlFactory.Instance etc.

**Comment by dario-l** [comment]
@schotime  Can I build database object on every request? Is it cheap?

```
    public IDatabase GetDatabase(string dbname /*or whatever you distinguish by*/)
    {
        return MyFactory.Build(new SqlServerDatabase($"Server=.;Database={dbname};Integrated Security=true"));
    }
```

**Comment by dario-l** [comment]
OK, I found that `GetDatabase` also runs `Build` method internally.

https://github.com/schotime/NPoco/blob/master/src/NPoco/DatabaseFactory.cs#L86

**Comment by schotime** [comment]
Yep. Build is cheap.

**Comment by plsft** [comment]
My applications' services (e.g. business layers) also need the database class/database factory. I typically inject them in program.cs to they are available to any controller/endpoint/page etc. How do I use DI for this factory into my scored/transient services? I'm migrating to net60 and net70 and need to support cross-platform win/linux.

**Comment by schotime** [comment]
services.AddScoped<IDatabase>(_ => new Database("connectionString"));
