### ISSUE TITLE
Deleting poco throws: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by firedog** [schotime/NPoco#625]
https://github.com/schotime/NPoco/blob/7c5ceaf9a9e0a67d237af6d70085e06ebbf8fcc3/src/NPoco/Database.cs#L1496

I have a poco with a version column that references other pocos (a one-to-one + a one-to-many). The related pocos are also using a version column each.

When using db.DeleteAsync(poco) or db.Delete(poco) I'm getting an exception "Sequence contains more than one matching element". I suspect it is the line referenced above that causes this.

Just guessing here but maybe the code should read: 

```c#
var versionColumn = pd?.Columns.SingleOrDefault(x => x.VersionColumn);
```

A workaround in the meantime is to use the delete that can take a primary key value:
```c#
 db.Delete<PocoType>(poco.Id)
```

**Comment by schotime** [comment]
Updated in 5.1.2
