### ISSUE TITLE
Oracle + ASP.NET Core MVC + Npoco + network-related or instance-specific error

### ISSUE THREAD

**Issue by Ashka59** [schotime/NPoco#626]
Hello, all the issue is explained there : 
https://stackoverflow.com/questions/65340680/failed-to-load-resource-the-server-responded-with-a-status-of-500-oracle

A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

![unknown](https://user-images.githubusercontent.com/52276175/102601073-f4b18b80-411f-11eb-906f-e5f986724882.png)
![unknown (1)](https://user-images.githubusercontent.com/52276175/102602656-1dd31b80-4122-11eb-9381-38f1e31a42b4.png)
![unknown (2)](https://user-images.githubusercontent.com/52276175/102602679-2592c000-4122-11eb-831c-e350319bacda.png)
![unknown (3)](https://user-images.githubusercontent.com/52276175/102602689-29bedd80-4122-11eb-924b-e6a2672a3f5f.png)

**Comment by schotime** [comment]
Probably don't use the return Sql Server `SqlClientFactory.Instance` would be my first guess. You'll need to use the oracle equivalent.

**Comment by Ashka59** [comment]
& do you know an oracle equivalent..?

Le ven. 18 déc. 2020 à 12:32, Adam Schroder <notifications@github.com> a
écrit :

**Comment by Ashka59** [comment]
Actually I have this in appsettings.json

`  "system.data": {
    "DbProviderFactories": {
      "ODP.NET, Managed Driver": {}
    }
  }`

**Comment by schotime** [comment]
var db = new Database("connstring...", DatabaseType.OracleManaged, Oracle.ManagedDataAccess.Client.OracleClientFactory.Instance);

**Comment by Ashka59** [comment]
In fact. It works : 
`
private static Database Load()
        {
            // Get Instance of Configuration with appsettings.json
            IConfigurationBuilder cfgBuilder = new ConfigurationBuilder();
            cfgBuilder.AddJsonFile("appsettings.json");
            IConfiguration cfg = cfgBuilder.Build();

            var connectionString = cfg["ConnectionStrings:Web:ConnectionString"];
            var provider = cfg["ConnectionStrings:Web:ProviderName"];
            if (provider != "Oracle.ManagedDataAccess.Client")
            {
                return null;
            }
            return new Database(connectionString, DatabaseType.OracleManaged, new OracleClientFactory());
        }
`
