### ISSUE TITLE
Auto select not available in .NET standard

### ISSUE THREAD

**Issue by Wolfos** [schotime/NPoco#628]
The .NET Standard 2.0 implementation seems to be missing the autoselect feature, requiring tonnes more initialization to setup a database connection.

**Comment by schotime** [comment]
Yes thats correct. DbProvider's didn't exist prior to .net standard 2.0 and I haven't brought them back. Tonnes is an over exaggeration though. 

```cs
var db = new Database("connstring", DatabaseType.SqlServer2012, SqlClientFactory.Instance);
```
