### ISSUE TITLE
Can´t excute a SQL script

### ISSUE THREAD

**Issue by rbrunken** [schotime/NPoco#629]
I try to execute this SQL script with my SQL Server:
if 0 = (select count(*) FROM msdb.dbo.backupset as BS WHERE BS.type = 'D' and BS.database_name = 'UTA1') begin select 'BAD' as Result ,'The backup of the database ' + 'UTA1' + ' was never taken.' as [Description] end else begin select case when lastBackupAge > 24 then 'BAD' else 'OK' end ,case when lastBackupAge > 24 then 'The backup of the database ' + 'UTA1' + ' is older then ' + convert(varchar(10),lastBackupAge) + ' hours' else 'The backup of the database ' + 'UTA1' + ' is recent' end as [Description] FROM (select DATEDIFF(hh, MAX(BS.backup_finish_date), GETDATE()) as lastBackupAge FROM    msdb.dbo.backupset as BS WHERE     BS.type = 'D' and BS.database_name = 'UTA1' GROUP BY BS.database_name) X end 

This program runs into a exception:
        using (var db = new NPoco.Database(connectionString, dbType, IsolationLevel.ReadCommitted))
            {
                var sqlResult = db.Single<SqlResult>(sqlText);
                if (string.IsNullOrWhiteSpace(sqlResult.Description))
                {
                    sqlResult.Description = "<Empty>";
                }
return sqlResult;
            }

If I execute the script with SQL Management Studio it works as expected.

**Comment by schotime** [comment]
if you are going to start your SQL with anything other than a select statement you'll need to prefix is with a `;` or turn the `EnableAutoSelect` off on the `Database`.

**Comment by rbrunken** [comment]
Hi Adam,
thanks for the fast answer. The EnableAutoSelect = false works fine for 
me.

Kind Regards
Reiner

------ Originalnachricht ------
Von: "Adam Schroder" <notifications@github.com>
An: "schotime/NPoco" <NPoco@noreply.github.com>
Cc: "Reiner" <reiner@brunken.de>; "Author" <author@noreply.github.com>
Gesendet: 02.03.2021 09:56:02
Betreff: Re: [schotime/NPoco] Can´t excute a SQL script (#629)
