### ISSUE TITLE
Any value of @ in the SQL causes exception

### ISSUE THREAD

**Issue by tbasallo** [schotime/NPoco#639]
I have some scripts that create users and such. IN this case, a login could be an email address. If I try to execute the following:
`await db.ExecuteAsync($"USE {databaseName}; CREATE USER [{loginModel.Name}] FOR LOGIN [{loginModel.Name}];");`

Where the login has an @ in it, i get the error:
`Parameter '@domain' specified but none of the passed arguments have a property with this name (in 'USE DB; CREATE USER [user@domain.com] FOR LOGIN [user@domain.com];')`

Is there a way to tell NPoco to ignore parameters? or the @ site?

**Comment by schotime** [comment]
You have to escape them with double @.

**Comment by tbasallo** [comment]
That did it. Thanks.
