### ISSUE TITLE
Possible bug in v5 ConvertFromOldConvention

### ISSUE THREAD

**Issue by p-m-j** [schotime/NPoco#642]
Changes to PropertyMapperNameConvention.FindMember (the introduction of the more robust IsPocoMemberEqual) results in level being updated where previously it was not. For our usage this later prevents another member from being found due to level filtering.

```csharp
var pocoMemberLevels = members.Where(x => !used.ContainsKey(x.PocoMember) && x.Level >= level);
```

I have a sample repo setup to demonstrate the issue which can be found at https://github.com/p-m-j/npoco5-umbraco-issues

Some further details and description of the problem can be found at https://github.com/umbraco/Umbraco-CMS/pull/9800

**Comment by schotime** [comment]
Ok, I think I have an idea about this. Will try and get a beta release out tomorrow to test against the repo. Sorry for the delay.

**Comment by p-m-j** [comment]
Awesome cheers!

**Comment by schotime** [comment]
https://www.nuget.org/packages/NPoco.SqlServer/5.3.2-preview1 has been pushed. I don't know if you can try it out, but it works in your repo repo.

**Comment by p-m-j** [comment]
Works like a charm, thanks very much.

**Comment by p-m-j** [comment]
No longer an issue with 5.3.2
