### ISSUE TITLE
Multiple `IncludeMany`

### ISSUE THREAD

**Issue by mattbrailsford** [schotime/NPoco#659]
I have a model with multiple nested collections that I'd like to populate in a single query. If I have a single collection I can call `IncludeMany` which works and populates the nested collection, however I'm unable to call this multiple times for multiple collections like you can with `Include`.

Is there any reason we shouldn't be able to perform multiple `IncludeMany`'s?

**Comment by schotime** [comment]
No reason, other than the significant complexity, which this library really isn't designed for. Entity Framework is more suited to these types of things. In hindsight I probably wouldn't have implemented this.
