### ISSUE TITLE
ORA-00933: SQL command not properly ended

### ISSUE THREAD

**Issue by ikvm** [schotime/NPoco#660]
oracle 19c and Oracle.ManagedDataAccess.Core 3.21.3, call InsertBatch throw exception "ORA-00933: SQL command not properly ended"

**Comment by schotime** [comment]
I don't use Oracle and you haven't really given and information about what the query looks like. Have you run the resulting query in Oracle etc?

**Comment by ikvm** [comment]
![image](https://user-images.githubusercontent.com/470915/167059434-be101f24-0d3e-4bfd-941c-d02908b2ec8a.png)

**Comment by schotime** [comment]
Is it because there is no ; at the very end?

**Comment by ikvm** [comment]
the ORACLE block statement is start with BEGIN and end with END;

**Comment by schotime** [comment]
If you add another semi colon to the end of the statement in your image what happens?

**Comment by ikvm** [comment]
![image](https://user-images.githubusercontent.com/470915/182415062-07073afe-d3fd-4f0d-a2eb-953439989d3c.png)

**Comment by wasabii** [comment]
@ikvm Do you have any contact information I can use to reach you by? I resorted to trying to ping you on this issue because I could not find any.
