### ISSUE TITLE
Exec generic Sql commands when connection opens (PRAGMA)

### ISSUE THREAD

**Issue by nhaberl** [schotime/NPoco#678]
Hello, is there a way to execute Sql commands on a central point whenever a connection opens ... 
In Sqlite I would like to set a handful of PRAGMA statements on each connection before any user generated connad executes against the database.

Like here: https://stackoverflow.com/questions/39930559/how-to-set-multiple-pragmas-using-sqlite-net

**Comment by schotime** [comment]
You can use this method, or one of the other ones that you can override in an inherited class you create.

![image](https://user-images.githubusercontent.com/202923/209951598-4d536cb8-fecf-4b0d-8110-74f288f9a2ce.png)
