### ISSUE TITLE
Parameters are not working

### ISSUE THREAD

**Issue by AaronSadlerUK** [schotime/NPoco#683]
Version: NPoco 5.3.2

I'm using the sqlBuilder with a template as follows:

`var template = sqlBuilder.AddTemplate($"select * from TABLE WHERE /**where**/");`

followed by:

`sqlBuilder.Where("COLUMN LIKE @0 OR COLUMN2 LIKE @0", new[]{ searchProperties.Keywords });`

I can see in my breakpoint that `searchProperties.Keywords` does indeed have a value, however I get the following exception:

`ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Parameter '@0' specified but only 0 parameters supplied`

When I look at the raw SQL generated I can see that @0 has not been replaced.

Is this a known bug, or am I doing something wrong here?

Thanks for all your help!

**Comment by schotime** [comment]
What is the type of `Keywords`?

**Comment by AaronSadlerUK** [comment]
It is a string, i have also tried with int in other where statements with the same issue

**Comment by schotime** [comment]
What if you try this?

`sqlBuilder.Where("COLUMN LIKE @0 OR COLUMN2 LIKE @0", searchProperties.Keywords);`

**Comment by AaronSadlerUK** [comment]
I tried that prior, I tried explicitly setting the array in case that was the issue.

It returns the same exception that no parameters are set, even though they are

**Comment by schotime** [comment]
You'll need to post a full sample
