### ISSUE TITLE
SqliteConnection misdetected as SqlServerConnection

### ISSUE THREAD

**Issue by Hakon** [schotime/NPoco#687]
Hi,

I've been trying to track down an issue where my SqliteConnection is misdetected as an SqlServerConnection:
```C#
    [Fact]
    public void npoco_bug()
    {
        var c = new SqliteConnection("Data Source=test.db");
        var db = new NPoco.Database(c);
        Assert.Equal("SqlServerDatabaseType", db.DatabaseType.GetType().Name);
    }
```
I expected the DatabaseType to be SQLiteDatabaseType. The reason for the misdetection is due to the uppercase **SQL**ite in the [Resolve method on DatabaseType](https://github.com/schotime/NPoco/blob/5117a55fde57547e928246c044fd40bd00b2d7d1/src/NPoco/DatabaseType.cs#L270). Is there another SqliteConnection type that I should be aware of that has the SQL capitalised?

I can make a patch if this is indeed a bug.

Regards,
Håkon

**Comment by schotime** [comment]
Sounds like a bug, can probably just add a `, StringComparison.OrdinalIgnoreCase` as the second parameter to `StartsWith` on that line you referenced.
