### ISSUE TITLE
Repository-wide license?

### ISSUE THREAD

**Issue by CMBrando** [schotime/NPoco#694]
Sorry this is a bit nitpicky, but while there is a license.txt file in the NPoco project it does not exist in the other project directories like NPoco.SqlServer.  This is causing problems for open source dependency license audits.  There is also no license information in NuGet for NPoco.SqlServer.

Could a license be applied to the whole repository on the home page so it's clear everything under the repository is covered by that license or added to each project directory? If not, could you confirm the license is the same as the main NPoco one?

**Comment by schotime** [comment]
Done. Has been added to root.

![image](https://github.com/schotime/NPoco/assets/202923/999fc5f3-af4f-49e2-b596-86d05c6d8599)
