### ISSUE TITLE
DateOnly Support

### ISSUE THREAD

**Issue by tbasallo** [schotime/NPoco#706]
There was another issue reporting this, but it was closed as fixed in Microsoft.Data.SqlClient (5.2.2). However, I am getting an exception with the latest in all libraries.

     System.InvalidCastException: Invalid cast from 'System.DateTime' to 'System.DateOnly'.

The SQL Server data type is date and property is DateOnly. 

Is this not supported natively? Is a mapper still required?

**Comment by schotime** [comment]
v6 Preview 6 has support. Hopefully this side of the new year I can release it without the preview, however it's currently running in a few prod environments to test it and no issues so far.

**Comment by tbasallo** [comment]
That'd be awesome!

I can run the preview in a couple environments to see if anything comes up.
