### ISSUE TITLE
Library current status?

### ISSUE THREAD

**Issue by ahazelwood** [schotime/NPoco#707]
I am curious what the current status of the library is.  It appears that several newer versions were being worked on, but curious what your thoughts were on the status of the library.

The SQL Server library in particular needs an update to the latest version to help mitigate Microsoft.Data.SqlClient vulnerabilities.

**Comment by schotime** [comment]
The current state is under development as it has always been. Nothing has changed.
You can always add a later version to your project which will pull the dependency up to that version.
