### ISSUE TITLE
FetchMultiple issue when using with dynamic

### ISSUE THREAD

**Issue by yasarab-arabi** [schotime/NPoco#76]
I was facing an issues when using FetchMultiple with dynamic using the same tables or have same column count in Select.

db.FetchMultiple<dynamic, dynamic>("Select * from Table1; Select Table1.* from Table1 inner join Table2 on Table1.Id = Table2.Id");

Thanks,
Mohd Arabi

**Comment by schotime** [comment]
What is the issue?
