### ISSUE TITLE
Persist Enum value as string instead of integer

### ISSUE THREAD

**Issue by techniq** [schotime/NPoco#96]
I'm having trouble finding a way to persist an enum as it's string name instead of it's integer value.  Currently, I have values in a table as string and they populate the model correctly, but when I write a new entity, it uses it's integer value instead.

If there is a way to change the mapping using `FluentMappingConfiguration` that would be great (as that's what I'm currently using).

**Comment by centur** [comment]
Umm, spent some hours before found this misconfiguration in my code. I was using default mapper and didn't realized that to save\restore enums as strings I need to use this custom one. Also it seems that if one using mix of fluent and attribute-based mappings - ColumnType from attribute doesn't picked by ColumnConfiguration:
I have this fluent mapping 
```c#
	For<ActivationDataModel>()
			.TableName("UserActivations")
			.PrimaryKey(x => x.Id, autoIncrement: false)
			.Columns(c =>
			{
				//c.Column(m => m.ActivationStatus).WithDbType<string>();
				c.Column(m => m.EmailStatus).WithDbType<string>();
			});
```
and this attribute :
```C#
	[ColumnType(typeof(string))]
	public ActivationStatus ActivationStatus { get; set; }
```
(This is not real code, just experiments trying to troubleshoot problems in my fluent configuration)

Both properties are enums. ColumnType attribute for ActivationStatus is not picked as string, thus it's not getting in Enum-As-String IF statement as per example above (DestType != typeof(string))
```C#
 if (SourceType.IsEnum && DestType == typeof(string))   { return x => x.ToString(); }
```
So my table got weird rows : some are with stringified enums, some with integers in nvarchar columns. And it fails when NPoco trying to map it back - error message with broken String->Enum mapping is very generic:  "The given key was not present in the dictionary."

@schotime Is there any simple way to provide a "default" mapping - if existing value in the database doesn't map back to any Enum values - set it to default(enum) when mapping back to poco
?

**Comment by schotime** [comment]
Firstly you cannot mix fluent config and attributes.
The latest NPoco (2.10.8) will map enums to strings by default if the column type is set to string and no mapper is found.

**Comment by dannylloyd** [comment]
@schotime You mention the latest version will map enums to strings by default, I am using 3.8 and I have to add the attribute `[ColumnType(typeof(string))]` to my enum to get it to map to string instead of integer. Am I doing something wrong? Will I need to add this attribute for every enum I want stored as a string?

Here is a subset of my class:
```
public class AdvocateClient
    {
        public int Id { get; set; }
        [ColumnType(typeof(string))]
        public Genders Gender { get; set; }

        public enum Genders
        {
            [Display(Name = "Male", Prompt = "M")]
            Male = 1,
            [Display(Name = "Female", Prompt = "F")]
            Female = 2
        }
    }
```

**Comment by tbasallo** [comment]
@andersjonsson that's by design. It will map to string be default **IF** the column type is set to string and no mapper is found.

The word **default** probably through you off. But you got it right with the attribute.
