### ISSUE TITLE
Add support for abstract class/interface instantiation using provided factory/mapper or similar

### ISSUE THREAD

**Issue by litera** [schotime/NPoco#97]
Let's say we have a *Table Per Hierarchy* database schema. Let's say we store various different content types (distinguished by `TypeId` column) in the same table as they share vast majority of fields. Let's say this content is something similar to Quora's:

* Question
* Answer
* Post

They have several common fields but only a few that are specific to each type. That's why we want to use inheritance:

```csharp
public abstract class ContentBase
{
    // common properties, Id, Author (Id, Name, ...), Title, Content, ...
}

public class Question: ContentBase
{
    public int AnswerCount { get; set; }
}

public class Answer: ContentBase
{
    public Question RelatedQuestion { get; set; }
}

public class Post: ContentBase
{
    // anything particular to this type
}
```

If we'd then want to display a stream similar to what we can see on Quora we'd need to get all content but in concrete types.

```csharp
db.Fetch<ContentBase, Author, ...>(Sql sql);
```

But this doesn't work as `ContentBase` is an abstract class. I don't know of any simple way how to accomplish this rather than resorting to custom classes with additional functionality.

I suppose a possible method call (but far from being ideal) could be:

```csharp
db.Fetch<T1, T2, ...>(
    Sql sql,
    Func<IDataReader, T1> converterT1, 
    Func<IDataReader, T2> converterT2,
    ...);
```

This would make it possible to work with abstract classes or even interfaces but using concrete classes that inherit/implement them. Upper syntax is not the actual one as it would prevent automatic mapper compilation relying on user code. So something else along the line would be greatly appreciated.

Could this be implemented?

**Comment by schotime** [comment]
hey,
I'm in the middle of V3 and going through all the issues, and came across this again. Probably in a better position to look at it and come up with some sort of solution.
You still keen on this?
Adam

**Comment by litera** [comment]
Sure I am! :)

**Comment by schotime** [comment]
Does this need to be per query or could it be per class type?
eg. Could you have something like?

```csharp
MapperFactory.Register(typeof(ContentBase), reader => {
        ContentBase result = null;
        ContentType typeId = (ContentType)reader.GetInt32(reader.GetOrdinal("TypeId"));
        switch(typeId) {
            case ContentType.Post:
                result = new Post();
                break;
            case ContentType.Question:
                result = new Question();
                break;
            case ContentType.Answer:
                result = new Answer();
                break;
            default: break;
        }
        return result;
    }));
```

**Comment by schotime** [comment]
Here is what it looks like at the moment.

https://github.com/schotime/NPoco/blob/bb90593520e3f10387d90dfac93126426e75e998/src/NPoco.Tests/NewMapper/NestedConventionTests.cs#L385

There are 3 tests there (23,24,25)

Abstract classes and interfaces.

**Comment by schotime** [comment]
Implemented in V3 and on NuGet as alpha

**Comment by litera** [comment]
This actually looks great! One mainly has to configure these things during app bootstrap and forget about them afterwards, because mappers will work their *miracle* in the background.

But this is just per type solution. How about per query? I don't have a reasonable scenario for it, but maybe you do? Usually when an app is being developed it connects to the same database and records usually represent same kind of stuff, so I don't really see any particular scenario where one could have a per query problem.

I'm trying to think about a some sort of *dynamic* table that could store many things. Something along the lines that Sharepoint uses where schemas on the client side seem very flexible, but they're usually stored in the same database table model. In such case resulting mapper should rely on data in those records which means that **it can't be preconfigured before the call** as users may add new types in that data. And that would be a per query example of such a problem that can't be solved with this app start mapping configuration.
